#include "gui/MonteCarloWizard.hpp"

#include "core/AseScriptGenerator.hpp"

#include <QComboBox>
#include <QDoubleSpinBox>
#include <QFormLayout>
#include <QSpinBox>
#include <QWidget>

#include <sstream>

namespace calango::gui {

namespace {

// The CALANGO_FRAME/CELL streaming helper shared by the generated scripts.
constexpr const char* kStreamHelper =
    "def _stream_frame():\n"
    "    lines = []\n"
    "    if atoms.pbc.any():\n"
    "        cell = atoms.cell[:]\n"
    "        lines.append(\"CALANGO_CELL \" + \" \".join(\n"
    "            f\"{v:.8f}\" for row in cell for v in row))\n"
    "    lines.append(f\"CALANGO_FRAME {len(atoms)}\")\n"
    "    for s, p in zip(atoms.get_chemical_symbols(), atoms.get_positions()):\n"
    "        lines.append(f\"{s} {p[0]:.6f} {p[1]:.6f} {p[2]:.6f}\")\n"
    "    sys.stdout.write(\"\\n\".join(lines) + \"\\n\")\n"
    "    sys.stdout.flush()\n\n";

} // namespace

MonteCarloWizard::MonteCarloWizard(QWidget* parent) : SimulationWizardBase(parent)
{
    buildUi();
    updateMethodEnabled();
}

QString MonteCarloWizard::wizardTitle() const
{
    return tr("Monte Carlo Simulation Setup");
}

QString MonteCarloWizard::settingsHeader() const
{
    return tr("Monte Carlo Settings");
}

QWidget* MonteCarloWizard::buildSettingsPage()
{
    auto* page = new QWidget(this);
    auto* form = new QFormLayout(page);

    methodCombo_ = new QComboBox(page);
    methodCombo_->addItem(tr("Basin Hopping (global optimization)"));
    methodCombo_->addItem(tr("Swap-atoms (alloy sampling)"));
    form->addRow(tr("Method:"), methodCombo_);
    connect(methodCombo_, &QComboBox::currentIndexChanged, this,
            &MonteCarloWizard::updateMethodEnabled);

    stepsSpin_ = new QSpinBox(page);
    stepsSpin_->setRange(1, 1000000);
    stepsSpin_->setValue(50);
    form->addRow(tr("Monte Carlo steps:"), stepsSpin_);

    temperatureSpin_ = new QDoubleSpinBox(page);
    temperatureSpin_->setRange(1.0, 100000.0);
    temperatureSpin_->setValue(1000.0);
    temperatureSpin_->setSuffix(tr(" K"));
    form->addRow(tr("Temperature:"), temperatureSpin_);

    displacementSpin_ = new QDoubleSpinBox(page);
    displacementSpin_->setRange(0.01, 5.0);
    displacementSpin_->setDecimals(3);
    displacementSpin_->setValue(0.4);
    displacementSpin_->setSuffix(tr(" Å"));
    displacementSpin_->setToolTip(tr("Max random atomic displacement per step."));
    form->addRow(tr("Perturbation amplitude:"), displacementSpin_);

    swapProbSpin_ = new QDoubleSpinBox(page);
    swapProbSpin_->setRange(0.0, 1.0);
    swapProbSpin_->setDecimals(2);
    swapProbSpin_->setSingleStep(0.05);
    swapProbSpin_->setValue(1.0);
    swapProbSpin_->setToolTip(tr("Probability of attempting a species swap each step."));
    form->addRow(tr("Swap probability:"), swapProbSpin_);

    fmaxSpin_ = new QDoubleSpinBox(page);
    fmaxSpin_->setRange(0.001, 1.0);
    fmaxSpin_->setDecimals(3);
    fmaxSpin_->setValue(0.05);
    fmaxSpin_->setSuffix(tr(" eV/Å"));
    fmaxSpin_->setToolTip(tr("Local-optimization force convergence for each hop."));
    form->addRow(tr("Energy convergence (fmax):"), fmaxSpin_);

    optimizerCombo_ = new QComboBox(page);
    optimizerCombo_->addItems({QStringLiteral("FIRE"), QStringLiteral("BFGS"),
                               QStringLiteral("LBFGS"),
                               QStringLiteral("QuasiNewton")});
    form->addRow(tr("Local optimizer:"), optimizerCombo_);

    seedSpin_ = new QSpinBox(page);
    seedSpin_->setRange(0, 1000000);
    seedSpin_->setValue(42);
    form->addRow(tr("Random seed:"), seedSpin_);
    return page;
}

void MonteCarloWizard::updateMethodEnabled()
{
    const bool basinHopping = methodCombo_->currentIndex() == 0;
    displacementSpin_->setEnabled(basinHopping);
    fmaxSpin_->setEnabled(basinHopping);
    optimizerCombo_->setEnabled(basinHopping);
    swapProbSpin_->setEnabled(!basinHopping);
}

QString MonteCarloWizard::buildBasinHoppingScript() const
{
    const std::string calc =
        core::AseScriptGenerator::calculatorSnippet(baseCalculatorConfig());
    const std::string optimizer = optimizerCombo_->currentText().toStdString();

    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Basin Hopping global optimization (generated by Calango).\n"
           "import sys\n"
           "import numpy as np\n"
           "from ase.io import read, write\n"
           "from ase.optimize import " << optimizer << "\n\n"
           "atoms = read(\"structure.extxyz\")\n\n"
        << calc << "\n"
        << kStreamHelper
        << "kB = 8.617333262e-5\n"
        << "T = " << temperatureSpin_->value() << "\n"
        << "dr = " << displacementSpin_->value() << "\n"
        << "nsteps = " << stepsSpin_->value() << "\n"
        << "fmax = " << fmaxSpin_->value() << "\n"
        << "rng = np.random.default_rng(" << seedSpin_->value() << ")\n\n"
           "def local_opt():\n"
        << "    opt = " << optimizer << "(atoms, logfile=None)\n"
           "    opt.run(fmax=fmax, steps=200)\n"
           "    return atoms.get_potential_energy()\n\n"
           "e_curr = local_opt()\n"
           "e_min = e_curr\n"
           "best = atoms.copy()\n"
           "print(f\"CALANGO_ENERGY 0 {e_curr:.6f}\", flush=True)\n"
           "_stream_frame()\n"
           "for step in range(1, nsteps + 1):\n"
           "    pos0 = atoms.get_positions().copy()\n"
           "    atoms.set_positions(pos0 + rng.uniform(-dr, dr, pos0.shape))\n"
           "    e = local_opt()\n"
           "    if e < e_curr or rng.random() < np.exp(-(e - e_curr) / (kB * T)):\n"
           "        e_curr = e\n"
           "        if e < e_min:\n"
           "            e_min = e\n"
           "            best = atoms.copy()\n"
           "    else:\n"
           "        atoms.set_positions(pos0)\n"
           "    print(f\"CALANGO_PROGRESS {step} {nsteps}\", flush=True)\n"
           "    print(f\"CALANGO_ENERGY {step} {e_curr:.6f}\", flush=True)\n"
           "    _stream_frame()\n"
           "write(\"basin_hopping_best.extxyz\", best)\n"
           "print(f\"CALANGO_RESULT e_min_eV={e_min:.6f}\", flush=True)\n"
           "print(\"CALANGO_DONE\", flush=True)\n";
    return QString::fromStdString(out.str());
}

QString MonteCarloWizard::buildSwapScript() const
{
    const std::string calc =
        core::AseScriptGenerator::calculatorSnippet(baseCalculatorConfig());

    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Swap-atoms Monte Carlo — Metropolis species swaps (generated by "
           "Calango).\n"
           "import sys\n"
           "import numpy as np\n"
           "from ase.io import read, write\n\n"
           "atoms = read(\"structure.extxyz\")\n\n"
        << calc << "\n"
        << kStreamHelper
        << "kB = 8.617333262e-5\n"
        << "T = " << temperatureSpin_->value() << "\n"
        << "nsteps = " << stepsSpin_->value() << "\n"
        << "swap_prob = " << swapProbSpin_->value() << "\n"
        << "rng = np.random.default_rng(" << seedSpin_->value() << ")\n\n"
           "numbers = atoms.get_atomic_numbers()\n"
           "distinct = np.unique(numbers)\n"
           "if len(distinct) < 2:\n"
           "    raise SystemExit(\"Swap-atoms needs at least two species.\")\n\n"
           "e_curr = atoms.get_potential_energy()\n"
           "e_min = e_curr\n"
           "best = atoms.copy()\n"
           "accepted = 0\n"
           "print(f\"CALANGO_ENERGY 0 {e_curr:.6f}\", flush=True)\n"
           "_stream_frame()\n"
           "for step in range(1, nsteps + 1):\n"
           "    if rng.random() < swap_prob:\n"
           "        nums = atoms.get_atomic_numbers()\n"
           "        i = rng.integers(len(nums))\n"
           "        # pick a partner of a different species\n"
           "        others = np.flatnonzero(nums != nums[i])\n"
           "        if len(others):\n"
           "            j = int(rng.choice(others))\n"
           "            nums[i], nums[j] = nums[j], nums[i]\n"
           "            atoms.set_atomic_numbers(nums)\n"
           "            e = atoms.get_potential_energy()\n"
           "            if e < e_curr or rng.random() < np.exp(-(e - e_curr) / (kB * T)):\n"
           "                e_curr = e\n"
           "                accepted += 1\n"
           "                if e < e_min:\n"
           "                    e_min = e\n"
           "                    best = atoms.copy()\n"
           "            else:\n"
           "                nums[i], nums[j] = nums[j], nums[i]  # revert\n"
           "                atoms.set_atomic_numbers(nums)\n"
           "    print(f\"CALANGO_PROGRESS {step} {nsteps}\", flush=True)\n"
           "    print(f\"CALANGO_ENERGY {step} {e_curr:.6f}\", flush=True)\n"
           "    _stream_frame()\n"
           "write(\"swap_mc_best.extxyz\", best)\n"
           "print(f\"CALANGO_RESULT e_min_eV={e_min:.6f} accepted={accepted}\", flush=True)\n"
           "print(\"CALANGO_DONE\", flush=True)\n";
    return QString::fromStdString(out.str());
}

QString MonteCarloWizard::generateScript() const
{
    return methodCombo_->currentIndex() == 0 ? buildBasinHoppingScript()
                                             : buildSwapScript();
}

} // namespace calango::gui
