#include "core/BornChargesScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>
#include <string>

namespace calango::core {

std::string generateBornChargesScript(const BornChargesConfig& config)
{
    // The Berry phase is defined on the UNSYMMETRIZED Brillouin zone, so the
    // symmetry switch is not the user's to make here. Setting it on the config
    // (rather than appending a second `symmetry=` after the shared keyword
    // block) is what keeps the generated call free of a duplicated keyword
    // argument, which Python rejects outright.
    BornChargesConfig cfg = config;
    cfg.calculator.gpawSymmetryOff = true;

    const bool gpaw = cfg.calculator.calculator == CalculatorKind::Gpaw;

    std::ostringstream out;
    out << "# Born effective charges Z* — generated by Calango\n"
           "#\n"
           "# Z*_{k,ab} = (Omega / e) * dP_a / du_{k,b}\n"
           "#\n"
           "# Evaluated by central finite differences of the BERRY-PHASE\n"
           "# polarization: each atom is displaced by +/- delta along each\n"
           "# Cartesian axis, the SCF is re-converged, and the macroscopic\n"
           "# polarization is read off the Berry phase of the occupied\n"
           "# manifold.\n"
           "#\n"
           "# Cost: 6 SCF runs per atom. That is the honest price of a\n"
           "# finite-difference Z* — there is no cheaper route through ASE.\n"
           "import json\n"
           "import os\n"
           "from pathlib import Path\n"
           "\n"
           "# GPAW's Berry-phase module lives in the new engine.\n"
           "os.environ.setdefault('GPAW_NEW', '1')\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "from ase.units import Bohr\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();
    if (cfg.baselinePath.empty())
        out << "atoms = read('structure.extxyz')\n\n";

    if (!gpaw) {
        // Refusing up front beats running 6N SCF cycles and failing at the
        // polarization step; the message names the one thing that has to change.
        out << "raise RuntimeError(\n"
               "    'Born effective charges need the Berry-phase polarization, "
               "which \\n'\n"
               "    'only the GPAW backend provides here. The selected engine "
               "was \"" << toString(cfg.calculator.calculator) << "\".\\n'\n"
               "    'Re-open the wizard and choose GPAW.')\n";
        return out.str();
    }

    if (!cfg.baselinePath.empty())
        out << "# --- Ground-state baseline ---------------------------------\n"
               "# A completed Single-Point Calculation supplies the converged\n"
               "# GEOMETRY the displacements are taken about, and the calculator\n"
               "# every displaced run is rebuilt from (calc.new()) — so all of\n"
               "# them use exactly the settings the baseline was validated with.\n"
               "#\n"
               "# It does NOT supply a density to evaluate at, the way the\n"
               "# Optics and Electronic Structure baselines do. Z* IS the\n"
               "# response of the charge distribution to a displacement, so each\n"
               "# displaced geometry re-converges its own SCF. There is no\n"
               "# fixed-density shortcut here.\n"
               "from gpaw import GPAW\n"
               "\n"
            << "_baseline = GPAW(r\"" << cfg.baselinePath << "\", txt=None)\n"
            << "atoms = _baseline.get_atoms()\n"
               "\n";

    out << "if not atoms.pbc.all():\n"
           "    raise RuntimeError(\n"
           "        'The Berry-phase polarization is defined for a periodic "
           "crystal.\\n'\n"
           "        'This structure is not periodic in all three directions — "
           "Z* is\\n'\n"
           "        'only meaningful for a bulk insulator. Build a periodic "
           "cell first.')\n"
           "\n"
        << AseScriptGenerator::gpawImports(cfg.calculator)
        << "# GPAW renamed this in the 25.x/26.x line (get_polarization_phase ->\n"
           "# polarization_phase) and changed both its calling convention and its\n"
           "# return type, so bind whichever spelling the installed GPAW has.\n"
           "try:\n"
           "    from gpaw.berryphase import polarization_phase as _phase_fn\n"
           "    _NEW_BERRY_API = True\n"
           "except ImportError:\n"
           "    from gpaw.berryphase import get_polarization_phase as _phase_fn\n"
           "    _NEW_BERRY_API = False\n"
           "\n"
        << "delta = " << cfg.displacement << "        # Angstrom\n";

    out << "indices = ";
    if (cfg.atomIndices.empty()) {
        out << "list(range(len(atoms)))\n";
    } else {
        out << "[";
        for (std::size_t i = 0; i < cfg.atomIndices.size(); ++i)
            out << (i ? ", " : "") << cfg.atomIndices[i];
        out << "]\n";
    }

    out << "cell = atoms.get_cell()\n"
           "volume = atoms.get_volume()\n"
           "reference = atoms.get_positions().copy()\n"
           "total_steps = 6 * len(indices)\n"
           "_calango_log.event('start', "
           "f'{len(indices)} atom(s), {total_steps} SCF runs')\n"
           "\n"
           "\n"
           "def polarization_phase_c(calc, tag):\n"
           "    \"\"\"Total polarization phase (3 crystal components, radians).\n"
           "\n"
           "    Papers over three GPAW generations: the modern call takes the\n"
           "    live calculator and returns a dict of phase components, the\n"
           "    transitional one reads a .gpw through `gpw_wfs=`, and the oldest\n"
           "    takes that path positionally and returns the bare array.\n"
           "    \"\"\"\n"
           "    if _NEW_BERRY_API:\n"
           "        try:\n"
           "            result = _phase_fn(calc=calc)\n"
           "        except (TypeError, AttributeError):\n"
           "            # Legacy engine: no calc.dft to gather, so round-trip\n"
           "            # the wavefunctions through a file instead.\n"
           "            gpw = f'born_{tag}.gpw'\n"
           "            calc.write(gpw, mode='all')\n"
           "            result = _phase_fn(gpw_wfs=Path(gpw))\n"
           "            os.remove(gpw)\n"
           "    else:\n"
           "        gpw = f'born_{tag}.gpw'\n"
           "        calc.write(gpw, mode='all')\n"
           "        result = _phase_fn(gpw)\n"
           "        os.remove(gpw)   # one .gpw per displacement fills the disk\n"
           "    if isinstance(result, dict):\n"
           "        # 'phase_c' is electronic + ionic, which is the total.\n"
           "        result = result['phase_c']\n"
           "    return np.asarray(result, dtype=float)\n"
           "\n"
           "\n"
           "def displaced_phase(displaced, tag):\n"
           "    \"\"\"Total polarization phase of one displaced geometry.\"\"\"\n";
    if (cfg.baselinePath.empty()) {
        out << "    calc = GPAW(\n"
            << AseScriptGenerator::gpawKeywordArguments(cfg.calculator, "        ")
            << "        txt=f'gpaw_{tag}.txt',\n"
               "    )\n";
    } else {
        // calc.new() rebuilds the baseline's calculator verbatim, so every
        // displaced SCF is run with the settings that were validated once —
        // rather than a second, hand-copied set that can drift from them.
        //
        // symmetry='off' is forced on top: the Berry phase is an integral over
        // the FULL Brillouin zone, and a symmetry-folded k-point set silently
        // gives the wrong polarization rather than an error.
        out << "    calc = _baseline.new(symmetry='off', "
               "txt=f'gpaw_{tag}.txt')\n";
    }
    out << "    displaced.calc = calc\n"
           "    displaced.get_potential_energy()\n"
           "    return polarization_phase_c(calc, tag)\n"
           "\n"
           "\n"
           "def phase_difference(plus_c, minus_c):\n"
           "    \"\"\"phi(+u) - phi(-u), resolved onto the correct branch.\n"
           "\n"
           "    The Berry phase is only defined MODULO 2*pi — the polarization\n"
           "    quantum — and the two displaced calculations routinely land on\n"
           "    different branches. Subtracting them raw then yields a Z* out by\n"
           "    an integer number of quanta: cubic BN came out at -540 e for\n"
           "    boron instead of +1.9, exactly 6 quanta off, while the nitrogen\n"
           "    (whose phases happened to agree) was already right.\n"
           "\n"
           "    A displacement of delta ~ 0.01 A cannot physically move the\n"
           "    polarization by anything close to a quantum, so the true\n"
           "    difference is the representative in (-pi, pi]; wrapping it there\n"
           "    is what picks the same branch for both.\n"
           "    \"\"\"\n"
           "    return (plus_c - minus_c + np.pi) % (2.0 * np.pi) - np.pi\n"
           "\n"
           "\n"
           "born = np.zeros((len(atoms), 3, 3))\n"
           "step = 0\n"
           "for atom_index in indices:\n"
           "    for axis in range(3):\n"
           "        phases = []\n"
           "        for sign in (+1, -1):\n"
           "            positions = reference.copy()\n"
           "            positions[atom_index, axis] += sign * delta\n"
           "            moved = atoms.copy()\n"
           "            moved.set_positions(positions)\n"
           "            tag = f'{atom_index}_{axis}_{\"p\" if sign > 0 else \"m\"}'\n"
           "            phases.append(displaced_phase(moved, tag))\n"
           "            step += 1\n"
           "            _calango_log.progress(step, total_steps)\n"
           "        # The branch is resolved on the PHASE, in crystal\n"
           "        # coordinates, before anything is converted to Cartesian.\n"
           "        dphi_c = phase_difference(phases[0], phases[1])\n"
           "        # Z*_{k,ab} = d(Omega P_a) / du_{k,b}. Omega*P is the cell\n"
           "        # dipole sum_c (phi_c / 2pi) a_c (e*A), so dividing by the\n"
           "        # displacement (A) leaves a result in units of e.\n"
           "        born[atom_index, :, axis] = (\n"
           "            (dphi_c / (2.0 * np.pi)) @ np.array(cell) / (2.0 * delta))\n"
           "    _calango_log.metric(atom_index,\n"
           "                        z_iso=float(np.trace(born[atom_index]) / 3.0))\n"
           "\n"
           "raw = born.copy()\n";

    out << "computed = np.array(indices)\n"
           "# The sum rule is a statement about ALL the atoms in the cell:\n"
           "# translating the whole crystal cannot polarize it, so sum_k Z*_k\n"
           "# must vanish over every k. A partial sum is not a residual and\n"
           "# subtracting it would corrupt the tensors it was meant to correct\n"
           "# — for one Si and one O of alpha-quartz it comes to 1.06 e, which\n"
           "# is the Si+2O neutrality of the formula unit, not an error.\n"
           "complete = len(indices) == len(atoms)\n"
           "residual = born[computed].sum(axis=0)\n"
           "asr_residual = float(np.abs(residual).max())\n";
    if (cfg.acousticSumRule) {
        out << "if complete:\n"
               "    # Whatever the full sum comes out to IS this calculation's\n"
               "    # own convergence error; spreading it evenly over the atoms\n"
               "    # is the standard correction.\n"
               "    born -= residual / len(atoms)\n"
               "    asr_imposed = True\n"
               "else:\n"
               "    asr_imposed = False\n"
               "    print('CALANGO_INFO acoustic sum rule NOT imposed: only '\n"
               "          f'{len(indices)} of {len(atoms)} atoms were computed, '\n"
               "          'so the sum over k is incomplete', flush=True)\n";
    } else {
        out << "asr_imposed = False\n";
    }

    out << "\n"
           "symbols = atoms.get_chemical_symbols()\n"
           "results = []\n"
           "for atom_index in indices:\n"
           "    tensor = born[atom_index]\n"
           "    # The isotropic part is the number usually quoted; the\n"
           "    # eigenvalues say how anisotropic the response really is.\n"
           "    eigenvalues = np.linalg.eigvals(\n"
           "        0.5 * (tensor + tensor.T)).real\n"
           "    results.append({\n"
           "        'index': int(atom_index),\n"
           "        'symbol': symbols[atom_index],\n"
           "        'tensor': [[float(v) for v in row] for row in tensor],\n"
           "        'raw_tensor': [[float(v) for v in row]\n"
           "                       for row in raw[atom_index]],\n"
           "        'isotropic': float(np.trace(tensor) / 3.0),\n"
           "        'eigenvalues': sorted(float(v) for v in eigenvalues),\n"
           "    })\n"
           "\n"
           "summary = {\n"
           "    'displacement_A': delta,\n"
           "    'acoustic_sum_rule': asr_imposed,\n"
           "    'asr_residual_e': asr_residual,\n"
           "    'volume_A3': float(volume),\n"
           "    'atoms': results,\n"
           "}\n"
           "with open('born_charges.json', 'w') as handle:\n"
           "    json.dump(summary, handle, indent=2)\n"
           "\n"
           "print(f'CALANGO_RESULT born_charges=born_charges.json '\n"
           "      f'atoms={len(results)} asr_residual_e={asr_residual:.4f}',\n"
           "      flush=True)\n";
    return out.str();
}

} // namespace calango::core
