#include "core/CalphadScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"
#include "core/TextUtils.hpp"

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <sstream>

namespace calango::core {

namespace {

/// A Python list literal of quoted, upper-cased names.
std::string nameList(const std::vector<std::string>& names)
{
    std::ostringstream out;
    out << "[";
    for (std::size_t i = 0; i < names.size(); ++i)
        out << (i ? ", " : "") << "\"" << upperCase(names[i]) << "\"";
    out << "]";
    return out.str();
}

} // namespace

std::string CalphadScriptGenerator::generate(const CalphadScriptConfig& config)
{
    // VA is appended rather than demanded of the caller: every sublattice
    // model that names a vacancy needs it in the component list, and the error
    // pycalphad raises without it names the components, not the vacancy.
    std::vector<std::string> components;
    for (const std::string& component : config.components)
        components.push_back(upperCase(component));
    if (std::find(components.begin(), components.end(), "VA")
        == components.end())
        components.push_back("VA");

    const std::string axis = upperCase(config.axisElement);
    const std::string axis2 = upperCase(config.secondAxisElement);

    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — CALPHAD equilibrium with pycalphad.\n"
           "#\n"
           "# Calango draws binary and ternary diagrams itself, in C++, with "
           "no solver:\n"
           "# the equilibrium of a system at a composition is the lower convex "
           "hull of\n"
           "# the phases' Gibbs curves, and a hull needs no iteration. What "
           "that\n"
           "# construction does NOT model is the part of a real database that "
           "is not a\n"
           "# substitutional solution — internal sublattice equilibria, the "
           "magnetic\n"
           "# (Inden-Hillert) contribution, ionic and associate models. This "
           "script is\n"
           "# for those, and for checking the ones Calango does model against "
           "an\n"
           "# independent implementation.\n"
           "#\n"
           "# It is a plain pycalphad script: edit it freely or run it "
           "standalone.\n"
           "\n"
           "import json\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "_database_file = r\"" << config.databaseFile << "\"\n"
           "_components = " << nameList(components) << "\n"
           "_requested_phases = " << nameList(config.phases) << "\n"
           "_results_path = r\"" << config.resultsJson << "\"\n"
           "_pressure = " << config.pressurePa << "\n";
    if (config.ternary) {
        out << "_axis = \"" << axis << "\"\n"
               "_axis2 = \"" << axis2 << "\"\n"
               "_section_temperature = " << config.sectionTemperatureK << "\n"
               "_composition_step = " << config.compositionStep << "\n";
    } else {
        out << "_axis = \"" << axis << "\"\n"
               "_temperature_min = " << config.minTemperatureK << "\n"
               "_temperature_max = " << config.maxTemperatureK << "\n"
               "_temperature_step = " << config.temperatureStepK << "\n"
               "_composition_step = " << config.compositionStep << "\n";
    }

    out << "\n"
           "# --- The one dependency, imported at RUN time -------------------"
           "-------\n"
           "# Nothing in Calango imports pycalphad; it is in no Calango "
           "environment by\n"
           "# default. The failure has to be a sentence with a command in it, "
           "not a\n"
           "# traceback, because the person reading it did not choose to "
           "depend on\n"
           "# pycalphad — they pressed a button.\n"
           "try:\n"
           "    from pycalphad import Database, equilibrium\n"
           "    from pycalphad import variables as _v\n"
           "except ImportError as _import_error:\n"
           "    _missing = (\n"
           "        \"This calculation needs pycalphad, and it is not "
           "installed in the \"\n"
           "        \"Python environment Calango is using (%s).\\n\\n\"\n"
           "        \"Install it with:\\n\"\n"
           "        \"    python -m pip install pycalphad\\n\"\n"
           "        \"or, in a conda environment:\\n\"\n"
           "        \"    conda install -c conda-forge pycalphad\\n\\n\"\n"
           "        \"Everything else in Calango's CALPHAD module — reading a "
           ".tdb, \"\n"
           "        \"fitting Redlich-Kister parameters to first-principles "
           "energies, \"\n"
           "        \"writing a database, and the binary and ternary phase "
           "diagrams — \"\n"
           "        \"runs without it.\" % _import_error)\n"
           "    print(\"CALANGO_ERROR \" + _missing, flush=True)\n"
           "    _calango_event(\"error\", _missing)\n"
           "    raise SystemExit(2)\n"
           "\n"
           "_calango_progress(0, 3)\n"
           "_calango_event(\"info\", \"Reading \" + _database_file)\n"
           "_database = Database(_database_file)\n"
           "_available = sorted(_database.phases.keys())\n"
           "# An unticked phase is SUSPENDED, not absent — but a phase the "
           "database\n"
           "# does not contain is a typo, and passing it through would fail "
           "inside\n"
           "# pycalphad with a message about the model rather than about the "
           "name.\n"
           "_phases = [_name for _name in _requested_phases "
           "if _name in _available]\n"
           "_dropped = [_name for _name in _requested_phases "
           "if _name not in _available]\n"
           "if _dropped:\n"
           "    print(\"CALANGO_WARN not in the database: \" + \", \""
           ".join(_dropped),\n"
           "          flush=True)\n"
           "if not _phases:\n"
           "    _phases = _available\n"
           "print(\"CALANGO_INFO phases=%d components=%d\"\n"
           "      % (len(_phases), len(_components)), flush=True)\n"
           "\n";

    if (config.ternary) {
        out << "# An isothermal section: both independent mole fractions are "
               "scanned and\n"
               "# the temperature is held. N = 1 fixes the system size to one "
               "mole, which\n"
               "# is what makes the reported energies per mole of atoms.\n"
               "_conditions = {\n"
               "    _v.X(_axis): (0.0, 1.0, _composition_step),\n"
               "    _v.X(_axis2): (0.0, 1.0, _composition_step),\n"
               "    _v.T: _section_temperature,\n"
               "    _v.P: _pressure,\n"
               "    _v.N: 1.0,\n"
               "}\n"
               "_calango_progress(1, 3)\n"
               "_equilibrium = equilibrium(_database, _components, _phases,\n"
               "                           _conditions)\n"
               "_calango_progress(2, 3)\n"
               "\n"
               "# squeeze() drops the length-1 N, P and T axes; the explicit\n"
               "# transpose then pins the remaining order, because the "
               "dimension\n"
               "# ordering pycalphad returns has changed between releases and "
               "indexing\n"
               "# positionally without pinning it silently transposes the "
               "diagram.\n"
               "_axis_name = \"X_\" + _axis\n"
               "_axis2_name = \"X_\" + _axis2\n"
               "_grid = _equilibrium.Phase.squeeze(drop=True).transpose(\n"
               "    _axis_name, _axis2_name, \"vertex\")\n"
               "_first = [float(_value) for _value "
               "in _grid.coords[_axis_name].values]\n"
               "_second = [float(_value) for _value "
               "in _grid.coords[_axis2_name].values]\n"
               "_values = _grid.values\n"
               "_points = []\n"
               "for _i, _x1 in enumerate(_first):\n"
               "    for _j, _x2 in enumerate(_second):\n"
               "        if _x1 + _x2 > 1.0 + 1e-9:\n"
               "            continue  # outside the composition triangle\n"
               "        _set = sorted({str(_name) for _name "
               "in _values[_i, _j, :]\n"
               "                       if str(_name).strip()})\n"
               "        if not _set:\n"
               "            continue  # the solver did not converge here\n"
               "        _points.append({\"x_\" + _axis.lower(): _x1,\n"
               "                        \"x_\" + _axis2.lower(): _x2,\n"
               "                        \"phases\": _set})\n"
               "\n"
               "_summary = {\n"
               "    \"schema\": \"calango.calphad.equilibrium/1\",\n"
               "    \"kind\": \"ternary_isothermal_section\",\n"
               "    \"database\": _database_file,\n"
               "    \"components\": _components,\n"
               "    \"phases\": _phases,\n"
               "    \"temperature_K\": float(_section_temperature),\n"
               "    \"axes\": [_axis, _axis2],\n"
               "}\n";
    } else {
        out << "# A T-x map. The upper temperature is nudged by half a step so "
               "that a\n"
               "# range whose span is an exact multiple of the step still "
               "includes its\n"
               "# own end point — numpy's arange excludes it about half the "
               "time,\n"
               "# depending on rounding, and a diagram missing its top row "
               "looks like a\n"
               "# physical result.\n"
               "_conditions = {\n"
               "    _v.X(_axis): (0.0, 1.0, _composition_step),\n"
               "    _v.T: (_temperature_min,\n"
               "           _temperature_max + 0.5 * _temperature_step,\n"
               "           _temperature_step),\n"
               "    _v.P: _pressure,\n"
               "    _v.N: 1.0,\n"
               "}\n"
               "_calango_progress(1, 3)\n"
               "_equilibrium = equilibrium(_database, _components, _phases,\n"
               "                           _conditions)\n"
               "_calango_progress(2, 3)\n"
               "\n"
               "# See the ternary branch: squeeze then transpose, because the\n"
               "# dimension order is not part of pycalphad's API.\n"
               "_axis_name = \"X_\" + _axis\n"
               "_grid = _equilibrium.Phase.squeeze(drop=True).transpose(\n"
               "    \"T\", _axis_name, \"vertex\")\n"
               "_temperatures = [float(_value) for _value "
               "in _grid.coords[\"T\"].values]\n"
               "_compositions = [float(_value) for _value\n"
               "                 in _grid.coords[_axis_name].values]\n"
               "_values = _grid.values\n"
               "_points = []\n"
               "for _i, _temperature in enumerate(_temperatures):\n"
               "    for _j, _composition in enumerate(_compositions):\n"
               "        _set = sorted({str(_name) for _name "
               "in _values[_i, _j, :]\n"
               "                       if str(_name).strip()})\n"
               "        if not _set:\n"
               "            continue  # the solver did not converge here\n"
               "        _points.append({\"T\": _temperature,\n"
               "                        \"x\": _composition,\n"
               "                        \"phases\": _set})\n"
               "\n"
               "_summary = {\n"
               "    \"schema\": \"calango.calphad.equilibrium/1\",\n"
               "    \"kind\": \"binary_tx_map\",\n"
               "    \"database\": _database_file,\n"
               "    \"components\": _components,\n"
               "    \"phases\": _phases,\n"
               "    \"axes\": [_axis],\n"
               "}\n";
    }

    out << "\n"
           "with open(_results_path, \"w\") as _handle:\n"
           "    json.dump({\"summary\": _summary, \"points\": _points}, "
           "_handle,\n"
           "              indent=2)\n"
           "_calango_progress(3, 3)\n"
           "print(\"CALANGO_INFO wrote \" + _results_path, flush=True)\n"
           "print(\"CALANGO_RESULT calphad_equilibrium=\" + _results_path,\n"
           "      flush=True)\n"
           "_calango_event(\"done\", \"%d equilibrium point(s)\" "
           "% len(_points))\n";
    return out.str();
}

} // namespace calango::core
