#include "core/ClusterExpansionScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <cstdio>
#include <sstream>

namespace calango::core {

std::string ClusterExpansionScriptGenerator::generate(
    const ClusterExpansionRunConfig& c)
{
    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — cluster-expansion batch optimization with "
        << toString(c.calculator.calculator) << ".\n"
           "# Relaxes every configuration in the input ensemble, writes the\n"
           "# ground-state trajectory, and emits cluster_expansion.json for\n"
           "# the formation-energy convex hull in the Results panel.\n"
           "# This is a plain ASE script: edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "import math\n"
           "\n"
           "from ase.io import read, write\n"
        << (c.singlePointOnly
                ? ""
                : "from ase.optimize import " + toString(c.calculator.optimizer) + "\n");
    // Variable-cell relaxation: the same ASE filter the standalone Geometry
    // Optimization run uses, imported the same way (ase.filters moved out of
    // ase.constraints in 3.23, and a batch script has to run on both).
    const bool relaxCell = !c.singlePointOnly && c.calculator.relaxCell;
    if (relaxCell)
        AseScriptGenerator::emitCellFilterImport(out, c.calculator.cellFilter);
    out << "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "input_path = r\"" << c.inputTrajectory << "\"\n"
        << "output_path = r\"" << c.outputTrajectory << "\"\n"
        << "fmax = " << c.calculator.fmax << "\n"
        << "max_steps = " << c.calculator.maxSteps << "\n"
        << "relax_cell = " << (relaxCell ? "True" : "False") << "\n"
        << "concentration_element = "
        << (c.concentrationElement.empty()
                ? std::string("None")
                : "\"" + c.concentrationElement + "\"")
        << "\n"
           "\n"
           "configs = read(input_path, index=\":\")\n"
           "if not configs:\n"
           "    raise RuntimeError(f\"No configurations found in {input_path}\")\n"
           "print(f\"CALANGO_INFO configurations={len(configs)}\", flush=True)\n"
           "\n"
           "# Concentration axis: the site fraction of one species. Picking the\n"
           "# alphabetically-second species present keeps the axis orientation\n"
           "# reproducible across runs of the same ensemble.\n"
           "species = sorted({s for atoms in configs\n"
           "                  for s in atoms.get_chemical_symbols()})\n"
           "if concentration_element is None:\n"
           "    concentration_element = species[1] if len(species) > 1 else species[0]\n"
           "print(f\"CALANGO_INFO species={','.join(species)} \"\n"
           "      f\"concentration_of={concentration_element}\", flush=True)\n"
           "\n"
           "\n"
           "def concentration_of(atoms):\n"
           "    symbols = atoms.get_chemical_symbols()\n"
           "    if not symbols:\n"
           "        return 0.0\n"
           "    return symbols.count(concentration_element) / len(symbols)\n"
           "\n"
           "\n"
           "records = []\n"
           "relaxed = []\n";

    // The calculator block is shared with every other generated script, so a
    // MACE/GPAW/QE setup behaves identically here. It binds to `atoms`, hence
    // the per-configuration rebind inside the loop below.
    out << "\n"
           "def attach_calculator(atoms):\n"
           "    \"\"\"Bind a fresh calculator to one configuration.\"\"\"\n";
    {
        // Re-indent the shared snippet into the function body.
        AseScriptGenerator::emitIndented(
            out, AseScriptGenerator::calculatorSnippet(c.calculator), "    ");
    }
    out << "    return atoms\n"
           "\n";

    // -- The design matrix ---------------------------------------------------
    //
    // Emitted literally rather than recomputed here. The builder enumerated
    // the cluster orbits and evaluated every configuration's correlation
    // vector against them; re-deriving that in Python would be a second
    // implementation of cluster enumeration whose disagreement with the first
    // would be invisible — a wrong design matrix still fits, and still yields
    // ECIs that look like physics.
    if (!c.correlations.empty()) {
        out << "# Cluster correlations, one row per configuration, in the same\n"
               "# frame order as the input trajectory. This is the design\n"
               "# matrix the ECI fit consumes; the energies below are its\n"
               "# right-hand side.\n"
               "orbit_labels = [";
        for (std::size_t i = 0; i < c.orbitLabels.size(); ++i) {
            out << (i ? ", " : "") << '"';
            for (const char ch : c.orbitLabels[i])
                if (ch == '"' || ch == '\\')
                    out << '\\' << ch;
                else
                    out << ch;
            out << '"';
        }
        out << "]\n"
               "correlations = [\n";
        char buffer[40];
        for (const auto& row : c.correlations) {
            out << "    [";
            for (std::size_t i = 0; i < row.size(); ++i) {
                // %.10g, and NOT the stream default of six significant
                // digits: the correlation columns are what the ECIs are
                // regressed against, and rounding them is rounding the
                // regressor, which biases every fitted interaction.
                std::snprintf(buffer, sizeof(buffer), "%.10g", row[i]);
                out << (i ? ", " : "") << buffer;
            }
            out << "],\n";
        }
        out << "]\n"
               "\n"
               "# The join is by FRAME INDEX, so a mismatch in length means the\n"
               "# rows no longer describe the structures. Fatal rather than\n"
               "# zipped-to-the-shorter: a design matrix silently truncated to\n"
               "# the first N configurations fits perfectly well and is wrong.\n"
               "if len(correlations) != len(configs):\n"
               "    raise RuntimeError(\n"
               "        f\"{len(correlations)} correlation rows for \"\n"
               "        f\"{len(configs)} configurations. The design matrix and \"\n"
               "        f\"the trajectory came from different builder runs; \"\n"
               "        f\"regenerate the ensemble.\")\n"
               "if correlations and any(len(row) != len(orbit_labels)\n"
               "                        for row in correlations):\n"
               "    raise RuntimeError(\n"
               "        \"Correlation rows disagree with the orbit labels; the \"\n"
               "        \"design matrix is ragged.\")\n"
               "\n";
    } else {
        // No matrix was supplied at generation time. Fall back to a sidecar
        // written beside the trajectory, so the ensemble can carry its own
        // design matrix without the builder having to thread it through the
        // run wizard. Absent, the ECI fitter refuses rather than fitting
        // against nothing.
        out << "# No design matrix was embedded at generation time. If the\n"
               "# builder wrote one beside the trajectory, use it; the join is\n"
               "# still by frame index and is still checked below.\n"
               "orbit_labels = []\n"
               "correlations = []\n"
               "# try/except rather than os.path.exists: this script does not\n"
               "# import os, and a bare `os.` here would be a NameError at run\n"
               "# time that byte-compiling cannot see.\n"
               "try:\n"
               "    with open(\"cluster_correlations.json\") as _handle:\n"
               "        _sidecar = json.load(_handle)\n"
               "    orbit_labels = _sidecar.get(\"orbit_labels\") or []\n"
               "    correlations = _sidecar.get(\"correlations\") or []\n"
               "    print(f\"CALANGO_INFO design matrix from \"\n"
               "          f\"cluster_correlations.json: {len(correlations)} x \"\n"
               "          f\"{len(orbit_labels)}\", flush=True)\n"
               "except FileNotFoundError:\n"
               "    print(\"CALANGO_WARN no cluster correlations available, so \"\n"
               "          \"cluster_expansion.json will carry no design matrix \"\n"
               "          \"and an ECI fit is not possible from it. Rebuild the \"\n"
               "          \"ensemble with the Cluster Expansion builder to get \"\n"
               "          \"one.\", flush=True)\n"
               "if len(correlations) not in (0, len(configs)):\n"
               "    raise RuntimeError(\n"
               "        f\"cluster_correlations.json has {len(correlations)} \"\n"
               "        f\"rows for {len(configs)} configurations; it belongs to \"\n"
               "        f\"a different ensemble.\")\n"
               "\n";
    }

    // g_j per configuration (Task 1, EGQCA): same join-by-frame-index
    // convention as correlations, but no ragged-row concern — it is one
    // int per config, not one row per config.
    if (!c.degeneracies.empty()) {
        out << "degeneracies = [";
        for (std::size_t i = 0; i < c.degeneracies.size(); ++i)
            out << (i ? ", " : "") << c.degeneracies[i];
        out << "]\n"
               "if len(degeneracies) != len(configs):\n"
               "    raise RuntimeError(\n"
               "        f\"{len(degeneracies)} degeneracies for \"\n"
               "        f\"{len(configs)} configurations; the ensemble and \"\n"
               "        f\"the degeneracy list came from different builder \"\n"
               "        f\"runs.\")\n"
               "\n";
    } else {
        out << "degeneracies = []\n\n";
    }

    out << "\n"
           "for index, atoms in enumerate(configs):\n"
           "    _calango_progress(index, len(configs))\n"
           "    formula = atoms.get_chemical_formula()\n"
           "    x = concentration_of(atoms)\n"
           "    _symbols = atoms.get_chemical_symbols()\n"
           "    # Full per-species composition, not just concentration_element's\n"
           "    # axis — the binary hull only ever needed the one scalar, but a\n"
           "    # ternary+ composition triangle needs every species' fraction.\n"
           "    composition = ({sp: _symbols.count(sp) / len(_symbols)\n"
           "                    for sp in species} if _symbols else {})\n"
           "    record = {\n"
           "        \"frame\": index,\n"
           "        \"formula\": formula,\n"
           "        \"concentration\": x,\n"
           "        \"composition\": composition,\n"
           "        \"degeneracy\": (degeneracies[index] if degeneracies "
                                    "else None),\n"
           "        \"natoms\": len(atoms),\n"
           "    }\n"
           "    if correlations:\n"
           "        record[\"correlation\"] = correlations[index]\n"
           "    try:\n"
           "        attach_calculator(atoms)\n";
    if (c.singlePointOnly) {
        out << "        # Single-point pass: evaluate at the builder's geometry.\n"
               "        energy = atoms.get_potential_energy()\n"
               "        record[\"steps\"] = 0\n";
    } else {
        if (relaxCell) {
            out << "        # Variable-cell: relax the atomic positions AND\n"
                   "        # the lattice of this configuration.\n";
            if (c.calculator.cellCustomMask) {
                // Voigt-order mask [xx, yy, zz, yz, xz, xy]: 1 = relax.
                out << "        _target = _CellFilter(atoms, mask=[";
                for (int i = 0; i < 6; ++i)
                    out << (c.calculator.cellMask[i] ? "1" : "0")
                        << (i < 5 ? ", " : "");
                out << "])\n";
            } else {
                out << "        _target = _CellFilter(atoms, "
                       "hydrostatic_strain="
                    << (c.calculator.cellHydrostatic ? "True" : "False")
                    << ")\n";
            }
        }
        out << "        opt = " << toString(c.calculator.optimizer) << "("
            << (relaxCell ? "_target" : "atoms")
            << ", logfile=\"-\")\n"
               "        opt.run(fmax=fmax, steps=max_steps)\n"
               "        energy = atoms.get_potential_energy()\n"
               "        record[\"steps\"] = int(opt.nsteps)\n"
               "        record[\"converged\"] = bool(\n"
               "            abs(atoms.get_forces()).max() <= fmax)\n";
        if (relaxCell)
            // The relaxed cell is the reason the run was slower, so it goes in
            // the record: a hull entry whose volume changed by 8 % is telling
            // you something the energy alone does not.
            out << "        record[\"volume\"] = float(atoms.get_volume())\n"
                   "        record[\"cell\"] = "
                   "[list(map(float, _v)) for _v in atoms.cell]\n";
    }
    out << "        record[\"energy\"] = float(energy)\n"
           "        record[\"energy_per_atom\"] = float(energy) / max(1, len(atoms))\n"
           "        relaxed.append(atoms)\n"
           "        print(f\"CALANGO_CONFIG frame={index} formula={formula} \"\n"
           "              f\"x={x:.4f} E={energy:.6f}\", flush=True)\n"
           "    except Exception as error:\n";
    if (c.continueOnFailure) {
        out << "        # One bad decoration must not lose the rest of the ensemble.\n"
               "        record[\"error\"] = str(error)\n"
               "        record[\"energy_per_atom\"] = math.nan\n"
               "        _calango_event(\"error\",\n"
               "                       f\"configuration {index} ({formula}) failed: {error}\")\n"
               "        print(f\"CALANGO_WARN frame={index} failed: {error}\", flush=True)\n";
    } else {
        out << "        raise\n";
    }
    out << "    records.append(record)\n"
           "\n"
           "_calango_progress(len(configs), len(configs))\n"
           "\n"
           "if relaxed:\n"
           "    write(output_path, relaxed)\n"
           "    print(f\"CALANGO_INFO wrote {output_path} \"\n"
           "          f\"({len(relaxed)} structures)\", flush=True)\n"
           "\n";

    // -- Formation energies ---------------------------------------------------
    //
    // Relative to the elemental endpoints, one reference energy per species —
    // the binary case (2 species) is simply this with K=2. Referencing the
    // ensemble's OWN purest-per-species configurations (rather than a
    // separate pure-element calculation) cancels the calculator's absolute
    // energy scale exactly, which is what makes hulls from different codes
    // comparable; it is also what makes this loop K-species-general for
    // free, since "purest in species s" needs no composition AXIS the way
    // the old x=0/x=1 endpoint search did.
    out << "# Formation energy per atom relative to the elemental endpoints —\n"
           "# one reference per species, generalizing the binary x=0/x=1\n"
           "# endpoints to however many species this ensemble has.\n"
           "valid = [r for r in records\n"
           "         if r.get(\"energy_per_atom\") is not None\n"
           "         and not math.isnan(r[\"energy_per_atom\"])]\n";
    if (c.useEnsembleEndpoints) {
        out << "references = {}\n"
               "if valid:\n"
               "    for _sp in species:\n"
               "        _purest = max(\n"
               "            r[\"composition\"].get(_sp, 0.0) for r in valid)\n"
               "        _candidates = [\n"
               "            r for r in valid\n"
               "            if abs(r[\"composition\"].get(_sp, 0.0) - _purest) < 1e-9]\n"
               "        references[_sp] = min(\n"
               "            r[\"energy_per_atom\"] for r in _candidates)\n";
    } else {
        // Manual references remain the two-species case the fields were
        // written for; a ternary+ ensemble asking for manual references is
        // refused (formation_energy left None) rather than silently
        // reporting energies with a missing species' contribution dropped.
        out << "references = {}\n"
               "if len(species) <= 2:\n"
               "    _other = next((s for s in species\n"
               "                  if s != concentration_element), None)\n"
               "    if _other is not None:\n"
               "        references[_other] = " << c.referenceA << "\n"
               "    references[concentration_element] = " << c.referenceB << "\n"
               "else:\n"
               "    print(\"CALANGO_WARN manual reference energies only cover \"\n"
               "          \"two species; this ensemble has \"\n"
               "          f\"{len(species)} — formation energies need \"\n"
               "          \"'Use ensemble endpoints' for more than two.\",\n"
               "          flush=True)\n";
    }
    out << "\n"
           "for record in records:\n"
           "    energy_per_atom = record.get(\"energy_per_atom\")\n"
           "    if (energy_per_atom is None or math.isnan(energy_per_atom)\n"
           "            or not references\n"
           "            or any(s not in references for s in species\n"
           "                  if record[\"composition\"].get(s, 0.0) > 1e-12)):\n"
           "        record[\"formation_energy\"] = None\n"
           "        continue\n"
           "    record[\"formation_energy\"] = energy_per_atom - sum(\n"
           "        frac * references[sp]\n"
           "        for sp, frac in record[\"composition\"].items())\n"
           "\n"
           "summary = {\n"
           "    \"concentration_element\": concentration_element,\n"
           "    \"relax_cell\": relax_cell,\n"
           "    \"species\": species,\n"
           "    \"references\": references,\n"
           "    # Kept for older binary-only consumers: the two species'\n"
           "    # references under their old names, when there are exactly two.\n"
           "    \"reference_a\": (references.get(next(\n"
           "        (s for s in species if s != concentration_element), None))\n"
           "        if len(species) == 2 else None),\n"
           "    \"reference_b\": (references.get(concentration_element)\n"
           "        if len(species) == 2 else None),\n"
           "    \"orbit_labels\": orbit_labels,\n"
           "    \"correlation_columns\": len(orbit_labels),\n"
           "    \"configurations\": records,\n"
           "}\n"
           "with open(\"cluster_expansion.json\", \"w\") as handle:\n"
           "    json.dump(summary, handle, indent=1)\n"
           "print(\"CALANGO_INFO wrote cluster_expansion.json\", flush=True)\n"
           "\n"
           "stable = [r for r in records\n"
           "          if r.get(\"formation_energy\") is not None\n"
           "          and r[\"formation_energy\"] <= 1e-9]\n"
           "print(f\"CALANGO_RESULT configurations={len(records)} \"\n"
           "      f\"relaxed={len(relaxed)} at_or_below_zero={len(stable)}\",\n"
           "      flush=True)\n"
           "\n"
           "print(\"CALANGO_DONE\", flush=True)\n";
    return out.str();
}

} // namespace calango::core
