#include "core/ClusterExpansionScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

std::string ClusterExpansionScriptGenerator::generate(
    const ClusterExpansionRunConfig& c)
{
    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — cluster-expansion batch optimization with "
        << toString(c.calculator.calculator) << ".\n"
           "# Relaxes every configuration in the input ensemble, writes the\n"
           "# ground-state trajectory, and emits cluster_expansion.json for\n"
           "# the formation-energy convex hull in the Results panel.\n"
           "# This is a plain ASE script: edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "import math\n"
           "\n"
           "from ase.io import read, write\n"
        << (c.singlePointOnly
                ? ""
                : "from ase.optimize import " + toString(c.calculator.optimizer) + "\n")
        << "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "input_path = r\"" << c.inputTrajectory << "\"\n"
        << "output_path = r\"" << c.outputTrajectory << "\"\n"
        << "fmax = " << c.calculator.fmax << "\n"
        << "max_steps = " << c.calculator.maxSteps << "\n"
        << "concentration_element = "
        << (c.concentrationElement.empty()
                ? std::string("None")
                : "\"" + c.concentrationElement + "\"")
        << "\n"
           "\n"
           "configs = read(input_path, index=\":\")\n"
           "if not configs:\n"
           "    raise RuntimeError(f\"No configurations found in {input_path}\")\n"
           "print(f\"CALANGO_INFO configurations={len(configs)}\", flush=True)\n"
           "\n"
           "# Concentration axis: the site fraction of one species. Picking the\n"
           "# alphabetically-second species present keeps the axis orientation\n"
           "# reproducible across runs of the same ensemble.\n"
           "species = sorted({s for atoms in configs\n"
           "                  for s in atoms.get_chemical_symbols()})\n"
           "if concentration_element is None:\n"
           "    concentration_element = species[1] if len(species) > 1 else species[0]\n"
           "print(f\"CALANGO_INFO species={','.join(species)} \"\n"
           "      f\"concentration_of={concentration_element}\", flush=True)\n"
           "\n"
           "\n"
           "def concentration_of(atoms):\n"
           "    symbols = atoms.get_chemical_symbols()\n"
           "    if not symbols:\n"
           "        return 0.0\n"
           "    return symbols.count(concentration_element) / len(symbols)\n"
           "\n"
           "\n"
           "records = []\n"
           "relaxed = []\n";

    // The calculator block is shared with every other generated script, so a
    // MACE/GPAW/QE setup behaves identically here. It binds to `atoms`, hence
    // the per-configuration rebind inside the loop below.
    out << "\n"
           "def attach_calculator(atoms):\n"
           "    \"\"\"Bind a fresh calculator to one configuration.\"\"\"\n";
    {
        // Re-indent the shared snippet into the function body.
        const std::string snippet =
            AseScriptGenerator::calculatorSnippet(c.calculator);
        std::istringstream lines(snippet);
        std::string line;
        while (std::getline(lines, line)) {
            if (line.empty())
                out << "\n";
            else
                out << "    " << line << "\n";
        }
    }
    out << "    return atoms\n"
           "\n";

    out << "\n"
           "for index, atoms in enumerate(configs):\n"
           "    _calango_progress(index, len(configs))\n"
           "    formula = atoms.get_chemical_formula()\n"
           "    x = concentration_of(atoms)\n"
           "    record = {\n"
           "        \"frame\": index,\n"
           "        \"formula\": formula,\n"
           "        \"concentration\": x,\n"
           "        \"natoms\": len(atoms),\n"
           "    }\n"
           "    try:\n"
           "        attach_calculator(atoms)\n";
    if (c.singlePointOnly) {
        out << "        # Single-point pass: evaluate at the builder's geometry.\n"
               "        energy = atoms.get_potential_energy()\n"
               "        record[\"steps\"] = 0\n";
    } else {
        out << "        opt = " << toString(c.calculator.optimizer)
            << "(atoms, logfile=\"-\")\n"
               "        opt.run(fmax=fmax, steps=max_steps)\n"
               "        energy = atoms.get_potential_energy()\n"
               "        record[\"steps\"] = int(opt.nsteps)\n"
               "        record[\"converged\"] = bool(\n"
               "            abs(atoms.get_forces()).max() <= fmax)\n";
    }
    out << "        record[\"energy\"] = float(energy)\n"
           "        record[\"energy_per_atom\"] = float(energy) / max(1, len(atoms))\n"
           "        relaxed.append(atoms)\n"
           "        print(f\"CALANGO_CONFIG frame={index} formula={formula} \"\n"
           "              f\"x={x:.4f} E={energy:.6f}\", flush=True)\n"
           "    except Exception as error:\n";
    if (c.continueOnFailure) {
        out << "        # One bad decoration must not lose the rest of the ensemble.\n"
               "        record[\"error\"] = str(error)\n"
               "        record[\"energy_per_atom\"] = math.nan\n"
               "        _calango_event(\"error\",\n"
               "                       f\"configuration {index} ({formula}) failed: {error}\")\n"
               "        print(f\"CALANGO_WARN frame={index} failed: {error}\", flush=True)\n";
    } else {
        out << "        raise\n";
    }
    out << "    records.append(record)\n"
           "\n"
           "_calango_progress(len(configs), len(configs))\n"
           "\n"
           "if relaxed:\n"
           "    write(output_path, relaxed)\n"
           "    print(f\"CALANGO_INFO wrote {output_path} \"\n"
           "          f\"({len(relaxed)} structures)\", flush=True)\n"
           "\n";

    // -- Formation energies -------------------------------------------------
    out << "# Formation energy per atom relative to the elemental endpoints.\n"
           "# Referencing the ensemble's own x = 0 and x = 1 configurations\n"
           "# cancels the calculator's absolute energy scale exactly, which is\n"
           "# what makes hulls from different codes comparable.\n"
           "valid = [r for r in records\n"
           "         if r.get(\"energy_per_atom\") is not None\n"
           "         and not math.isnan(r[\"energy_per_atom\"])]\n";
    if (c.useEnsembleEndpoints) {
        out << "reference_a = None\n"
               "reference_b = None\n"
               "if valid:\n"
               "    lo = min(valid, key=lambda r: r[\"concentration\"])\n"
               "    hi = max(valid, key=lambda r: r[\"concentration\"])\n"
               "    # Use the LOWEST energy found at each endpoint composition,\n"
               "    # not merely the first — the endpoint may itself appear as\n"
               "    # several decorations.\n"
               "    at_lo = [r for r in valid\n"
               "             if abs(r[\"concentration\"] - lo[\"concentration\"]) < 1e-9]\n"
               "    at_hi = [r for r in valid\n"
               "             if abs(r[\"concentration\"] - hi[\"concentration\"]) < 1e-9]\n"
               "    reference_a = min(r[\"energy_per_atom\"] for r in at_lo)\n"
               "    reference_b = min(r[\"energy_per_atom\"] for r in at_hi)\n"
               "    x_lo, x_hi = lo[\"concentration\"], hi[\"concentration\"]\n"
               "    if abs(x_hi - x_lo) < 1e-9:\n"
               "        # Fixed-composition ensemble: there is no second\n"
               "        # endpoint, so formation energies are reported relative\n"
               "        # to the most stable configuration found.\n"
               "        reference_b = reference_a\n"
               "        x_lo, x_hi = 0.0, 1.0\n";
    } else {
        out << "reference_a = " << c.referenceA << "\n"
            << "reference_b = " << c.referenceB << "\n"
               "x_lo, x_hi = 0.0, 1.0\n";
    }
    out << "\n"
           "for record in records:\n"
           "    energy_per_atom = record.get(\"energy_per_atom\")\n"
           "    if (energy_per_atom is None or math.isnan(energy_per_atom)\n"
           "            or reference_a is None):\n"
           "        record[\"formation_energy\"] = None\n"
           "        continue\n"
           "    span = (x_hi - x_lo) if abs(x_hi - x_lo) > 1e-12 else 1.0\n"
           "    t = (record[\"concentration\"] - x_lo) / span\n"
           "    record[\"formation_energy\"] = (\n"
           "        energy_per_atom - ((1.0 - t) * reference_a + t * reference_b))\n"
           "\n"
           "summary = {\n"
           "    \"concentration_element\": concentration_element,\n"
           "    \"species\": species,\n"
           "    \"reference_a\": reference_a,\n"
           "    \"reference_b\": reference_b,\n"
           "    \"configurations\": records,\n"
           "}\n"
           "with open(\"cluster_expansion.json\", \"w\") as handle:\n"
           "    json.dump(summary, handle, indent=1)\n"
           "print(\"CALANGO_INFO wrote cluster_expansion.json\", flush=True)\n"
           "\n"
           "stable = [r for r in records\n"
           "          if r.get(\"formation_energy\") is not None\n"
           "          and r[\"formation_energy\"] <= 1e-9]\n"
           "print(f\"CALANGO_RESULT configurations={len(records)} \"\n"
           "      f\"relaxed={len(relaxed)} at_or_below_zero={len(stable)}\",\n"
           "      flush=True)\n"
           "\n"
           "print(\"CALANGO_DONE\", flush=True)\n";
    return out.str();
}

} // namespace calango::core
