#include "core/CutoffConvergenceScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <algorithm>
#include <sstream>

namespace calango::core {

std::string CutoffConvergenceScriptGenerator::generate(
    const CutoffConvergenceRunConfig& config)
{
    // Ascending and unique, whatever the wizard handed over: the script takes
    // "the last cutoff" as its reference, so the ordering is load-bearing.
    std::vector<double> cutoffs = config.cutoffsEv;
    std::sort(cutoffs.begin(), cutoffs.end());
    cutoffs.erase(std::unique(cutoffs.begin(), cutoffs.end()), cutoffs.end());

    // The sweep varies PW(ecut); any other GPAW discretization would hold the
    // sweep variable constant and measure noise.
    CalculatorConfig calculator = config.calculator;
    calculator.gpawMode = GpawMode::PlaneWave;

    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — plane-wave cutoff convergence with GPAW.\n"
           "# One fixed-geometry SCF per cutoff, on the same structure. The\n"
           "# highest cutoff is the reference: every point is recorded as its\n"
           "# distance from that run in total energy per atom and in the\n"
           "# maximum force magnitude, which are the quantities a production\n"
           "# cutoff has to reproduce. Absolute totals are NOT comparable\n"
           "# between codes or PAW datasets — only these differences are.\n"
           "# This is a plain ASE script: edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "import math\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << AseScriptGenerator::gpawImports(calculator)
        << "\n"
           "# The sweep, in eV, ascending — the last entry is the reference.\n"
           "CUTOFFS = [";
    for (std::size_t i = 0; i < cutoffs.size(); ++i)
        out << (i ? ", " : "") << cutoffs[i];
    out << "]\n"
           "\n"
           "results_path = r\""
        << config.resultsJson
        << "\"\n"
           "\n"
           "atoms = read(r\""
        << config.structureFile
        << "\")\n"
           "natoms = max(1, len(atoms))\n"
           "print(f\"CALANGO_INFO natoms={len(atoms)} \"\n"
           "      f\"cutoffs={len(CUTOFFS)}\", flush=True)\n"
           "\n"
           "\n"
           "def attach_calculator(atoms, ecut):\n"
           "    \"\"\"Bind a fresh GPAW calculator at one cutoff.\n"
           "\n"
           "    Fresh per point rather than reused: a shared calculator would\n"
           "    carry the previous cutoff's converged density into the next\n"
           "    SCF and quietly smooth out the very convergence behaviour the\n"
           "    sweep is trying to measure.\n"
           "    \"\"\"\n"
           "    atoms.calc = GPAW(\n"
           "        mode=PW(ecut),  # the sweep variable, eV\n";
    {
        // The same keyword block every other generated GPAW script uses,
        // minus its mode= line — that role is taken by the loop variable
        // above. Everything else (XC, k-points, eigensolver, mixer,
        // convergence targets, spin, Hubbard U, symmetry) is held fixed
        // across the sweep, as a convergence study requires.
        const std::string keywords =
            AseScriptGenerator::gpawKeywordArguments(calculator, "        ");
        std::istringstream lines(keywords);
        std::string line;
        while (std::getline(lines, line)) {
            if (line.find("mode=PW(") != std::string::npos)
                continue;
            out << line << "\n";
        }
    }
    out << "        txt=f\"gpaw_ecut_{ecut:g}.out\",\n"
           "    )\n"
           "\n"
           "\n"
           "points = []\n"
           "evaluated = []  # per successful point: record + forces + eigenvalues\n"
           "\n"
           "for index, ecut in enumerate(CUTOFFS):\n"
           "    _calango_log.progress(index, len(CUTOFFS))\n"
           "    record = {\"ecut_eV\": float(ecut)}\n"
           "    try:\n"
           "        attach_calculator(atoms, ecut)\n"
           "        energy = float(atoms.get_potential_energy())\n"
           "        forces = np.asarray(atoms.get_forces(), dtype=float)\n"
           "        # The per-atom force NORM, not the largest Cartesian\n"
           "        # component — componentwise maxima under-report by up to\n"
           "        # sqrt(3) depending on the force's direction.\n"
           "        magnitudes = (np.linalg.norm(forces, axis=1)\n"
           "                      if forces.size else np.zeros(0))\n"
           "        fmax = float(magnitudes.max()) if magnitudes.size else 0.0\n"
           "        record[\"energy_eV\"] = energy\n"
           "        record[\"energy_per_atom_eV\"] = energy / natoms\n"
           "        record[\"fmax_eV_per_A\"] = fmax\n"
           "        # Eigenvalues for the spectral-convergence metric:\n"
           "        # k-averaged band energies (a plain mean over spins and\n"
           "        # IBZ k-points; weights deliberately ignored — this is a\n"
           "        # per-band fingerprint to difference against the\n"
           "        # reference, not a density of states).\n"
           "        band_means = None\n"
           "        try:\n"
           "            calc = atoms.calc\n"
           "            nspins = calc.get_number_of_spins()\n"
           "            nkpts = len(calc.get_ibz_k_points())\n"
           "            eig = np.array(\n"
           "                [[calc.get_eigenvalues(kpt=k, spin=s)\n"
           "                  for k in range(nkpts)]\n"
           "                 for s in range(nspins)])\n"
           "            band_means = eig.mean(axis=(0, 1))\n"
           "        except Exception as eig_error:\n"
           "            # Forces and energies still stand; the third plot\n"
           "            # simply has one point fewer.\n"
           "            print(f\"CALANGO_WARN ecut={ecut:g} no eigenvalues: \"\n"
           "                  f\"{eig_error}\", flush=True)\n"
           "        evaluated.append({\"record\": record, \"forces\": forces,\n"
           "                          \"band_means\": band_means})\n"
           "        _calango_log.metric(index, energy=energy, max_force=fmax)\n"
           "        print(f\"CALANGO_MEMBER ecut={ecut:g} E={energy:.6f} \"\n"
           "              f\"fmax={fmax:.6f}\", flush=True)\n"
           "    except Exception as error:\n";
    if (config.continueOnFailure) {
        out << "        # One diverging low-cutoff SCF must not lose the rest\n"
               "        # of the curve.\n"
               "        record[\"error\"] = str(error)\n"
               "        _calango_log.event(\"error\",\n"
               "                           f\"ecut {ecut:g} failed: {error}\")\n"
               "        print(f\"CALANGO_WARN ecut={ecut:g} failed: {error}\",\n"
               "              flush=True)\n";
    } else {
        out << "        raise\n";
    }
    out << "    points.append(record)\n"
           "\n"
           "_calango_log.progress(len(CUTOFFS), len(CUTOFFS))\n"
           "\n"
           "# -- Convergence relative to the best run --------------------------\n"
           "if not evaluated:\n"
           "    raise RuntimeError(\"Every cutoff failed — nothing to use as \"\n"
           "                       \"the convergence reference.\")\n"
           "# CUTOFFS is ascending, so the last successful point is the run at\n"
           "# the highest cutoff — the reference the sweep is judged against.\n"
           "ref = evaluated[-1]\n"
           "reference = ref[\"record\"]\n"
           "for entry in evaluated:\n"
           "    p = entry[\"record\"]\n"
           "    # ΔE = (E_total − E_reference) / N — energy convergence is\n"
           "    # judged per atom so the criterion transfers between cells.\n"
           "    p[\"delta_energy_per_atom_eV\"] = (\n"
           "        p[\"energy_eV\"] - reference[\"energy_eV\"]) / natoms\n"
           "    # Force error: the largest atom-wise |F_i − F_i,ref| — the\n"
           "    # forces are compared vector-by-vector against the reference\n"
           "    # run and NOT divided by the atom count (a force is already a\n"
           "    # per-atom quantity). Comparing max|F| scalars instead would\n"
           "    # miss two wrong forces that happen to share a magnitude.\n"
           "    p[\"force_error_eV_per_A\"] = float(\n"
           "        np.linalg.norm(entry[\"forces\"] - ref[\"forces\"],\n"
           "                       axis=1).max()) if len(atoms) else 0.0\n"
           "    p[\"delta_fmax_eV_per_A\"] = (\n"
           "        p[\"fmax_eV_per_A\"] - reference[\"fmax_eV_per_A\"])\n"
           "    # Eigenvalue convergence: mean absolute difference of the\n"
           "    # k-averaged band energies against the reference, over the\n"
           "    # bands both runs computed.\n"
           "    if (entry[\"band_means\"] is not None\n"
           "            and ref[\"band_means\"] is not None):\n"
           "        nbands = min(len(entry[\"band_means\"]),\n"
           "                     len(ref[\"band_means\"]))\n"
           "        p[\"eigenvalue_mad_eV\"] = float(\n"
           "            np.abs(entry[\"band_means\"][:nbands]\n"
           "                   - ref[\"band_means\"][:nbands]).mean())\n"
           "\n"
           "converged = [e[\"record\"] for e in evaluated]\n"
           "\n"
           "summary = {\n"
           "    \"formula\": atoms.get_chemical_formula(),\n"
           "    \"natoms\": int(len(atoms)),\n"
           "    \"cutoffs\": len(points),\n"
           "    \"evaluated\": len(converged),\n"
           "    \"failed\": len(points) - len(converged),\n"
           "    \"reference\": {\n"
           "        \"ecut_eV\": reference[\"ecut_eV\"],\n"
           "        \"energy_eV\": reference[\"energy_eV\"],\n"
           "        \"energy_per_atom_eV\": reference[\"energy_per_atom_eV\"],\n"
           "        \"fmax_eV_per_A\": reference[\"fmax_eV_per_A\"],\n"
           "    },\n"
           "}\n"
           "\n"
           "with open(results_path, \"w\") as handle:\n"
           "    json.dump({\"summary\": summary, \"points\": points}, handle,\n"
           "              indent=2)\n"
           "print(f\"CALANGO_INFO wrote {results_path}\", flush=True)\n"
           "print(\"CALANGO_RESULT cutoff_convergence=\" + results_path,\n"
           "      flush=True)\n"
           "_calango_log.event(\"done\",\n"
           "                   f\"{len(converged)} of {len(points)} cutoffs \"\n"
           "                   f\"evaluated; reference \"\n"
           "                   f\"{reference['ecut_eV']:g} eV\")\n";
    return out.str();
}

} // namespace calango::core
