#include "core/CutoffConvergenceScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"
#include "core/ConvergenceSweepBlocks.hpp"

#include <algorithm>
#include <sstream>

namespace calango::core {

std::string CutoffConvergenceScriptGenerator::generate(
    const CutoffConvergenceRunConfig& config)
{
    // Ascending and unique, whatever the wizard handed over: the script takes
    // "the last cutoff" as its reference, so the ordering is load-bearing.
    std::vector<double> cutoffs = config.cutoffsEv;
    std::sort(cutoffs.begin(), cutoffs.end());
    cutoffs.erase(std::unique(cutoffs.begin(), cutoffs.end()), cutoffs.end());

    // The sweep varies the plane-wave cutoff; for GPAW any other
    // discretization would hold the sweep variable constant and measure
    // noise, so PW mode is forced (the field is inert for VASP, which is
    // plane-wave throughout).
    CalculatorConfig calculator = config.calculator;
    calculator.gpawMode = GpawMode::PlaneWave;
    const bool vasp = calculator.calculator == CalculatorKind::Vasp;
    if (vasp) {
        // Nothing restarts between points; one cutoff's wavefunction and
        // density files must not leak into the next.
        calculator.vaspLwave = false;
        calculator.vaspLcharg = false;
    }

    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — plane-wave cutoff convergence with "
        << (vasp ? "VASP" : "GPAW") << ".\n"
           "# One fixed-geometry SCF per cutoff, on the same structure. The\n"
           "# highest cutoff is the reference: every point is recorded as its\n"
           "# distance from that run in total energy per atom and in the\n"
           "# maximum force magnitude, which are the quantities a production\n"
           "# cutoff has to reproduce. Absolute totals are NOT comparable\n"
           "# between codes or PAW datasets — only these differences are.\n"
           "# This is a plain ASE script: edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "import math\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();
    if (!vasp)
        out << AseScriptGenerator::gpawImports(calculator);
    out << "\n"
           "# The sweep, in eV, ascending — the last entry is the reference.\n"
           "CUTOFFS = [";
    for (std::size_t i = 0; i < cutoffs.size(); ++i)
        out << (i ? ", " : "") << cutoffs[i];
    out << "]\n"
           "\n"
           "results_path = r\""
        << config.resultsJson
        << "\"\n"
           "\n"
           "atoms = read(r\""
        << config.structureFile
        << "\")\n"
           "natoms = max(1, len(atoms))\n"
           "print(f\"CALANGO_INFO natoms={len(atoms)} \"\n"
           "      f\"cutoffs={len(CUTOFFS)}\", flush=True)\n"
           "\n"
           "\n"
           "def attach_calculator(atoms, ecut):\n"
           "    \"\"\"Bind a fresh calculator at one cutoff.\n"
           "\n"
           "    Fresh per point rather than reused: a shared calculator would\n"
           "    carry the previous cutoff's converged density into the next\n"
           "    SCF and quietly smooth out the very convergence behaviour the\n"
           "    sweep is trying to measure.\n"
           "    \"\"\"\n";
    if (vasp) {
        // The standard VASP calculator block (kpts, xc, INCAR extras), with
        // ENCUT then overridden by the loop variable. One directory per
        // cutoff: a shrinking basis must not pick up the previous point's
        // WAVECAR.
        const std::string snippet =
            AseScriptGenerator::calculatorSnippet(calculator);
        std::istringstream lines(snippet);
        std::string line;
        while (std::getline(lines, line)) {
            if (line.empty())
                out << "\n";
            else
                out << "    " << line << "\n";
        }
        out << "    # ENCUT is the sweep variable; istart=0 forbids any\n"
               "    # restart from a previous point's files.\n"
               "    atoms.calc.set(encut=float(ecut), istart=0,\n"
               "                   directory=f\"ecut_{ecut:g}\")\n";
    } else {
        out << "    atoms.calc = GPAW(\n"
               "        mode=PW(ecut),  # the sweep variable, eV\n";
        // The same keyword block every other generated GPAW script uses,
        // minus its mode= line — that role is taken by the loop variable
        // above. Everything else (XC, k-points, eigensolver, mixer,
        // convergence targets, spin, Hubbard U, symmetry) is held fixed
        // across the sweep, as a convergence study requires.
        const std::string keywords =
            AseScriptGenerator::gpawKeywordArguments(calculator, "        ");
        std::istringstream lines(keywords);
        std::string line;
        while (std::getline(lines, line)) {
            if (line.find("mode=PW(") != std::string::npos)
                continue;
            out << line << "\n";
        }
        out << "        txt=f\"gpaw_ecut_{ecut:g}.out\",\n"
               "    )\n";
    }
    out << ""
           "\n"
           "\n"
           "points = []\n"
           "evaluated = []  # per successful point: record + forces + eigenvalues\n"
           "\n"
           "for index, ecut in enumerate(CUTOFFS):\n"
           "    _calango_progress(index, len(CUTOFFS))\n"
           "    record = {\"ecut_eV\": float(ecut)}\n"
           "    try:\n"
           "        attach_calculator(atoms, ecut)\n"
        << convergence_sweep::measurementBlock(
               "ecut={ecut:g}",
               "        # Eigenvalues for the spectral-convergence metric:\n"
               "        # k-averaged band energies (a plain mean over spins and\n"
               "        # IBZ k-points; weights deliberately ignored — this is a\n"
               "        # per-band fingerprint to difference against the\n"
               "        # reference, not a density of states).\n")
        << "    except Exception as error:\n";
    if (config.continueOnFailure) {
        out << "        # One diverging low-cutoff SCF must not lose the rest\n"
               "        # of the curve.\n"
               "        record[\"error\"] = str(error)\n"
               "        _calango_event(\"error\",\n"
               "                       f\"ecut {ecut:g} failed: {error}\")\n"
               "        print(f\"CALANGO_WARN ecut={ecut:g} failed: {error}\",\n"
               "              flush=True)\n";
    } else {
        out << "        raise\n";
    }
    out << "    points.append(record)\n"
           "\n"
           "_calango_progress(len(CUTOFFS), len(CUTOFFS))\n"
           "\n"
        << convergence_sweep::analysisBlock(
               "# CUTOFFS is ascending, so the last successful point is the run at\n"
               "# the highest cutoff — the reference the sweep is judged against.\n",
               "cutoff")
        << "\n"
           "summary = {\n"
           "    \"formula\": atoms.get_chemical_formula(),\n"
           "    \"natoms\": int(len(atoms)),\n"
           "    \"cutoffs\": len(points),\n"
           "    \"evaluated\": len(converged),\n"
           "    \"failed\": len(points) - len(converged),\n"
           "    \"reference\": {\n"
           "        \"ecut_eV\": reference[\"ecut_eV\"],\n"
           "        \"energy_eV\": reference[\"energy_eV\"],\n"
           "        \"energy_per_atom_eV\": reference[\"energy_per_atom_eV\"],\n"
           "        \"fmax_eV_per_A\": reference[\"fmax_eV_per_A\"],\n"
           "    },\n"
           "}\n"
           "\n"
           "with open(results_path, \"w\") as handle:\n"
           "    json.dump({\"summary\": summary, \"points\": points}, handle,\n"
           "              indent=2)\n"
           "print(f\"CALANGO_INFO wrote {results_path}\", flush=True)\n"
           "print(\"CALANGO_RESULT cutoff_convergence=\" + results_path,\n"
           "      flush=True)\n"
           "_calango_event(\"done\",\n"
           "               f\"{len(converged)} of {len(points)} cutoffs \"\n"
           "               f\"evaluated; reference \"\n"
           "               f\"{reference['ecut_eV']:g} eV\")\n";
    return out.str();
}

} // namespace calango::core
