#include "core/DefectScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <algorithm>
#include <set>
#include <sstream>

namespace calango::core {

namespace {

/// Python literal for a path, or None when empty.
std::string pathLiteral(const std::string& path)
{
    return path.empty() ? std::string("None") : "r\"" + path + "\"";
}

} // namespace

std::string generateDefectScript(const DefectConfig& cfg)
{
    // q = 0 is the reference every other charge state is measured against and
    // the line the diagram is anchored on, so it is present whatever the
    // caller asked for. Sorted and de-duplicated: the diagram's envelope and
    // the transition-level search both walk the list in order.
    std::set<int> chargeSet(cfg.charges.begin(), cfg.charges.end());
    chargeSet.insert(0);

    std::ostringstream out;
    out << "# Charged-defect formation energies (FNV) — generated by Calango\n"
           "#\n"
           "#   E_f[X^q](E_F) = E_tot[X^q] - E_tot[host] - sum_i n_i mu_i\n"
           "#                   + q (E_VBM + E_F) + E_corr(q)\n"
           "#\n"
           "# One fixed-geometry SCF per charge state, then the\n"
           "# Freysoldt-Neugebauer-Van de Walle correction for the spurious\n"
           "# interaction between the periodic images of the charge and its\n"
           "# neutralizing background.\n"
           "import json\n"
           "\n"
           "import numpy as np\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "from gpaw import GPAW\n"
           "\n"
           "# --- Inherited inputs ---------------------------------------------\n"
        << "PRISTINE = " << pathLiteral(cfg.pristinePath) << "\n"
        << "NEUTRAL = " << pathLiteral(cfg.neutralDefectPath) << "\n"
        << "EPSILON = " << cfg.dielectricConstant << "\n"
        << "DEFECT_INDEX = " << cfg.defectIndex << "\n"
        << "RC = " << cfg.modelChargeRadius << "        # Angstrom\n"
        << "MODEL_ECUT = " << cfg.modelCutoffEv << "    # eV\n"
        << "RAVG = " << cfg.averagingRadius << "        # Angstrom\n"
        << "APPLY_FNV = " << (cfg.applyFnvCorrection ? "True" : "False") << "\n"
        << "FERMI_POINTS = " << std::max(2, cfg.fermiPoints) << "\n"
        << "CHARGES = [";
    bool first = true;
    for (const int q : chargeSet) {
        out << (first ? "" : ", ") << q;
        first = false;
    }
    out << "]\n";

    // Species / chemical potentials as a plain list of records, so the script
    // reads exactly what the wizard collected and the JSON can echo it back.
    out << "SPECIES = [";
    for (std::size_t i = 0; i < cfg.species.size(); ++i) {
        const DefectSpecies& s = cfg.species[i];
        out << (i ? ",\n           " : "") << "{'symbol': '" << s.symbol
            << "', 'count': " << s.count << ", 'mu_eV': "
            << s.chemicalPotentialEv << "}";
    }
    out << "]\n\n";

    out << R"PY(
# --- Host reference ------------------------------------------------------
host = GPAW(PRISTINE, txt=None)
atoms_host = host.get_atoms()
E_host = float(host.get_potential_energy())

# The Fermi level of the diagram is measured FROM THE VALENCE BAND MAXIMUM of
# the host, not from its Fermi level: E_F is a variable here (the electron
# chemical potential of the sample), and the VBM is the fixed zero the
# convention places it against.
try:
    from ase.dft.bandgap import bandgap
    gap, vbm_k, cbm_k = bandgap(host, output=None)
    eigs = np.array([host.get_eigenvalues(kpt=k, spin=s)
                     for s in range(host.get_number_of_spins())
                     for k in range(len(host.get_ibz_k_points()))])
    occ = host.get_fermi_level()
    E_VBM = float(eigs[eigs <= occ].max())
    E_CBM = float(eigs[eigs > occ].min())
    E_GAP = float(E_CBM - E_VBM)
except Exception as exc:
    raise RuntimeError(
        'Could not determine the host band edges from ' + str(PRISTINE)
        + f': {exc!r}. A charged-defect diagram is drawn across the band gap, '
          'so the host must be an insulator or semiconductor with a resolved '
          'gap — a metallic reference has no gap to place the levels in.')

if E_GAP <= 1e-3:
    raise RuntimeError(
        f'The host reference has essentially no band gap (E_gap = {E_GAP:.4f} '
        'eV). Charged-defect formation energies are only defined against a '
        'gap: in a metal the Fermi level is pinned and there is no interval '
        'for the transition levels to lie in.')

print(f'CALANGO_INFO host E_VBM={E_VBM:.4f} eV E_CBM={E_CBM:.4f} eV '
      f'E_gap={E_GAP:.4f} eV', flush=True)
_calango_progress(1, len(CHARGES) + 2)

# --- Neutral defect ------------------------------------------------------
neutral = GPAW(NEUTRAL, txt=None)
atoms_defect = neutral.get_atoms()

if len(atoms_host) == len(atoms_defect) and not SPECIES:
    print('CALANGO_WARN the defect and host cells hold the same number of '
          'atoms and no species exchange was declared. If this is a '
          'substitution, declare both the removed and the added species — '
          'otherwise the chemical-potential term is missing and every '
          'formation energy is shifted by a constant.', flush=True)

# Every charge state is run at the NEUTRAL defect's geometry with the
# NEUTRAL defect's parameters. Re-relaxing per charge would be a different
# (and more expensive) study; changing any other parameter would make the
# energy differences meaningless, since they are differences of total
# energies from separate SCFs.
base_params = dict(neutral.parameters)
base_params.pop('charge', None)
base_params.pop('txt', None)

results = {}
for step, q in enumerate(CHARGES):
    if q == 0:
        E_q = float(neutral.get_potential_energy())
        calc_q = neutral
        gpw_q = NEUTRAL
    else:
        atoms_q = atoms_defect.copy()
        calc_q = GPAW(charge=float(q), txt=f'gpaw_defect_q{q}.txt',
                      **base_params)
        atoms_q.calc = calc_q
        E_q = float(atoms_q.get_potential_energy())
        # mode='all' because the FNV alignment needs the electrostatic
        # potential on the grid, not just the energy.
        gpw_q = f'defect_q{q}.gpw'
        calc_q.write(gpw_q, mode='all')
    results[q] = {'E_tot_eV': E_q, 'gpw': gpw_q, 'correction_eV': 0.0,
                  'correction_terms': {}}
    print(f'CALANGO_INFO charge q={q:+d} E_tot={E_q:.6f} eV', flush=True)
    _calango_progress(step + 2, len(CHARGES) + 2)

# --- FNV corrections -----------------------------------------------------
# q = 0 needs none: there is no net charge, so no spurious image interaction
# and no potential to align.
if APPLY_FNV:
    from gpaw.defects import charged_defect_corrections
    for q in CHARGES:
        if q == 0:
            continue
        calc_q = GPAW(results[q]['gpw'], txt=None)
        corr = charged_defect_corrections(
            calc_pristine=host, calc_defect=calc_q,
            defect_index=DEFECT_INDEX, charge=float(q), epsilon=EPSILON,
            ecut=MODEL_ECUT, rc=RC, ravg=RAVG)
        E_corr = float(corr.calculate_correction())
        results[q]['correction_eV'] = E_corr
        results[q]['correction_terms'] = {
            'isolated_eV': float(corr.calculate_isolated_correction()
                                 * 27.211386245988),
            'periodic_eV': float(corr.calculate_periodic_correction()
                                 * 27.211386245988),
            'alignment_eV': float(corr.calculate_potential_alignment()
                                  * 27.211386245988),
        }
        print(f'CALANGO_INFO charge q={q:+d} E_corr={E_corr:+.4f} eV',
              flush=True)
else:
    print('CALANGO_WARN FNV correction disabled — the formation energies '
          'below still carry the spurious periodic-image interaction, which '
          'grows as q^2 and decays only as 1/L. Use this for a supercell '
          'convergence study, not for a number to quote.', flush=True)

# --- Formation energies --------------------------------------------------
# The chemical-potential term. `count` is how many atoms the DEFECT has that
# the host does not, so a vacancy (count = -1) ADDS mu back.
mu_term = sum(s['count'] * s['mu_eV'] for s in SPECIES)

fermi = np.linspace(0.0, E_GAP, FERMI_POINTS)
lines = {}
for q in CHARGES:
    r = results[q]
    intercept = (r['E_tot_eV'] - E_host - mu_term + q * E_VBM
                 + r['correction_eV'])
    # E_f is linear in E_F with slope q — that is the whole content of the
    # diagram, and why the charge state of a line can be read off its slope.
    lines[q] = intercept + q * fermi
    r['formation_energy_at_VBM_eV'] = float(intercept)

stack = np.array([lines[q] for q in CHARGES])
envelope = stack.min(axis=0)
stable = [CHARGES[i] for i in stack.argmin(axis=0)]

# --- Transition levels ---------------------------------------------------
# eps(q/q') is where the two lines cross:
#   E_f[q](eps) = E_f[q'](eps)  =>  eps = (I_q' - I_q) / (q - q')
# Only crossings that lie ON the lower envelope are thermodynamic transition
# levels; the others are between two states neither of which is ever the
# ground state, and reporting them as levels would be wrong.
transitions = []
for i in range(1, len(stable)):
    if stable[i] == stable[i - 1]:
        continue
    q_from, q_to = stable[i - 1], stable[i]
    I_from = results[q_from]['formation_energy_at_VBM_eV']
    I_to = results[q_to]['formation_energy_at_VBM_eV']
    if q_from == q_to:
        continue
    eps = (I_to - I_from) / (q_from - q_to)
    transitions.append({
        'from_charge': int(q_from),
        'to_charge': int(q_to),
        'level_eV_above_VBM': float(eps),
        'level_eV_below_CBM': float(E_GAP - eps),
        'formation_energy_eV': float(I_from + q_from * eps),
    })
    # "+0" is not how a charge state is written; defect notation is (+/0).
    _lbl = lambda q: ('+' * q if q > 0 else '-' * -q) or '0'
    print(f'CALANGO_INFO transition ({_lbl(q_from)}/{_lbl(q_to)}) at E_F = '
          f'{eps:.4f} eV above VBM', flush=True)

if not transitions:
    print('CALANGO_INFO no transition level inside the gap — one charge '
          'state is the ground state across the whole Fermi-level range.',
          flush=True)

summary = {
    'host': {
        'E_tot_eV': E_host,
        'E_VBM_eV': E_VBM,
        'E_CBM_eV': E_CBM,
        'E_gap_eV': E_GAP,
        'natoms': int(len(atoms_host)),
    },
    'defect': {
        'formula': atoms_defect.get_chemical_formula(),
        'natoms': int(len(atoms_defect)),
        'defect_index': int(DEFECT_INDEX),
    },
    'fnv': {
        'applied': bool(APPLY_FNV),
        'epsilon': float(EPSILON),
        'model_charge_radius_A': float(RC),
        'model_cutoff_eV': float(MODEL_ECUT),
        'averaging_radius_A': float(RAVG),
    },
    'species': SPECIES,
    'chemical_potential_term_eV': float(mu_term),
    'charges': [
        {
            'charge': int(q),
            'E_tot_eV': results[q]['E_tot_eV'],
            'correction_eV': results[q]['correction_eV'],
            'correction_terms': results[q]['correction_terms'],
            'formation_energy_at_VBM_eV':
                results[q]['formation_energy_at_VBM_eV'],
            'formation_energy_eV': [float(v) for v in lines[q]],
        }
        for q in CHARGES
    ],
    'fermi_level_eV': [float(v) for v in fermi],
    'envelope_eV': [float(v) for v in envelope],
    'stable_charge': [int(v) for v in stable],
    'transitions': transitions,
}
with open('charged_defects.json', 'w') as handle:
    json.dump(summary, handle, indent=2)

_calango_progress(len(CHARGES) + 2, len(CHARGES) + 2)
print(f'CALANGO_RESULT charged_defects=charged_defects.json '
      f'charges={len(CHARGES)} transitions={len(transitions)} '
      f'gap={E_GAP:.3f}', flush=True)
print('CALANGO_DONE', flush=True)
)PY";
    return out.str();
}

} // namespace calango::core
