#include "core/DsimScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"
#include "core/LocaleSafeNumber.hpp"

#include <sstream>

namespace calango::core {

namespace {

std::string num(double v)
{
    return localeSafeFormat(v);
}

std::string pyStr(const std::string& s)
{
    return "\"" + s + "\"";
}

/// Literal `ase.Atoms(...)` construction for one structure, so the script
/// needs no staged structure file for any of the N + N(N-1) supercells —
/// the same "precompute the geometry in C++, bake it into the script"
/// idiom ElasticScriptGenerator uses for its strain matrices.
std::string atomsLiteral(const Structure& s)
{
    std::ostringstream out;
    out << "Atoms(symbols=[";
    bool first = true;
    for (const Atom& atom : s.atoms()) {
        if (!first)
            out << ", ";
        first = false;
        out << "\"" << atom.symbol() << "\"";
    }
    out << "], positions=[";
    first = true;
    for (const Atom& atom : s.atoms()) {
        if (!first)
            out << ", ";
        first = false;
        out << "[" << num(atom.position.x) << ", " << num(atom.position.y) << ", "
            << num(atom.position.z) << "]";
    }
    out << "], cell=[";
    const auto& v = s.cell().vectors();
    for (int i = 0; i < 3; ++i) {
        out << "[" << num(v[i].x) << ", " << num(v[i].y) << ", " << num(v[i].z) << "]";
        if (i < 2)
            out << ", ";
    }
    out << "], pbc=True)";
    return out.str();
}

std::string pristineLabel(const std::string& species)
{
    return "pristine_" + species;
}

std::string impurityLabel(const std::string& solute, const std::string& host)
{
    return solute + "_in_" + host;
}

} // namespace

std::string generateDsimScript(const DsimConfig& c)
{
    const std::size_t n = c.species.size();
    std::ostringstream out;

    out << "#!/usr/bin/env python3\n"
        << "# Generated by Calango " << CALANGO_VERSION
        << " — Dilute Solution Interpolation (DSI) model for ";
    for (std::size_t i = 0; i < n; ++i)
        out << c.species[i] << (i + 1 < n ? "-" : "");
    out << ".\n"
           "#\n"
        << "# Relaxes " << n << " pristine supercell(s) and " << n * (n - 1)
        << " single-impurity supercell(s) (one per ordered species pair),\n"
           "# then interpolates the mixing enthalpy DeltaH_mix (subregular\n"
           "# solution model, Eq. 4+6+9-10 of the working paper — see\n"
           "# docs/sphinx/source/simulations/dsim.md). Every formula below is\n"
           "# reimplemented here rather than imported: this is a plain ASE\n"
           "# script, edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "from itertools import combinations_with_replacement\n"
           "\n"
           "from ase import Atoms\n"
        << "from ase.optimize import " << toString(c.calculator.optimizer) << "\n";
    AseScriptGenerator::emitCellFilterImport(out, c.calculator.cellFilter);
    out << "\n" << AseScriptGenerator::jsonLoggerPreamble();

    out << "def attach_calculator(atoms):\n"
           "    \"\"\"Bind a fresh calculator to one configuration.\"\"\"\n";
    AseScriptGenerator::emitIndented(out, AseScriptGenerator::calculatorSnippet(c.calculator), "    ");
    out << "    return atoms\n"
           "\n\n";

    out << "SPECIES = [";
    for (std::size_t i = 0; i < n; ++i)
        out << pyStr(c.species[i]) << (i + 1 < n ? ", " : "");
    out << "]\n"
        << "SUPERCELL_ATOM_COUNT = " << (c.pristine.empty() ? 0 : c.pristine.front().size()) << "\n"
           "DILUTION = 1.0 / SUPERCELL_ATOM_COUNT\n"
        << "FMAX = " << num(c.calculator.fmax) << "\n"
        << "MAX_STEPS = " << c.calculator.maxSteps << "\n"
           "\n"
           "# Every pristine and impurity supercell this run needs (Eq. 9-10),\n"
           "# precomputed by Calango's own supercell/single-substitution\n"
           "# builders and baked in as literal geometry — no separate\n"
           "# structure file to stage.\n"
           "LABELS = [\n";
    for (std::size_t i = 0; i < n; ++i)
        out << "    " << pyStr(pristineLabel(c.species[i])) << ",\n";
    for (std::size_t i = 0; i < n; ++i)
        for (std::size_t j = 0; j < n; ++j)
            if (i != j)
                out << "    " << pyStr(impurityLabel(c.species[i], c.species[j])) << ",\n";
    out << "]\n"
           "STRUCTURES = [\n";
    for (std::size_t i = 0; i < n; ++i)
        out << "    " << atomsLiteral(c.pristine[i]) << ",  # pristine " << c.species[i] << "\n";
    for (std::size_t i = 0; i < n; ++i)
        for (std::size_t j = 0; j < n; ++j)
            if (i != j)
                out << "    " << atomsLiteral(c.impurity[i][j]) << ",  # " << c.species[i]
                    << " diluted in " << c.species[j] << "\n";
    out << "]\n"
           "\n"
           "def relax(atoms, tag):\n"
           "    \"\"\"Relax ions AND cell (the paper's protocol: force "
           "criterion\n"
           "    < 0.02 eV/A INCLUDING unit-cell relaxation), return\n"
           "    {'energy': eV, 'energy_per_atom': eV, 'steps': int,\n"
           "    'converged': bool}.\n"
           "    \"\"\"\n"
           "    attach_calculator(atoms)\n"
           "    try:\n"
           "        atoms.calc.set(directory=f'calc_{tag}')\n"
           "    except Exception:\n"
           "        pass\n";
    if (c.calculator.cellCustomMask) {
        out << "    target = _CellFilter(atoms, mask=[";
        for (int i = 0; i < 6; ++i)
            out << (c.calculator.cellMask[i] ? "1" : "0") << (i < 5 ? ", " : "");
        out << "])\n";
    } else {
        out << "    target = _CellFilter(atoms, hydrostatic_strain="
            << (c.calculator.cellHydrostatic ? "True" : "False") << ")\n";
    }
    out << "    opt = " << toString(c.calculator.optimizer)
        << "(target, logfile=f'relax_{tag}.log')\n"
           "    opt.run(fmax=FMAX, steps=MAX_STEPS)\n"
           "    energy = float(atoms.get_potential_energy())\n"
           "    converged = bool(abs(atoms.get_forces()).max() <= FMAX)\n"
           "    return {'energy': energy, 'energy_per_atom': energy / len(atoms),\n"
           "            'steps': int(opt.nsteps), 'converged': converged,\n"
           "            'natoms': len(atoms), 'volume': float(atoms.get_volume()),\n"
           "            'formula': atoms.get_chemical_formula()}\n"
           "\n"
           "\n"
           "records = {}\n"
           "failures = {}\n"
           "for step, (label, atoms) in enumerate(zip(LABELS, STRUCTURES)):\n"
           "    _calango_event('start', f'relaxing {label} "
           "({len(atoms)} atoms)')\n"
           "    try:\n"
           "        records[label] = relax(atoms, label)\n"
           "        print(f'CALANGO_CONFIG label={label} '\n"
           "              f'E={records[label][\"energy\"]:.6f} '\n"
           "              f'converged={records[label][\"converged\"]}',\n"
           "              flush=True)\n"
           "    except Exception as exc:\n"
           "        failures[label] = str(exc)\n"
           "        _calango_event('error', f'{label} FAILED: {exc}')\n"
           "        print(f'CALANGO_WARN {label} failed: {exc}', flush=True)\n"
           "    _calango_progress(step + 1, len(LABELS))\n"
           "\n"
           "# -- Analysis (Eq. 4+6+9-10): only meaningful once every "
           "supercell --\n"
           "# ------- relaxed. Formulas below are the SAME as core::Dsim's\n"
           "# (computeMMatrix/enthalpyOfMixing/simplexGrid), kept in step by\n"
           "# hand since a generated script never imports Calango.\n"
           "EPSILON = 1e-8\n"
           "N = len(SPECIES)\n"
           "EV_TO_KJ_PER_MOL = 96.485332\n"
           "analysis = None\n"
           "if not failures:\n"
           "    # N x N TOTAL-energy matrix (RAW, not energy_per_atom — see\n"
           "    # Dsim.hpp's unit-convention note): diagonal pristine,\n"
           "    # off-diagonal[i][j] = species i diluted in host j.\n"
           "    energy_matrix = [[0.0] * N for _ in range(N)]\n"
           "    for i in range(N):\n"
           "        energy_matrix[i][i] = records[f'pristine_{SPECIES[i]}']['energy']\n"
           "    for i in range(N):\n"
           "        for j in range(N):\n"
           "            if i != j:\n"
           "                energy_matrix[i][j] = records[\n"
           "                    f'{SPECIES[i]}_in_{SPECIES[j]}']['energy']\n"
           "\n"
           "    m_matrix = [[0.0] * N for _ in range(N)]\n"
           "    for i in range(N):\n"
           "        for j in range(N):\n"
           "            if i != j:\n"
           "                m_matrix[i][j] = energy_matrix[i][j] - (\n"
           "                    DILUTION * energy_matrix[i][i]\n"
           "                    + (1.0 - DILUTION) * energy_matrix[j][j])\n"
           "\n"
           "    def enthalpy_of_mixing(composition):\n"
           "        total = 0.0\n"
           "        for i in range(N):\n"
           "            for j in range(i + 1, N):\n"
           "                xi, xj = composition[i], composition[j]\n"
           "                omega = (m_matrix[j][i] * xi + m_matrix[i][j] * xj) \\\n"
           "                    / (xi + xj + EPSILON)\n"
           "                total += omega * xi * xj\n"
           "        return total\n"
           "\n"
           "    def simplex_grid(resolution):\n"
           "        # combinations_with_replacement + counting -- oncapintada's\n"
           "        # own MultiComponentAlloy.simplex_grid() construction.\n"
           "        grid = []\n"
           "        for combo in combinations_with_replacement(range(N), resolution):\n"
           "            counts = [0] * N\n"
           "            for c in combo:\n"
           "                counts[c] += 1\n"
           "            grid.append([v / resolution for v in counts])\n"
           "        return grid\n"
           "\n"
           "    RESOLUTION = 100 if N == 2 else 20\n"
           "\n"
           "    binary = None\n"
           "    if N == 2:\n"
           "        x_grid = [i / RESOLUTION for i in range(RESOLUTION + 1)]\n"
           "        h_ev = [enthalpy_of_mixing([1.0 - x, x]) for x in x_grid]\n"
           "        binary = {\n"
           "            'm_b_in_a_eV': m_matrix[1][0], 'm_a_in_b_eV': m_matrix[0][1],\n"
           "            'dHdx_at_0_eV': m_matrix[1][0], 'dHdx_at_1_eV': -m_matrix[0][1],\n"
           "            'x_grid': x_grid,\n"
           "            'enthalpy_eV_per_atom': h_ev,\n"
           "            'enthalpy_kJ_per_mol': [h * EV_TO_KJ_PER_MOL for h in h_ev],\n"
           "        }\n"
           "\n"
           "    ternary = None\n"
           "    if N == 3:\n"
           "        grid = simplex_grid(RESOLUTION)\n"
           "        h_ev = [enthalpy_of_mixing(pt) for pt in grid]\n"
           "        ternary = {\n"
           "            'resolution': RESOLUTION,\n"
           "            'xB': [pt[1] for pt in grid], 'xC': [pt[2] for pt in grid],\n"
           "            'enthalpy_eV_per_atom': h_ev,\n"
           "            'enthalpy_kJ_per_mol': [h * EV_TO_KJ_PER_MOL for h in h_ev],\n"
           "        }\n"
           "\n"
           "    # Every N>=2: the N(N-1)/2 pairwise binary sub-curves (species i\n"
           "    # vs. j, every other species held at 0 -- exact for that pair,\n"
           "    # not an approximation, since the other pairwise terms vanish\n"
           "    # when a third species' fraction is 0).\n"
           "    pairwise = []\n"
           "    for i in range(N):\n"
           "        for j in range(i + 1, N):\n"
           "            x_grid = [k / RESOLUTION for k in range(RESOLUTION + 1)]\n"
           "            h_ev = []\n"
           "            for x in x_grid:\n"
           "                composition = [0.0] * N\n"
           "                composition[i] = 1.0 - x\n"
           "                composition[j] = x\n"
           "                h_ev.append(enthalpy_of_mixing(composition))\n"
           "            pairwise.append({\n"
           "                'species_i': SPECIES[i], 'species_j': SPECIES[j],\n"
           "                'x_grid': x_grid, 'enthalpy_eV_per_atom': h_ev,\n"
           "                'enthalpy_kJ_per_mol': [h * EV_TO_KJ_PER_MOL for h in h_ev],\n"
           "            })\n"
           "\n"
           "    analysis = {\n"
           "        'energy_matrix': energy_matrix, 'm_matrix': m_matrix,\n"
           "        'binary': binary, 'ternary': ternary, 'pairwise': pairwise,\n"
           "    }\n"
           "    print(f'CALANGO_INFO M matrix computed for {N} species', "
           "flush=True)\n"
           "else:\n"
           "    print(f'CALANGO_WARN {len(failures)}/{len(LABELS)} supercell(s) "
           "failed — '\n"
           "          'DeltaH_mix cannot be evaluated', flush=True)\n"
           "\n"
           "summary = {\n"
           "    'schema': 'calango.dsim/2',\n"
           "    'species': SPECIES,\n"
           "    'supercell_atom_count': SUPERCELL_ATOM_COUNT,\n"
           "    'dilution': DILUTION,\n"
        << "    'optimizer': " << pyStr(toString(c.calculator.optimizer)) << ",\n"
           "    'fmax_eV_per_A': FMAX,\n"
           "    'records': records,\n"
           "    'failures': failures,\n"
           "    'analysis': analysis,\n"
           "}\n"
           "with open('dsim.json', 'w') as handle:\n"
           "    json.dump(summary, handle, indent=2)\n"
           "\n"
           "print(f'CALANGO_RESULT dsim=dsim.json '\n"
           "      f'relaxed={len(records)}/{len(LABELS)} '\n"
           "      f'dHmix_available={analysis is not None}', flush=True)\n";

    return out.str();
}

} // namespace calango::core
