#include "core/ElasticScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"
#include "core/LocaleSafeNumber.hpp"
#include "core/StrainScriptHelpers.hpp"
#include "core/StrainVoigt.hpp"

#include <sstream>

namespace calango::core {

namespace {

std::string num(double v)
{
    return localeSafeFormat(v);
}

const char* methodRequestedLiteral(ElasticMethod m)
{
    switch (m) {
    case ElasticMethod::StressStrain:
        return "stress";
    case ElasticMethod::EnergyStrain:
        return "energy";
    case ElasticMethod::Auto:
        return "auto";
    }
    return "auto";
}

} // namespace

std::string generateElasticScript(const ElasticConfig& config)
{
    ElasticConfig cfg = config;
    const bool is2D = cfg.vacuumAxis >= 0 && cfg.vacuumAxis <= 2;

    std::vector<int> voigt = cfg.voigtComponents;
    if (voigt.empty()) {
        if (is2D) {
            voigt = inPlaneVoigtComponents(cfg.vacuumAxis);
        } else {
            for (int i = 0; i < 6; ++i)
                voigt.push_back(i);
        }
    } else if (is2D) {
        std::vector<int> filtered;
        for (int v : voigt)
            if (!voigtInvolvesAxis(v, cfg.vacuumAxis))
                filtered.push_back(v);
        voigt = filtered;
    }

    // Energy-strain needs the OFF-DIAGONAL cross-curvature stencil
    // (PAIR_POINTS below) whenever the run might end up using energy-strain
    // at all — which for ElasticMethod::Auto is only known at RUNTIME (after
    // probing whether the chosen engine implements get_stress() at the
    // reference point). Emitting the pair stencil for Auto too, even though
    // it may go unused, is the price of deciding the method from a real
    // capability probe rather than guessing ahead of time; StressStrain
    // never needs it (a single-component sweep already gives the FULL
    // stress column, off-diagonals included).
    const bool mayNeedPairs = cfg.method != ElasticMethod::StressStrain;

    std::ostringstream out;
    out << "# Elastic tensor C_ij (Voigt, GPa) — generated by Calango\n"
           "#\n"
           "# Finite-strain method: apply a small homogeneous strain to the\n"
           "# relaxed reference cell and read off either the STRESS\n"
           "# (stress-strain, primary: sigma_i = C_ij * eps_j, fit directly\n"
           "# — a single-component sweep already gives a full matrix COLUMN,\n"
           "# stress being a 6-vector) or the ENERGY (energy-strain, fallback\n"
           "# for an engine with no stress: C_jj = d^2E/deps_j^2 / V0 from a\n"
           "# quadratic fit on the diagonal, plus a combined two-component\n"
           "# stencil for the off-diagonal C_jk, j != k — the standard\n"
           "# \"independent/combined strain\" technique, e.g. Ravindran et\n"
           "# al., J. Appl. Phys. 84, 4891 (1998)). Reuses the SAME\n"
           "# strain-generation core (StrainVoigt.hpp, StrainScriptHelpers)\n"
           "# the piezoelectric module differentiates POLARIZATION over.\n"
           "#\n"
        << "# Cost: " << strainSampleMultiples(cfg.pointsPerComponent).size()
        << " evaluation(s) per requested Voigt component (" << voigt.size()
        << " requested) for stress-strain, "
        << "plus one more (shared) reference point. If the engine has no\n"
           "# stress and this run falls back to energy-strain, "
        << (mayNeedPairs ? (voigt.size() * (voigt.size() > 0 ? voigt.size() - 1 : 0) / 2 * 4) : 0)
        << " more\n"
           "# combined-strain point(s) fill in the off-diagonal terms.\n";
    if (is2D)
        out << "# 2D structure: vacuum axis " << cfg.vacuumAxis
            << "; strain restricted to the in-plane component(s) "
            << [&] {
                   std::ostringstream v;
                   v << "[";
                   for (std::size_t i = 0; i < voigt.size(); ++i)
                       v << voigt[i] << (i + 1 < voigt.size() ? ", " : "");
                   v << "]";
                   return v.str();
               }()
            << ".\n";

    if (is2D && voigt.empty()) {
        out << "raise RuntimeError(\n"
               "    'Every requested Voigt strain component touches the "
               "vacuum axis\\n'\n"
            << "    '(axis " << cfg.vacuumAxis
            << ") of this 2D structure; none of them is a physically\\n'\n"
               "    'meaningful in-plane strain. Choose from the in-plane "
               "components\\n'\n"
               "    'instead (xx, yy and/or xy for a vacuum along z).')\n";
        return out.str();
    }

    out << "import json\n"
           "from pathlib import Path\n"
           "\n"
           "import numpy as np\n"
           "from ase import units\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();

    if (cfg.baselinePath.empty()) {
        out << "from ase.io import read\n"
               "atoms = read('structure.extxyz')\n\n";
    } else {
        out << "# --- Ground-state baseline ---------------------------------\n"
               "# A completed Single-Point/Geometry-Optimization run supplies\n"
               "# the RELAXED REFERENCE geometry the strains are applied to,\n"
               "# and the calculator every strained point is rebuilt from\n"
               "# (calc.new()) — the same baseline-inheriting convention as\n"
               "# the piezoelectric module, minus its symmetry='off' forcing:\n"
               "# stress and energy, unlike the Berry phase, have no\n"
               "# objection to GPAW's ordinary symmetry reduction.\n"
               "from gpaw import GPAW\n"
               "\n"
            << "_baseline = GPAW(r\"" << cfg.baselinePath << "\", txt=None)\n"
            << "atoms = _baseline.get_atoms()\n"
               "\n";
    }

    out << strainPeriodicityGuardPython("Computing elastic constants")
        << strainVacuumAxisBlockPython(is2D ? cfg.vacuumAxis : -1);

    if (cfg.useSymmetry) {
        out << strainPointGroupDetectionPython(cfg.symmetryTolerance,
            "the tensor symmetrization is skipped (forbidden components "
            "will not be zeroed) and the crystal-class Born criterion falls "
            "back to the general (eigenvalue) one.");
    } else {
        out << "point_group = None\n"
               "point_group_ops_cartesian = []\n";
    }

    // --- Strain points, precomputed in C++ (StrainVoigt.hpp) --------------
    out << "\n"
           "# --- Strain points (Calango-precomputed deformation gradients) --\n"
        << "STRAIN_MAGNITUDE = " << num(cfg.strainMagnitude) << "\n"
           "SINGLE_POINTS = [\n";
    for (int v : voigt) {
        for (int mult : strainSampleMultiples(cfg.pointsPerComponent)) {
            const double eps = cfg.strainMagnitude * static_cast<double>(mult);
            const Matrix3 f = deformationGradient(unitVoigtStrain(v, eps));
            out << "    {\"voigt\": " << v << ", \"eps\": " << num(eps)
                << ", \"F\": " << strainMatrixLiteral(f) << "},\n";
        }
    }
    out << "]\n"
           "\n"
           "# Combined two-component points for the off-diagonal C_jk\n"
           "# (j != k) energy-strain fallback — see the module doc comment.\n"
           "# Empty when the run can only ever use stress-strain, which\n"
           "# never needs them.\n"
           "PAIR_POINTS = [\n";
    if (mayNeedPairs) {
        for (std::size_t a = 0; a < voigt.size(); ++a) {
            for (std::size_t b = a + 1; b < voigt.size(); ++b) {
                const int j = voigt[a];
                const int k = voigt[b];
                for (int sj : {-1, 1}) {
                    for (int sk : {-1, 1}) {
                        VoigtStrain vs{};
                        vs[static_cast<std::size_t>(j)] = cfg.strainMagnitude * sj;
                        vs[static_cast<std::size_t>(k)] = cfg.strainMagnitude * sk;
                        const Matrix3 f = deformationGradient(vs);
                        out << "    {\"j\": " << j << ", \"k\": " << k
                            << ", \"sj\": " << sj << ", \"sk\": " << sk
                            << ", \"F\": " << strainMatrixLiteral(f) << "},\n";
                    }
                }
            }
        }
    }
    out << "]\n"
           "\n"
        << applyStrainFunctionPython();

    out << "def strained_response(atoms, tag):\n"
           "    \"\"\"Attach a calculator to `atoms`, optionally relax the\n"
           "    internal coordinates, and return {'energy': eV, 'stress':\n"
           "    Voigt GPa list or None}. Called on a FRESH copy every time —\n"
           "    including for the eps=0 reference point (see below) — so\n"
           "    the reference and every strained point go through the exact\n"
           "    same code path, the fix the piezoelectric module needed\n"
           "    after its own reference point took a different one.\n"
           "    \"\"\"\n";
    if (cfg.baselinePath.empty()) {
        AseScriptGenerator::emitIndented(out, AseScriptGenerator::calculatorSnippet(cfg.calculator), "    ");
        out << "    # Best-effort per-point working directory / log file —\n"
               "    # silently ignored by any calculator that does not\n"
               "    # accept the keyword, so this never breaks a simple\n"
               "    # engine (EMT, MACE, ...) that does not need one.\n"
               "    try:\n"
               "        atoms.calc.set(directory=f'calc_{tag}')\n"
               "    except Exception:\n"
               "        pass\n";
    } else {
        out << "    atoms.calc = _baseline.new(txt=f'gpaw_{tag}.txt')\n";
    }
    if (cfg.relaxIons) {
        out << "    # RELAXED-ION: minimize the internal coordinates at this\n"
               "    # fixed (strained) cell before reading off stress/energy\n"
               "    # — the physical, mechanical-equilibrium response. The\n"
               "    # cell itself is never touched here, but ATOMS ARE FREE\n"
               "    # TO MOVE ALONG EVERY AXIS, including the vacuum normal\n"
               "    # for a 2D structure: a monolayer is not necessarily\n"
               "    # mirror-symmetric, and thickness change / buckling\n"
               "    # under in-plane strain is a real physical effect this\n"
               "    # deliberately does not constrain away.\n"
               "    from ase.optimize import LBFGS\n"
               "    LBFGS(atoms, logfile=f'relax_{tag}.log').run(\n"
            << "        fmax=" << num(cfg.relaxFmaxEvPerA) << ", steps="
            << cfg.relaxMaxSteps << ")\n";
    } else {
        out << "    # CLAMPED-ION: internal coordinates stay at their "
               "strain-scaled\n"
               "    # positions from apply_strain(); only the electronic "
               "state is\n"
               "    # re-converged.\n";
    }
    out << "    energy = float(atoms.get_potential_energy())\n"
           "    # Not every calculator implements a stress/virial (many\n"
           "    # classical and ML potentials do not) — caught here, once,\n"
           "    # rather than at every call site, and is exactly what the\n"
           "    # eps=0 reference point's response uses below to decide\n"
           "    # stress-strain vs. energy-strain for ElasticMethod::Auto.\n"
           "    try:\n"
           "        stress_GPa = (atoms.get_stress(voigt=True) / units.GPa).tolist()\n"
           "    except Exception:\n"
           "        stress_GPa = None\n"
           "    return {'energy': energy, 'stress': stress_GPa}\n"
           "\n"
           "\n"
           "V0 = atoms.get_volume()\n"
           "total_reference_steps = 1\n"
           "_calango_event('start', 'reference point')\n"
           "reference_response = strained_response(atoms.copy(), 'ref')\n"
           "print(f'CALANGO_INFO reference energy = "
           "{reference_response[\"energy\"]:.6f} eV, '\n"
           "      f'stress available = "
           "{reference_response[\"stress\"] is not None}', flush=True)\n"
           "\n"
        << "_method_requested = '" << methodRequestedLiteral(cfg.method) << "'\n"
        << "if _method_requested == 'auto':\n"
           "    _method = 'stress' if reference_response['stress'] is not "
           "None else 'energy'\n"
           "    if _method == 'energy':\n"
           "        print('CALANGO_WARN the selected engine does not "
           "implement a\\n'\n"
           "              '             stress tensor -- falling back to "
           "the energy-strain\\n'\n"
           "              '             method for the WHOLE run (mixing "
           "methods across\\n'\n"
           "              '             Voigt components would not be "
           "physically\\n'\n"
           "              '             consistent).', flush=True)\n"
           "elif _method_requested == 'stress':\n"
           "    if reference_response['stress'] is None:\n"
           "        raise RuntimeError(\n"
           "            'Stress-strain was explicitly requested, but the "
           "selected\\n'\n"
           "            'engine does not implement atoms.get_stress(). "
           "Choose\\n'\n"
           "            'Energy-strain (or Auto) instead.')\n"
           "    _method = 'stress'\n"
           "else:\n"
           "    _method = 'energy'\n"
           "\n"
           "WORK_POINTS = list(SINGLE_POINTS)\n"
           "if _method == 'energy':\n"
           "    WORK_POINTS = WORK_POINTS + list(PAIR_POINTS)\n"
           "total_steps = len(WORK_POINTS)\n"
           "\n"
           "by_single = {}\n"
           "by_single_failures = {}\n"
           "by_pair = {}\n"
           "by_pair_failures = {}\n"
           "step = 0\n"
           "for point in SINGLE_POINTS:\n"
           "    strained = apply_strain(atoms, point['F'])\n"
           "    tag = (f'{point[\"voigt\"]}_'\n"
           "           f'{\"p\" if point[\"eps\"] > 0 else \"m\"}'\n"
           "           f'{abs(point[\"eps\"]):.6f}')\n"
           "    try:\n"
           "        response = strained_response(strained, tag)\n"
           "    except Exception as exc:\n"
           "        by_single_failures.setdefault(\n"
           "            point['voigt'], []).append(\n"
           "                {'eps': point['eps'], 'error': str(exc)})\n"
           "        _calango_event(\n"
           "            'warning',\n"
           "            f'strain point voigt={point[\"voigt\"]} '\n"
           "            f'eps={point[\"eps\"]:+.4f} FAILED: {exc}')\n"
           "        step += 1\n"
           "        _calango_progress(step, total_steps)\n"
           "        continue\n"
           "    by_single.setdefault(point['voigt'], []).append(\n"
           "        (point['eps'], response))\n"
           "    step += 1\n"
           "    _calango_progress(step, total_steps)\n"
           "\n"
           "if _method == 'energy':\n"
           "    for point in PAIR_POINTS:\n"
           "        strained = apply_strain(atoms, point['F'])\n"
           "        tag = (f'pair_{point[\"j\"]}_{point[\"k\"]}_'\n"
           "               f'{point[\"sj\"]:+d}{point[\"sk\"]:+d}')\n"
           "        key = (point['j'], point['k'])\n"
           "        sign_key = (point['sj'], point['sk'])\n"
           "        try:\n"
           "            response = strained_response(strained, tag)\n"
           "        except Exception as exc:\n"
           "            by_pair_failures.setdefault(\n"
           "                str(key), []).append(\n"
           "                    {'signs': list(sign_key), 'error': str(exc)})\n"
           "            _calango_event(\n"
           "                'warning',\n"
           "                f'combined strain point j={point[\"j\"]} '\n"
           "                f'k={point[\"k\"]} signs={sign_key} FAILED: "
           "{exc}')\n"
           "            step += 1\n"
           "            _calango_progress(step, total_steps)\n"
           "            continue\n"
           "        by_pair.setdefault(key, {})[sign_key] = response['energy']\n"
           "        step += 1\n"
           "        _calango_progress(step, total_steps)\n"
           "\n"
           "VOIGT_PAIRS = [(0, 0), (1, 1), (2, 2), (1, 2), (0, 2), (0, 1)]\n"
           "REQUESTED_VOIGT = sorted({p['voigt'] for p in SINGLE_POINTS})\n"
           "# Zero-initialized, NOT NaN: every entry this run never touches\n"
           "# (a vacuum-axis row/column for 2D, or a genuinely missing\n"
           "# component) stays at this exact-zero placeholder all the way\n"
           "# through symmetrization below, and is converted to NaN only\n"
           "# AFTER — for the identical IEEE-754 reason the piezoelectric\n"
           "# module's own tensor is masked post-symmetrization rather than\n"
           "# pre-: 0.0 * nan is nan, not 0.0, and a genuine point-group\n"
           "# operation's EXACT-ZERO mixing coefficient (e.g. z never mixes\n"
           "# with x/y for any real 2D operation) only stays exact-zero, and\n"
           "# so correctly keeps unrelated entries clean, if what it\n"
           "# multiplies is a real number through the whole computation.\n"
           "C = np.zeros((6, 6))\n"
           "components_with_no_data = []\n"
           "# The raw stress/energy-vs-strain data behind each column, kept\n"
           "# so the results viewer can plot the linearity the fit assumes —\n"
           "# same purpose as the piezoelectric module's\n"
           "# per_component_P_of_eps.\n"
           "per_component = {}\n"
           "\n"
           "if _method == 'stress':\n"
           "    for v in REQUESTED_VOIGT:\n"
           "        points = by_single.get(v, [])\n"
           "        if not points:\n"
           "            components_with_no_data.append(v)\n"
           "            continue\n"
           "        series = ([(0.0, reference_response)]\n"
           "                  + sorted(points, key=lambda p: p[0]))\n"
           "        eps_values = np.array([p[0] for p in series])\n"
           "        per_component[v] = {\n"
           "            'eps': eps_values.tolist(),\n"
           "            'stress_GPa': [p[1]['stress'] for p in series],\n"
           "        }\n"
           "        for i in range(6):\n"
           "            if IS_2D and i == VACUUM_AXIS:\n"
           "                # A slab's out-of-plane stress component "
           "(sigma_zz and\n"
           "                # its shears) is exactly as ill-defined as the "
           "piezoelectric\n"
           "                # module's out-of-plane polarization row, for "
           "the same\n"
           "                # reason (the periodic cell integrates however "
           "much vacuum\n"
           "                # was chosen) -- left at the zero placeholder, "
           "never fit.\n"
           "                continue\n"
           "            stresses_i = np.array(\n"
           "                [p[1]['stress'][i] for p in series])\n"
           "            slope, _intercept = np.polyfit(eps_values, stresses_i, 1)\n"
           "            C[i, v] = slope\n"
           "else:\n"
           "    for v in REQUESTED_VOIGT:\n"
           "        points = by_single.get(v, [])\n"
           "        if not points:\n"
           "            components_with_no_data.append(v)\n"
           "            continue\n"
           "        series = ([(0.0, reference_response['energy'])]\n"
           "                  + [(eps, resp['energy'])\n"
           "                     for eps, resp in sorted(points, key=lambda p: p[0])])\n"
           "        eps_values = np.array([p[0] for p in series])\n"
           "        energies = np.array([p[1] for p in series])\n"
           "        per_component[v] = {\n"
           "            'eps': eps_values.tolist(),\n"
           "            'energy_eV': energies.tolist(),\n"
           "        }\n"
           "        # Quadratic fit E = c2*eps^2 + c1*eps + c0; the DIAGONAL\n"
           "        # curvature is 2*c2 (np.polyfit returns highest-degree\n"
           "        # coefficient first) -- see core::quadraticCurvature,\n"
           "        # unit-tested against synthetic data.\n"
           "        _coeffs = np.polyfit(eps_values, energies, 2)\n"
           "        curvature = 2.0 * _coeffs[0]\n"
           "        C[v, v] = curvature / V0 / units.GPa\n"
           "\n"
           "    pair_failures_full = []\n"
           "    for _a in range(len(REQUESTED_VOIGT)):\n"
           "        for _b in range(_a + 1, len(REQUESTED_VOIGT)):\n"
           "            j, k = REQUESTED_VOIGT[_a], REQUESTED_VOIGT[_b]\n"
           "            if j in components_with_no_data or k in "
           "components_with_no_data:\n"
           "                continue\n"
           "            quad = by_pair.get((j, k), {})\n"
           "            needed = {(1, 1), (1, -1), (-1, 1), (-1, -1)}\n"
           "            if not needed.issubset(quad.keys()):\n"
           "                pair_failures_full.append([j, k])\n"
           "                continue\n"
           "            # Mixed second partial derivative from the standard\n"
           "            # 4-point central-difference stencil -- see\n"
           "            # core::crossCurvature, unit-tested against\n"
           "            # synthetic data.\n"
           "            cross = (quad[(1, 1)] - quad[(1, -1)]\n"
           "                     - quad[(-1, 1)] + quad[(-1, -1)]) \\\n"
           "                / (4.0 * STRAIN_MAGNITUDE * STRAIN_MAGNITUDE)\n"
           "            Cjk = cross / V0 / units.GPa\n"
           "            C[j, k] = Cjk\n"
           "            C[k, j] = Cjk\n"
           "\n"
           "if components_with_no_data:\n"
           "    print(f'CALANGO_WARN {len(components_with_no_data)} Voigt '\n"
           "          f'component(s) have NO surviving strain point and are '\n"
           "          f'reported as NaN: {components_with_no_data}',\n"
           "          flush=True)\n"
           "\n"
           "# --- Point-group symmetrization ----------------------------------\n"
           "# Rank-4 analogue of the piezoelectric module's rank-3 tensor\n"
           "# transform: C'_ijkl = R_ii' R_jj' R_kk' R_ll' C_i'j'k'l',\n"
           "# averaged over the group. See core::symmetrizeElasticTensor for\n"
           "# the same routine in C++, unit-tested against synthetic point\n"
           "# groups. Unlike the piezoelectric tensor, C is NEVER forced to\n"
           "# zero by inversion symmetry (every rank-4 tensor is\n"
           "# inversion-invariant), so there is no centrosymmetric refusal\n"
           "# counterpart here.\n"
           "def _expand_voigt4(m):\n"
           "    t = np.zeros((3, 3, 3, 3))\n"
           "    for a, (i, j) in enumerate(VOIGT_PAIRS):\n"
           "        for b, (k, l) in enumerate(VOIGT_PAIRS):\n"
           "            v = m[a, b]\n"
           "            t[i, j, k, l] = v\n"
           "            t[j, i, k, l] = v\n"
           "            t[i, j, l, k] = v\n"
           "            t[j, i, l, k] = v\n"
           "    return t\n"
           "\n"
           "\n"
           "def _contract_voigt4(t):\n"
           "    m = np.zeros((6, 6))\n"
           "    for a, (i, j) in enumerate(VOIGT_PAIRS):\n"
           "        for b, (k, l) in enumerate(VOIGT_PAIRS):\n"
           "            m[a, b] = t[i, j, k, l]\n"
           "    return m\n"
           "\n"
           "\n"
           "def _symmetrize4(m, ops):\n"
           "    if not ops:\n"
           "        return m.copy()\n"
           "    cart = _expand_voigt4(m)\n"
           "    total = np.zeros_like(cart)\n"
           "    for r in ops:\n"
           "        total += np.einsum('ip,jq,kr,ls,pqrs->ijkl', r, r, r, r, "
           "cart)\n"
           "    return _contract_voigt4(total / len(ops))\n"
           "\n"
           "\n"
           "C_symmetrized = _symmetrize4(C, point_group_ops_cartesian)\n"
           "\n"
           "# NaN masking happens HERE, after symmetrization -- see the\n"
           "# comment beside C's zero-initialization above.\n"
           "if IS_2D:\n"
           "    C[VACUUM_AXIS, :] = np.nan\n"
           "    C[:, VACUUM_AXIS] = np.nan\n"
           "    C_symmetrized[VACUUM_AXIS, :] = np.nan\n"
           "    C_symmetrized[:, VACUUM_AXIS] = np.nan\n"
           "for _v in components_with_no_data:\n"
           "    C[:, _v] = np.nan\n"
           "    C[_v, :] = np.nan\n"
           "    C_symmetrized[:, _v] = np.nan\n"
           "    C_symmetrized[_v, :] = np.nan\n"
           "\n"
           "\n"
           "def _classify_point_group(pg):\n"
           "    cubic = {'23', 'm-3', '432', '-43m', 'm-3m'}\n"
           "    hexagonal = {'6', '-6', '6/m', '622', '6mm', '-6m2', '6/mmm'}\n"
           "    trigonal = {'3', '-3', '32', '3m', '-3m'}\n"
           "    tetragonal = {'4', '-4', '4/m', '422', '4mm', '-42m', "
           "'4/mmm'}\n"
           "    orthorhombic = {'222', 'mm2', 'mmm'}\n"
           "    if pg in cubic:\n"
           "        return 'cubic'\n"
           "    if pg in hexagonal:\n"
           "        return 'hexagonal'\n"
           "    if pg in trigonal:\n"
           "        return 'trigonal'\n"
           "    if pg in tetragonal:\n"
           "        return 'tetragonal'\n"
           "    if pg in orthorhombic:\n"
           "        return 'orthorhombic'\n"
           "    return 'other'\n"
           "\n"
           "\n"
           "def _crit(expr, value):\n"
           "    return {'expression': expr, 'value': float(value),\n"
           "            'satisfied': bool(value > 0.0)}\n"
           "\n"
           "\n"
           "def _born_criteria(c, crystal_class):\n"
           "    # Mouhat & Coudert, Phys. Rev. B 90, 224104 (2014) —\n"
           "    # identical formulas to core::bornCriteriaForClass, mirrored\n"
           "    # here so the standalone script and Calango's own logic\n"
           "    # agree (see the module doc comment: generated scripts never\n"
           "    # import Calango).\n"
           "    c11, c12, c13, c14 = c[0, 0], c[0, 1], c[0, 2], c[0, 3]\n"
           "    c22, c23 = c[1, 1], c[1, 2]\n"
           "    c33 = c[2, 2]\n"
           "    c44, c55, c66 = c[3, 3], c[4, 4], c[5, 5]\n"
           "    out = []\n"
           "    if crystal_class == 'cubic':\n"
           "        out.append(_crit('C11 - C12', c11 - c12))\n"
           "        out.append(_crit('C11 + 2*C12', c11 + 2 * c12))\n"
           "        out.append(_crit('C44', c44))\n"
           "    elif crystal_class == 'hexagonal':\n"
           "        out.append(_crit('C11 - C12', c11 - c12))\n"
           "        out.append(_crit('C33*(C11+C12) - 2*C13^2',\n"
           "                         c33 * (c11 + c12) - 2 * c13 ** 2))\n"
           "        out.append(_crit('C44', c44))\n"
           "    elif crystal_class == 'tetragonal':\n"
           "        out.append(_crit('C11 - C12', c11 - c12))\n"
           "        out.append(_crit('C33*(C11+C12) - 2*C13^2',\n"
           "                         c33 * (c11 + c12) - 2 * c13 ** 2))\n"
           "        out.append(_crit('C44', c44))\n"
           "        out.append(_crit('C66', c66))\n"
           "    elif crystal_class == 'trigonal':\n"
           "        out.append(_crit('C11 - C12', c11 - c12))\n"
           "        out.append(_crit('C44', c44))\n"
           "        out.append(_crit('C33*(C11+C12) - 2*C13^2',\n"
           "                         c33 * (c11 + c12) - 2 * c13 ** 2))\n"
           "        out.append(_crit('C44*(C11-C12) - 2*C14^2',\n"
           "                         c44 * (c11 - c12) - 2 * c14 ** 2))\n"
           "    elif crystal_class == 'orthorhombic':\n"
           "        out.append(_crit('C11', c11))\n"
           "        out.append(_crit('C11*C22 - C12^2', c11 * c22 - c12 ** 2))\n"
           "        out.append(_crit(\n"
           "            'C11*C22*C33 + 2*C12*C13*C23 - C11*C23^2 - "
           "C22*C13^2 - C33*C12^2',\n"
           "            c11 * c22 * c33 + 2 * c12 * c13 * c23 - c11 * c23 ** "
           "2\n"
           "            - c22 * c13 ** 2 - c33 * c12 ** 2))\n"
           "        out.append(_crit('C44', c44))\n"
           "        out.append(_crit('C55', c55))\n"
           "        out.append(_crit('C66', c66))\n"
           "    return out\n"
           "\n"
           "\n"
           "def _elastic_moduli(c):\n"
           "    # Voigt/Reuss/Hill averages -- Hill, Proc. Phys. Soc. A 65,\n"
           "    # 349 (1952) -- identical formulas to core::"
           "computeElasticModuli.\n"
           "    c11, c22, c33 = c[0, 0], c[1, 1], c[2, 2]\n"
           "    c12, c13, c23 = c[0, 1], c[0, 2], c[1, 2]\n"
           "    c44, c55, c66 = c[3, 3], c[4, 4], c[5, 5]\n"
           "    bulk_v = ((c11 + c22 + c33) + 2 * (c12 + c13 + c23)) / 9.0\n"
           "    shear_v = ((c11 + c22 + c33) - (c12 + c13 + c23)\n"
           "               + 3 * (c44 + c55 + c66)) / 15.0\n"
           "    result = {\n"
           "        'bulk_voigt_GPa': float(bulk_v),\n"
           "        'shear_voigt_GPa': float(shear_v),\n"
           "        'bulk_reuss_GPa': None, 'shear_reuss_GPa': None,\n"
           "        'bulk_hill_GPa': None, 'shear_hill_GPa': None,\n"
           "        'young_hill_GPa': None, 'poisson_hill': None,\n"
           "        'reuss_valid': False,\n"
           "    }\n"
           "    try:\n"
           "        s = np.linalg.inv(c)\n"
           "    except np.linalg.LinAlgError:\n"
           "        return result\n"
           "    s11, s22, s33 = s[0, 0], s[1, 1], s[2, 2]\n"
           "    s12, s13, s23 = s[0, 1], s[0, 2], s[1, 2]\n"
           "    s44, s55, s66 = s[3, 3], s[4, 4], s[5, 5]\n"
           "    bulk_r_denom = (s11 + s22 + s33) + 2 * (s12 + s13 + s23)\n"
           "    shear_r_num = (4 * (s11 + s22 + s33) - 4 * (s12 + s13 + s23)\n"
           "                   + 3 * (s44 + s55 + s66))\n"
           "    if abs(bulk_r_denom) < 1e-12 or abs(shear_r_num) < 1e-12:\n"
           "        return result\n"
           "    bulk_r = 1.0 / bulk_r_denom\n"
           "    shear_r = 15.0 / shear_r_num\n"
           "    bulk_h = 0.5 * (bulk_v + bulk_r)\n"
           "    shear_h = 0.5 * (shear_v + shear_r)\n"
           "    denom = 3 * bulk_h + shear_h\n"
           "    result['bulk_reuss_GPa'] = float(bulk_r)\n"
           "    result['shear_reuss_GPa'] = float(shear_r)\n"
           "    result['bulk_hill_GPa'] = float(bulk_h)\n"
           "    result['shear_hill_GPa'] = float(shear_h)\n"
           "    if abs(denom) < 1e-12:\n"
           "        return result\n"
           "    result['young_hill_GPa'] = float(9 * bulk_h * shear_h / "
           "denom)\n"
           "    result['poisson_hill'] = float(\n"
           "        (3 * bulk_h - 2 * shear_h) / (2 * denom))\n"
           "    result['reuss_valid'] = True\n"
           "    return result\n"
           "\n"
           "\n"
           "def _elastic_moduli_2d(c11, c22, c12):\n"
           "    det = c11 * c22 - c12 ** 2\n"
           "    return {\n"
           "        'young_x_N_per_m': float(det / c22) if abs(c22) > 1e-12 "
           "else None,\n"
           "        'young_y_N_per_m': float(det / c11) if abs(c11) > 1e-12 "
           "else None,\n"
           "        'poisson_xy': float(c12 / c22) if abs(c22) > 1e-12 else "
           "None,\n"
           "        'poisson_yx': float(c12 / c11) if abs(c11) > 1e-12 else "
           "None,\n"
           "        'layer_modulus_N_per_m': float((c11 + c22 + 2 * c12) / "
           "4.0),\n"
           "    }\n"
           "\n"
           "\n"
           "def _born_stability_2d(c11, c22, c12, c66):\n"
           "    pd = _crit('C11*C22 - C12^2', c11 * c22 - c12 ** 2)\n"
           "    sp = _crit('C66', c66)\n"
           "    return {\n"
           "        'positive_definite': pd, 'shear_positive': sp,\n"
           "        'stable': bool(pd['satisfied'] and sp['satisfied']\n"
           "                       and c11 > 0.0),\n"
           "    }\n"
           "\n"
           "\n";

    out << "if IS_2D:\n"
           "    _plane_axes = [a for a in range(3) if a != VACUUM_AXIS]\n"
           "    _p, _q = _plane_axes[0], _plane_axes[1]\n"
           "    _shear_lookup = {(0, 1): 5, (1, 0): 5, (0, 2): 4, (2, 0): 4,\n"
           "                     (1, 2): 3, (2, 1): 3}\n"
           "    _shear_idx = _shear_lookup[(_p, _q)]\n"
           "    c11_2d_GPa = float(C_symmetrized[_p, _p])\n"
           "    c22_2d_GPa = float(C_symmetrized[_q, _q])\n"
           "    c12_2d_GPa = float(C_symmetrized[_p, _q])\n"
           "    c66_2d_GPa = float(C_symmetrized[_shear_idx, _shear_idx])\n"
           "    # C_2D [N/m] = C_3D [Pa] * L_vacuum [m] -- the same\n"
           "    # \"multiply by the vacuum axis's own cell length\" identity\n"
           "    # the piezoelectric module uses (volume = area * vacuum\n"
           "    # length, guaranteed here since strain never touches the\n"
           "    # vacuum axis), converting the volumetric GPa value to the\n"
           "    # areal N/m one that does not depend on how much vacuum was\n"
           "    # chosen.\n"
           "    _vacuum_length_m = _axis_length_A * 1e-10\n"
           "\n"
           "    def _to_2d_N_per_m(value_GPa):\n"
           "        return value_GPa * 1e9 * _vacuum_length_m\n"
           "\n"
           "    c11_2d_Nm = _to_2d_N_per_m(c11_2d_GPa)\n"
           "    c22_2d_Nm = _to_2d_N_per_m(c22_2d_GPa)\n"
           "    c12_2d_Nm = _to_2d_N_per_m(c12_2d_GPa)\n"
           "    c66_2d_Nm = _to_2d_N_per_m(c66_2d_GPa)\n"
           "    moduli_2d = _elastic_moduli_2d(c11_2d_Nm, c22_2d_Nm, "
           "c12_2d_Nm)\n"
           "    stability_2d = _born_stability_2d(\n"
           "        c11_2d_Nm, c22_2d_Nm, c12_2d_Nm, c66_2d_Nm)\n"
           "    eigenvalues = None\n"
           "    crystal_class = None\n"
           "    born_criteria = []\n"
           "    stable_general = None\n"
           "    stable_class = None\n"
           "    moduli = None\n"
           "else:\n"
           "    c11_2d_Nm = c22_2d_Nm = c12_2d_Nm = c66_2d_Nm = None\n"
           "    moduli_2d = None\n"
           "    stability_2d = None\n"
           "    try:\n"
           "        eigenvalues = np.linalg.eigvalsh(C_symmetrized).tolist()\n"
           "    except Exception:\n"
           "        eigenvalues = None\n"
           "    crystal_class = (_classify_point_group(point_group)\n"
           "                     if point_group else 'other')\n"
           "    born_criteria = _born_criteria(C_symmetrized, crystal_class)\n"
           "    # None (not False) when there is nothing to report: an\n"
           "    # eigendecomposition failure, or a crystal class with no\n"
           "    # closed-form criterion (CrystalClass::Other, or no spglib).\n"
           "    # False must mean \"checked and found unstable\", never\n"
           "    # conflated with \"not checked at all\".\n"
           "    stable_general = (all(e > 0.0 for e in eigenvalues)\n"
           "                      if eigenvalues is not None else None)\n"
           "    stable_class = (all(c['satisfied'] for c in born_criteria)\n"
           "                    if born_criteria else None)\n"
           "    try:\n"
           "        moduli = _elastic_moduli(C_symmetrized)\n"
           "    except Exception:\n"
           "        moduli = None\n"
           "\n"
           "summary = {\n"
           "    'method': _method,\n"
        << "    'method_requested': _method_requested,\n"
        << "    'strain_magnitude': " << num(cfg.strainMagnitude) << ",\n"
        << "    'points_per_component': " << cfg.pointsPerComponent << ",\n"
        << "    'relax_ions': " << (cfg.relaxIons ? "True" : "False") << ",\n"
           "    'voigt_components': REQUESTED_VOIGT,\n"
           "    'point_group': point_group,\n"
           "    'crystal_class': crystal_class,\n"
           "    'is_2d': IS_2D,\n"
           "    'vacuum_axis': VACUUM_AXIS,\n"
           "    'vacuum_axis_length_A': (\n"
           "        _axis_length_A if IS_2D else None),\n"
           "    'components_with_no_data': components_with_no_data,\n"
           "    'strain_point_failures': {\n"
           "        str(k): v for k, v in by_single_failures.items()},\n"
           "    'pair_strain_point_failures': (\n"
           "        {str(k): v for k, v in by_pair_failures.items()}\n"
           "        if _method == 'energy' else {}),\n"
           "    'pair_missing': (\n"
           "        pair_failures_full if _method == 'energy' else []),\n"
           "    'per_component_response': {\n"
           "        str(k): v for k, v in per_component.items()},\n"
           "    'reference_energy_eV': reference_response['energy'],\n"
           "    'C_raw_GPa': C.tolist(),\n"
           "    'C_symmetrized_GPa': C_symmetrized.tolist(),\n"
           "    'eigenvalues_GPa': eigenvalues,\n"
           "    'stable_general': stable_general,\n"
           "    'born_criteria': born_criteria,\n"
           "    'stable_crystal_class': stable_class,\n"
           "    'moduli': moduli,\n"
           "    'C11_2D_N_per_m': c11_2d_Nm,\n"
           "    'C22_2D_N_per_m': c22_2d_Nm,\n"
           "    'C12_2D_N_per_m': c12_2d_Nm,\n"
           "    'C66_2D_N_per_m': c66_2d_Nm,\n"
           "    'moduli_2d': moduli_2d,\n"
           "    'born_stability_2d': stability_2d,\n"
           "}\n"
           "with open('elastic.json', 'w') as handle:\n"
           "    json.dump(summary, handle, indent=2)\n"
           "\n"
           "print(f'CALANGO_RESULT elastic=elastic.json '\n"
           "      f'method={_method} '\n"
           "      f'components={len(REQUESTED_VOIGT) - "
           "len(components_with_no_data)}/{len(REQUESTED_VOIGT)} '\n"
           "      f'point_group={point_group}',\n"
           "      flush=True)\n";

    return out.str();
}

} // namespace calango::core
