#include "core/ElectronicScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

std::string generateElectronicScript(const ElectronicConfig& c)
{
    std::ostringstream out;
    out << "# Electronic band structure";
    if (c.pdos && c.backend == ElectronicBackend::Gpaw)
        out << " + PDOS";
    out << " — generated by Calango\n"
           "import json\n"
           "\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "atoms = read(\"structure.extxyz\")\n"
        << "npoints = " << c.npoints << "\n"
        << "path_str = " << (c.kpath.empty() ? "None" : "\"" + c.kpath + "\"")
        << "\n"
           "bandpath = atoms.cell.bandpath(path_str, npoints=npoints)\n"
           "print(f\"CALANGO_INFO k-path {bandpath.path}\", flush=True)\n"
           "_calango_log.progress(1, 4)\n"
           "\n"
           "pdos = None\n";

    switch (c.backend) {
    case ElectronicBackend::FreeElectrons:
        out << "# Empty-lattice (free-electron) reference bands — always\n"
               "# available, no electronic-structure package required.\n"
               "from ase.calculators.test import FreeElectrons\n"
               "\n"
            << "atoms.calc = FreeElectrons(nvalence=" << c.nvalence << ",\n"
               "                           kpts={\"path\": bandpath.path,\n"
               "                                 \"npoints\": npoints})\n"
               "atoms.get_potential_energy()\n"
               "_calango_log.progress(3, 4)\n"
               "bs = atoms.calc.band_structure()\n"
               "efermi = float(bs.reference)\n";
        break;

    case ElectronicBackend::Gpaw:
        out << AseScriptGenerator::gpawImports(c.gpaw) << "\n";
        if (!c.baselineDensityPath.empty()) {
            // Non-self-consistent (NSCF) run off a converged baseline density:
            // load the .gpw the Single-Point Calculation saved and evaluate the
            // band dispersion + PDOS at fixed charge density. No inline SCF.
            out << "# NSCF band structure from a fixed baseline charge density\n"
                   "# (produced by a prior Single-Point Calculation).\n"
                << "calc = GPAW(\"" << c.baselineDensityPath
                << "\", txt=\"gpaw_bands.txt\")\n"
                   "atoms = calc.get_atoms()\n"
                   "efermi = float(calc.get_fermi_level())\n"
                   "_calango_log.progress(2, 4)\n"
                   "\n"
                   "band_calc = calc.fixed_density(kpts=bandpath, "
                   "symmetry=\"off\",\n"
                   "                               txt=\"gpaw_bands.txt\")\n"
                   "bs = band_calc.band_structure()\n"
                   "_calango_log.progress(3, 4)\n";
        } else {
            // Legacy self-contained path: converge the SCF density inline, then
            // the NSCF band run reuses it via fixed_density.
            out << "calc = GPAW(\n"
                << AseScriptGenerator::gpawKeywordArguments(c.gpaw, "    ")
                << "    txt=\"gpaw_scf.txt\",\n"
                   ")\n"
                   "atoms.calc = calc\n"
                   "atoms.get_potential_energy()\n"
                   "efermi = float(calc.get_fermi_level())\n"
                   "_calango_log.progress(2, 4)\n"
                   "\n"
                   "band_calc = calc.fixed_density(kpts=bandpath, "
                   "symmetry=\"off\",\n"
                   "                               txt=\"gpaw_bands.txt\")\n"
                   "bs = band_calc.band_structure()\n"
                   "_calango_log.progress(3, 4)\n";
        }
        if (c.spinOrbit)
            // Non-perturbative SOC: the scalar-relativistic states along the
            // path are re-diagonalized in the spinor basis, so the result is
            // ONE spin channel of doubled, spin-mixed bands rather than the
            // two collinear channels. The Fermi level moves with them, which
            // is why it is re-read here rather than kept from the SCF.
            out << "\n"
                   "# --- Spin-orbit coupling -----------------------------------\n"
                   "# Re-diagonalizes the converged states in the spinor basis\n"
                   "# (gpaw.spinorbit). Lifts the degeneracies a scalar-\n"
                   "# relativistic run leaves: the Γ-point valence band of a\n"
                   "# III-V semiconductor, Rashba splitting, band inversion.\n"
                   "import numpy as _np\n"
                   "from ase.spectrum.band_structure import BandStructure\n"
                   "from gpaw.spinorbit import soc_eigenstates\n"
                   "\n"
                   "_soc = soc_eigenstates(band_calc)\n"
                   "_soc_energies = _np.asarray(_soc.eigenvalues())\n"
                   "efermi = float(_soc.fermi_level)\n"
                   "# (nkpt, nband) -> (1, nkpt, nband): spinor bands are a\n"
                   "# single channel, not a spin-up/spin-down pair.\n"
                   "bs = BandStructure(path=bs.path,\n"
                   "                   energies=_soc_energies[_np.newaxis],\n"
                   "                   reference=efermi)\n"
                   "print(f\"CALANGO_INFO spin-orbit coupling applied, \"\n"
                   "      f\"E_F = {efermi:.4f} eV\", flush=True)\n";
        if (c.pdos)
            out << "\n"
                   "# Element/orbital-projected DOS. The projection is re-sampled\n"
                   "# at a dedicated (typically denser) fixed-density k-mesh so\n"
                   "# the DOS is smooth independently of the SCF/band sampling.\n"
                << "pdos_npts = " << c.pdosPoints << "\n"
                << "pdos_width = " << c.pdosWidthEv << "\n"
                << "pdos_kpts = (" << c.pdosKpts[0] << ", " << c.pdosKpts[1]
                << ", " << c.pdosKpts[2] << ")\n"
                << "dos_calc = calc.fixed_density(kpts=pdos_kpts, symmetry=\"off\",\n"
                   "                              txt=\"gpaw_pdos.txt\")\n"
                   "\n"
                   "# Projection API. GPAW 26 made its NEW engine the default,\n"
                   "# and that engine dropped `get_orbital_ldos` — so on GPAW 26\n"
                   "# the old call raises AttributeError for every atom, every\n"
                   "# projection is skipped, and the run finishes with no PDOS\n"
                   "# and no error. gpaw.dos.DOSCalculator.raw_pdos has an\n"
                   "# identical signature in both engines and is the portable\n"
                   "# route; the legacy call is kept only for GPAW versions old\n"
                   "# enough to predate it.\n"
                   "#\n"
                   "# shift_fermi_level=False keeps the energies on the same\n"
                   "# absolute scale as `efermi` below, which is what the viewer\n"
                   "# plots the Fermi line against.\n"
                   "_dos = None\n"
                   "try:\n"
                   "    from gpaw.dos import DOSCalculator\n"
                   "\n"
                   "    _dos = DOSCalculator.from_calculator(dos_calc,\n"
                   "                                         shift_fermi_level=False)\n"
                   "except Exception as _e:\n"
                   "    print(f\"CALANGO_INFO DOSCalculator unavailable ({_e!r}); \"\n"
                   "          \"falling back to get_orbital_ldos\", flush=True)\n"
                   "\n"
                   "projections = {}\n"
                   "pdos_energies = None\n"
                   "if _dos is not None:\n"
                   "    # The calculator's own energy window spans the computed\n"
                   "    # eigenvalues, so the grid always covers the bands.\n"
                   "    pdos_energies = _dos.get_energies(npoints=pdos_npts)\n"
                   "for index, symbol in enumerate(atoms.get_chemical_symbols()):\n"
                   "    for angular_index, angular in enumerate(\"spdf\"):\n"
                   "        if _dos is not None:\n"
                   "            try:\n"
                   "                d = _dos.raw_pdos(pdos_energies, a=index,\n"
                   "                                  l=angular_index,\n"
                   "                                  width=pdos_width)\n"
                   "            except Exception:\n"
                   "                continue  # shell absent from this species\n"
                   "        else:\n"
                   "            try:\n"
                   "                e, d = dos_calc.get_orbital_ldos(\n"
                   "                    a=index, angular=angular, npts=pdos_npts,\n"
                   "                    width=pdos_width)\n"
                   "            except Exception:\n"
                   "                continue\n"
                   "            pdos_energies = e\n"
                   "        d = [float(v) for v in d]\n"
                   "        if max(d) <= 1e-10:\n"
                   "            continue  # orbital not present on this species\n"
                   "        key = f\"{symbol} {angular}\"\n"
                   "        if key in projections:\n"
                   "            projections[key] = [a + b for a, b in\n"
                   "                                zip(projections[key], d)]\n"
                   "        else:\n"
                   "            projections[key] = d\n"
                   "if projections:\n"
                   "    pdos = {\"energies\": [float(v) for v in pdos_energies],\n"
                   "            \"efermi\": efermi, \"projections\": projections}\n"
                   "    print(f\"CALANGO_INFO pdos channels: \"\n"
                   "          f\"{sorted(projections)}\", flush=True)\n"
                   "else:\n"
                   "    # Loud, not silent: a missing PDOS used to look like a\n"
                   "    # successful run that simply had nothing to show.\n"
                   "    print(\"CALANGO_INFO no PDOS projections were produced\",\n"
                   "          flush=True)\n";
        break;

    case ElectronicBackend::Espresso:
        out << "# Quantum ESPRESSO workflow (pw.x must be installed).\n"
               "# EDIT ME: point pseudopotentials at your SSSP/pslibrary set.\n"
               "from ase.calculators.espresso import Espresso\n"
               "\n"
               "pseudopotentials = {s: f\"{s}.UPF\" for s in\n"
               "                    set(atoms.get_chemical_symbols())}\n"
            << "kgrid = " << c.scfKpts << "\n"
            << "scf = Espresso(pseudopotentials=pseudopotentials,\n"
               "               input_data={\"control\": {\"calculation\": \"scf\"},\n"
            << "                           \"system\": {\"ecutwfc\": "
            << c.ecutEv / 13.605693122994 << "}},\n"
               "               kpts=(kgrid, kgrid, kgrid))\n"
               "atoms.calc = scf\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_log.progress(2, 4)\n"
               "\n"
               "bands = Espresso(pseudopotentials=pseudopotentials,\n"
               "                 input_data={\"control\": {\"calculation\": \"bands\",\n"
               "                                         \"restart_mode\": \"restart\"},\n"
            << "                             \"system\": {\"ecutwfc\": "
            << c.ecutEv / 13.605693122994 << "}},\n"
               "                 kpts=bandpath)\n"
               "atoms.calc = bands\n"
               "atoms.get_potential_energy()\n"
               "bs = atoms.calc.band_structure()\n"
               "bs._reference = efermi\n"
               "_calango_log.progress(3, 4)\n";
        break;

    case ElectronicBackend::Siesta:
        out << "# SIESTA workflow (requires the siesta binary + SIESTA_PP_PATH).\n"
               "# EDIT ME: set the pseudopotential family / basis set.\n"
               "from ase.calculators.siesta import Siesta\n"
               "from ase.units import Ry\n"
               "\n"
            << "kgrid = " << c.scfKpts << "\n"
            << "scf = Siesta(xc=\"PBE\", mesh_cutoff=200 * Ry,\n"
               "             energy_shift=0.01 * Ry,\n"
               "             kpts=[kgrid, kgrid, kgrid])\n"
               "atoms.calc = scf\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_log.progress(2, 4)\n"
               "\n"
               "# Non-self-consistent band run along the path.\n"
               "bands = Siesta(xc=\"PBE\", mesh_cutoff=200 * Ry,\n"
               "               energy_shift=0.01 * Ry, kpts=bandpath)\n"
               "atoms.calc = bands\n"
               "atoms.get_potential_energy()\n"
               "bs = atoms.calc.band_structure()\n"
               "bs._reference = efermi\n"
               "_calango_log.progress(3, 4)\n";
        break;

    case ElectronicBackend::Vasp:
        out << "# VASP workflow (requires VASP_PP_PATH + ASE_VASP_COMMAND).\n"
               "# EDIT ME: adjust the INCAR tags for your system.\n"
               "from ase.calculators.vasp import Vasp\n"
               "\n"
            << "kgrid = " << c.scfKpts << "\n"
            << "scf = Vasp(xc=\"PBE\", encut=" << c.ecutEv << ",\n"
               "           kpts=(kgrid, kgrid, kgrid), ismear=0, sigma=0.05,\n"
               "           directory=\".\")\n"
               "atoms.calc = scf\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_log.progress(2, 4)\n"
               "\n"
               "# Non-self-consistent band run (ICHARG=11 reuses the SCF density).\n"
            << "bands = Vasp(xc=\"PBE\", encut=" << c.ecutEv << ", icharg=11,\n"
               "             directory=\".\", kpts=bandpath)\n"
               "atoms.calc = bands\n"
               "atoms.get_potential_energy()\n"
               "bs = atoms.calc.band_structure()\n"
               "bs._reference = efermi\n"
               "_calango_log.progress(3, 4)\n";
        break;
    }

    out << "\n"
           "x, special_x, special_labels = bs.path.get_linear_kpoint_axis()\n"
           "data = {\n"
           "    \"x\": list(map(float, x)),\n"
           "    \"special_x\": list(map(float, special_x)),\n"
           "    \"special_labels\": list(special_labels),\n"
           "    \"efermi\": float(efermi),\n"
           "    # energies[spin][kpoint][band] in eV\n"
           "    \"energies\": [[list(map(float, kpt)) for kpt in spin]\n"
           "                 for spin in bs.energies],\n"
           "}\n"
           "with open(\"bands.json\", \"w\") as handle:\n"
           "    json.dump(data, handle)\n"
           "if pdos is not None:\n"
           "    with open(\"pdos.json\", \"w\") as handle:\n"
           "        json.dump(pdos, handle)\n"
           "_calango_log.progress(4, 4)\n"
           "print(f\"CALANGO_RESULT bands={len(data['energies'][0][0])} \"\n"
           "      f\"kpts={len(data['x'])} efermi_eV={efermi:.4f}\", flush=True)\n";
    return out.str();
}

} // namespace calango::core
