#include "core/ElectronicScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

std::string generateElectronicScript(const ElectronicConfig& c)
{
    std::ostringstream out;
    out << "# Electronic band structure";
    if (c.pdos && c.backend == ElectronicBackend::Gpaw)
        out << " + PDOS";
    out << " — generated by Calango\n"
           "import json\n"
           "\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "atoms = read(\"structure.extxyz\")\n"
        << "npoints = " << c.npoints << "\n"
        << "path_str = " << (c.kpath.empty() ? "None" : "\"" + c.kpath + "\"")
        << "\n"
           "bandpath = atoms.cell.bandpath(path_str, npoints=npoints)\n"
           "print(f\"CALANGO_INFO k-path {bandpath.path}\", flush=True)\n"
           "_calango_log.progress(1, 4)\n"
           "\n"
           "pdos = None\n";

    switch (c.backend) {
    case ElectronicBackend::FreeElectrons:
        out << "# Empty-lattice (free-electron) reference bands — always\n"
               "# available, no electronic-structure package required.\n"
               "from ase.calculators.test import FreeElectrons\n"
               "\n"
            << "atoms.calc = FreeElectrons(nvalence=" << c.nvalence << ",\n"
               "                           kpts={\"path\": bandpath.path,\n"
               "                                 \"npoints\": npoints})\n"
               "atoms.get_potential_energy()\n"
               "_calango_log.progress(3, 4)\n"
               "bs = atoms.calc.band_structure()\n"
               "efermi = float(bs.reference)\n";
        break;

    case ElectronicBackend::Gpaw:
        out << "from gpaw import GPAW, PW\n"
               "\n"
            << "kgrid = " << c.scfKpts << "\n"
            << "calc = GPAW(mode=PW(" << c.ecutEv << "), xc=\"PBE\",\n"
               "            kpts=(kgrid, kgrid, kgrid),\n"
               "            txt=\"gpaw_scf.txt\")\n"
               "atoms.calc = calc\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(calc.get_fermi_level())\n"
               "_calango_log.progress(2, 4)\n"
               "\n"
               "band_calc = calc.fixed_density(kpts=bandpath, symmetry=\"off\",\n"
               "                               txt=\"gpaw_bands.txt\")\n"
               "bs = band_calc.band_structure()\n"
               "_calango_log.progress(3, 4)\n";
        if (c.pdos)
            out << "\n"
                   "# Element/orbital-projected DOS from the SCF wavefunctions.\n"
                << "pdos_npts = " << c.pdosPoints << "\n"
                << "pdos_width = " << c.pdosWidthEv << "\n"
                << "projections = {}\n"
                   "pdos_energies = None\n"
                   "for index, symbol in enumerate(atoms.get_chemical_symbols()):\n"
                   "    for angular in \"spdf\":\n"
                   "        try:\n"
                   "            e, d = calc.get_orbital_ldos(a=index, angular=angular,\n"
                   "                                         npts=pdos_npts,\n"
                   "                                         width=pdos_width)\n"
                   "        except Exception:\n"
                   "            continue\n"
                   "        if max(d) <= 1e-10:\n"
                   "            continue  # orbital not present on this species\n"
                   "        pdos_energies = e\n"
                   "        key = f\"{symbol} {angular}\"\n"
                   "        if key in projections:\n"
                   "            projections[key] = [a + b for a, b in\n"
                   "                                zip(projections[key], d)]\n"
                   "        else:\n"
                   "            projections[key] = list(map(float, d))\n"
                   "if projections:\n"
                   "    pdos = {\"energies\": list(map(float, pdos_energies)),\n"
                   "            \"efermi\": efermi, \"projections\": projections}\n";
        break;

    case ElectronicBackend::Espresso:
        out << "# Quantum ESPRESSO workflow (pw.x must be installed).\n"
               "# EDIT ME: point pseudopotentials at your SSSP/pslibrary set.\n"
               "from ase.calculators.espresso import Espresso\n"
               "\n"
               "pseudopotentials = {s: f\"{s}.UPF\" for s in\n"
               "                    set(atoms.get_chemical_symbols())}\n"
            << "kgrid = " << c.scfKpts << "\n"
            << "scf = Espresso(pseudopotentials=pseudopotentials,\n"
               "               input_data={\"control\": {\"calculation\": \"scf\"},\n"
            << "                           \"system\": {\"ecutwfc\": "
            << c.ecutEv / 13.605693122994 << "}},\n"
               "               kpts=(kgrid, kgrid, kgrid))\n"
               "atoms.calc = scf\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_log.progress(2, 4)\n"
               "\n"
               "bands = Espresso(pseudopotentials=pseudopotentials,\n"
               "                 input_data={\"control\": {\"calculation\": \"bands\",\n"
               "                                         \"restart_mode\": \"restart\"},\n"
            << "                             \"system\": {\"ecutwfc\": "
            << c.ecutEv / 13.605693122994 << "}},\n"
               "                 kpts=bandpath)\n"
               "atoms.calc = bands\n"
               "atoms.get_potential_energy()\n"
               "bs = atoms.calc.band_structure()\n"
               "bs._reference = efermi\n"
               "_calango_log.progress(3, 4)\n";
        break;

    case ElectronicBackend::Siesta:
        out << "# SIESTA workflow (requires the siesta binary + SIESTA_PP_PATH).\n"
               "# EDIT ME: set the pseudopotential family / basis set.\n"
               "from ase.calculators.siesta import Siesta\n"
               "from ase.units import Ry\n"
               "\n"
            << "kgrid = " << c.scfKpts << "\n"
            << "scf = Siesta(xc=\"PBE\", mesh_cutoff=200 * Ry,\n"
               "             energy_shift=0.01 * Ry,\n"
               "             kpts=[kgrid, kgrid, kgrid])\n"
               "atoms.calc = scf\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_log.progress(2, 4)\n"
               "\n"
               "# Non-self-consistent band run along the path.\n"
               "bands = Siesta(xc=\"PBE\", mesh_cutoff=200 * Ry,\n"
               "               energy_shift=0.01 * Ry, kpts=bandpath)\n"
               "atoms.calc = bands\n"
               "atoms.get_potential_energy()\n"
               "bs = atoms.calc.band_structure()\n"
               "bs._reference = efermi\n"
               "_calango_log.progress(3, 4)\n";
        break;

    case ElectronicBackend::Vasp:
        out << "# VASP workflow (requires VASP_PP_PATH + ASE_VASP_COMMAND).\n"
               "# EDIT ME: adjust the INCAR tags for your system.\n"
               "from ase.calculators.vasp import Vasp\n"
               "\n"
            << "kgrid = " << c.scfKpts << "\n"
            << "scf = Vasp(xc=\"PBE\", encut=" << c.ecutEv << ",\n"
               "           kpts=(kgrid, kgrid, kgrid), ismear=0, sigma=0.05,\n"
               "           directory=\".\")\n"
               "atoms.calc = scf\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_log.progress(2, 4)\n"
               "\n"
               "# Non-self-consistent band run (ICHARG=11 reuses the SCF density).\n"
            << "bands = Vasp(xc=\"PBE\", encut=" << c.ecutEv << ", icharg=11,\n"
               "             directory=\".\", kpts=bandpath)\n"
               "atoms.calc = bands\n"
               "atoms.get_potential_energy()\n"
               "bs = atoms.calc.band_structure()\n"
               "bs._reference = efermi\n"
               "_calango_log.progress(3, 4)\n";
        break;
    }

    out << "\n"
           "x, special_x, special_labels = bs.path.get_linear_kpoint_axis()\n"
           "data = {\n"
           "    \"x\": list(map(float, x)),\n"
           "    \"special_x\": list(map(float, special_x)),\n"
           "    \"special_labels\": list(special_labels),\n"
           "    \"efermi\": float(efermi),\n"
           "    # energies[spin][kpoint][band] in eV\n"
           "    \"energies\": [[list(map(float, kpt)) for kpt in spin]\n"
           "                 for spin in bs.energies],\n"
           "}\n"
           "with open(\"bands.json\", \"w\") as handle:\n"
           "    json.dump(data, handle)\n"
           "if pdos is not None:\n"
           "    with open(\"pdos.json\", \"w\") as handle:\n"
           "        json.dump(pdos, handle)\n"
           "_calango_log.progress(4, 4)\n"
           "print(f\"CALANGO_RESULT bands={len(data['energies'][0][0])} \"\n"
           "      f\"kpts={len(data['x'])} efermi_eV={efermi:.4f}\", flush=True)\n";
    return out.str();
}

} // namespace calango::core
