#include "core/ElfScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>
#include <string>

namespace calango::core {

namespace {

/// Ground-state acquisition block. Both branches leave `calc` (a calculator
/// holding wavefunctions/density) and `atoms` defined, and log progress 1..2.
///
/// The ELF η(r) is a kinetic-energy-density post-process evaluated through
/// GPAW, so the GPAW path is the fully supported one: it is built from the
/// wizard's Calculator Settings (mode / cutoff / xc / k-points / mixer / …) via
/// the shared AseScriptGenerator helpers. When a different SCF engine is
/// selected the script still runs that engine's ground state, but the ELF
/// evaluation below is guarded and raises a clear error if the calculator can
/// not supply the localization function.
std::string groundState(const ElfConfig& cfg)
{
    std::ostringstream out;

    if (!cfg.baselineDir.empty()) {
        // Restart GPAW from a baseline process's .gpw (inherently GPAW).
        out << "_base = r\"" << cfg.baselineDir << "\"\n"
               "_gpw = sorted(glob.glob(os.path.join(_base, '*.gpw')))\n"
               "if not _gpw:\n"
               "    raise RuntimeError('No GPAW wavefunction (.gpw) found in '\n"
               "                       + _base + '. The ELF needs the full '\n"
               "                       'wavefunctions — re-run GPAW with '\n"
               "                       \"calc.write('wfs.gpw', mode='all').\")\n"
               "from gpaw import GPAW\n"
               "calc = GPAW(_gpw[0], txt=None)\n"
               "atoms = calc.get_atoms()\n"
               "_log.progress(1, 3)\n";
        return out.str();
    }

    out << "atoms = read('structure.extxyz')\n"
           "_log.progress(1, 3)\n";

    if (cfg.calculator.calculator == CalculatorKind::Gpaw) {
        out << AseScriptGenerator::gpawImports(cfg.calculator)
            << "calc = GPAW(\n"
            << AseScriptGenerator::gpawKeywordArguments(cfg.calculator, "    ")
            << "    txt='gpaw.txt',\n"
               ")\n"
               "atoms.calc = calc\n"
               "atoms.get_potential_energy()\n"
               "_log.progress(2, 3)\n";
    } else {
        // Non-GPAW engine: run its ground state (env is bound per engine from
        // Preferences). The ELF evaluation below still requires a GPAW-style
        // localization function and will raise a clear error otherwise.
        out << "# Ground state via the selected engine ("
            << toString(cfg.calculator.calculator) << ").\n"
            << AseScriptGenerator::calculatorSnippet(cfg.calculator)
            << "atoms.get_potential_energy()\n"
               "_log.progress(2, 3)\n";
    }
    return out.str();
}

} // namespace

std::string generateElfScript(const ElfConfig& cfg)
{
    // Preamble mirrors PartialChargeDialog: JSON/np helpers, ASE reader and the
    // CalangoLog progress logger the controller scrapes for progress markers.
    const std::string preamble =
        "# Electron Localization Function (ELF) — generated by Calango\n"
        "import json\n"
        "import os\n"
        "import glob\n"
        "# GPAW 25.x computes the ELF (kinetic-energy density) only in its new\n"
        "# engine, so enable it before importing gpaw.\n"
        "os.environ.setdefault('GPAW_NEW', '1')\n"
        "import numpy as np\n"
        "from ase.io import read\n"
        "from calango_log import CalangoLog\n"
        "_log = CalangoLog()\n";

    // ELF evaluation, hardened against GPAW version drift and grid-layout /
    // spin-shape mismatches:
    //   * ELF.update() takes (wfs) in some versions and no arg in others;
    //   * get_electronic_localization_function() accepts gridrefinement/spin
    //     only in some versions;
    //   * the result may come back spin-resolved (leading spin axis) or as a
    //     non-contiguous / non-float array — normalize to one contiguous
    //     C-ordered float64 3D grid before write_cube.
    const std::string compute =
        "elf_grid = None\n"
        "_errs = []\n"
        "try:\n"
        "    from gpaw.elf import ELF\n"
        "    elf = ELF(calc)\n"
        "    try:\n"
        "        elf.update(calc.wfs)\n"
        "    except TypeError:\n"
        "        elf.update()\n"
        "    try:\n"
        "        elf_grid = elf.get_electronic_localization_function(\n"
        "            gridrefinement=2)\n"
        "    except TypeError:\n"
        "        elf_grid = elf.get_electronic_localization_function()\n"
        "except Exception as _e:\n"
        "    _errs.append('gpaw.elf.ELF: ' + repr(_e))\n"
        "    try:\n"
        "        elf_grid = calc.get_electronic_localization_function()\n"
        "    except Exception as _e2:\n"
        "        _errs.append('calc.get_electronic_localization_function: '\n"
        "                     + repr(_e2))\n"
        "if elf_grid is None:\n"
        "    raise RuntimeError('Could not evaluate the ELF with this "
        "calculator/GPAW '\n"
        "                       'version: ' + ' | '.join(_errs))\n"
        "elf_grid = np.asarray(elf_grid, dtype=float)\n"
        "if elf_grid.ndim == 4:  # (spin, nx, ny, nz) -> collapse the spin axis\n"
        "    elf_grid = elf_grid[0]\n"
        "elf_grid = np.ascontiguousarray(elf_grid, dtype=float)\n"
        "_log.progress(3, 3)\n";

    // Write elf.cube on the ELF grid and emit the result marker the controller
    // watches for. `atoms` is always defined by the acquisition step.
    const std::string tail =
        "from ase.io.cube import write_cube\n"
        "with open('elf.cube', 'w') as _fh:\n"
        "    write_cube(_fh, atoms, data=elf_grid)\n"
        "print('CALANGO_RESULT elf=elf.cube', flush=True)\n";

    return preamble + groundState(cfg) + compute + tail;
}

} // namespace calango::core
