#include "core/EnergyDiagramScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

std::string generateEnergyDiagramScript(const EnergyDiagramConfig& cfg)
{
    std::ostringstream out;
    out << "# Energy Diagrams (molecules / non-periodic systems) — generated "
           "by Calango\n"
           "#\n"
           "# These are KOHN-SHAM EIGENVALUE-DIFFERENCE transitions, NOT "
           "TDDFT or\n"
           "# BSE excitation energies: each entry is E_virtual - E_occupied "
           "from a\n"
           "# single ground-state SCF, with no excited-state relaxation of "
           "the\n"
           "# density and no electron-hole binding. Useful for orbital "
           "character\n"
           "# and dipole selection rules; not a substitute for a real "
           "excited-state\n"
           "# method when the absolute transition energy matters.\n"
           "import json\n"
           "import os\n"
           "import glob\n"
           "import numpy as np\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << AseScriptGenerator::gpawRestartFromBaselineScript(
               cfg.baselineDir, "Energy Diagrams",
               "Energy Diagrams reads the SAVED Kohn-Sham states — re-run "
               "the single-point with wavefunctions saved (mode=all).")
        << "_calango_progress(1, 2)\n"
           "\n"
           "_weights = calc.get_k_point_weights()\n"
           "if len(_weights) != 1:\n"
           "    raise RuntimeError(\n"
           "        'Energy Diagrams needs a non-periodic or Gamma-only "
           "baseline '\n"
           "        '(exactly one k-point); this one has %d. Re-run the "
           "single-point '\n"
           "        'on a non-periodic structure, or with a single Gamma-"
           "point '\n"
           "        'k-grid.' % len(_weights))\n"
           "\n"
           "_nspins = calc.get_number_of_spins()\n"
           "_all_levels = []   # every STORED state: spin, band, energy_eV,\n"
           "                   # occupation — unfiltered, used only to find\n"
           "                   # HOMO/LUMO, never drawn directly (see _levels)\n"
           "_spin_homo = {}    # spin -> band index of that channel's HOMO "
           "(-1 = none occupied)\n"
           "for _s in range(_nspins):\n"
           "    _eigs = calc.get_eigenvalues(kpt=0, spin=_s)\n"
           "    _occs = calc.get_occupation_numbers(kpt=0, spin=_s)\n"
           "    _homo = -1\n"
           "    for _n, _e in enumerate(_eigs):\n"
           "        _occ = float(_occs[_n]) if _occs is not None else 0.0\n"
           "        _all_levels.append({'spin': int(_s), 'band': int(_n),\n"
           "                            'energy_eV': float(_e), "
           "'occupation': _occ})\n"
           "        if _occ > 0.5:\n"
           "            _homo = _n\n"
           "    _spin_homo[_s] = _homo\n"
           "\n"
           "# HOMO / LUMO across every channel — the smallest gap the "
           "structure\n"
           "# actually has, not one channel's alone. Computed from EVERY\n"
           "# stored state, before any windowing below, so the window's own\n"
           "# width can never move the answer.\n"
           "_occupied = [lv for lv in _all_levels if lv['occupation'] > "
           "0.5]\n"
           "_virtual = [lv for lv in _all_levels if lv['occupation'] <= "
           "0.5]\n"
           "_homo = max(_occupied, key=lambda lv: lv['energy_eV']) "
           "if _occupied else None\n"
           "_lumo = min(_virtual, key=lambda lv: lv['energy_eV']) "
           "if _virtual else None\n"
           "_gap_eV = (_lumo['energy_eV'] - _homo['energy_eV']) "
           "if (_homo and _lumo) else None\n"
           "\n"
        << "_below = " << cfg.occupiedBandsBelowHomo << "\n"
        << "_above = " << cfg.virtualBandsAboveLumo << "\n"
           "# One shared band window across every spin channel, wide enough\n"
           "# for any channel's own HOMO/LUMO — the SAME window the "
           "transitions\n"
           "# below are restricted to. Bands outside it (e.g. a molecule's\n"
           "# high-lying, closely-spaced empty \"box states\" well above the\n"
           "# LUMO, which real GPAW nbands defaults routinely include) are\n"
           "# chemically uninteresting and, left in, would dominate the level\n"
           "# diagram's shared linear energy axis and squeeze every level\n"
           "# actually near the gap into an unreadable cluster — this window\n"
           "# is what keeps the diagram AND the transitions table showing the\n"
           "# same, deliberately bounded, frontier manifold.\n"
           "_homo_indices = [h for h in _spin_homo.values() if h >= 0]\n"
           "if _homo_indices:\n"
           "    _n1 = max(0, min(_homo_indices) - _below + 1)\n"
           "    _n2 = min(calc.get_number_of_bands(),\n"
           "              max(_homo_indices) + 1 + _above)\n"
           "else:\n"
           "    # No occupied state anywhere: nothing to center a window on,\n"
           "    # so fall back to showing every stored band rather than an\n"
           "    # empty diagram.\n"
           "    _n1, _n2 = 0, len(_all_levels)\n"
           "_levels = [lv for lv in _all_levels\n"
           "          if _n1 <= lv['band'] < _n2]  # what the diagram draws\n"
           "\n"
           "# Degenerate levels (within the tolerance) grouped into one row\n"
           "# with a degeneracy count, per spin channel — bands never mix\n"
           "# across spin, so grouping crosses band index but not spin.\n"
        << "_tol = " << cfg.degeneracyToleranceEv << "\n"
        << "_groups = []\n"
           "for _s in range(_nspins):\n"
           "    _chan = sorted((lv for lv in _levels if lv['spin'] == _s),\n"
           "                  key=lambda lv: lv['band'])\n"
           "    _current = None\n"
           "    for _lv in _chan:\n"
           "        if _current is not None and \\\n"
           "                abs(_lv['energy_eV'] - _current['energy_eV']) "
           "<= _tol:\n"
           "            _current['bands'].append(_lv['band'])\n"
           "            _current['occupation'] += _lv['occupation']\n"
           "            _current['energy_eV'] = (\n"
           "                sum(calc.get_eigenvalues(kpt=0, spin=_s)[b]\n"
           "                    for b in _current['bands'])\n"
           "                / len(_current['bands']))\n"
           "        else:\n"
           "            if _current is not None:\n"
           "                _groups.append(_current)\n"
           "            _current = {'spin': _s, 'bands': [_lv['band']],\n"
           "                       'energy_eV': _lv['energy_eV'],\n"
           "                       'occupation': _lv['occupation']}\n"
           "    if _current is not None:\n"
           "        _groups.append(_current)\n"
           "for _g in _groups:\n"
           "    _g['degeneracy'] = len(_g['bands'])\n"
           "_calango_progress(2, 2)\n"
           "\n";

    out << "_transitions = []\n";
    if (cfg.computeTransitions) {
        out << "from gpaw.utilities.dipole import "
               "dipole_matrix_elements_from_calc\n"
               "from ase.units import Bohr, Hartree\n"
               "\n"
               "# Reuses the SAME (_n1, _n2) window computed above for the "
               "level\n"
               "# diagram — one window, one place it is computed, both "
               "consumers\n"
               "# agree on what \"the frontier manifold\" means.\n"
               "if _homo_indices:\n"
               "    _d_snnv = dipole_matrix_elements_from_calc(calc, _n1, "
               "_n2)\n"
        << "    _threshold = " << cfg.oscillatorStrengthThreshold << "\n"
        << "    for _s in range(_nspins):\n"
           "        _homo_s = _spin_homo.get(_s, -1)\n"
           "        if _homo_s < 0:\n"
           "            continue\n"
           "        _eigs = calc.get_eigenvalues(kpt=0, spin=_s)\n"
           "        for _i in range(max(_n1, _homo_s - _below + 1), "
           "_homo_s + 1):\n"
           "            for _j in range(_homo_s + 1, min(_n2, "
           "_homo_s + 1 + _above)):\n"
           "                _mu = _d_snnv[_s, _i - _n1, _j - _n1, :]\n"
           "                _mu2 = float(np.sum(_mu ** 2))  # (eA)^2\n"
           "                _dE = float(_eigs[_j] - _eigs[_i])  # eV\n"
           "                _f = (2.0 / 3.0) * (_dE / Hartree) * \\\n"
           "                    (_mu2 / (Bohr ** 2))\n"
           "                _wavelength_nm = (1239.841984 / _dE) if _dE > "
           "0.0 else None\n"
           "                _transitions.append({\n"
           "                    'spin': int(_s), 'from_band': int(_i), "
           "'to_band': int(_j),\n"
           "                    'energy_eV': _dE, "
           "'wavelength_nm': _wavelength_nm,\n"
           "                    'oscillator_strength': _f,\n"
           "                    'dipole_eA': [float(v) for v in _mu],\n"
           "                    'allowed': bool(_f > _threshold),\n"
           "                })\n"
           "\n"
           "else:\n"
           "    pass\n"
           "\n";
    }

    out << "_summary = {\n"
           "    'baseline_dir': _base,\n"
           "    'gpw': _gpw_path,\n"
           "    'nspins': int(_nspins),\n"
           "    'levels': _levels,\n"
           "    # How many stored bands existed before the frontier window\n"
           "    # above was applied — informational only (not read by the\n"
           "    # viewer), so a wide SCF band count is visible rather than\n"
           "    # silently disappearing.\n"
           "    'levels_total': len(_all_levels),\n"
           "    'groups': _groups,\n"
           "    'homo': _homo,\n"
           "    'lumo': _lumo,\n"
           "    'gap_eV': _gap_eV,\n"
           "    'transitions': _transitions,\n"
           "    # GPAW's own independently computed ground-state dipole "
           "moment —\n"
           "    # a useful reference figure, unrelated to how the "
           "transitions\n"
           "    # above are computed.\n"
           "    'reference_dipole_eA': "
           "[float(v) for v in atoms.get_dipole_moment()],\n"
           "}\n"
        << "with open(r\"" << cfg.resultsJson << "\", 'w') as _fh:\n"
           "    json.dump(_summary, _fh, indent=2)\n"
        << "print('CALANGO_RESULT energy_diagram=" << cfg.resultsJson
        << "', flush=True)\n"
        << "print(f'CALANGO_SUMMARY levels={len(_levels)} "
           "(of {len(_all_levels)} stored) "
           "transitions={len(_transitions)} "
           "gap_eV={_gap_eV if _gap_eV is not None else float(\"nan\"):.3f}', "
           "flush=True)\n"
           "_calango_event('done', "
           "f'Energy diagram written to "
        << cfg.resultsJson << "')\n";

    return out.str();
}

} // namespace calango::core
