#include "core/FermiSurfaceScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"
#include "core/WannierScriptGenerator.hpp"

#include <algorithm>
#include <sstream>

namespace calango::core {

std::string generateFermiSurfaceScript(const FermiSurfaceConfig& cfg)
{
    // 4 is the smallest grid marching cubes can produce anything from; the
    // upper bound is a guard rail on a multiplicative cost (64^3 is already
    // 262k diagonalizations).
    const int nx = std::clamp(cfg.gridSamples[0], 4, 128);
    const int ny = std::clamp(cfg.gridSamples[1], 4, 128);
    const int nz = std::clamp(cfg.gridSamples[2], 4, 128);
    const int maxIter = cfg.maxIterations > 0 ? cfg.maxIterations : 50;

    std::ostringstream out;
    out << "# Wannier-interpolated Fermi surface — generated by Calango\n"
           "#\n"
           "# The Fermi surface is the sheet E_n(k) = E_F. It is interpolated\n"
           "# from the localized Wannier Hamiltonian rather than sampled\n"
           "# directly: H(R) is short-ranged, so E_n(k) costs one small\n"
           "# diagonalization per point and a grid dense enough to resolve a\n"
           "# surface becomes affordable.\n"
           "import json\n"
           "import os\n"
           "import glob\n"
           "\n"
           "import numpy as np\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << wannierHrInterpolatorPreamble()
        << "_base = r\"" << cfg.mlwfDir << "\"\n"
        << "_nx = " << nx << "\n"
        << "_ny = " << ny << "\n"
        << "_nz = " << nz << "\n"
        << "_offset = " << cfg.energyOffsetEv << "\n"
        << "_max_iter = " << maxIter << "\n"
        << R"PY(
# --- Locate the MLWF run's inputs ----------------------------------------
# Same resolution order as the Wannier interpolation: wannier.json records
# where the wavefunctions actually are, because an MLWF started from a
# single-point baseline reads them from that job's directory and writes none
# of its own.
_mj = os.path.join(_base, 'wannier.json')
if not os.path.exists(_mj):
    raise RuntimeError(
        'No wannier.json in ' + _base + '. The Fermi surface is interpolated '
        'from a completed MLWF localization — point this at one.')
_meta = json.load(open(_mj))

)PY";

    // The engine dispatch, shared verbatim with the Wannier
    // Interpolation and topological-invariant modules: all three need
    // exactly H(k), and all three used to get it only from a .gpw.
    out << wannierHrSetupBlock("the Fermi surface", 2, 4);

    // The GPAW arm, unchanged, one level in under that `else:`.
    AseScriptGenerator::emitIndented(out, R"PY(
_gpw_path = _meta.get('gpw')
if not (_gpw_path and os.path.exists(_gpw_path)):
    _found = sorted(glob.glob(os.path.join(_base, '*.gpw')))
    _gpw_path = _found[0] if _found else None
if not _gpw_path:
    raise RuntimeError(
        'The MLWF run in ' + _base + ' left no GPAW wavefunction (.gpw) to '
        'interpolate from and recorded no path to one. Re-run the MLWF '
        'calculation.')

from gpaw import GPAW
calc = GPAW(_gpw_path, txt='gpaw_fermi_surface.txt')
atoms = calc.get_atoms()
try:
    efermi = float(calc.get_fermi_level())
except Exception:
    efermi = 0.0

# Wannier localization needs the full Brillouin zone; a symmetry-reduced .gpw
# carries only the irreducible wedge and fails deep inside ase.dft.wannier.
if len(calc.get_ibz_k_points()) < len(calc.get_bz_k_points()):
    raise RuntimeError(
        'The wavefunctions in ' + _gpw_path + ' were written by a '
        'symmetry-reduced run. Wannier localization needs the full Brillouin '
        'zone — re-run the baseline single-point with "Symmetry: off".')

nwannier = int(_meta.get('nwannier') or len(_meta.get('centers', [])) or 0)
if nwannier <= 0:
    raise RuntimeError('wannier.json records no Wannier-function count — the '
                       'MLWF run did not complete.')
projection = _meta.get('projection', 'orbitals')
_calango_progress(1, 4)

# --- Rebuild the localization --------------------------------------------
# The SAME localization the MLWF run produced, from the same wavefunctions
# with the same seed and count: an interpolation off a different Wannier gauge
# would describe a different (though equally valid) set of bands.
from ase.dft.wannier import Wannier
wan = Wannier(nwannier=nwannier, calc=calc, initialwannier=projection)
_prev = None
for _it in range(_max_iter):
    wan.localize(step=0.25, tolerance=1e-6)
    _val = float(wan.get_functional_value())
    if _prev is not None and abs(_val - _prev) < 1e-6:
        break
    _prev = _val
print(f'CALANGO_INFO localization functional = {float(wan.get_functional_value()):.6f}',
      flush=True)
_calango_progress(2, 4)
)PY", "    ");

    out << R"PY(

# --- Interpolate onto a 3D k-grid ----------------------------------------
# Fractional -1/2 .. 1/2, endpoint EXCLUDED: -1/2 and +1/2 are the same k by
# periodicity, and including both would duplicate a face of the grid, which
# marching cubes would then close the surface across.
#
# One sample count per reciprocal direction. They are independent because the
# reciprocal cell generally is not cubic — a slab with a short c has a long b3,
# and sampling that as finely as the in-plane directions spends the budget
# resolving the axis with the least structure along it.
_frac_x = (np.arange(_nx) / _nx) - 0.5
_frac_y = (np.arange(_ny) / _ny) - 0.5
_frac_z = (np.arange(_nz) / _nz) - 0.5
print(f'CALANGO_INFO interpolating {_nx}x{_ny}x{_nz} = {_nx * _ny * _nz} '
      f'k-points over {nwannier} Wannier bands', flush=True)

_energies = np.empty((_nx, _ny, _nz, nwannier), dtype=float)
for i, kx in enumerate(_frac_x):
    for j, ky in enumerate(_frac_y):
        for k, kz in enumerate(_frac_z):
            H_ww = wan.get_hamiltonian_kpoint(np.array([kx, ky, kz]))
            _energies[i, j, k] = np.linalg.eigvalsh(H_ww)
    _calango_progress(2 + (i + 1) / len(_frac_x), 4)

# 2*pi restored so the axes are the 1/Angstrom every Fermi-surface figure is
# drawn in; ASE's reciprocal() omits it.
_recip = 2.0 * np.pi * np.asarray(atoms.cell.reciprocal())
_calango_progress(3, 4)

# Only bands that actually CROSS the target energy can contribute a sheet.
# Reporting the others would make the viewer extract empty isosurfaces from
# grids that cannot contain one.
_target = efermi + _offset
_bands = []
for _b in range(nwannier):
    _lo = float(_energies[:, :, :, _b].min())
    _hi = float(_energies[:, :, :, _b].max())
    _bands.append({
        'band': int(_b),
        'min_eV': _lo,
        'max_eV': _hi,
        'crosses_fermi': bool(_lo <= _target <= _hi),
        'energies_eV': [float(v) for v in _energies[:, :, :, _b].ravel()],
    })
_crossing = [b['band'] for b in _bands if b['crosses_fermi']]
print(f'CALANGO_INFO {len(_crossing)} of {nwannier} bands cross E_F'
      + (f' (bands {_crossing})' if _crossing else
         ' — this system has no Fermi surface at the requested energy'),
      flush=True)

result = {
    'fermi_eV': efermi,
    'energy_offset_eV': float(_offset),
    'target_energy_eV': float(_target),
    # A three-element list now. Older runs wrote a single int, and the viewer
    # still accepts that — an isotropic grid is the special case, not a
    # different schema.
    'samples': [int(_nx), int(_ny), int(_nz)],
    'nwannier': int(nwannier),
    'formula': atoms.get_chemical_formula(),
    'cell_A': [[float(v) for v in row] for row in np.asarray(atoms.cell)],
    'reciprocal_2pi_per_A': [[float(v) for v in row] for row in _recip],
    'crossing_bands': [int(b) for b in _crossing],
    'bands': _bands,
}
with open('fermi_surface.json', 'w') as _fh:
    json.dump(result, _fh)
_calango_progress(4, 4)
print('CALANGO_RESULT fermi_surface=fermi_surface.json', flush=True)
print('CALANGO_DONE', flush=True)
)PY";
    return out.str();
}

} // namespace calango::core
