#include "core/GrapheneOxideMdmcScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

std::string
GrapheneOxideMdmcScriptGenerator::generate(const GrapheneOxideMdmcConfig& c)
{
    std::ostringstream out;

    out << "#!/usr/bin/env python3\n"
           "# Hybrid MD / Monte Carlo refinement of a graphene oxide "
           "decoration.\n"
           "#\n"
           "# Generated by Calango. Self-contained: nothing here imports "
           "Calango,\n"
           "# so this file runs anywhere ASE and the calculator are "
           "installed.\n"
           "\n"
           "import json\n"
           "import math\n"
           "import random\n"
           "\n"
           "import numpy as np\n"
           "from ase import Atoms\n"
           "from ase.io import read, write\n"
           "from ase.neighborlist import NeighborList, natural_cutoffs\n"
           "from ase import units\n"
           "from ase.md.langevin import Langevin\n"
           "from ase.md.velocitydistribution import MaxwellBoltzmannDistribution\n"
           "\n"
           "# Imported unconditionally even for a constant-volume run: the\n"
           "# integrator choice below reads the name whichever branch it takes,\n"
           "# and an import that exists only in one configuration is a\n"
           "# NameError waiting for the first person to flip the flag.\n"
           "try:\n"
           "    from ase.md.nptberendsen import NPTBerendsen\n"
           "except ImportError:  # constant pressure unavailable in this ASE\n"
           "    NPTBerendsen = None\n";
    out << "\n" << AseScriptGenerator::jsonLoggerPreamble() << "\n";

    // ---- Baked-in parameters -------------------------------------------
    out << "input_path = r\"" << c.inputStructure << "\"\n"
        << "output_path = r\"" << c.outputStructure << "\"\n"
        << "trajectory_path = r\"" << c.trajectory << "\"\n"
        << "temperature_K = " << c.temperatureK << "\n"
        << "mc_cycles = " << c.cycles << "\n"
        << "md_steps = " << c.mdStepsPerCycle << "\n"
        << "timestep_fs = " << c.timestepFs << "\n"
        << "friction_per_fs = " << c.frictionPerFs << "\n"
        << "both_faces = " << (c.bothFaces ? "True" : "False") << "\n"
        << "snapshot_interval = " << c.snapshotInterval << "\n"
        << "seed = " << c.seed << "\n"
        << "constant_pressure = " << (c.constantPressure ? "True" : "False")
        << "\n"
        << "pressure_GPa = " << c.pressureGpa << "\n"
        << "viewport_every = " << c.viewportEveryCycles << "\n"
        << "stream_md_frames = " << (c.streamMdFrames ? "True" : "False")
        << "\n"
        << "\n"
           "rng = random.Random(seed)\n"
           "np.random.seed(seed)\n"
           "\n";

    // ---- Structure + calculator ----------------------------------------
    out << "atoms = read(input_path)\n"
           "\n"
           "\n"
           "def attach_calculator(system):\n"
           "    \"\"\"Bind a calculator to `system`. One definition, so every\n"
           "    energy in this run comes from an identically configured "
           "engine.\"\"\"\n"
           "    atoms = system\n";
    AseScriptGenerator::emitIndented(
        out, AseScriptGenerator::calculatorSnippet(c.calculator),
                 "    ");
    out << "    return atoms\n"
           "\n"
           "\n"
           "attach_calculator(atoms)\n"
           "\n"
        // Live geometry for the viewport, through the SAME helper every other
        // generated script uses. A second implementation of the block format
        // would be a second thing to keep in step with the one regex that
        // parses it.
        << AseScriptGenerator::streamFrameHelper() << "\n";

    // ---- Bond perception, group inventory, site graph -------------------
    out << R"PY(
# =====================================================================
# Bond perception
# =====================================================================
# Every topological statement below - which carbons are framework, what a
# functional group is, whether the chemistry survived the dynamics - is
# derived from BONDS, and bonds are derived from distances. Doing that in
# one place means the "before" and "after" pictures cannot disagree
# because they were computed two different ways.

BOND_SCALE = 1.2  # natural_cutoffs are covalent radii; this is the usual slack


def bond_graph(system):
    """Bonds as an adjacency list.

    skin=0.0 is not a detail. NeighborList defaults to skin=0.3 and adds it to
    EACH atom's cutoff, so a C-O pair is called bonded out to
    1.2*(0.76+0.66) + 0.6 = 2.30 A. The carbons next to a hydroxyl's host sit
    at 2.05 A from its oxygen, well inside that - so with the default skin
    every group reads as bonded to half its neighbourhood, no functional group
    is ever recognised, and the topology check calls intact chemistry broken.
    The buffer exists for repeated MD queries on a list that is not rebuilt;
    this rebuilds every time, and wants the honest cutoff.
    """
    cutoffs = [BOND_SCALE * r for r in natural_cutoffs(system)]
    neighbor_list = NeighborList(cutoffs, skin=0.0, self_interaction=False,
                                 bothways=True)
    neighbor_list.update(system)
    return [set(neighbor_list.get_neighbors(i)[0]) for i in range(len(system))]


def connected_components(graph):
    seen = [False] * len(graph)
    components = 0
    for start in range(len(graph)):
        if seen[start]:
            continue
        components += 1
        stack = [start]
        seen[start] = True
        while stack:
            node = stack.pop()
            for neighbor in graph[node]:
                if not seen[neighbor]:
                    seen[neighbor] = True
                    stack.append(neighbor)
    return components


# =====================================================================
# The framework, and the groups sitting on it
# =====================================================================
# A FRAMEWORK carbon is one of the carbons of the sheet or flake itself,
# and the test is its CARBON coordination alone: two or more carbon
# neighbours. Everything else - oxygens, hydroxyl and edge hydrogens, and
# the carbon a carboxyl brings with it - belongs to a functional group.
#
# Emphatically NOT "and bonded to no oxygen". That reading excludes every
# carbon that carries a group, which is to say every carbon this run exists
# to move a group off - the inventory then comes back empty and the whole
# calculation refuses to start. The carboxyl carbon is excluded by the
# coordination test on its own: it has one carbon neighbour, not two.

symbols = atoms.get_chemical_symbols()
graph0 = bond_graph(atoms)

framework = []
for i, symbol in enumerate(symbols):
    if symbol != "C":
        continue
    carbon_neighbors = [j for j in graph0[i] if symbols[j] == "C"]
    if len(carbon_neighbors) >= 2:
        framework.append(i)
framework_set = set(framework)

# Basal vs edge, from coordination alone - the same rule the builder used.
is_edge = {}
for i in framework:
    is_edge[i] = len([j for j in graph0[i] if j in framework_set]) < 3

n_edge = sum(1 for i in framework if is_edge[i])
_calango_event("info", f"framework carbons: {len(framework)} "
                       f"({len(framework) - n_edge} basal, {n_edge} edge)")


def collect_groups(system, graph):
    """Every functional group, as (kind, group_atoms, host_carbons).

    Detection runs LARGEST FIRST. A carboxyl contains both a C=O and a
    C-OH, so looking for carbonyls or hydroxyls first would tear every
    carboxyl into two half-groups that the sampler would then try to move
    independently.
    """
    symbols = system.get_chemical_symbols()
    claimed = set()
    groups = []

    # -- Carboxyl: a non-framework carbon bonded to a framework carbon and
    #    to two oxygens, one of which carries the acidic hydrogen.
    for i, symbol in enumerate(symbols):
        if symbol != "C" or i in framework_set or i in claimed:
            continue
        hosts = [j for j in graph[i] if j in framework_set]
        oxygens = [j for j in graph[i] if symbols[j] == "O"]
        if len(hosts) != 1 or len(oxygens) != 2:
            continue
        # Recipe order: carbon, the double-bonded O, the hydroxyl O, its H.
        # The hydroxyl O is the one carrying a hydrogen; with none (a
        # deprotonated carboxylate) the shorter C-O is the double bond.
        acid = [o for o in oxygens if any(symbols[h] == "H" for h in graph[o])]
        if acid:
            single_o = acid[0]
        else:
            distances = [(system.get_distance(i, o, mic=True), o)
                         for o in oxygens]
            single_o = max(distances)[1]
        double_o = [o for o in oxygens if o != single_o][0]
        acid_h = [h for h in graph[single_o] if symbols[h] == "H"]
        members = [i, double_o, single_o] + acid_h
        if any(m in claimed for m in members):
            continue
        claimed.update(members)
        groups.append(("carboxyl", members, hosts))

    # -- Epoxide: one oxygen bridging TWO framework carbons.
    for i, symbol in enumerate(symbols):
        if symbol != "O" or i in claimed:
            continue
        hosts = [j for j in graph[i] if j in framework_set]
        hydrogens = [j for j in graph[i] if symbols[j] == "H"]
        if len(hosts) == 2 and not hydrogens:
            claimed.add(i)
            groups.append(("epoxide", [i], sorted(hosts)))

    # -- Hydroxyl: an oxygen on one framework carbon, carrying a hydrogen.
    for i, symbol in enumerate(symbols):
        if symbol != "O" or i in claimed:
            continue
        hosts = [j for j in graph[i] if j in framework_set]
        hydrogens = [j for j in graph[i] if symbols[j] == "H"]
        if len(hosts) == 1 and len(hydrogens) == 1:
            members = [i, hydrogens[0]]  # recipe order: O then H
            claimed.update(members)
            groups.append(("hydroxyl", members, hosts))

    # -- Carbonyl: an oxygen on one framework carbon, with no hydrogen.
    for i, symbol in enumerate(symbols):
        if symbol != "O" or i in claimed:
            continue
        hosts = [j for j in graph[i] if j in framework_set]
        if len(hosts) == 1:
            claimed.add(i)
            groups.append(("carbonyl", [i], hosts))

    return groups


# =====================================================================
# Reactive site graph
# =====================================================================
# A port of Calango's core::ReactiveSiteGraph, whose C++ tests are the
# reference for the rules below. Two site types that are COUPLED:
#
#   single  one carbon        - hydroxyl, carbonyl, carboxyl
#   pair    two bonded basal  - epoxide
#
# Occupying one carbon must withdraw every pair containing it, including
# pairs whose other carbon is still free; releasing one carbon revives a
# pair only when its partner is free too. Getting the second rule wrong in
# the permissive direction puts two groups on one carbon, which is a
# pentavalent carbon - not an unlikely structure but an impossible one.

class SiteGraph:
    def __init__(self, framework, is_edge, graph):
        self.owner = {i: None for i in framework}
        self.is_edge = is_edge
        self.pairs = []
        self.pairs_touching = {i: [] for i in framework}
        framework_set = set(framework)
        for i in framework:
            if is_edge[i]:
                continue
            for j in graph[i]:
                # j > i registers each bond ONCE: walking the adjacency
                # sees i-j and j-i, which would double the epoxide capacity.
                if j <= i or j not in framework_set or is_edge[j]:
                    continue
                index = len(self.pairs)
                self.pairs.append((i, j))
                self.pairs_touching[i].append(index)
                self.pairs_touching[j].append(index)
        self.free_pairs = set(range(len(self.pairs)))
        self.free_basal = {i for i in framework if not is_edge[i]}
        self.free_edge = {i for i in framework if is_edge[i]}

    def occupy(self, carbon, tag):
        self.owner[carbon] = tag
        self.free_basal.discard(carbon)
        self.free_edge.discard(carbon)
        for index in self.pairs_touching[carbon]:
            self.free_pairs.discard(index)

    def release(self, carbon):
        self.owner[carbon] = None
        if self.is_edge[carbon]:
            self.free_edge.add(carbon)
        else:
            self.free_basal.add(carbon)
        for index in self.pairs_touching[carbon]:
            a, b = self.pairs[index]
            if self.owner[a] is None and self.owner[b] is None:
                self.free_pairs.add(index)

    def draw_single(self, edge, rng):
        pool = self.free_edge if edge else self.free_basal
        return rng.choice(sorted(pool)) if pool else None

    def draw_pair(self, rng):
        if not self.free_pairs:
            return None
        return self.pairs[rng.choice(sorted(self.free_pairs))]

    def consistent(self):
        for index, (a, b) in enumerate(self.pairs):
            free = self.owner[a] is None and self.owner[b] is None
            if free != (index in self.free_pairs):
                return False
        return True


# =====================================================================
# Group geometry
# =====================================================================
# Rebuilding a group from its recipe rather than transplanting its atoms
# rigidly: after a burst of dynamics the old group is no longer in a clean
# geometry, and carrying its accumulated distortion to the new site would
# bias the energy of every move that followed.

CO_EPOXIDE = 1.44
CO_HYDROXYL = 1.48
OH = 0.98
CO_CARBONYL = 1.23
CC_CARBOXYL = 1.48
CO_DOUBLE = 1.21
CO_SINGLE = 1.34


def sheet_normal(positions, framework):
    """Unit normal of the carbon plane, by least squares."""
    points = positions[framework]
    centered = points - points.mean(axis=0)
    _, _, vh = np.linalg.svd(centered)
    return vh[2] / np.linalg.norm(vh[2])


def outward_direction(positions, carbon, graph, framework_set, normal):
    """In-plane direction pointing away from the flake at an edge carbon."""
    neighbors = [j for j in graph[carbon] if j in framework_set]
    if not neighbors:
        return np.array([1.0, 0.0, 0.0])
    away = positions[carbon] - positions[neighbors].mean(axis=0)
    away -= np.dot(away, normal) * normal
    norm = np.linalg.norm(away)
    return away / norm if norm > 1e-6 else np.array([1.0, 0.0, 0.0])


def build_group(kind, hosts, positions, graph, framework_set, normal,
                face, rng):
    """Atoms (symbols, positions) for `kind` attached at `hosts`."""
    if kind == "epoxide":
        a, b = hosts
        mid = 0.5 * (positions[a] + positions[b])
        half = 0.5 * np.linalg.norm(positions[a] - positions[b])
        height = math.sqrt(max(CO_EPOXIDE ** 2 - half ** 2, 0.25))
        return ["O"], [mid + face * height * normal]

    host = hosts[0]
    base = positions[host]
    if kind == "hydroxyl":
        o = base + face * CO_HYDROXYL * normal
        # A random azimuth for the O-H: pointing every hydroxyl the same
        # way would give the cell a spurious in-plane dipole.
        phi = rng.uniform(0.0, 2.0 * math.pi)
        ref = np.array([1.0, 0.0, 0.0])
        if abs(np.dot(ref, normal)) > 0.9:
            ref = np.array([0.0, 1.0, 0.0])
        u = np.cross(normal, ref)
        u /= np.linalg.norm(u)
        v = np.cross(normal, u)
        radial = math.cos(phi) * u + math.sin(phi) * v
        return ["O", "H"], [o, o + 0.94 * OH * radial + face * 0.33 * OH * normal]

    direction = outward_direction(positions, host, graph, framework_set, normal)
    if kind == "carbonyl":
        return ["O"], [base + CO_CARBONYL * direction]

    if kind == "carboxyl":
        # -COOH brings its own sp2 carbon; the two oxygens sit at the
        # trigonal +-60 degrees, and the acidic H folds back syn.
        carbon = base + CC_CARBOXYL * direction
        side = 1.0 if rng.random() < 0.5 else -1.0

        def rotate(vec, angle):
            axis = normal
            return (vec * math.cos(angle)
                    + np.cross(axis, vec) * math.sin(angle)
                    + axis * np.dot(axis, vec) * (1.0 - math.cos(angle)))

        double_o = carbon + CO_DOUBLE * rotate(direction, -side * math.pi / 3.0)
        single_o = carbon + CO_SINGLE * rotate(direction, side * math.pi / 3.0)
        acidic_h = single_o + OH * rotate(direction, -side * 14.0 * math.pi / 180.0)
        return ["C", "O", "O", "H"], [carbon, double_o, single_o, acidic_h]

    raise ValueError(f"unknown group kind: {kind}")


GROUP_REGION = {
    "epoxide": "pair",
    "hydroxyl": "basal",
    "carbonyl": "edge",
    "carboxyl": "edge",
}

# Expected connectivity of each group, checked after the dynamics.
# (oxygens bonded to the group's own carbon, hydrogens on those oxygens)
def topology_intact(kind, hosts, member_indices, system, graph):
    symbols = system.get_chemical_symbols()
    members = set(member_indices)
    if kind == "epoxide":
        o = member_indices[0]
        bonded_hosts = [j for j in graph[o] if j in framework_set]
        return len(bonded_hosts) == 2 and set(bonded_hosts) == set(hosts)
    if kind == "hydroxyl":
        oxygens = [i for i in member_indices if symbols[i] == "O"]
        if len(oxygens) != 1:
            return False
        o = oxygens[0]
        bonded_hosts = [j for j in graph[o] if j in framework_set]
        hydrogens = [j for j in graph[o] if symbols[j] == "H" and j in members]
        return len(bonded_hosts) == 1 and bonded_hosts[0] == hosts[0] \
            and len(hydrogens) == 1
    if kind == "carbonyl":
        o = member_indices[0]
        bonded_hosts = [j for j in graph[o] if j in framework_set]
        return len(bonded_hosts) == 1 and bonded_hosts[0] == hosts[0]
    if kind == "carboxyl":
        carbons = [i for i in member_indices if symbols[i] == "C"]
        if len(carbons) != 1:
            return False
        c = carbons[0]
        bonded_hosts = [j for j in graph[c] if j in framework_set]
        oxygens = [j for j in graph[c] if symbols[j] == "O" and j in members]
        return len(bonded_hosts) == 1 and bonded_hosts[0] == hosts[0] \
            and len(oxygens) == 2
    return False
)PY";

    // ---- The Monte Carlo loop -------------------------------------------
    out << R"PY(

# =====================================================================
# Assemble the initial state
# =====================================================================

groups = collect_groups(atoms, graph0)
if not groups:
    _calango_event("error",
                   "No functional groups found - there is nothing to move. "
                   "MDMC refines an EXISTING decoration; build one first.")
    raise SystemExit(1)

sites = SiteGraph(framework, is_edge, graph0)
for kind, members, hosts in groups:
    for host in hosts:
        sites.occupy(host, kind)
if not sites.consistent():
    _calango_event("error", "initial site bookkeeping is inconsistent")
    raise SystemExit(1)

counts = {k: sum(1 for g in groups if g[0] == k)
          for k in ("epoxide", "hydroxyl", "carboxyl", "carbonyl")}
_calango_event("info", f"groups: {len(groups)} - " + ", ".join(
    f"{n} {k}" for k, n in counts.items() if n))

# The number of separate molecules at the start. Any move that changes it
# has released a fragment, and that is the failure this whole run has to
# refuse - see the topology check below.
reference_components = connected_components(graph0)


def run_md(system):
    """A short burst of dynamics at the target temperature.

    Short on purpose: this is not a relaxation, it is enough motion to let
    the neighbours accommodate the group that just moved. The run costs
    cycles x md_steps energy evaluations, so this is the wall clock.
    """
    if md_steps <= 0:
        return system.get_potential_energy()
    MaxwellBoltzmannDistribution(system, temperature_K=temperature_K)
    if constant_pressure:
        if NPTBerendsen is None:
            raise RuntimeError(
                "Constant-pressure MDMC needs ase.md.nptberendsen, which this "
                "ASE does not provide.")
        dynamics = NPTBerendsen(system, timestep=timestep_fs * units.fs,
                                temperature_K=temperature_K,
                                pressure_au=pressure_GPa * units.GPa,
                                compressibility_au=4.57e-5 / units.bar)
    else:
        dynamics = Langevin(system, timestep=timestep_fs * units.fs,
                            temperature_K=temperature_K,
                            friction=friction_per_fs / units.fs)
    dynamics.run(md_steps)
    return system.get_potential_energy()


def _viewport_due(cycle):
    """Is this cycle one the viewport should be shown?"""
    return viewport_every > 0 and cycle % viewport_every == 0


def chemistry_survived(system):
    """Did the dynamics leave the material we started with?

    Molecular dynamics on a reactive surface will abstract a hydroxyl and a
    neighbouring hydrogen and release water. The energy drops, the move
    looks excellent, and the structure is no longer graphene oxide. So the
    topology is checked before the energy is ever consulted.
    """
    graph = bond_graph(system)
    for (kind, members, hosts) in groups:
        if not topology_intact(kind, hosts, members, system, graph):
            return False
    # Whatever fragment came off, the component count sees it.
    return connected_components(graph) == reference_components


kB = units.kB
energy = run_md(atoms)
if not chemistry_survived(atoms):
    _calango_event("error",
                   "The chemistry did not survive the initial equilibration. "
                   "The temperature or the step count is too high for this "
                   "structure - nothing sampled from here would be graphene "
                   "oxide.")
    raise SystemExit(1)

initial_energy = energy
best_energy = energy
best_atoms = atoms.copy()
_calango_event("info", f"initial energy after equilibration: {energy:.6f} eV")

accepted = 0
rejected_topology = 0
rejected_metropolis = 0
no_site = 0
snapshots = [atoms.copy()] if snapshot_interval > 0 else []

# The atom COUNT and ORDERING never change during the run. A move relocates
# a group of the same kind, so its atoms keep their indices and only their
# positions move. That is what makes reversion exact and cheap: restoring a
# position array undoes everything, and no index anywhere - framework, site
# graph, group inventory - has to be remapped.
for cycle in range(1, mc_cycles + 1):
    index = rng.randrange(len(groups))
    kind, members, hosts = groups[index]
    region = GROUP_REGION[kind]

    saved_positions = atoms.get_positions()
    saved_hosts = list(hosts)
    saved_free_basal = set(sites.free_basal)
    saved_free_edge = set(sites.free_edge)
    saved_free_pairs = set(sites.free_pairs)
    saved_owner = dict(sites.owner)

    def revert():
        atoms.set_positions(saved_positions)
        groups[index] = (kind, members, saved_hosts)
        sites.owner = saved_owner
        sites.free_basal = saved_free_basal
        sites.free_edge = saved_free_edge
        sites.free_pairs = saved_free_pairs

    # ---- 1. Lift the group off its carbons -------------------------------
    for host in hosts:
        sites.release(host)

    # ---- 2. Draw a new site of the kind this group needs -----------------
    if region == "pair":
        target = sites.draw_pair(rng)
        new_hosts = list(target) if target else None
    else:
        drawn = sites.draw_single(region == "edge", rng)
        new_hosts = [drawn] if drawn is not None else None

    if new_hosts is None:
        # Saturated for this group kind: the move was never generated, so it
        # must not enter the acceptance statistics as a rejection.
        revert()
        no_site += 1
        continue

    # ---- 3. Rebuild the group at the new site ----------------------------
    # Rebuilt from its recipe rather than transplanted rigidly: after a burst
    # of dynamics the old group carries accumulated distortion, and moving
    # that along would bias the energy of every later move.
    positions = atoms.get_positions()
    normal = sheet_normal(positions, framework)
    face = 1.0
    if region != "edge" and both_faces:
        face = rng.choice([1.0, -1.0])

    new_symbols, new_positions = build_group(
        kind, new_hosts, positions, graph0, framework_set, normal, face, rng)
    if len(new_symbols) != len(members):
        # The recipe and the inventory disagree about what this group is.
        # Refusing beats writing atoms into the wrong slots.
        revert()
        rejected_topology += 1
        continue
    for atom_index, position in zip(members, new_positions):
        positions[atom_index] = position
    atoms.set_positions(positions)

    for host in new_hosts:
        sites.occupy(host, kind)
    groups[index] = (kind, members, new_hosts)

    # ---- 4. Relax, then check the chemistry survived ---------------------
    try:
        trial_energy = run_md(atoms)
        # The geometry the DYNAMICS produced, before it has been judged. Shows
        # the atoms moving; opt-in because a rejected move's geometry is not a
        # state of the ensemble and streaming it costs a frame either way.
        if stream_md_frames and _viewport_due(cycle):
            _stream_frame()
    except Exception as exc:  # a calculator that fell over is a rejection
        _calango_event("warning",
                       f"cycle {cycle}: energy evaluation failed: {exc}")
        revert()
        rejected_topology += 1
        _calango_progress(cycle, mc_cycles)
        continue

    if not chemistry_survived(atoms):
        revert()
        rejected_topology += 1
        _calango_metric(cycle, energy=energy)
        _calango_progress(cycle, mc_cycles)
        continue

    # ---- 5. Metropolis ---------------------------------------------------
    delta = trial_energy - energy
    if delta <= 0.0 or rng.random() < math.exp(-delta / (kB * temperature_K)):
        energy = trial_energy
        accepted += 1
        if trial_energy < best_energy:
            best_energy = trial_energy
            best_atoms = atoms.copy()
        if snapshot_interval > 0 and accepted % snapshot_interval == 0:
            snapshots.append(atoms.copy())
        # An ACCEPTED move: a new state of the ensemble, with its topology
        # already validated. This is the one worth watching - it is the
        # discrete group hop the whole run exists to sample.
        if _viewport_due(cycle):
            _stream_frame()
    else:
        revert()
        rejected_metropolis += 1

    _calango_metric(cycle, energy=energy)
    _calango_progress(cycle, mc_cycles)

if not sites.consistent():
    _calango_event("warning",
                   "site bookkeeping ended inconsistent - the reported "
                   "structure is still valid, but report this")

acceptance = accepted / mc_cycles if mc_cycles else 0.0
_calango_event("info",
               f"accepted {accepted}/{mc_cycles} ({100.0 * acceptance:.1f} %); "
               f"rejected {rejected_metropolis} by energy, "
               f"{rejected_topology} by broken chemistry; "
               f"{no_site} cycles found no free site")
if rejected_topology > 0.5 * mc_cycles:
    _calango_event("warning",
                   "More than half the moves broke the chemistry. The dynamics "
                   "is too hot or too long for this material - lower the "
                   "temperature or the MD steps per cycle.")

# The BEST configuration, not the last one: a finite-temperature walk ends
# wherever it happens to be, and reporting that throws away the answer.
write(output_path, best_atoms)
if snapshots:
    write(trajectory_path, snapshots)

summary = {
    "initial_energy_eV": float(initial_energy),
    "best_energy_eV": float(best_energy),
    "final_energy_eV": float(energy),
    "energy_gain_eV": float(initial_energy - best_energy),
    "cycles": mc_cycles,
    "accepted": accepted,
    "acceptance_ratio": acceptance,
    "rejected_metropolis": rejected_metropolis,
    "rejected_topology": rejected_topology,
    "cycles_without_site": no_site,
    "temperature_K": temperature_K,
    "md_steps_per_cycle": md_steps,
    "group_counts": counts,
}
with open("mdmc_summary.json", "w") as handle:
    json.dump(summary, handle, indent=2)

print(f"CALANGO_RESULT best_energy={best_energy:.6f} eV "
      f"gain={initial_energy - best_energy:.6f} eV "
      f"acceptance={acceptance:.3f}", flush=True)
print("CALANGO_DONE", flush=True)
)PY";

    return out.str();
}

} // namespace calango::core
