#include "core/GwScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

namespace {

void emitGpawGw(std::ostringstream& out, const GwConfig& c)
{
    out << "# --- Baseline ground state (inherited, NOT re-converged) --------\n"
           "# G0W0 is a perturbative correction ON TOP of a specific DFT\n"
           "# solution: E_qp = e_DFT + Z (Sigma(e_DFT) - V_xc). Re-converging\n"
           "# the ground state here would correct a different starting point\n"
           "# than the one that was inspected, and the correction is only\n"
           "# meaningful relative to its own reference.\n"
           "from gpaw import GPAW\n"
           "\n"
        << "gs = GPAW(r\"" << c.baselinePath << "\", txt=None)\n"
           "n_electrons = gs.get_number_of_electrons()\n"
           "n_occ = max(1, int(round(n_electrons / 2.0)))\n"
        << "n_bands = " << (c.bands > 0 ? std::to_string(c.bands)
                                        : std::string("max(8 * n_occ, 40)"))
        << "\n"
           "_calango_log.progress(1, 4)\n"
           "\n"
           "# --- Fixed-density NSCF with the empty bands GW sums over -------\n"
           "# The self-energy sums over unoccupied states, so the baseline's\n"
           "# handful of empty bands is nowhere near enough. They are converged\n"
           "# at the FIXED baseline density — still no self-consistency.\n"
           "# symmetry='off': the response code needs the unfolded Brillouin\n"
           "# zone.\n"
           "nscf = gs.fixed_density(\n"
           "    nbands=n_bands,\n"
           "    convergence={\"bands\": -10},\n"
           "    symmetry=\"off\",\n"
           "    txt=\"gpaw_nscf.txt\",\n"
           ")\n"
           "nscf.write(\"gw_gs.gpw\", mode=\"all\")\n"
           "_calango_log.progress(2, 4)\n"
           "\n"
           "# --- G0W0 quasiparticle correction -------------------------------\n"
           "from gpaw.response.g0w0 import G0W0\n"
           "\n"
        << "band_lo = max(0, n_occ - " << c.correctedBandsBelow << ")\n"
        << "band_hi = min(n_bands, n_occ + " << c.correctedBandsAbove << ")\n"
           "gw = G0W0(\n"
           "    calc=\"gw_gs.gpw\",\n"
           "    filename=\"gw\",\n"
           "    bands=(band_lo, band_hi),\n"
        << "    ecut=" << c.screeningCutoffEv << ",  # screened-interaction "
           "cutoff, eV — THE convergence parameter\n"
        << "    ppa=" << (c.frequency == GwFrequencyTreatment::PlasmonPole
                              ? "True"
                              : "False")
        << ",  # plasmon-pole vs. full real-axis frequency integration\n"
           "    # The screening sum must not ask for more bands than the ground\n"
           "    # state holds. Left to its default, G0W0 sizes this from ecut\n"
           "    # and overruns the NSCF band count — the run then dies on\n"
           "    # \"Increase GS-nbands or decrease chi0-nbands!\" only after the\n"
           "    # ground state has been recomputed.\n"
           "    nbands=n_bands,\n"
           "    nblocks=1,\n"
           ")\n"
           "result = gw.calculate()\n"
           "_calango_log.progress(3, 4)\n"
           "\n"
           "# result['qp'] is (spin, kpoint, band) in eV; 'eps' holds the DFT\n"
           "# eigenvalues over the same window, so the two are directly\n"
           "# comparable band for band.\n"
           "qp = np.asarray(result[\"qp\"])\n"
           "dft = np.asarray(result[\"eps\"])\n"
           "\n"
           "# Band edges: the highest occupied and lowest unoccupied state\n"
           "# within the corrected window. n_occ - band_lo is the index of the\n"
           "# HOMO inside that window.\n"
           "homo_index = n_occ - band_lo - 1\n"
           "lumo_index = homo_index + 1\n"
           "\n"
           "\n"
           "def _edges(values):\n"
           "    if homo_index < 0 or lumo_index >= values.shape[2]:\n"
           "        return None, None, None\n"
           "    vbm = float(np.max(values[:, :, homo_index]))\n"
           "    cbm = float(np.min(values[:, :, lumo_index]))\n"
           "    return vbm, cbm, cbm - vbm\n"
           "\n"
           "\n"
           "dft_vbm, dft_cbm, dft_gap = _edges(dft)\n"
           "gw_vbm, gw_cbm, gw_gap = _edges(qp)\n";
}

void emitYamboGw(std::ostringstream& out, const GwConfig& c)
{
    // Yambo is a chain of external executables, not a Python API, so the
    // script's job is orchestration + parsing rather than computation.
    out << "# --- Yambo G0W0 pipeline ----------------------------------------\n"
           "# Yambo has no Python API for this workflow, so the run is a chain\n"
           "# of executables. Each step is checked: a failure part-way through\n"
           "# otherwise leaves a plausible-looking directory whose report file\n"
           "# is from the PREVIOUS run.\n"
           "import glob\n"
           "import os\n"
           "import re\n"
           "import shutil\n"
           "import subprocess\n"
           "\n"
        << "baseline = r\"" << c.baselinePath << "\"\n"
           "\n"
           "\n"
           "def run(command, cwd=None, step=\"\"):\n"
           "    print(f\"CALANGO_INFO running: {' '.join(command)}\", flush=True)\n"
           "    completed = subprocess.run(command, cwd=cwd, capture_output=True,\n"
           "                               text=True)\n"
           "    if completed.returncode != 0:\n"
           "        raise RuntimeError(\n"
           "            f\"{step or command[0]} failed (exit "
           "{completed.returncode}).\\n\"\n"
           "            f\"stdout:\\n{completed.stdout[-2000:]}\\n\"\n"
           "            f\"stderr:\\n{completed.stderr[-2000:]}\")\n"
           "    return completed.stdout\n"
           "\n"
           "\n"
           "# 1. Locate the Quantum ESPRESSO .save directory the SCF wrote.\n"
           "saves = glob.glob(os.path.join(baseline, \"*.save\"))\n"
           "if not saves:\n"
           "    raise RuntimeError(\n"
           "        f\"no *.save directory in {baseline} — Yambo starts from a \"\n"
           "        \"completed pw.x run's saved wavefunctions.\")\n"
           "save_dir = saves[0]\n"
           "print(f\"CALANGO_INFO baseline save={save_dir}\", flush=True)\n"
           "_calango_log.progress(1, 4)\n"
           "\n"
           "# 2. p2y converts it into a Yambo SAVE/ database. It writes into\n"
           "#    its working directory, so it runs INSIDE the .save.\n"
           "run([\"p2y\"], cwd=save_dir, step=\"p2y (PWscf -> Yambo)\")\n"
           "produced = os.path.join(save_dir, \"SAVE\")\n"
           "if not os.path.isdir(produced):\n"
           "    raise RuntimeError(\"p2y did not produce a SAVE/ database\")\n"
           "if os.path.isdir(\"SAVE\"):\n"
           "    shutil.rmtree(\"SAVE\")\n"
           "shutil.copytree(produced, \"SAVE\")\n"
           "# Initialize the database in the job directory.\n"
           "run([\"yambo\"], step=\"yambo (database initialization)\")\n"
           "_calango_log.progress(2, 4)\n"
           "\n"
           "# 3. Generate the G0W0 input. -g n selects the GW solver, -p p the\n"
           "#    plasmon-pole screening (-p r would be the real-axis form).\n"
        << "run([\"yambo\", \"-g\", \"n\", \"-p\", \""
        << (c.frequency == GwFrequencyTreatment::PlasmonPole ? "p" : "r")
        << "\",\n"
           "     \"-F\", \"gw.in\"], step=\"yambo (input generation)\")\n"
           "\n"
           "# Patch the generated input with the convergence parameters. Yambo\n"
           "# inputs are line-oriented `Key= value` records, so each is\n"
           "# rewritten in place rather than appended — appending a duplicate\n"
           "# key silently loses to the first occurrence.\n"
           "with open(\"gw.in\") as handle:\n"
           "    lines = handle.readlines()\n"
           "\n"
           "overrides = {\n"
        << "    \"EXXRLvcs\": \"" << c.screeningCutoffEv << " eV\",\n"
        << "    \"NGsBlkXp\": \"" << c.screeningCutoffEv << " eV\",\n"
           "}\n"
           "patched = []\n"
           "seen = set()\n"
           "for line in lines:\n"
           "    key = line.split(\"=\")[0].strip().lstrip(\"%\").strip()\n"
           "    if key in overrides:\n"
           "        patched.append(f\"{key}= {overrides[key]}\\n\")\n"
           "        seen.add(key)\n"
           "    else:\n"
           "        patched.append(line)\n"
           "for key, value in overrides.items():\n"
           "    if key not in seen:\n"
           "        patched.append(f\"{key}= {value}\\n\")\n"
           "with open(\"gw.in\", \"w\") as handle:\n"
           "    handle.writelines(patched)\n"
           "\n"
           "# 4. Run it.\n"
        << "cores = " << (c.yamboCores > 1 ? std::to_string(c.yamboCores)
                                           : std::string("1"))
        << "\n"
           "command = ([\"mpirun\", \"-np\", str(cores)] if cores > 1 else []) + \\\n"
           "          [\"yambo\", \"-F\", \"gw.in\", \"-J\", \"gw\"]\n"
           "run(command, step=\"yambo (G0W0)\")\n"
           "_calango_log.progress(3, 4)\n"
           "\n"
           "# 5. Parse the quasiparticle report.\n"
           "#    Yambo writes o-<job>.qp with a commented header naming the\n"
           "#    columns, e.g.\n"
           "#      #  K-point  Band  Eo [eV]  E-Eo [eV]  Sc|Eo [eV]\n"
           "#    The column ORDER has differed between Yambo versions, so the\n"
           "#    header is parsed rather than assumed. Guessing wrong here does\n"
           "#    not fail loudly — it silently reports one column as another.\n"
           "QP_ALIASES = {\n"
           "    \"k-point\": \"kpoint\", \"kpt\": \"kpoint\", \"k\": \"kpoint\",\n"
           "    \"band\": \"band\", \"bnd\": \"band\",\n"
           "    \"eo\": \"e_dft\",\n"
           "    \"e-eo\": \"correction\",\n"
           "    \"e\": \"e_qp\",\n"
           "}\n"
           "# Used only when a report carries no recognizable header.\n"
           "QP_DEFAULT_COLUMNS = [\"kpoint\", \"band\", \"e_dft\", \"correction\"]\n"
           "\n"
           "\n"
           "def qp_header_columns(line):\n"
           "    \"\"\"Column keys from a '#' header line, or None if it names "
           "none.\"\"\"\n"
           "    text = line.lstrip(\"#\").strip()\n"
           "    if not text:\n"
           "        return None\n"
           "    # Column titles contain single spaces (\"K-point\", \"Sc|Eo "
           "[eV]\"),\n"
           "    # so they are separated on runs of two or more.\n"
           "    names = [part for part in re.split(r\"\\s{2,}\", text) if part]\n"
           "    keys = [QP_ALIASES.get(re.sub(r\"\\[.*?\\]\", \"\", name)"
           ".strip().lower())\n"
           "            for name in names]\n"
           "    # A header is only usable if it locates the energy itself.\n"
           "    return keys if \"e_dft\" in keys else None\n"
           "\n"
           "\n"
           "def parse_qp_report(path):\n"
           "    \"\"\"(band, kpoint, E_DFT, E_qp) rows from a Yambo .qp "
           "report.\"\"\"\n"
           "    columns = None\n"
           "    rows = []\n"
           "    with open(path) as handle:\n"
           "        for line in handle:\n"
           "            stripped = line.strip()\n"
           "            if not stripped:\n"
           "                continue\n"
           "            if stripped.startswith(\"#\"):\n"
           "                found = qp_header_columns(stripped)\n"
           "                if found:\n"
           "                    columns = found\n"
           "                continue\n"
           "            fields = re.split(r\"\\s+\", stripped)\n"
           "            record = {}\n"
           "            for key, field in zip(columns or QP_DEFAULT_COLUMNS,\n"
           "                                  fields):\n"
           "                if key is None:\n"
           "                    continue\n"
           "                try:\n"
           "                    record[key] = float(field)\n"
           "                except ValueError:\n"
           "                    record = None\n"
           "                    break\n"
           "            if not record or \"e_dft\" not in record:\n"
           "                continue\n"
           "            e_dft = record[\"e_dft\"]\n"
           "            if \"correction\" in record:\n"
           "                e_qp = e_dft + record[\"correction\"]\n"
           "            elif \"e_qp\" in record:\n"
           "                e_qp = record[\"e_qp\"]\n"
           "            else:\n"
           "                continue\n"
           "            rows.append((int(record.get(\"band\", 0)),\n"
           "                         int(record.get(\"kpoint\", 0)),\n"
           "                         e_dft, e_qp))\n"
           "    return rows\n"
           "\n"
           "\n"
           "# -J gw names the outputs o-gw.*, so that is the report this run\n"
           "# produced. Any other .qp in the directory is from an earlier run\n"
           "# and must not be preferred over it just because it sorts first.\n"
           "reports = ([p for p in glob.glob(\"o-gw.qp\")]\n"
           "           or sorted(glob.glob(\"*.qp\"), key=os.path.getmtime,\n"
           "                     reverse=True))\n"
           "if not reports:\n"
           "    raise RuntimeError(\"yambo produced no .qp quasiparticle report\")\n"
           "print(f\"CALANGO_INFO quasiparticle report={reports[0]}\", flush=True)\n"
           "rows = parse_qp_report(reports[0])\n"
           "if not rows:\n"
           "    raise RuntimeError(f\"could not parse any quasiparticle rows from \"\n"
           "                       f\"{reports[0]}\")\n"
           "\n"
           "# Band edges: occupied states are those below the DFT Fermi level,\n"
           "# which yambo reports relative to (E_DFT is already referenced to\n"
           "# it), so the sign of E_DFT separates valence from conduction.\n"
           "dft_valence = [r[2] for r in rows if r[2] <= 0.0]\n"
           "dft_conduction = [r[2] for r in rows if r[2] > 0.0]\n"
           "gw_valence = [r[3] for r in rows if r[2] <= 0.0]\n"
           "gw_conduction = [r[3] for r in rows if r[2] > 0.0]\n"
           "dft_vbm = max(dft_valence) if dft_valence else None\n"
           "dft_cbm = min(dft_conduction) if dft_conduction else None\n"
           "gw_vbm = max(gw_valence) if gw_valence else None\n"
           "gw_cbm = min(gw_conduction) if gw_conduction else None\n"
           "dft_gap = (dft_cbm - dft_vbm) if None not in (dft_vbm, dft_cbm) "
           "else None\n"
           "gw_gap = (gw_cbm - gw_vbm) if None not in (gw_vbm, gw_cbm) else None\n"
           "# Group by k-point so the reported matrix is (k-point x band), the\n"
           "# same shape the GPAW path emits and the viewer's table assumes.\n"
           "by_kpoint = {}\n"
           "for band, kpt, e_dft, e_qp in rows:\n"
           "    by_kpoint.setdefault(kpt, []).append((band, e_dft, e_qp))\n"
           "ordered = [sorted(states)\n"
           "           for _, states in sorted(by_kpoint.items())]\n"
           "band_counts = {len(states) for states in ordered}\n"
           "if len(band_counts) == 1:\n"
           "    dft = np.asarray([[s[1] for s in states] for states in ordered])\n"
           "    qp = np.asarray([[s[2] for s in states] for states in ordered])\n"
           "else:\n"
           "    # Ragged: yambo corrected a different number of bands per\n"
           "    # k-point. Reporting a padded matrix would invent states, so\n"
           "    # the states are emitted as one flat row and the reason said.\n"
           "    print(\"CALANGO_INFO quasiparticle rows are ragged \"\n"
           "          f\"(bands per k-point: {sorted(band_counts)}); reporting \"\n"
           "          \"them ungrouped\", flush=True)\n"
           "    dft = np.asarray([[r[2] for r in rows]])\n"
           "    qp = np.asarray([[r[3] for r in rows]])\n";
}

} // namespace

std::string generateGwScript(const GwConfig& config)
{
    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# G0W0 quasiparticle corrections — generated by Calango "
        << CALANGO_VERSION << "\n"
           "#\n"
           "# The quasiparticle energy is\n"
           "#   E_qp(n,k) = e_DFT(n,k) + Z(n,k) [Sigma(n,k; e_DFT) - V_xc(n,k)]\n"
           "# i.e. the DFT eigenvalue with its exchange-correlation potential\n"
           "# replaced by the (energy-dependent, non-local) self-energy. It is a\n"
           "# ONE-SHOT correction: nothing here is self-consistent, and the\n"
           "# result is only meaningful relative to the baseline it corrects.\n"
           "import json\n"
           "\n"
           "import numpy as np\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "_calango_log.progress(0, 4)\n"
           "\n";

    if (config.engine == GwEngine::Gpaw)
        emitGpawGw(out, config);
    else
        emitYamboGw(out, config);

    out << "\n"
           "# --- Summary ------------------------------------------------------\n"
        << "engine = \""
        << (config.engine == GwEngine::Gpaw ? "GPAW" : "Yambo") << "\"\n"
           "summary = {\n"
           "    \"engine\": engine,\n"
        << "    \"frequency_treatment\": \""
        << (config.frequency == GwFrequencyTreatment::PlasmonPole
                ? "plasmon-pole"
                : "real-axis")
        << "\",\n"
        << "    \"screening_cutoff_eV\": " << config.screeningCutoffEv << ",\n"
           "    \"dft_vbm_eV\": dft_vbm,\n"
           "    \"dft_cbm_eV\": dft_cbm,\n"
           "    \"dft_gap_eV\": dft_gap,\n"
           "    \"gw_vbm_eV\": gw_vbm,\n"
           "    \"gw_cbm_eV\": gw_cbm,\n"
           "    \"gw_gap_eV\": gw_gap,\n"
           "    # The headline number: how much the gap opens. GW typically\n"
           "    # widens a DFT gap by 0.5-2 eV, and a NEGATIVE renormalization\n"
           "    # is a strong hint the calculation is unconverged rather than a\n"
           "    # physical result.\n"
           "    \"gap_renormalization_eV\": (\n"
           "        None if None in (dft_gap, gw_gap) else gw_gap - dft_gap),\n"
           "    \"dft_eigenvalues_eV\": [[float(v) for v in row]\n"
           "                            for row in np.atleast_2d(dft.reshape("
           "-1, dft.shape[-1]))],\n"
           "    \"qp_eigenvalues_eV\": [[float(v) for v in row]\n"
           "                           for row in np.atleast_2d(qp.reshape("
           "-1, qp.shape[-1]))],\n"
           "}\n"
           "with open(\"gw.json\", \"w\") as handle:\n"
           "    json.dump(summary, handle)\n"
           "_calango_log.progress(4, 4)\n"
           "if summary[\"gap_renormalization_eV\"] is not None:\n"
           "    print(f\"CALANGO_RESULT dft_gap_eV={dft_gap:.4f} \"\n"
           "          f\"gw_gap_eV={gw_gap:.4f} \"\n"
           "          f\"renormalization_eV=\"\n"
           "          f\"{summary['gap_renormalization_eV']:.4f}\", flush=True)\n"
           "print(\"CALANGO_INFO wrote gw.json\", flush=True)\n"
           "print(\"CALANGO_DONE\", flush=True)\n";
    return out.str();
}

} // namespace calango::core
