#include "core/KPath.hpp"

#include <iomanip>
#include <sstream>

namespace calango::core {

namespace {

/// "G" is spelled out in exported files for readability.
std::string exportLabel(const std::string& label)
{
    return label == "G" ? "GAMMA" : label;
}

void emitPoint(std::ostringstream& out, const KPathPoint& point)
{
    out << "  " << std::fixed << std::setprecision(6)
        << std::setw(10) << point.fractional.x << " "
        << std::setw(10) << point.fractional.y << " "
        << std::setw(10) << point.fractional.z;
}

} // namespace

std::string toVaspKpoints(const std::vector<KPathPoint>& path, int divisionsPerSegment)
{
    std::ostringstream out;
    out << "k-path generated by Calango\n"
        << divisionsPerSegment << "\n"
        << "Line mode\n"
        << "Reciprocal\n";
    for (std::size_t i = 0; i + 1 < path.size(); ++i) {
        emitPoint(out, path[i]);
        out << "  ! " << exportLabel(path[i].label) << "\n";
        emitPoint(out, path[i + 1]);
        out << "  ! " << exportLabel(path[i + 1].label) << "\n";
        if (i + 2 < path.size())
            out << "\n";
    }
    return out.str();
}

std::string toQeKpointsCard(const std::vector<KPathPoint>& path, int pointsPerSegment)
{
    std::ostringstream out;
    out << "K_POINTS crystal_b\n" << path.size() << "\n";
    for (std::size_t i = 0; i < path.size(); ++i) {
        emitPoint(out, path[i]);
        // The count on the last point is ignored by pw.x; 1 by convention.
        out << " " << (i + 1 < path.size() ? pointsPerSegment : 1)
            << " ! " << exportLabel(path[i].label) << "\n";
    }
    return out.str();
}

} // namespace calango::core
