#include "core/KPath.hpp"

#include <iomanip>
#include <sstream>

namespace calango::core {

namespace {

/// "G" is spelled out in exported files for readability.
std::string exportLabel(const std::string& label)
{
    return label == "G" ? "GAMMA" : label;
}

void emitPoint(std::ostringstream& out, const KPathPoint& point)
{
    out << "  " << std::fixed << std::setprecision(6)
        << std::setw(10) << point.fractional.x << " "
        << std::setw(10) << point.fractional.y << " "
        << std::setw(10) << point.fractional.z;
}

/// Sections that can actually be drawn as lines (>= 2 points).
KPathSegments usable(const KPathSegments& sections)
{
    KPathSegments result;
    for (const auto& section : sections)
        if (section.size() >= 2)
            result.push_back(section);
    return result;
}

} // namespace

std::string toVaspKpoints(const KPathSegments& sections, int divisionsPerSegment)
{
    const KPathSegments path = usable(sections);
    std::ostringstream out;
    out << "k-path generated by Calango\n"
        << divisionsPerSegment << "\n"
        << "Line mode\n"
        << "Reciprocal\n";
    bool firstBlock = true;
    for (const auto& section : path) {
        for (std::size_t i = 0; i + 1 < section.size(); ++i) {
            if (!firstBlock)
                out << "\n";
            firstBlock = false;
            emitPoint(out, section[i]);
            out << "  ! " << exportLabel(section[i].label) << "\n";
            emitPoint(out, section[i + 1]);
            out << "  ! " << exportLabel(section[i + 1].label) << "\n";
        }
    }
    return out.str();
}

std::string toQeKpointsCard(const KPathSegments& sections, int pointsPerSegment)
{
    const KPathSegments path = usable(sections);
    std::size_t total = 0;
    for (const auto& section : path)
        total += section.size();

    std::ostringstream out;
    out << "K_POINTS crystal_b\n" << total << "\n";
    for (const auto& section : path) {
        for (std::size_t i = 0; i < section.size(); ++i) {
            emitPoint(out, section[i]);
            // A count of 1 on a section's last point both terminates the
            // line and encodes the discontinuity to the next section.
            out << " " << (i + 1 < section.size() ? pointsPerSegment : 1)
                << " ! " << exportLabel(section[i].label) << "\n";
        }
    }
    return out.str();
}

std::string toCastepPath(const KPathSegments& sections)
{
    const KPathSegments path = usable(sections);
    std::ostringstream out;
    out << "%BLOCK SPECTRAL_KPOINT_PATH\n";
    for (std::size_t s = 0; s < path.size(); ++s) {
        if (s > 0)
            out << "  break\n";
        for (const KPathPoint& point : path[s]) {
            emitPoint(out, point);
            out << "  ! " << exportLabel(point.label) << "\n";
        }
    }
    out << "%ENDBLOCK SPECTRAL_KPOINT_PATH\n";
    return out.str();
}

std::string toSiestaBandLines(const KPathSegments& sections, int pointsPerSegment)
{
    const KPathSegments path = usable(sections);
    const auto siestaLabel = [](const std::string& label) {
        return label == "G" ? std::string("\\Gamma") : label;
    };

    std::ostringstream out;
    out << "BandLinesScale ReciprocalLatticeVectors\n"
        << "%block BandLines\n";
    for (const auto& section : path) {
        for (std::size_t i = 0; i < section.size(); ++i) {
            // Each section restarts with a count of 1 (= "jump here").
            out << " " << std::setw(4) << (i == 0 ? 1 : pointsPerSegment);
            emitPoint(out, section[i]);
            out << "  " << siestaLabel(section[i].label) << "\n";
        }
    }
    out << "%endblock BandLines\n";
    return out.str();
}

std::string toAsePythonScript(const KPathSegments& sections, int totalPoints)
{
    const KPathSegments path = usable(sections);

    // Deduplicated special-point dictionary + "," separated path string.
    std::vector<KPathPoint> unique;
    const auto remember = [&unique](const KPathPoint& point) {
        for (const auto& existing : unique)
            if (existing.label == point.label)
                return;
        unique.push_back(point);
    };
    std::string pathString;
    for (std::size_t s = 0; s < path.size(); ++s) {
        if (s > 0)
            pathString += ",";
        for (const KPathPoint& point : path[s]) {
            remember(point);
            pathString += point.label;
        }
    }

    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# k-path generated by Calango — band-structure path for ASE.\n"
           "# Attach it to your Atoms object's cell to sample k-points.\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
           "atoms = read(\"structure.extxyz\")  # EDIT ME: your structure file\n"
           "\n"
           "special_points = {\n";
    for (const KPathPoint& point : unique) {
        out << "    \"" << point.label << "\": np.array(["
            << std::fixed << std::setprecision(6)
            << point.fractional.x << ", " << point.fractional.y << ", "
            << point.fractional.z << "]),\n";
    }
    out << "}\n"
        << "path_string = \"" << pathString << "\"  # \",\" = discontinuity\n"
        << "\n"
        << "bandpath = atoms.cell.bandpath(path=path_string,\n"
        << "                               npoints=" << totalPoints << ",\n"
        << "                               special_points=special_points)\n"
           "print(bandpath)\n"
           "kpts = bandpath.kpts  # (npoints, 3) fractional k-points\n"
           "np.savetxt(\"kpath.dat\", kpts, header=str(bandpath.path))\n";
    return out.str();
}

} // namespace calango::core
