#include "core/KpointsConvergenceScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

std::string KpointsConvergenceScriptGenerator::generate(
    const KpointsConvergenceRunConfig& config)
{
    const bool vasp =
        config.calculator.calculator == CalculatorKind::Vasp;
    CalculatorConfig calculator = config.calculator;
    if (vasp) {
        // Nothing restarts between points; one mesh's wavefunction and
        // density files must not leak into the next.
        calculator.vaspLwave = false;
        calculator.vaspLcharg = false;
    }

    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — k-point convergence with " << (vasp ? "VASP" : "GPAW")
        << ".\n"
           "# One fixed-geometry SCF per Monkhorst-Pack mesh, on the same\n"
           "# structure. The densest mesh is the reference: every point is\n"
           "# recorded as its distance from that run in total energy per atom\n"
           "# and in the maximum force magnitude, which are the quantities a\n"
           "# production k-grid has to reproduce.\n"
           "# This is a plain ASE script: edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "import math\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();
    if (!vasp)
        out << AseScriptGenerator::gpawImports(calculator);
    out << "\n"
           "# The sweep, ascending in density — the last entry is the\n"
           "# reference. K_PER_AXIS is the scalar each mesh was built from\n"
           "# (the swept axes' subdivision count); a pinned axis (a slab's\n"
           "# vacuum direction) stays at 1 in MESHES without disturbing it.\n"
           "MESHES = [";
    for (std::size_t i = 0; i < config.meshes.size(); ++i) {
        const auto& mesh = config.meshes[i];
        out << (i ? ", " : "") << "(" << mesh.kpts[0] << ", " << mesh.kpts[1]
            << ", " << mesh.kpts[2] << ")";
    }
    out << "]\n"
           "K_PER_AXIS = [";
    for (std::size_t i = 0; i < config.meshes.size(); ++i)
        out << (i ? ", " : "") << config.meshes[i].kPerAxis;
    out << "]\n"
           "\n"
           "results_path = r\""
        << config.resultsJson
        << "\"\n"
           "\n"
           "atoms = read(r\""
        << config.structureFile
        << "\")\n"
           "natoms = max(1, len(atoms))\n"
           "print(f\"CALANGO_INFO natoms={len(atoms)} \"\n"
           "      f\"meshes={len(MESHES)}\", flush=True)\n"
           "\n"
           "\n"
           "def attach_calculator(atoms, kpts):\n"
           "    \"\"\"Bind a fresh calculator at one k-point mesh.\n"
           "\n"
           "    Fresh per point rather than reused: a shared calculator would\n"
           "    carry the previous mesh's converged density into the next SCF\n"
           "    and quietly smooth out the very convergence behaviour the\n"
           "    sweep is trying to measure.\n"
           "    \"\"\"\n";
    if (vasp) {
        // The standard VASP calculator block (ENCUT, xc, INCAR extras), with
        // the mesh then overridden by the loop variable. One directory per
        // mesh; istart=0 forbids restarts across points. ASE's `gamma`
        // keyword is the Γ-centring switch for VASP's KPOINTS file.
        const std::string snippet =
            AseScriptGenerator::calculatorSnippet(calculator);
        std::istringstream lines(snippet);
        std::string line;
        while (std::getline(lines, line)) {
            if (line.empty())
                out << "\n";
            else
                out << "    " << line << "\n";
        }
        out << "    atoms.calc.set(kpts=tuple(kpts),\n"
            << "                   gamma="
            << (calculator.kptsGammaCentered ? "True" : "False")
            << ",  # Γ-centred KPOINTS, held across the sweep\n"
               "                   istart=0,\n"
               "                   directory="
               "f\"kpts_{kpts[0]}x{kpts[1]}x{kpts[2]}\")\n";
    } else {
        out << "    atoms.calc = GPAW(\n";
        if (calculator.kptsGammaCentered)
            out << "        # Γ-centred, as configured — held across the "
                   "sweep.\n"
                   "        kpts={\"size\": tuple(kpts), \"gamma\": True},\n";
        else
            out << "        kpts=tuple(kpts),  # the sweep variable\n";
        // The same keyword block every other generated GPAW script uses,
        // minus its kpts= line — that role is taken by the loop variable
        // above. Everything else (mode/cutoff, XC, eigensolver, mixer,
        // convergence targets, spin, Hubbard U, symmetry) is held fixed
        // across the sweep, as a convergence study requires.
        const std::string keywords = AseScriptGenerator::gpawKeywordArguments(
            calculator, "        ");
        std::istringstream lines(keywords);
        std::string line;
        while (std::getline(lines, line)) {
            if (line.find("kpts=") != std::string::npos)
                continue;
            out << line << "\n";
        }
        out << "        txt=f\"gpaw_kpts_{kpts[0]}x{kpts[1]}x{kpts[2]}"
               ".out\",\n"
               "    )\n";
    }
    out << ""
           "\n"
           "\n"
           "points = []\n"
           "evaluated = []  # per successful point: record + forces + eigenvalues\n"
           "\n"
           "for index, kpts in enumerate(MESHES):\n"
           "    _calango_progress(index, len(MESHES))\n"
           "    record = {\"kpts\": list(kpts),\n"
           "              \"k_per_axis\": int(K_PER_AXIS[index])}\n"
           "    label = \"x\".join(str(k) for k in kpts)\n"
           "    try:\n"
           "        attach_calculator(atoms, kpts)\n"
           "        energy = float(atoms.get_potential_energy())\n"
           "        forces = np.asarray(atoms.get_forces(), dtype=float)\n"
           "        # The per-atom force NORM, not the largest Cartesian\n"
           "        # component — componentwise maxima under-report by up to\n"
           "        # sqrt(3) depending on the force's direction.\n"
           "        magnitudes = (np.linalg.norm(forces, axis=1)\n"
           "                      if forces.size else np.zeros(0))\n"
           "        fmax = float(magnitudes.max()) if magnitudes.size else 0.0\n"
           "        record[\"energy_eV\"] = energy\n"
           "        record[\"energy_per_atom_eV\"] = energy / natoms\n"
           "        record[\"fmax_eV_per_A\"] = fmax\n"
           "        # Eigenvalues for the spectral-convergence metric:\n"
           "        # k-averaged band energies. Different meshes sample\n"
           "        # different k-points, so eigenvalues cannot be compared\n"
           "        # k-by-k across the sweep — but each band's BZ average\n"
           "        # can, and its drift with the mesh is exactly the\n"
           "        # sampling error the sweep measures. Weights are\n"
           "        # deliberately ignored: a fingerprint, not a DOS.\n"
           "        band_means = None\n"
           "        try:\n"
           "            calc = atoms.calc\n"
           "            nspins = calc.get_number_of_spins()\n"
           "            nkpts = len(calc.get_ibz_k_points())\n"
           "            eig = np.array(\n"
           "                [[calc.get_eigenvalues(kpt=k, spin=s)\n"
           "                  for k in range(nkpts)]\n"
           "                 for s in range(nspins)])\n"
           "            band_means = eig.mean(axis=(0, 1))\n"
           "        except Exception as eig_error:\n"
           "            # Forces and energies still stand; the third plot\n"
           "            # simply has one point fewer.\n"
           "            print(f\"CALANGO_WARN kpts={label} no eigenvalues: \"\n"
           "                  f\"{eig_error}\", flush=True)\n"
           "        evaluated.append({\"record\": record, \"forces\": forces,\n"
           "                          \"band_means\": band_means})\n"
           "        _calango_metric(index, energy=energy, max_force=fmax)\n"
           "        print(f\"CALANGO_MEMBER kpts={label} E={energy:.6f} \"\n"
           "              f\"fmax={fmax:.6f}\", flush=True)\n"
           "    except Exception as error:\n";
    if (config.continueOnFailure) {
        out << "        # One diverging coarse-mesh SCF must not lose the\n"
               "        # rest of the curve.\n"
               "        record[\"error\"] = str(error)\n"
               "        _calango_event(\"error\",\n"
               "                       f\"kpts {label} failed: {error}\")\n"
               "        print(f\"CALANGO_WARN kpts={label} failed: {error}\",\n"
               "              flush=True)\n";
    } else {
        out << "        raise\n";
    }
    out << "    points.append(record)\n"
           "\n"
           "_calango_progress(len(MESHES), len(MESHES))\n"
           "\n"
           "# -- Convergence relative to the best run --------------------------\n"
           "if not evaluated:\n"
           "    raise RuntimeError(\"Every mesh failed — nothing to use as \"\n"
           "                       \"the convergence reference.\")\n"
           "# MESHES ascends in density, so the last successful point is the\n"
           "# densest mesh — the reference the sweep is judged against.\n"
           "ref = evaluated[-1]\n"
           "reference = ref[\"record\"]\n"
           "for entry in evaluated:\n"
           "    p = entry[\"record\"]\n"
           "    # ΔE = (E_total − E_reference) / N — energy convergence is\n"
           "    # judged per atom so the criterion transfers between cells.\n"
           "    p[\"delta_energy_per_atom_eV\"] = (\n"
           "        p[\"energy_eV\"] - reference[\"energy_eV\"]) / natoms\n"
           "    # Force error: the largest atom-wise |F_i − F_i,ref| — the\n"
           "    # forces are compared vector-by-vector against the reference\n"
           "    # run and NOT divided by the atom count (a force is already a\n"
           "    # per-atom quantity). Comparing max|F| scalars instead would\n"
           "    # miss two wrong forces that happen to share a magnitude.\n"
           "    p[\"force_error_eV_per_A\"] = float(\n"
           "        np.linalg.norm(entry[\"forces\"] - ref[\"forces\"],\n"
           "                       axis=1).max()) if len(atoms) else 0.0\n"
           "    p[\"delta_fmax_eV_per_A\"] = (\n"
           "        p[\"fmax_eV_per_A\"] - reference[\"fmax_eV_per_A\"])\n"
           "    # Eigenvalue convergence: mean absolute difference of the\n"
           "    # k-averaged band energies against the reference, over the\n"
           "    # bands both runs computed.\n"
           "    if (entry[\"band_means\"] is not None\n"
           "            and ref[\"band_means\"] is not None):\n"
           "        nbands = min(len(entry[\"band_means\"]),\n"
           "                     len(ref[\"band_means\"]))\n"
           "        p[\"eigenvalue_mad_eV\"] = float(\n"
           "            np.abs(entry[\"band_means\"][:nbands]\n"
           "                   - ref[\"band_means\"][:nbands]).mean())\n"
           "\n"
           "converged = [e[\"record\"] for e in evaluated]\n"
           "\n"
           "summary = {\n"
           "    \"formula\": atoms.get_chemical_formula(),\n"
           "    \"natoms\": int(len(atoms)),\n"
           "    \"meshes\": len(points),\n"
           "    \"evaluated\": len(converged),\n"
           "    \"failed\": len(points) - len(converged),\n"
           "    \"reference\": {\n"
           "        \"kpts\": reference[\"kpts\"],\n"
           "        \"k_per_axis\": reference[\"k_per_axis\"],\n"
           "        \"energy_eV\": reference[\"energy_eV\"],\n"
           "        \"energy_per_atom_eV\": reference[\"energy_per_atom_eV\"],\n"
           "        \"fmax_eV_per_A\": reference[\"fmax_eV_per_A\"],\n"
           "    },\n"
           "}\n"
           "\n"
           "with open(results_path, \"w\") as handle:\n"
           "    json.dump({\"summary\": summary, \"points\": points}, handle,\n"
           "              indent=2)\n"
           "print(f\"CALANGO_INFO wrote {results_path}\", flush=True)\n"
           "print(\"CALANGO_RESULT kpoints_convergence=\" + results_path,\n"
           "      flush=True)\n"
           "_calango_event(\"done\",\n"
           "               f\"{len(converged)} of {len(points)} meshes \"\n"
           "               f\"evaluated; reference \"\n"
           "               + \"x\".join(str(k) for k in reference[\"kpts\"]))\n";
    return out.str();
}

} // namespace calango::core
