#include "core/LdosScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

namespace {

/// Python list literal of the spin indices this LdosConfig sums over,
/// resolved against the baseline's ACTUAL spin count at run time — not
/// baked in at generation time, since the wizard only knows the baseline's
/// spin polarization from calculator.json, which may be absent or stale.
/// An unpolarized/molecular baseline (nspins == 1) always uses channel 0
/// regardless of what the user picked; "Up"/"Down" only mean something once
/// a second channel exists.
std::string spinSelectionPython(LdosSpinChannel spin)
{
    switch (spin) {
    case LdosSpinChannel::Up:
        return "[0] if _nspins == 1 else [0]";
    case LdosSpinChannel::Down:
        return "[0] if _nspins == 1 else [1]";
    case LdosSpinChannel::Sum:
    default:
        return "[0] if _nspins == 1 else [0, 1]";
    }
}

const char* spinLabel(LdosSpinChannel spin)
{
    switch (spin) {
    case LdosSpinChannel::Up:
        return "up";
    case LdosSpinChannel::Down:
        return "down";
    case LdosSpinChannel::Sum:
    default:
        return "sum";
    }
}

} // namespace

std::string generateLdosScript(const LdosConfig& cfg)
{
    std::ostringstream out;
    out << "# Local Density of States (LDOS) — generated by Calango\n"
           "import json\n"
           "import os\n"
           "import glob\n"
           "import numpy as np\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << AseScriptGenerator::gpawRestartFromBaselineScript(
               cfg.baselineDir, "Local Density of States",
               "The LDOS integrates the SAVED Kohn-Sham states — re-run the "
               "single-point with wavefunctions saved (mode=all).")
        << "_calango_progress(1, 2)\n"
        << "\n"
        << AseScriptGenerator::gpawWaveFunctionHelperScript()
        << "\n";

    out << "_efermi = calc.get_fermi_level()\n"
        << "_e_min = " << cfg.energyMin
        << (cfg.relativeToFermi ? " + _efermi\n" : "\n")
        << "_e_max = " << cfg.energyMax
        << (cfg.relativeToFermi ? " + _efermi\n" : "\n")
        << "_nspins = calc.get_number_of_spins()\n"
        << "_spins = " << spinSelectionPython(cfg.spin) << "\n"
        << "_weights = calc.get_k_point_weights()\n"
        << "\n"
           "_ldos = None\n"
           "_states = []\n"
           "for _s in _spins:\n"
           "    for _k in range(len(_weights)):\n"
           "        _eigs = calc.get_eigenvalues(kpt=_k, spin=_s)\n"
           "        for _n, _e in enumerate(_eigs):\n"
           "            if not (_e_min <= _e <= _e_max):\n"
           "                continue\n"
           "            _psi = _calango_wave_function(calc, _n, _k, _s,\n"
           "                                          all_electron=False)\n"
           "            if _psi is None:\n"
           "                continue\n"
           "            _contribution = _weights[_k] * np.abs(_psi) ** 2\n"
           "            _ldos = (_contribution if _ldos is None\n"
           "                    else _ldos + _contribution)\n"
           "            _states.append({\n"
           "                'spin': int(_s), 'kpt': int(_k), 'band': int(_n),\n"
           "                'eigenvalue_eV': float(_e),\n"
           "                'weight': float(_weights[_k]),\n"
           "            })\n"
           "\n"
           "if _ldos is None:\n"
           "    raise RuntimeError(\n"
           "        'No Kohn-Sham states fall inside the selected energy "
           "window '\n"
           "        '[%.4f, %.4f] eV. Widen the window.' % (_e_min, _e_max))\n"
        << "_calango_progress(2, 2)\n"
        << "\n"
           "from ase.io.cube import write_cube\n"
        << "with open(r\"" << cfg.outputCube << "\", 'w') as _fh:\n"
           "    write_cube(_fh, atoms, data=_ldos)\n"
        << "\n"
        << "_summary = {\n"
           "    'baseline_dir': _base,\n"
           "    'gpw': _gpw_path,\n"
           "    'energy_min_eV': float(_e_min),\n"
           "    'energy_max_eV': float(_e_max),\n"
        << "    'relative_to_fermi': "
        << (cfg.relativeToFermi ? "True" : "False") << ",\n"
           "    'fermi_level_eV': float(_efermi),\n"
        << "    'spin_selection': '" << spinLabel(cfg.spin) << "',\n"
           "    'nspins': int(_nspins),\n"
           "    'nstates': len(_states),\n"
           "    'total_weight': float(sum(_st['weight'] for _st in "
           "_states)),\n"
           "    'states': _states,\n"
        << "    'cube': r\"" << cfg.outputCube << "\",\n"
           "}\n"
        << "with open(r\"" << cfg.resultsJson << "\", 'w') as _fh:\n"
           "    json.dump(_summary, _fh, indent=2)\n"
        << "print('CALANGO_RESULT ldos=" << cfg.resultsJson << "', flush=True)\n"
        << "print(f'CALANGO_SUMMARY states={len(_states)} "
           "window=[{_e_min:.3f},{_e_max:.3f}] eV', flush=True)\n"
           "_calango_event('done', "
           "f'LDOS written to " << cfg.outputCube << " ({len(_states)} states)')\n";

    return out.str();
}

} // namespace calango::core
