#include "core/LdosScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

namespace {

/// Python list literal of the spin indices this LdosConfig sums over,
/// resolved against the baseline's ACTUAL spin count at run time — not
/// baked in at generation time, since the wizard only knows the baseline's
/// spin polarization from calculator.json, which may be absent or stale.
/// An unpolarized/molecular baseline (nspins == 1) always uses channel 0
/// regardless of what the user picked; "Up"/"Down" only mean something once
/// a second channel exists.
std::string spinSelectionPython(LdosSpinChannel spin)
{
    switch (spin) {
    case LdosSpinChannel::Up:
        return "[0] if _nspins == 1 else [0]";
    case LdosSpinChannel::Down:
        return "[0] if _nspins == 1 else [1]";
    case LdosSpinChannel::Sum:
    default:
        return "[0] if _nspins == 1 else [0, 1]";
    }
}

const char* spinLabel(LdosSpinChannel spin)
{
    switch (spin) {
    case LdosSpinChannel::Up:
        return "up";
    case LdosSpinChannel::Down:
        return "down";
    case LdosSpinChannel::Sum:
    default:
        return "sum";
    }
}

} // namespace

std::string generateLdosScript(const LdosConfig& cfg)
{
    // VASP is a COMPLETELY DIFFERENT path -- a post-processing LPARD run
    // VASP performs itself, not a sum over stored wavefunctions -- so it
    // bypasses everything below rather than threading a second engine
    // branch through GPAW-oriented code. Same shape as
    // generateWannierScript()'s own VASP dispatch.
    if (cfg.calculator.calculator == CalculatorKind::Vasp)
        return generateVaspLdosScript(cfg);

    std::ostringstream out;
    out << "# Local Density of States (LDOS) — generated by Calango\n"
           "import json\n"
           "import os\n"
           "import glob\n"
           "import numpy as np\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << AseScriptGenerator::gpawRestartFromBaselineScript(
               cfg.baselineDir, "Local Density of States",
               "The LDOS integrates the SAVED Kohn-Sham states — re-run the "
               "single-point with wavefunctions saved (mode=all).")
        << "_calango_progress(1, 2)\n"
        << "\n"
        << AseScriptGenerator::gpawWaveFunctionHelperScript()
        << "\n";

    out << "_efermi = calc.get_fermi_level()\n"
        << "_e_min = " << cfg.energyMin
        << (cfg.relativeToFermi ? " + _efermi\n" : "\n")
        << "_e_max = " << cfg.energyMax
        << (cfg.relativeToFermi ? " + _efermi\n" : "\n")
        << "_nspins = calc.get_number_of_spins()\n"
        << "_spins = " << spinSelectionPython(cfg.spin) << "\n"
        << "_weights = calc.get_k_point_weights()\n"
        << "\n"
           "_ldos = None\n"
           "_states = []\n"
           "for _s in _spins:\n"
           "    for _k in range(len(_weights)):\n"
           "        _eigs = calc.get_eigenvalues(kpt=_k, spin=_s)\n"
           "        for _n, _e in enumerate(_eigs):\n"
           "            if not (_e_min <= _e <= _e_max):\n"
           "                continue\n"
           "            _psi = _calango_wave_function(calc, _n, _k, _s,\n"
           "                                          all_electron=False)\n"
           "            if _psi is None:\n"
           "                continue\n"
           "            _contribution = _weights[_k] * np.abs(_psi) ** 2\n"
           "            _ldos = (_contribution if _ldos is None\n"
           "                    else _ldos + _contribution)\n"
           "            _states.append({\n"
           "                'spin': int(_s), 'kpt': int(_k), 'band': int(_n),\n"
           "                'eigenvalue_eV': float(_e),\n"
           "                'weight': float(_weights[_k]),\n"
           "            })\n"
           "\n"
           "if _ldos is None:\n"
           "    raise RuntimeError(\n"
           "        'No Kohn-Sham states fall inside the selected energy "
           "window '\n"
           "        '[%.4f, %.4f] eV. Widen the window.' % (_e_min, _e_max))\n"
        << "_calango_progress(2, 2)\n"
        << "\n"
           "from ase.io.cube import write_cube\n"
        << "with open(r\"" << cfg.outputCube << "\", 'w') as _fh:\n"
           "    write_cube(_fh, atoms, data=_ldos)\n"
        << "\n"
        << "_summary = {\n"
           "    'baseline_dir': _base,\n"
           "    'gpw': _gpw_path,\n"
           "    'energy_min_eV': float(_e_min),\n"
           "    'energy_max_eV': float(_e_max),\n"
        << "    'relative_to_fermi': "
        << (cfg.relativeToFermi ? "True" : "False") << ",\n"
           "    'fermi_level_eV': float(_efermi),\n"
        << "    'spin_selection': '" << spinLabel(cfg.spin) << "',\n"
           "    'nspins': int(_nspins),\n"
           "    'nstates': len(_states),\n"
           "    'total_weight': float(sum(_st['weight'] for _st in "
           "_states)),\n"
           "    'states': _states,\n"
        << "    'cube': r\"" << cfg.outputCube << "\",\n"
           "}\n"
        << "with open(r\"" << cfg.resultsJson << "\", 'w') as _fh:\n"
           "    json.dump(_summary, _fh, indent=2)\n"
        << "print('CALANGO_RESULT ldos=" << cfg.resultsJson << "', flush=True)\n"
        << "print(f'CALANGO_SUMMARY states={len(_states)} "
           "window=[{_e_min:.3f},{_e_max:.3f}] eV', flush=True)\n"
           "_calango_event('done', "
           "f'LDOS written to " << cfg.outputCube << " ({len(_states)} states)')\n";

    return out.str();
}


std::string generateVaspLdosScript(const LdosConfig& cfg)
{
    const CalculatorConfig& c = cfg.calculator;
    const std::string kpts = std::to_string(c.kpts[0]) + ", "
        + std::to_string(c.kpts[1]) + ", " + std::to_string(c.kpts[2]);
    // Must match whatever wrote the WAVECAR: ISTART = 1 "redefines and
    // re-pads the set of plane waves according to the new cell size/shape
    // and the new plane wave cut-off" (VASP wiki: ISTART) rather than
    // refusing, so a PREC/ENCUT mismatch is silent, not an error.
    const std::string vaspPrec = AseScriptGenerator::vaspPrecString(c.vaspPrec);

    std::ostringstream out;
    out << "# Local Density of States (LDOS) via VASP's LPARD — generated by "
           "Calango\n"
           "#\n"
           "# NOT the sum Calango performs on the GPAW path. VASP computes the\n"
           "# state-resolved density itself: LPARD = .TRUE. evaluates the\n"
           "# partial charge density from the orbitals in a WAVECAR, selecting\n"
           "# states by the energy window in EINT. The VASP wiki calls it \"a\n"
           "# postprocessing step that requires a pre-converged calculation\"\n"
           "# in which \"no electronic (or ionic) minimization is performed\".\n"
           "import json\n"
           "import os\n"
           "import shutil\n"
           "import subprocess\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "from ase.calculators.vasp import Vasp, VaspChargeDensity\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "atoms = read('structure.extxyz')\n"
        << AseScriptGenerator::vaspPotcarResolutionSnippet(c)
        << "_calango_progress(1, 4)\n"
           "\n"
        << "_base = r\"" << cfg.baselineDir << "\"\n"
        << R"PY(
# --- Stage the parent's orbitals -----------------------------------------
# `baseline.WAVECAR` is what MainWindow::stageJob() copies in for a REMOTE
# job (the parent's own directory does not exist on the compute node), so it
# wins over the generation-time absolute path when it is present.
def _stage(name, staged, why):
    _local = 'baseline.' + name
    _src = _local if os.path.exists(_local) else os.path.join(_base, name)
    if not os.path.exists(_src):
        raise RuntimeError(
            'No %s found for the parent run in %s. %s' % (name, _base, why))
    if os.path.abspath(_src) != os.path.abspath(name):
        shutil.copyfile(_src, name)
    return os.path.getsize(name)

_wave_bytes = _stage(
    'WAVECAR', 'baseline.WAVECAR',
    'LPARD reads the converged ORBITALS, which live only in WAVECAR - '
    're-run the parent with LWAVE = .TRUE. (Calango sets it automatically '
    'when an LDOS node is chained onto a VASP parent).')
# A WAVECAR that exists but holds nothing is the common shape of this
# failure: VASP creates the file at startup and only fills it at the end, so
# a parent that died mid-run leaves a small one behind. Caught here, by
# size, rather than 300 lines into VASP's own output.
if _wave_bytes < 4096:
    raise RuntimeError(
        'The parent WAVECAR is only %d bytes - it holds no orbitals. The '
        'parent run did not finish, or ran with LWAVE = .FALSE.'
        % _wave_bytes)
_calango_event('info', 'staged the parent WAVECAR (%.1f MB)'
               % (_wave_bytes / 1048576.0))

# CHGCAR is not required by LPARD (the wiki's own recipe copies only POSCAR,
# KPOINTS and WAVECAR) but it costs nothing to reuse when the parent left one
# and it keeps the potential identical to the parent's.
try:
    _stage('CHGCAR', 'baseline.CHGCAR', '')
except RuntimeError:
    _calango_event('info', 'the parent left no CHGCAR; LPARD does not need '
                           'one - the orbitals in WAVECAR are the input.')

# --- Refuse a noncollinear parent ----------------------------------------
# "LPARD is not supported for noncollinear calculations" (VASP wiki: LPARD).
# A spin-orbit parent would otherwise fail inside VASP with no indication
# that the module, not the input, is the problem.
_parent_incar = os.path.join(_base, 'INCAR')
if os.path.exists(_parent_incar):
    with open(_parent_incar) as _fh:
        _txt = _fh.read().upper()
    for _tag in ('LSORBIT', 'LNONCOLLINEAR'):
        for _line in _txt.splitlines():
            _line = _line.split('!')[0].split('#')[0]
            if _tag in _line and 'T' in _line.split('=')[-1]:
                raise RuntimeError(
                    'The parent run is noncollinear (%s = .TRUE.). The VASP '
                    'wiki states that LPARD is not supported for '
                    'noncollinear calculations, so an LDOS cannot be taken '
                    'from it - re-run the parent collinear, or use the GPAW '
                    'route.' % _tag)

# --- The parent's Fermi level, for the record ----------------------------
# NBMOD = -3 makes VASP add E_F to the EINT bounds itself, so this is not an
# input; it is recorded so ldos.json can report the ABSOLUTE window that was
# actually used, the way the GPAW path does.
_efermi = None
_parent_outcar = os.path.join(_base, 'OUTCAR')
if os.path.exists(_parent_outcar):
    with open(_parent_outcar, errors='replace') as _fh:
        for _line in _fh:
            if 'E-fermi' in _line:
                try:
                    _efermi = float(_line.split(':')[1].split()[0])
                except (IndexError, ValueError):
                    pass
if _efermi is None:
    _calango_event('warning',
                   'could not read the parent Fermi level from OUTCAR; the '
                   'window below is still applied by VASP itself, but '
                   'ldos.json can only report it relative to E_F.')
else:
    _calango_event('info', 'parent Fermi level: %.4f eV' % _efermi)
_calango_progress(2, 4)
)PY";

    // --- The LPARD pass itself --------------------------------------------
    out << "\n"
           "# --- The LPARD pass ------------------------------------------\n"
           "# Every tag here is from the VASP wiki, and only these select the\n"
           "# states: NBMOD picks the selection MODE, EINT carries the window\n"
           "# in eV. ISTART = 1 is VASP's own default when a WAVECAR exists\n"
           "# and is set explicitly so the INCAR says what it is doing.\n"
        << "_calc = Vasp(\n"
        << "    xc=\"" << c.vaspXc << "\", encut=" << c.planeWaveCutoffEv
        << ", prec=\"" << vaspPrec << "\",\n"
        << "    kpts=(" << kpts << "), gamma="
        << (c.kptsGammaCentered ? "True" : "False") << ", directory=\".\",\n"
           "    # \"Continuation job: restart with constant energy cut-off.\n"
           "    #  Orbitals are read from the WAVECAR file.\" (wiki: ISTART)\n"
           "    istart=1,\n"
           "    # \"Determines whether partial (band and/or k-point-\n"
           "    #  decomposed) charge densities are evaluated.\" (wiki: LPARD)\n"
           "    lpard=True,\n";

    // NBMOD / EINT / IBAND, per the wiki's own precedence rules.
    if (!cfg.bands.empty()) {
        out << "    # IBAND is set, so \"NBMOD is set automatically to the "
               "number of\n"
               "    # values passed in IBAND\" and EINT is not consulted at "
               "all\n"
               "    # (wiki: NBMOD). The energy window is therefore NOT "
               "written.\n"
            << "    iband=[";
        for (std::size_t i = 0; i < cfg.bands.size(); ++i)
            out << (i ? ", " : "") << cfg.bands[i];
        out << "],\n";
    } else {
        out << (cfg.relativeToFermi
                    ? "    # \"Use an energy interval to select contributing "
                      "bands and add\n"
                      "    #  the Fermi energy to the passed values\" "
                      "(wiki: NBMOD = -3)\n"
                      "    nbmod=-3,\n"
                    : "    # \"Use an absolute energy interval to select "
                      "contributing\n"
                      "    #  bands\" (wiki: NBMOD = -2)\n"
                      "    nbmod=-2,\n")
            << "    # The window, in eV. VASP flips the two values internally "
               "if the\n"
               "    # first is larger, so the order here is not load-bearing "
               "(wiki: EINT).\n"
            << "    eint=[" << cfg.energyMin << ", " << cfg.energyMax
            << "],\n";
    }
    if (!cfg.kpoints.empty()) {
        out << "    # KPUSE: only these k-points contribute (1-based).\n"
            << "    kpuse=[";
        for (std::size_t i = 0; i < cfg.kpoints.size(); ++i)
            out << (i ? ", " : "") << cfg.kpoints[i];
        out << "],\n";
    }
    out << "    # LSEPB/LSEPK: one summed PARCHG, or one file per band and/or\n"
           "    # k-point named PARCHG.<band>.<kpt> (wiki: LSEPB).\n"
        << "    lsepb=" << (cfg.separateBands ? "True" : "False")
        << ", lsepk=" << (cfg.separateKpoints ? "True" : "False") << ",\n"
           "    # Nothing to write back: this run updates neither the density\n"
           "    # nor the orbitals it read.\n"
           "    lwave=False, lcharg=False,\n"
        // No LDAU block, deliberately. An LPARD pass performs no electronic
        // minimization at all -- it reads converged orbitals and sums them --
        // so a Hubbard correction has nothing to act on here, and the LDOS
        // wizard has no calculator stage to specify one on anyway. Emitting
        // the wizard's own (empty, or worse, defaulted) table would risk
        // writing a +U the parent never had.
        << ")\n";

    out << R"PY(
# ASE's own run() would parse OUTCAR for an energy afterwards. An LPARD run
# performs no minimization and reports none, so the inputs are written and
# the binary invoked directly - the result of this job is PARCHG, not a
# number ASE knows how to read back.
_calc.write_input(atoms)

# The wiki's own recipe for an LPARD run is "copy POSCAR, KPOINTS, and
# WAVECAR to a new directory" - the k-points must be the ones the orbitals
# were computed on. So the parent's KPOINTS is copied over the one ASE just
# wrote from the (n1, n2, n3) triple above, which is a FALLBACK, not the
# intent: a triple cannot express an explicit k-point list or a line-mode
# path at all, and for an even grid a Monkhorst-Pack and a Gamma-centred
# mesh of the same size are different meshes.
_parent_kpoints = os.path.join(_base, 'KPOINTS')
if os.path.exists(_parent_kpoints):
    shutil.copyfile(_parent_kpoints, 'KPOINTS')
    _calango_event('info', "reusing the parent's KPOINTS verbatim")
else:
    _calango_event('warning',
                   'the parent left no KPOINTS file; this run regenerates '
                   'the mesh from its recorded grid, which is right only if '
                   'the parent used the same one.')

# The WAVECAR belongs to a specific cell. ISTART = 1 "redefines and re-pads
# the set of plane waves according to the new cell size/shape" rather than
# refusing (wiki: ISTART), so a mismatch here is silent reinterpretation of
# somebody else's orbitals - said out loud instead.
_parent_poscar = os.path.join(_base, 'POSCAR')
if os.path.exists(_parent_poscar):
    try:
        from ase.io import read as _read
        _pcell = np.asarray(_read(_parent_poscar, format='vasp').cell)
        if not np.allclose(_pcell, np.asarray(atoms.cell), atol=1e-4):
            _calango_event('warning',
                           'this run\'s cell differs from the parent\'s. '
                           'VASP will re-pad the plane-wave basis rather '
                           'than refuse, so the LDOS would describe the '
                           'parent\'s orbitals in the wrong cell.')
    except Exception as _exc:
        _calango_event('info', 'could not compare cells (%s)' % _exc)

_command = (os.environ.get('ASE_VASP_COMMAND')
            or os.environ.get('VASP_COMMAND')
            or 'vasp_std')
_calango_event('info', 'running: %s' % _command)
_proc = subprocess.run(_command, shell=True, capture_output=True, text=True)
with open('vasp.out', 'w') as _fh:
    _fh.write(_proc.stdout)
if _proc.stderr:
    with open('vasp.err', 'w') as _fh:
        _fh.write(_proc.stderr)

# VASP's own warning banner is spelled with spaces between the letters, so a
# naive grep for 'warning' finds nothing in a run that emitted several. Every
# one of them is surfaced rather than assumed benign.
for _line in _proc.stdout.splitlines():
    if 'W A R N I N G' in _line or 'internal error' in _line.lower():
        _calango_event('warning', 'VASP: ' + _line.strip())
if _proc.returncode != 0:
    raise RuntimeError(
        'VASP exited %d during the LPARD pass. The last lines of its output:'
        '\n%s' % (_proc.returncode,
                  '\n'.join(_proc.stdout.splitlines()[-20:]) or '(none)'))
_calango_progress(3, 4)

# --- Collect the PARCHG files --------------------------------------------
# LSEPB/LSEPK decide the names: 'PARCHG' when both are off, otherwise
# PARCHG.<band>.<kpt> with ALLB/ALLK standing in for a summed axis.
_parchg = sorted(_f for _f in os.listdir('.') if _f.startswith('PARCHG'))
if not _parchg:
    raise RuntimeError(
        'VASP finished but wrote no PARCHG. With NBMOD = -1 - which is what '
        'VASP falls back to when neither EINT nor IBAND is set - the density '
        'goes to CHGCAR instead and no partial charge output is produced. '
        'Check the INCAR this job wrote, and OUTCAR for VASP\'s own account.')
)PY";

    out << "\n"
           "from ase.io.cube import write_cube\n"
        << "_outputs = []\n"
        << "for _i, _name in enumerate(_parchg):\n"
           "    _chg = VaspChargeDensity(_name)\n"
           "    _frame = _chg.atoms[-1]\n"
           "    # ASE's VaspChargeDensity._read_chg already divides the raw\n"
           "    # CHGCAR values by the cell volume (`chg /= volume`, verified\n"
           "    # against ase/calculators/vasp/vasp.py), so what comes back is\n"
           "    # ALREADY e/Ang^3 - the units the cube writer and every\n"
           "    # Calango consumer assume. Dividing again is off by the cell\n"
           "    # volume, which for Si is a factor of 40: the integral below\n"
           "    # is what catches it, and it is checked against the valence\n"
           "    # electron count in tests/vasp_lpard_ldos_test.py.\n"
           "    _grid = np.asarray(_chg.chg[-1], dtype=float)\n"
        << "    _cube = (r\"" << cfg.outputCube << "\" if len(_parchg) == 1\n"
           "             else 'ldos_%s.cube' % _name[len('PARCHG'):].strip("
           "'.') )\n"
           "    with open(_cube, 'w') as _fh:\n"
           "        write_cube(_fh, _frame, data=_grid)\n"
           "    _outputs.append({\n"
           "        'parchg': _name,\n"
           "        'cube': _cube,\n"
           "        'grid': [int(_v) for _v in _grid.shape],\n"
           "        'integral_e': float(_grid.sum() * _frame.get_volume()\n"
           "                            / _grid.size),\n"
           "    })\n"
           "    _calango_event('info', '%s -> %s (%dx%dx%d, %.4f e)'\n"
           "                   % (_name, _cube, _grid.shape[0], "
           "_grid.shape[1],\n"
           "                      _grid.shape[2], "
           "_outputs[-1]['integral_e']))\n"
           "_calango_progress(4, 4)\n"
           "\n";

    out << "_summary = {\n"
           "    'engine': 'VASP',\n"
           "    'baseline_dir': _base,\n"
           "    'gpw': None,\n"
        << "    'energy_min_eV': " << cfg.energyMin << ",\n"
        << "    'energy_max_eV': " << cfg.energyMax << ",\n"
        << "    'relative_to_fermi': "
        << (cfg.relativeToFermi ? "True" : "False") << ",\n"
           "    'fermi_level_eV': _efermi,\n"
           // The GPAW path enumerates every state it summed. VASP does the
           // selection internally and reports no state list, so the field is
           // present and empty rather than absent: a consumer that reads
           // `nstates` must be able to tell "none selected" from "not
           // reported", and only an explicit null does that.
           "    'nstates': None,\n"
           "    'states': [],\n"
        // The selection mode VASP actually ran in, recorded so a reader of
        // ldos.json can tell a Fermi-relative window from an absolute one
        // from an explicit band list without re-deriving it from the INCAR.
        << "    'nbmod': "
        << (cfg.bands.empty() ? (cfg.relativeToFermi ? "-3" : "-2")
                              : std::to_string(cfg.bands.size()))
        << ",\n"
        << "    'iband': ["
        << [&] {
               std::string list;
               for (std::size_t i = 0; i < cfg.bands.size(); ++i)
                   list += (i ? ", " : "") + std::to_string(cfg.bands[i]);
               return list;
           }()
        << "],\n"
        << "    'separate_bands': "
        << (cfg.separateBands ? "True" : "False") << ",\n"
        << "    'separate_kpoints': "
        << (cfg.separateKpoints ? "True" : "False") << ",\n"
           "    'outputs': _outputs,\n"
           "    'cube': _outputs[0]['cube'],\n"
           "}\n"
        << "with open(r\"" << cfg.resultsJson << "\", 'w') as _fh:\n"
           "    json.dump(_summary, _fh, indent=2)\n"
        << "print('CALANGO_RESULT ldos=" << cfg.resultsJson << "', flush=True)\n"
           "print('CALANGO_SUMMARY parchg=%d window=[%s,%s] eV'\n"
        << "      % (len(_outputs), " << cfg.energyMin << ", "
        << cfg.energyMax << "), flush=True)\n"
           "_calango_event('done', 'LDOS written to %s (%d PARCHG file(s))'\n"
           "               % (_outputs[0]['cube'], len(_outputs)))\n";

    return out.str();
}

} // namespace calango::core
