#include "core/OpticsScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>
#include <string>

namespace calango::core {

std::string generateOpticsScript(const OpticsConfig& cfg)
{
    const CalculatorConfig& c = cfg.calculator;

    // The list of (json-key, GPAW axis) pairs the response loop iterates over,
    // filtered to the directions the user asked for. Guard against an empty
    // selection so the script always produces at least one spectrum.
    std::string directions;
    const auto addDirection = [&directions](bool enabled, const char* key,
                                            const char* axis) {
        if (!enabled)
            return;
        if (!directions.empty())
            directions += ", ";
        directions += std::string("(\"") + key + "\", \"" + axis + "\")";
    };
    addDirection(cfg.dirX, "xx", "x");
    addDirection(cfg.dirY, "yy", "y");
    addDirection(cfg.dirZ, "zz", "z");
    if (directions.empty())
        directions = "(\"xx\", \"x\")";

    std::ostringstream out;
    out << "# Optical properties (linear dielectric response) — generated by "
           "Calango\n"
           "import json\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "atoms = read(\"structure.extxyz\")\n"
           "_calango_log.progress(0, 4)\n"
           "\n"
           "# --- Ground state (self-consistent) "
           "---------------------------------\n"
           "# GPAW's response module needs a plane-wave ground state, so PW mode\n"
           "# is used here regardless of the engine's default discretization.\n"
           "from gpaw import GPAW, PW\n"
           "\n"
           "calc = GPAW(\n"
        << "    mode=PW(" << c.planeWaveCutoffEv << "),  # plane-wave cutoff, eV\n"
        << "    xc=\"" << c.gpawXc << "\",\n"
        << "    kpts=(" << c.kpts[0] << ", " << c.kpts[1] << ", " << c.kpts[2]
        << "),  # Monkhorst-Pack grid\n"
           "    txt=\"gpaw_gs.txt\",\n"
           ")\n"
           "atoms.calc = calc\n"
           "atoms.get_potential_energy()\n"
           "calc.write(\"gs.gpw\", mode=\"all\")\n"
           "_calango_log.progress(1, 4)\n"
           "\n"
           "# --- Fixed-density NSCF with extra empty bands "
           "----------------------\n"
           "# The dielectric response sums transitions into unoccupied states, so\n"
           "# a generous number of empty bands (and a denser k-grid) improves the\n"
           "# spectrum. The empty bands are converged at the fixed SCF density.\n"
           "gs = GPAW(\"gs.gpw\")\n"
           "n_occ = max(1, int(round(gs.get_number_of_electrons() / 2.0)))\n"
           "n_bands = max(4 * n_occ, 24)  # occupied + empty bands\n"
           "nscf = gs.fixed_density(\n"
           "    nbands=n_bands,\n"
           "    convergence={\"bands\": max(2 * n_occ, 12)},\n"
           "    symmetry=\"off\",\n"
           "    txt=\"gpaw_nscf.txt\",\n"
           ")\n"
           "nscf.write(\"gs_nscf.gpw\", mode=\"all\")\n"
           "_calango_log.progress(2, 4)\n"
           "\n"
           "# --- Dielectric function via GPAW's response module "
           "-----------------\n"
           "try:\n"
           "    from gpaw.response.df import DielectricFunction\n"
           "except Exception as exc:  # pragma: no cover\n"
           "    raise RuntimeError(\n"
           "        \"GPAW's response module (gpaw.response.df) is required for \"\n"
           "        \"the optical-properties workflow but could not be imported: \"\n"
           "        f\"{exc}\"\n"
           "    )\n"
           "\n"
        << "frequencies = np.linspace(" << cfg.omegaMinEv << ", " << cfg.omegaMaxEv
        << ", " << cfg.npoints << ")  # photon energy grid, eV\n"
           "df = DielectricFunction(\n"
           "    \"gs_nscf.gpw\",\n"
           "    frequencies=frequencies,\n"
        << "    eta=" << cfg.broadeningEv << ",  # Lorentzian broadening η, eV\n"
           "    txt=\"gpaw_df.txt\",\n"
           ")\n"
           "_calango_log.progress(3, 4)\n"
           "\n"
           "# ħc = 197.3269804 eV·nm = 197.3269804e-7 eV·cm. With ħω in eV the\n"
           "# absorption coefficient α = 2 (ω / ħc) k then comes out in cm^-1.\n"
           "hbar_c_eV_cm = 197.3269804e-7\n"
           "omega_eV = frequencies\n"
           "\n"
           "results = {\"energy_eV\": [float(w) for w in frequencies]}\n"
           "\n"
        << "directions = [" << directions << "]\n"
           "for key, axis in directions:\n"
           "    # (nlfc, lfc): without and with local-field corrections; the\n"
           "    # local-field-corrected result is the physically complete one.\n"
           "    eps_nlfc, eps_lfc = df.get_dielectric_function(direction=axis)\n"
           "    eps = np.asarray(eps_lfc)\n"
           "    eps1 = eps.real\n"
           "    eps2 = eps.imag\n"
           "    refractive = np.sqrt(eps)  # complex refractive index N = n + i k\n"
           "    n = refractive.real\n"
           "    k = refractive.imag\n"
           "    absorption = 2.0 * (omega_eV / hbar_c_eV_cm) * k  # cm^-1\n"
           "    reflectivity = ((n - 1.0) ** 2 + k ** 2) / "
           "((n + 1.0) ** 2 + k ** 2)\n"
           "    loss = (-1.0 / eps).imag  # energy-loss function -Im(1/ε)\n"
           "    results[key] = {\n"
           "        \"eps1\": [float(v) for v in eps1],\n"
           "        \"eps2\": [float(v) for v in eps2],\n"
           "        \"absorption\": [float(v) for v in absorption],\n"
           "        \"reflectivity\": [float(v) for v in reflectivity],\n"
           "        \"n\": [float(v) for v in n],\n"
           "        \"k\": [float(v) for v in k],\n"
           "        \"loss\": [float(v) for v in loss],\n"
           "    }\n"
           "    # Convenience top-level duplicate of the diagonal ε components.\n"
           "    results[\"eps_\" + key] = {\n"
           "        \"eps1\": [float(v) for v in eps1],\n"
           "        \"eps2\": [float(v) for v in eps2],\n"
           "    }\n"
           "\n"
           "with open(\"optics.json\", \"w\") as handle:\n"
           "    json.dump(results, handle)\n"
           "_calango_log.progress(4, 4)\n"
           "print(\"CALANGO_RESULT optics=optics.json\", flush=True)\n";
    return out.str();
}

} // namespace calango::core
