#include "core/PiezoelectricScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"
#include "core/LocaleSafeNumber.hpp"
#include "core/PolarizationScriptHelpers.hpp"
#include "core/StrainVoigt.hpp"

#include <sstream>

namespace calango::core {

namespace {

std::string num(double v)
{
    return localeSafeFormat(v);
}

/// One Python-literal deformation-gradient matrix, computed HERE in C++
/// (StrainVoigt.hpp) rather than re-derived in the generated script, so the
/// Voigt mapping this module is unit-tested against (StrainVoigtTest.cpp)
/// is exactly what runs.
std::string matrixLiteral(const Matrix3& f)
{
    std::ostringstream out;
    out << "[[" << num(f[0][0]) << ", " << num(f[0][1]) << ", " << num(f[0][2]) << "], "
        << "[" << num(f[1][0]) << ", " << num(f[1][1]) << ", " << num(f[1][2]) << "], "
        << "[" << num(f[2][0]) << ", " << num(f[2][1]) << ", " << num(f[2][2]) << "]]";
    return out.str();
}

/// The +-multiples of `strainMagnitude` sampled for one component, in
/// increasing order: 2 points -> {-1, +1}; 4 -> {-2, -1, +1, +2}. 0 is never
/// included here — the zero-strain point is the baseline itself, evaluated
/// once and shared by every component, not re-evaluated per component.
std::vector<int> sampleMultiples(int pointsPerComponent)
{
    int half = pointsPerComponent / 2;
    if (half < 1)
        half = 1;
    std::vector<int> out;
    for (int m = half; m >= 1; --m)
        out.push_back(-m);
    for (int m = 1; m <= half; ++m)
        out.push_back(m);
    return out;
}

} // namespace

std::string generatePiezoelectricScript(const PiezoelectricConfig& config)
{
    // The Berry phase is defined on the UNSYMMETRIZED Brillouin zone, same
    // reasoning as Born Effective Charges: point-group k-folding is not the
    // user's choice to make here.
    PiezoelectricConfig cfg = config;
    cfg.calculator.gpawSymmetryOff = true;

    std::vector<int> voigt = cfg.voigtComponents;
    if (voigt.empty())
        for (int i = 0; i < 6; ++i)
            voigt.push_back(i);

    std::ostringstream out;
    out << "# Piezoelectric tensor e_i,alpha = dP_i / d(eps_alpha) — "
           "generated by Calango\n"
           "#\n"
           "# Finite-difference strain-polarization method: apply a small\n"
           "# homogeneous strain to the relaxed reference cell, evaluate the\n"
           "# total polarization P by the modern (Berry-phase) theory at each\n"
           "# strained point, and differentiate. Reuses the same GPAW\n"
           "# Berry-phase evaluation Born Effective Charges differentiates\n"
           "# over ATOMIC DISPLACEMENTS (core/PolarizationScriptHelpers) —\n"
           "# here it is differentiated over CELL STRAIN instead.\n"
           "#\n"
        << "# Cost: " << sampleMultiples(cfg.pointsPerComponent).size()
        << " SCF run(s) per requested Voigt component ("
        << voigt.size() << " requested), plus one reuse of the baseline's\n"
           "# own converged wavefunctions for the eps = 0 reference point.\n";

    if (cfg.calculator.calculator != CalculatorKind::Gpaw) {
        // Refusing up front beats running any strained SCF and failing at
        // the polarization step — same rationale as Born Charges.
        out << "raise RuntimeError(\n"
               "    'The piezoelectric tensor needs the Berry-phase "
               "polarization\\n'\n"
               "    '(GPAW). The selected engine was \""
            << toString(cfg.calculator.calculator) << "\".\\n'\n"
               "    'Re-open the wizard and choose GPAW.')\n";
        return out.str();
    }

    out << "import json\n"
           "import os\n"
           "from pathlib import Path\n"
           "\n"
           "# GPAW's Berry-phase module lives in the new engine.\n"
           "os.environ.setdefault('GPAW_NEW', '1')\n"
           "import numpy as np\n"
           "from ase.units import _e\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();

    if (cfg.baselinePath.empty()) {
        out << "from ase.io import read\n"
               "atoms = read('structure.extxyz')\n\n";
    } else {
        out << "# --- Ground-state baseline ---------------------------------\n"
               "# A completed Single-Point Calculation supplies the RELAXED\n"
               "# REFERENCE geometry the strains are applied to, and the\n"
               "# calculator every strained run is rebuilt from (calc.new()),\n"
               "# exactly as in Born Effective Charges.\n"
               "from gpaw import GPAW\n"
               "\n"
            << "_baseline = GPAW(r\"" << cfg.baselinePath << "\", txt=None)\n"
            << "atoms = _baseline.get_atoms()\n"
               "\n";
    }

    out << "if not atoms.pbc.all():\n"
           "    raise RuntimeError(\n"
           "        'The Berry-phase polarization is defined for a periodic "
           "crystal.\\n'\n"
           "        'This structure is not periodic in all three directions — "
           "the\\n'\n"
           "        'piezoelectric tensor is only meaningful for a bulk "
           "insulator.')\n"
           "\n"
        << AseScriptGenerator::gpawImports(cfg.calculator)
        << berryPhaseImportShim();

    // --- Symmetry: point-group detection and the centrosymmetric refusal --
    if (cfg.useSymmetry) {
        out << "\n"
               "# --- Symmetry --------------------------------------------\n"
               "point_group = None\n"
               "point_group_ops_cartesian = []\n"
               "try:\n"
               "    import spglib\n"
            << "    _sym_symprec = " << num(cfg.symmetryTolerance) << "\n"
            << "    _sym_cell = (atoms.cell[:], atoms.get_scaled_positions(),\n"
               "                 atoms.numbers)\n"
               "    _sym_data = spglib.get_symmetry_dataset(\n"
               "        _sym_cell, symprec=_sym_symprec)\n"
               "    _sym_ops = spglib.get_symmetry(_sym_cell, symprec=_sym_symprec)\n"
               "    if _sym_data is not None and _sym_ops is not None:\n"
               "        point_group = (_sym_data['pointgroup']\n"
               "                       if isinstance(_sym_data, dict)\n"
               "                       else getattr(_sym_data, 'pointgroup', None))\n"
               "        # Cartesian rotation from spglib's FRACTIONAL one.\n"
               "        # r_cart = cell^T . f_frac (cell rows are lattice\n"
               "        # vectors), and spglib's R acts as f' = R . f, so the\n"
               "        # matching Cartesian map is\n"
               "        #     R_cart = cell^T . R . (cell^T)^-1.\n"
               "        _cellT = np.array(atoms.cell[:]).T\n"
               "        _cellT_inv = np.linalg.inv(_cellT)\n"
               "        for _r_frac in _sym_ops['rotations']:\n"
               "            _r_cart = _cellT @ np.asarray(_r_frac, dtype=float) "
               "@ _cellT_inv\n"
               "            point_group_ops_cartesian.append(_r_cart)\n"
               "        print(f'CALANGO_INFO point group: {point_group}, '\n"
               "              f'{len(point_group_ops_cartesian)} operation(s)',\n"
               "              flush=True)\n"
               "except ImportError:\n"
               "    print('CALANGO_WARN spglib not installed: the "
               "centrosymmetric\\n'\n"
               "          '             refusal and the tensor "
               "symmetrization are both\\n'\n"
               "          '             skipped.', flush=True)\n"
               "\n"
               "\n"
               "def _is_inversion(r, tol=1e-6):\n"
               "    return np.allclose(r, -np.eye(3), atol=tol)\n"
               "\n"
               "\n"
               "if any(_is_inversion(r) for r in point_group_ops_cartesian):\n"
               "    raise RuntimeError(\n"
               "        f'The reference structure is CENTROSYMMETRIC (point "
               "group '\n"
               "        f'{point_group}). Every component of the piezoelectric "
               "tensor\\n'\n"
               "        'is forced to zero by symmetry for a centrosymmetric "
               "point\\n'\n"
               "        'group — this is exact, not an approximation, so no "
               "strained\\n'\n"
               "        'calculation would change the answer. Refusing before "
               "spending\\n'\n"
               "        'any compute.')\n";
    } else {
        out << "point_group = None\n"
               "point_group_ops_cartesian = []\n";
    }

    // --- Strain points, precomputed in C++ (StrainVoigt.hpp) --------------
    out << "\n"
           "# --- Strain points (Calango-precomputed deformation gradients) --\n"
           "STRAIN_POINTS = [\n";
    for (int v : voigt) {
        for (int mult : sampleMultiples(cfg.pointsPerComponent)) {
            const double eps = cfg.strainMagnitude * static_cast<double>(mult);
            const Matrix3 f = deformationGradient(unitVoigtStrain(v, eps));
            out << "    {\"voigt\": " << v << ", \"eps\": " << num(eps)
                << ", \"F\": " << matrixLiteral(f) << "},\n";
        }
    }
    out << "]\n"
           "\n"
           "def apply_strain(reference, f_matrix):\n"
           "    new_cell = np.array(reference.get_cell()[:]) @ np.array(f_matrix).T\n"
           "    strained = reference.copy()\n"
           "    # scale_atoms=True keeps the FRACTIONAL coordinates fixed — the\n"
           "    # CLAMPED-ION convention this base case computes.\n"
           "    strained.set_cell(new_cell, scale_atoms=True)\n"
           "    return strained\n"
           "\n"
           "\n"
           "def strained_phase(strained, tag):\n"
           "    # calc.new() rebuilds the baseline's calculator verbatim, and\n"
           "    # symmetry='off' is forced on top for the same reason as Born\n"
           "    # Charges: the Berry phase integrates the FULL Brillouin zone.\n"
           "    calc = _baseline.new(symmetry='off', txt=f'gpaw_{tag}.txt')\n"
           "    strained.calc = calc\n";
    if (cfg.relaxIons) {
        out << "    # RELAXED-ION: minimize the internal coordinates at this\n"
               "    # fixed (strained) cell before reading off the "
               "polarization —\n"
               "    # the physical, zero-stress response, at the cost of one\n"
               "    # geometry optimization per strain point on top of the "
               "SCF.\n"
               "    from ase.optimize import LBFGS\n"
               "    LBFGS(strained, logfile=f'relax_{tag}.log').run(\n"
            << "        fmax=" << num(cfg.relaxFmaxEvPerA) << ", steps="
            << cfg.relaxMaxSteps << ")\n";
    } else {
        out << "    # CLAMPED-ION: internal coordinates stay at their "
               "strain-scaled\n"
               "    # positions from apply_strain(); only the SCF is "
               "re-converged.\n"
               "    strained.get_potential_energy()\n";
    }
    out << "    return polarization_phase_c(strained.calc, tag)\n"
           "\n"
           "\n"
        << polarizationPhaseCFunction();

    out << "def phase_to_polarization(phase_c, cell, volume):\n"
           "    # (phase / 2*pi) . cell projects the 3 crystal-axis phases "
           "onto a\n"
           "    # Cartesian dipole moment (e.A per cell); dividing by the "
           "cell\n"
           "    # volume gives the polarization in e/A^2, and _e * 1e20 "
           "converts\n"
           "    # e/A^2 -> C/m^2 (1 A^2 = 1e-20 m^2).\n"
           "    dipole_eA = (np.asarray(phase_c) / (2.0 * np.pi)) @ np.array(cell)\n"
           "    return dipole_eA / volume * _e * 1e20\n"
           "\n"
           "\n"
           "cell0 = atoms.get_cell()[:]\n"
           "volume0 = atoms.get_volume()\n"
           "total_steps = len(STRAIN_POINTS)\n"
           "_calango_event('start', f'{total_steps} strained SCF run(s)')\n"
           "\n"
           "reference_phase = polarization_phase_c(_baseline, 'ref')\n"
           "P0 = phase_to_polarization(reference_phase, cell0, volume0)\n"
           "print(f'CALANGO_INFO reference polarization P0 = {list(P0)} "
           "C/m^2', flush=True)\n"
           "\n"
           "by_component = {}\n"
           "step = 0\n"
           "for point in STRAIN_POINTS:\n"
           "    strained = apply_strain(atoms, point['F'])\n"
           "    tag = (f'{point[\"voigt\"]}_'\n"
           "           f'{\"p\" if point[\"eps\"] > 0 else \"m\"}'\n"
           "           f'{abs(point[\"eps\"]):.6f}')\n"
           "    phase = strained_phase(strained, tag)\n"
           "    by_component.setdefault(point['voigt'], []).append(\n"
           "        (point['eps'], phase))\n"
           "    step += 1\n"
           "    _calango_progress(step, total_steps)\n"
           "\n"
           "VOIGT_PAIRS = [(0, 0), (1, 1), (2, 2), (1, 2), (0, 2), (0, 1)]\n"
           "raw_tensor = np.zeros((3, 6))\n"
           "per_component = {}\n"
           "for voigt_index, points in by_component.items():\n"
           "    # The eps = 0 reference anchors the branch fix (it removes any\n"
           "    # ambiguity about which side of zero the series starts "
           "continuous\n"
           "    # from) and, because the fit below has a FREE intercept, its "
           "own\n"
           "    # small offset from the strained points' SCF lands entirely in\n"
           "    # that intercept rather than biasing the fitted slope.\n"
           "    series = [(0.0, reference_phase)] + sorted(points, key=lambda "
           "p: p[0])\n"
           "    eps_values = np.array([p[0] for p in series])\n"
           "    phases = np.array([p[1] for p in series])\n"
           "    # Branch fix: choose, at each strain point, the representative\n"
           "    # of the multivalued Berry phase (defined only modulo 2*pi —\n"
           "    # the polarization quantum) that keeps the series continuous —\n"
           "    # the classic pitfall of this method. Per crystal-axis\n"
           "    # component, since each is independently defined mod 2*pi.\n"
           "    unwrapped = np.unwrap(phases, axis=0)\n"
           "    P_series = np.array([\n"
           "        phase_to_polarization(row, cell0, volume0) for row in "
           "unwrapped])\n"
           "    per_component[voigt_index] = {\n"
           "        'eps': eps_values.tolist(),\n"
           "        'P_Cm2': P_series.tolist(),\n"
           "    }\n"
           "    for i in range(3):\n"
           "        slope, _intercept = np.polyfit(eps_values, P_series[:, i], "
           "1)\n"
           "        raw_tensor[i, voigt_index] = slope\n"
           "\n"
           "# --- Proper vs. improper piezoelectric response -----------------\n"
           "# The above is the IMPROPER (clamped-cell-shape) tensor:\n"
           "# differencing P at FIXED REDUCED coordinates under a cell strain\n"
           "# (scale_atoms=True) picks up a pure volume-definition artefact the\n"
           "# physical, proper (finite-sample, fixed-shape) piezoelectric\n"
           "# response does not have. Vanderbilt, \"Berry-phase theory of\n"
           "# proper piezoelectric response\", J. Phys. Chem. Solids 61, 147\n"
           "# (2000); arXiv:cond-mat/9903137, Eq. (15), symmetrized in the\n"
           "# (necessarily symmetric) strain pair — see\n"
           "# core::properPiezoelectricCorrection for the derivation:\n"
           "#     e_proper[i,(jk)] = e_improper[i,(jk)] + delta_jk * P0[i]\n"
           "#         - 0.5 * (delta_ij * P0[k] + delta_ik * P0[j])\n"
           "correction = np.zeros((3, 6))\n"
           "for alpha, (j, k) in enumerate(VOIGT_PAIRS):\n"
           "    for i in range(3):\n"
           "        d_jk = 1.0 if j == k else 0.0\n"
           "        d_ij = 1.0 if i == j else 0.0\n"
           "        d_ik = 1.0 if i == k else 0.0\n"
           "        correction[i, alpha] = (d_jk * P0[i]\n"
           "            - 0.5 * (d_ij * P0[k] + d_ik * P0[j]))\n"
           "proper_tensor = raw_tensor + correction\n"
           "\n"
           "# --- Point-group symmetrization ----------------------------------\n"
           "# General tensor transform e'_ijk = R_ii' R_jj' R_kk' e_i'j'k',\n"
           "# averaged over the group: this simultaneously zeroes whatever\n"
           "# Voigt component symmetry forbids and cleans up the numerical\n"
           "# noise in the components it allows. See\n"
           "# core::symmetrizePiezoelectricTensor for the same routine in C++,\n"
           "# unit-tested against synthetic point groups.\n"
           "def _expand_voigt(v):\n"
           "    t = np.zeros((3, 3, 3))\n"
           "    for alpha, (j, k) in enumerate(VOIGT_PAIRS):\n"
           "        t[:, j, k] = v[:, alpha]\n"
           "        t[:, k, j] = v[:, alpha]\n"
           "    return t\n"
           "\n"
           "\n"
           "def _contract_voigt(t):\n"
           "    v = np.zeros((3, 6))\n"
           "    for alpha, (j, k) in enumerate(VOIGT_PAIRS):\n"
           "        v[:, alpha] = t[:, j, k]\n"
           "    return v\n"
           "\n"
           "\n"
           "def _symmetrize(v, ops):\n"
           "    if not ops:\n"
           "        return v\n"
           "    cart = _expand_voigt(v)\n"
           "    total = np.zeros_like(cart)\n"
           "    for r in ops:\n"
           "        total += np.einsum('ip,jq,kr,pqr->ijk', r, r, r, cart)\n"
           "    return _contract_voigt(total / len(ops))\n"
           "\n"
           "\n"
           "improper_symmetrized = _symmetrize(raw_tensor, "
           "point_group_ops_cartesian)\n"
           "proper_symmetrized = _symmetrize(proper_tensor, "
           "point_group_ops_cartesian)\n";

    if (cfg.elasticStiffnessGpa) {
        out << "\n"
               "# --- e -> d conversion (elastic stiffness supplied) -------------\n"
               "# d = e . S, S = C^-1 (compliance). C is supplied in GPa; d\n"
               "# is reported in the conventional pm/V: S[1/GPa] = "
               "S_SI[1/Pa]*1e9,\n"
               "# and d[m/V] = d[C/N] = e[C/m^2] . S_SI[1/Pa], so\n"
               "#     d[pm/V] = (e . S_GPa) * 1e-9 * 1e12 = (e . S_GPa) * 1e3.\n"
            << "C_stiffness_GPa = np.array(" << [&] {
            std::ostringstream m;
            m << "[";
            const auto& c = *cfg.elasticStiffnessGpa;
            for (int i = 0; i < 6; ++i) {
                m << "[";
                for (int j = 0; j < 6; ++j)
                    m << num(c[static_cast<std::size_t>(i)][static_cast<std::size_t>(j)])
                      << (j < 5 ? ", " : "");
                m << "]" << (i < 5 ? ", " : "");
            }
            m << "]";
            return m.str();
        }() << ")\n"
               "S_compliance_per_GPa = np.linalg.inv(C_stiffness_GPa)\n"
               "d_tensor_pmV = (proper_symmetrized @ S_compliance_per_GPa) * 1e3\n";
    } else {
        out << "\n"
               "C_stiffness_GPa = None\n"
               "d_tensor_pmV = None\n";
    }

    out << "\n"
           "summary = {\n"
        << "    'strain_magnitude': " << num(cfg.strainMagnitude) << ",\n"
        << "    'points_per_component': " << cfg.pointsPerComponent << ",\n"
        << "    'relax_ions': " << (cfg.relaxIons ? "True" : "False") << ",\n"
           "    'voigt_components': sorted(by_component.keys()),\n"
           "    'point_group': point_group,\n"
           "    'reference_polarization_Cm2': P0.tolist(),\n"
           "    'improper_tensor_Cm2': raw_tensor.tolist(),\n"
           "    'improper_tensor_symmetrized_Cm2': improper_symmetrized.tolist(),\n"
           "    'proper_tensor_Cm2': proper_tensor.tolist(),\n"
           "    'proper_tensor_symmetrized_Cm2': proper_symmetrized.tolist(),\n"
           "    'per_component_P_of_eps': {str(k): v for k, v in "
           "per_component.items()},\n"
           "    'elastic_stiffness_input_GPa': (\n"
           "        C_stiffness_GPa.tolist() if C_stiffness_GPa is not None "
           "else None),\n"
           "    'd_tensor_pmV': (\n"
           "        d_tensor_pmV.tolist() if d_tensor_pmV is not None else "
           "None),\n"
           "}\n"
           "with open('piezoelectric.json', 'w') as handle:\n"
           "    json.dump(summary, handle, indent=2)\n"
           "\n"
           "print(f'CALANGO_RESULT piezoelectric=piezoelectric.json '\n"
           "      f'components={len(by_component)} point_group={point_group}',\n"
           "      flush=True)\n";

    return out.str();
}

} // namespace calango::core
