#include "core/PiezoelectricScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"
#include "core/LocaleSafeNumber.hpp"
#include "core/PolarizationScriptHelpers.hpp"
#include "core/StrainScriptHelpers.hpp"
#include "core/StrainVoigt.hpp"

#include <sstream>

namespace calango::core {

namespace {

std::string num(double v)
{
    return localeSafeFormat(v);
}

} // namespace

std::string generatePiezoelectricScript(const PiezoelectricConfig& config)
{
    // The Berry phase is defined on the UNSYMMETRIZED Brillouin zone, same
    // reasoning as Born Effective Charges: point-group k-folding is not the
    // user's choice to make here.
    PiezoelectricConfig cfg = config;
    cfg.calculator.gpawSymmetryOff = true;

    const bool is2D = cfg.vacuumAxis >= 0 && cfg.vacuumAxis <= 2;

    std::vector<int> voigt = cfg.voigtComponents;
    if (voigt.empty()) {
        // Default set: all six for bulk, in-plane only for a 2D structure —
        // straining the vacuum axis (not a real lattice parameter) is not a
        // physical deformation, so it is never a sensible default.
        if (is2D) {
            voigt = inPlaneVoigtComponents(cfg.vacuumAxis);
        } else {
            for (int i = 0; i < 6; ++i)
                voigt.push_back(i);
        }
    } else if (is2D) {
        // Defense in depth: even an EXPLICIT selection must not strain the
        // vacuum axis of a 2D structure. The wizard already disables those
        // checkboxes once it detects one, but this generator is what a
        // saved or hand-edited config ultimately runs, and it has to be
        // correct on its own rather than trust the caller.
        std::vector<int> filtered;
        for (int v : voigt)
            if (!voigtInvolvesAxis(v, cfg.vacuumAxis))
                filtered.push_back(v);
        voigt = filtered;
    }

    std::ostringstream out;
    out << "# Piezoelectric tensor e_i,alpha = dP_i / d(eps_alpha) — "
           "generated by Calango\n"
           "#\n"
           "# Finite-difference strain-polarization method: apply a small\n"
           "# homogeneous strain to the relaxed reference cell, evaluate the\n"
           "# total polarization P by the modern (Berry-phase) theory at each\n"
           "# strained point, and differentiate. Reuses the same GPAW\n"
           "# Berry-phase evaluation Born Effective Charges differentiates\n"
           "# over ATOMIC DISPLACEMENTS (core/PolarizationScriptHelpers) —\n"
           "# here it is differentiated over CELL STRAIN instead.\n"
           "#\n"
        << "# Cost: " << strainSampleMultiples(cfg.pointsPerComponent).size()
        << " SCF run(s) per requested Voigt component ("
        << voigt.size() << " requested), plus one more (symmetry off) for the\n"
           "# eps = 0 reference point — it is re-converged rather than reused\n"
           "# from the baseline: the Berry phase needs symmetry off, and the\n"
           "# baseline's own density was converged with it on.\n";
    if (is2D)
        out << "# 2D structure: vacuum axis " << cfg.vacuumAxis
            << "; strain restricted to the in-plane component(s) "
            << [&] {
                   std::ostringstream v;
                   v << "[";
                   for (std::size_t i = 0; i < voigt.size(); ++i)
                       v << voigt[i] << (i + 1 < voigt.size() ? ", " : "");
                   v << "]";
                   return v.str();
               }()
            << ".\n";

    if (cfg.calculator.calculator != CalculatorKind::Gpaw) {
        // Refusing up front beats running any strained SCF and failing at
        // the polarization step — same rationale as Born Charges.
        out << "raise RuntimeError(\n"
               "    'The piezoelectric tensor needs the Berry-phase "
               "polarization\\n'\n"
               "    '(GPAW). The selected engine was \""
            << toString(cfg.calculator.calculator) << "\".\\n'\n"
               "    'Re-open the wizard and choose GPAW.')\n";
        return out.str();
    }

    if (is2D && voigt.empty()) {
        // Every requested component touched the vacuum axis and was
        // stripped above — refuse cleanly rather than run a strain loop
        // over zero points and silently write an empty tensor.
        out << "raise RuntimeError(\n"
               "    'Every requested Voigt strain component touches the "
               "vacuum axis\\n'\n"
            << "    '(axis " << cfg.vacuumAxis
            << ") of this 2D structure; none of them is a physically\\n'\n"
               "    'meaningful in-plane strain. Choose from the in-plane "
               "components\\n'\n"
               "    'instead (xx, yy and/or xy for a vacuum along z).')\n";
        return out.str();
    }

    out << "import json\n"
           "import os\n"
           "from pathlib import Path\n"
           "\n"
           "# GPAW's Berry-phase module lives in the new engine.\n"
           "os.environ.setdefault('GPAW_NEW', '1')\n"
           "import numpy as np\n"
           "from ase.units import _e\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();

    if (cfg.baselinePath.empty()) {
        out << "from ase.io import read\n"
               "atoms = read('structure.extxyz')\n\n";
    } else {
        out << "# --- Ground-state baseline ---------------------------------\n"
               "# A completed Single-Point Calculation supplies the RELAXED\n"
               "# REFERENCE geometry the strains are applied to, and the\n"
               "# calculator every strained run is rebuilt from (calc.new()),\n"
               "# exactly as in Born Effective Charges.\n"
               "from gpaw import GPAW\n"
               "\n"
            << "_baseline = GPAW(r\"" << cfg.baselinePath << "\", txt=None)\n"
            << "atoms = _baseline.get_atoms()\n"
               "\n";
    }

    // Periodicity: at least the two in-plane directions, three for bulk. A
    // monolayer legitimately declares pbc=[True, True, False] OR
    // pbc=[True, True, True] with a vacuum gap (the ordinary ASE slab
    // convention, and what a structure imported from most builders/DFT
    // codes carries) — neither is refused here; IS_2D below is what tells
    // the two apart, from the wizard's own detection, not from this check.
    out << strainPeriodicityGuardPython("The Berry-phase polarization")
        << strainVacuumAxisBlockPython(is2D ? cfg.vacuumAxis : -1)
        << AseScriptGenerator::gpawImports(cfg.calculator)
        << berryPhaseImportShim();

    // --- Symmetry: point-group detection and the centrosymmetric refusal --
    if (cfg.useSymmetry) {
        out << strainPointGroupDetectionPython(cfg.symmetryTolerance,
                   "the centrosymmetric refusal and the tensor symmetrization "
                   "are both skipped.")
            << "\n"
               "def _is_inversion(r, tol=1e-6):\n"
               "    return np.allclose(r, -np.eye(3), atol=tol)\n"
               "\n"
               "\n"
               "if any(_is_inversion(r) for r in point_group_ops_cartesian):\n"
               "    raise RuntimeError(\n"
               "        f'The reference structure is CENTROSYMMETRIC (point "
               "group '\n"
               "        f'{point_group}). Every component of the piezoelectric "
               "tensor\\n'\n"
               "        'is forced to zero by symmetry for a centrosymmetric "
               "point\\n'\n"
               "        'group — this is exact, not an approximation, so no "
               "strained\\n'\n"
               "        'calculation would change the answer. Refusing before "
               "spending\\n'\n"
               "        'any compute.')\n";
    } else {
        out << "point_group = None\n"
               "point_group_ops_cartesian = []\n";
    }

    // --- Strain points, precomputed in C++ (StrainVoigt.hpp) --------------
    out << "\n"
           "# --- Strain points (Calango-precomputed deformation gradients) --\n"
           "STRAIN_POINTS = [\n";
    for (int v : voigt) {
        for (int mult : strainSampleMultiples(cfg.pointsPerComponent)) {
            const double eps = cfg.strainMagnitude * static_cast<double>(mult);
            const Matrix3 f = deformationGradient(unitVoigtStrain(v, eps));
            out << "    {\"voigt\": " << v << ", \"eps\": " << num(eps)
                << ", \"F\": " << strainMatrixLiteral(f) << "},\n";
        }
    }
    out << "]\n"
           "\n"
        << applyStrainFunctionPython()
        << "def strained_phase(strained, tag):\n"
           "    # calc.new() rebuilds the baseline's calculator verbatim, and\n"
           "    # symmetry='off' is forced on top for the same reason as Born\n"
           "    # Charges: the Berry phase integrates the FULL Brillouin zone.\n"
           "    calc = _baseline.new(symmetry='off', txt=f'gpaw_{tag}.txt')\n"
           "    strained.calc = calc\n";
    if (cfg.relaxIons) {
        out << "    # RELAXED-ION: minimize the internal coordinates at this\n"
               "    # fixed (strained) cell before reading off the "
               "polarization —\n"
               "    # the physical, zero-stress response, at the cost of one\n"
               "    # geometry optimization per strain point on top of the "
               "SCF.\n"
               "    from ase.optimize import LBFGS\n"
               "    LBFGS(strained, logfile=f'relax_{tag}.log').run(\n"
            << "        fmax=" << num(cfg.relaxFmaxEvPerA) << ", steps="
            << cfg.relaxMaxSteps << ")\n";
    } else {
        out << "    # CLAMPED-ION: internal coordinates stay at their "
               "strain-scaled\n"
               "    # positions from apply_strain(); only the SCF is "
               "re-converged.\n"
               "    strained.get_potential_energy()\n";
    }
    out << "    return polarization_phase_c(strained.calc, tag)\n"
           "\n"
           "\n"
        << polarizationPhaseCFunction();

    out << "def phase_to_polarization(phase_c, cell, volume):\n"
           "    # (phase / 2*pi) . cell projects the 3 crystal-axis phases "
           "onto a\n"
           "    # Cartesian dipole moment (e.A per cell); dividing by the "
           "cell\n"
           "    # volume gives the polarization in e/A^2, and _e * 1e20 "
           "converts\n"
           "    # e/A^2 -> C/m^2 (1 A^2 = 1e-20 m^2).\n"
           "    dipole_eA = (np.asarray(phase_c) / (2.0 * np.pi)) @ np.array(cell)\n"
           "    return dipole_eA / volume * _e * 1e20\n"
           "\n"
           "\n"
           "cell0 = atoms.get_cell()[:]\n"
           "volume0 = atoms.get_volume()\n"
           "total_steps = len(STRAIN_POINTS)\n"
           "_calango_event('start', f'{total_steps} strained SCF run(s)')\n"
           "\n"
           "# The reference (eps = 0) point goes through strained_phase() "
           "too, on\n"
           "# an unmodified copy of the reference geometry (F = identity) — "
           "NOT\n"
           "# a direct call on _baseline. _baseline's own density was "
           "converged\n"
           "# WITH symmetry reduction (whatever the baseline run used); "
           "GPAW's\n"
           "# Berry-phase code unconditionally refuses to run under "
           "symmetry\n"
           "# ('Does not work with Symmetry'), so evaluating it straight on\n"
           "# _baseline crashes on the very first call, before a single "
           "strained\n"
           "# point ever runs. Routing the reference through the SAME "
           "function\n"
           "# every strained point uses — symmetry off, re-converged from "
           "scratch\n"
           "# — is not a special case for the reference; it is removing "
           "the one\n"
           "# that caused this bug.\n"
           "reference_phase = strained_phase(atoms.copy(), 'ref')\n"
           "P0 = phase_to_polarization(reference_phase, cell0, volume0)\n"
           "print(f'CALANGO_INFO reference polarization P0 = {list(P0)} "
           "C/m^2', flush=True)\n"
           "\n"
           "by_component = {}\n"
           "by_component_failures = {}\n"
           "step = 0\n"
           "for point in STRAIN_POINTS:\n"
           "    strained = apply_strain(atoms, point['F'])\n"
           "    tag = (f'{point[\"voigt\"]}_'\n"
           "           f'{\"p\" if point[\"eps\"] > 0 else \"m\"}'\n"
           "           f'{abs(point[\"eps\"]):.6f}')\n"
           "    # A single strain point's SCF failing to converge, or its "
           "Berry-\n"
           "    # phase evaluation raising, must not discard every other "
           "point's\n"
           "    # already-completed work — the failure is recorded, "
           "surfaced with\n"
           "    # a CALANGO event so the caller sees exactly which point "
           "and why,\n"
           "    # and the loop moves on to the rest of the stencil.\n"
           "    try:\n"
           "        phase = strained_phase(strained, tag)\n"
           "    except Exception as exc:\n"
           "        by_component_failures.setdefault(\n"
           "            point['voigt'], []).append(\n"
           "                {'eps': point['eps'], 'error': str(exc)})\n"
           "        _calango_event(\n"
           "            'warning',\n"
           "            f'strain point voigt={point[\"voigt\"]} '\n"
           "            f'eps={point[\"eps\"]:+.4f} FAILED: {exc}')\n"
           "        step += 1\n"
           "        _calango_progress(step, total_steps)\n"
           "        continue\n"
           "    by_component.setdefault(point['voigt'], []).append(\n"
           "        (point['eps'], phase))\n"
           "    step += 1\n"
           "    _calango_progress(step, total_steps)\n"
           "\n"
           "VOIGT_PAIRS = [(0, 0), (1, 1), (2, 2), (1, 2), (0, 2), (0, 1)]\n"
           "raw_tensor = np.zeros((3, 6))\n"
           "per_component = {}\n"
           "components_with_no_data = []\n"
           "# Every REQUESTED component, not just the ones that produced at\n"
           "# least one surviving point — a component whose every strain point\n"
           "# failed still needs to be visited, so it is reported (NaN'd and\n"
           "# named) rather than silently missing from both the tensor and the\n"
           "# summary.\n"
           "for voigt_index in sorted({p['voigt'] for p in STRAIN_POINTS}):\n"
           "    points = by_component.get(voigt_index, [])\n"
           "    if not points:\n"
           "        components_with_no_data.append(voigt_index)\n"
           "        raw_tensor[:, voigt_index] = np.nan\n"
           "        continue\n"
           "    # The eps = 0 reference anchors the branch fix (it removes any\n"
           "    # ambiguity about which side of zero the series starts "
           "continuous\n"
           "    # from) and, because the fit below has a FREE intercept, its "
           "own\n"
           "    # small offset from the strained points' SCF lands entirely in\n"
           "    # that intercept rather than biasing the fitted slope.\n"
           "    series = [(0.0, reference_phase)] + sorted(points, key=lambda "
           "p: p[0])\n"
           "    eps_values = np.array([p[0] for p in series])\n"
           "    phases = np.array([p[1] for p in series])\n"
           "    # Branch fix: choose, at each strain point, the representative\n"
           "    # of the multivalued Berry phase (defined only modulo 2*pi —\n"
           "    # the polarization quantum) that keeps the series continuous —\n"
           "    # the classic pitfall of this method. Per crystal-axis\n"
           "    # component, since each is independently defined mod 2*pi.\n"
           "    unwrapped = np.unwrap(phases, axis=0)\n"
           "    P_series = np.array([\n"
           "        phase_to_polarization(row, cell0, volume0) for row in "
           "unwrapped])\n"
           "    per_component[voigt_index] = {\n"
           "        'eps': eps_values.tolist(),\n"
           "        'P_Cm2': P_series.tolist(),\n"
           "    }\n"
           "    for i in range(3):\n"
           "        if IS_2D and i == VACUUM_AXIS:\n"
           "            # The out-of-plane polarization is not meaningful for\n"
           "            # a slab (the periodic Berry phase along a vacuum\n"
           "            # direction integrates almost entirely empty space) —\n"
           "            # left NaN below, never fit.\n"
           "            continue\n"
           "        slope, _intercept = np.polyfit(eps_values, P_series[:, i], "
           "1)\n"
           "        raw_tensor[i, voigt_index] = slope\n"
           "# NOT NaN'd here yet — see the note beside the four np.nan\n"
           "# assignments after symmetrization below for why.\n"
           "if components_with_no_data:\n"
           "    print(f'CALANGO_WARN {len(components_with_no_data)} Voigt '\n"
           "          f'component(s) have NO surviving strain point and are '\n"
           "          f'reported as NaN: {components_with_no_data}',\n"
           "          flush=True)\n"
           "\n"
           "# --- Proper vs. improper piezoelectric response -----------------\n"
           "# The above is the IMPROPER (clamped-cell-shape) tensor:\n"
           "# differencing P at FIXED REDUCED coordinates under a cell strain\n"
           "# (scale_atoms=True) picks up a pure volume-definition artefact the\n"
           "# physical, proper (finite-sample, fixed-shape) piezoelectric\n"
           "# response does not have. Vanderbilt, \"Berry-phase theory of\n"
           "# proper piezoelectric response\", J. Phys. Chem. Solids 61, 147\n"
           "# (2000); arXiv:cond-mat/9903137, Eq. (15), symmetrized in the\n"
           "# (necessarily symmetric) strain pair — see\n"
           "# core::properPiezoelectricCorrection for the derivation:\n"
           "#     e_proper[i,(jk)] = e_improper[i,(jk)] + delta_jk * P0[i]\n"
           "#         - 0.5 * (delta_ij * P0[k] + delta_ik * P0[j])\n"
           "correction = np.zeros((3, 6))\n"
           "for alpha, (j, k) in enumerate(VOIGT_PAIRS):\n"
           "    for i in range(3):\n"
           "        d_jk = 1.0 if j == k else 0.0\n"
           "        d_ij = 1.0 if i == j else 0.0\n"
           "        d_ik = 1.0 if i == k else 0.0\n"
           "        correction[i, alpha] = (d_jk * P0[i]\n"
           "            - 0.5 * (d_ij * P0[k] + d_ik * P0[j]))\n"
           "proper_tensor = raw_tensor + correction\n"
           "\n"
           "# --- Point-group symmetrization ----------------------------------\n"
           "# General tensor transform e'_ijk = R_ii' R_jj' R_kk' e_i'j'k',\n"
           "# averaged over the group: this simultaneously zeroes whatever\n"
           "# Voigt component symmetry forbids and cleans up the numerical\n"
           "# noise in the components it allows. See\n"
           "# core::symmetrizePiezoelectricTensor for the same routine in C++,\n"
           "# unit-tested against synthetic point groups.\n"
           "def _expand_voigt(v):\n"
           "    t = np.zeros((3, 3, 3))\n"
           "    for alpha, (j, k) in enumerate(VOIGT_PAIRS):\n"
           "        t[:, j, k] = v[:, alpha]\n"
           "        t[:, k, j] = v[:, alpha]\n"
           "    return t\n"
           "\n"
           "\n"
           "def _contract_voigt(t):\n"
           "    v = np.zeros((3, 6))\n"
           "    for alpha, (j, k) in enumerate(VOIGT_PAIRS):\n"
           "        v[:, alpha] = t[:, j, k]\n"
           "    return v\n"
           "\n"
           "\n"
           "def _symmetrize(v, ops):\n"
           "    if not ops:\n"
           "        return v\n"
           "    cart = _expand_voigt(v)\n"
           "    total = np.zeros_like(cart)\n"
           "    for r in ops:\n"
           "        total += np.einsum('ip,jq,kr,pqr->ijk', r, r, r, cart)\n"
           "    return _contract_voigt(total / len(ops))\n"
           "\n"
           "\n"
           "improper_symmetrized = _symmetrize(raw_tensor, "
           "point_group_ops_cartesian)\n"
           "proper_symmetrized = _symmetrize(proper_tensor, "
           "point_group_ops_cartesian)\n"
           "\n"
           "# The out-of-plane row is masked to NaN HERE — after correction\n"
           "# and symmetrization run, not before. Both raw_tensor and\n"
           "# proper_tensor feed _symmetrize()'s einsum contraction, and IEEE\n"
           "# 754 defines 0.0 * nan as nan, not 0.0: masking the row to NaN\n"
           "# earlier would poison every OTHER row too, the instant a group\n"
           "# operation's rotation matrix multiplies a NaN entry by its\n"
           "# (exactly zero, since z is never mixed with x/y by a genuine 2D\n"
           "# point-group operation) off-block coefficient. Left as a real\n"
           "# number through the math, that coefficient being exactly zero is\n"
           "# what correctly keeps the vacuum row's meaningless data out of\n"
           "# every in-plane row's result — only the NUMBER reported for the\n"
           "# vacuum row itself has to be hidden, once nothing downstream can\n"
           "# still contaminate anything by reading it.\n"
           "if IS_2D:\n"
           "    raw_tensor[VACUUM_AXIS, :] = np.nan\n"
           "    proper_tensor[VACUUM_AXIS, :] = np.nan\n"
           "    improper_symmetrized[VACUUM_AXIS, :] = np.nan\n"
           "    proper_symmetrized[VACUUM_AXIS, :] = np.nan\n"
           "\n"
           "# --- 2D (sheet) coefficients, in C/m -----------------------------\n"
           "# e_ij above is C/m^2: dP/deps divided by the FULL 3D cell volume,\n"
           "# which for a slab includes however much vacuum the cell happens\n"
           "# to carry — pad the cell with more empty space and the reported\n"
           "# e_ij shrinks, even though nothing physical changed. Multiplying\n"
           "# back by the vacuum axis's own cell length exactly cancels that:\n"
           "# volume = area * vacuum_length (the vacuum axis is orthogonal to\n"
           "# the periodic plane in every slab this module's strains touch,\n"
           "# since only in-plane components are ever applied to a 2D cell —\n"
           "# see apply_strain()'s assertion above), so\n"
           "#     e_2D = dP/deps / volume * vacuum_length "
           "= dP/deps / area,\n"
           "# a coefficient in C/m that no longer depends on how much vacuum\n"
           "# was chosen — the meaningful, reportable quantity for a "
           "monolayer.\n"
           "if IS_2D:\n"
           "    _vacuum_length_m = _axis_length_A * 1e-10\n"
           "\n"
           "    def _to_2d(tensor_Cm2):\n"
           "        return (np.asarray(tensor_Cm2) * "
           "_vacuum_length_m).tolist()\n"
           "\n"
           "    raw_tensor_2d_Cm = _to_2d(raw_tensor)\n"
           "    improper_symmetrized_2d_Cm = _to_2d(improper_symmetrized)\n"
           "    proper_tensor_2d_Cm = _to_2d(proper_tensor)\n"
           "    proper_symmetrized_2d_Cm = _to_2d(proper_symmetrized)\n"
           "else:\n"
           "    _vacuum_length_m = None\n"
           "    raw_tensor_2d_Cm = None\n"
           "    improper_symmetrized_2d_Cm = None\n"
           "    proper_tensor_2d_Cm = None\n"
           "    proper_symmetrized_2d_Cm = None\n";

    if (cfg.elasticStiffnessGpa) {
        out << "\n"
               "# --- e -> d conversion (elastic stiffness supplied) -------------\n"
               "# d = e . S, S = C^-1 (compliance). C is supplied in GPa; d\n"
               "# is reported in the conventional pm/V: S[1/GPa] = "
               "S_SI[1/Pa]*1e9,\n"
               "# and d[m/V] = d[C/N] = e[C/m^2] . S_SI[1/Pa], so\n"
               "#     d[pm/V] = (e . S_GPa) * 1e-9 * 1e12 = (e . S_GPa) * 1e3.\n"
            << "C_stiffness_GPa = np.array(" << [&] {
            std::ostringstream m;
            m << "[";
            const auto& c = *cfg.elasticStiffnessGpa;
            for (int i = 0; i < 6; ++i) {
                m << "[";
                for (int j = 0; j < 6; ++j)
                    m << num(c[static_cast<std::size_t>(i)][static_cast<std::size_t>(j)])
                      << (j < 5 ? ", " : "");
                m << "]" << (i < 5 ? ", " : "");
            }
            m << "]";
            return m.str();
        }() << ")\n"
               "S_compliance_per_GPa = np.linalg.inv(C_stiffness_GPa)\n"
               "d_tensor_pmV = (proper_symmetrized @ S_compliance_per_GPa) * 1e3\n";
    } else {
        out << "\n"
               "C_stiffness_GPa = None\n"
               "d_tensor_pmV = None\n";
    }

    out << "\n"
           "summary = {\n"
        << "    'strain_magnitude': " << num(cfg.strainMagnitude) << ",\n"
        << "    'points_per_component': " << cfg.pointsPerComponent << ",\n"
        << "    'relax_ions': " << (cfg.relaxIons ? "True" : "False") << ",\n"
           "    'voigt_components': sorted({p['voigt'] for p in "
           "STRAIN_POINTS}),\n"
           "    'point_group': point_group,\n"
           "    'is_2d': IS_2D,\n"
           "    'vacuum_axis': VACUUM_AXIS,\n"
           "    'vacuum_axis_length_A': (\n"
           "        _axis_length_A if IS_2D else None),\n"
           "    'components_with_no_data': components_with_no_data,\n"
           "    'strain_point_failures': {\n"
           "        str(k): v for k, v in by_component_failures.items()},\n"
           "    'reference_polarization_Cm2': P0.tolist(),\n"
           "    'improper_tensor_Cm2': raw_tensor.tolist(),\n"
           "    'improper_tensor_symmetrized_Cm2': improper_symmetrized.tolist(),\n"
           "    'proper_tensor_Cm2': proper_tensor.tolist(),\n"
           "    'proper_tensor_symmetrized_Cm2': proper_symmetrized.tolist(),\n"
           "    'improper_tensor_2d_Cm': raw_tensor_2d_Cm,\n"
           "    'improper_tensor_symmetrized_2d_Cm': "
           "improper_symmetrized_2d_Cm,\n"
           "    'proper_tensor_2d_Cm': proper_tensor_2d_Cm,\n"
           "    'proper_tensor_symmetrized_2d_Cm': "
           "proper_symmetrized_2d_Cm,\n"
           "    'per_component_P_of_eps': {str(k): v for k, v in "
           "per_component.items()},\n"
           "    'elastic_stiffness_input_GPa': (\n"
           "        C_stiffness_GPa.tolist() if C_stiffness_GPa is not None "
           "else None),\n"
           "    'd_tensor_pmV': (\n"
           "        d_tensor_pmV.tolist() if d_tensor_pmV is not None else "
           "None),\n"
           "}\n"
           "with open('piezoelectric.json', 'w') as handle:\n"
           "    json.dump(summary, handle, indent=2)\n"
           "\n"
           "print(f'CALANGO_RESULT piezoelectric=piezoelectric.json '\n"
           "      f'components={len(by_component)}/"
           "{len(set(p[\"voigt\"] for p in STRAIN_POINTS))} '\n"
           "      f'point_group={point_group}',\n"
           "      flush=True)\n";

    return out.str();
}

} // namespace calango::core
