#include "core/RamanIrScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>
#include <string>

namespace calango::core {

namespace {

/// Python literal for an optional path: a raw string, or None when unset.
std::string pathLiteral(const std::string& path)
{
    if (path.empty())
        return "None";
    return "r\"" + path + "\"";
}

} // namespace

std::string generateRamanIrScript(const RamanIrConfig& config)
{
    RamanIrConfig cfg = config;
    // The response evaluation integrates over the FULL Brillouin zone, and a
    // displaced geometry has lower symmetry than the equilibrium one anyway —
    // so a symmetry-reduced k-set built for the undisplaced cell would be wrong
    // for every displacement. Same reasoning as the Born-charges generator.
    cfg.calculator.gpawSymmetryOff = true;

    const bool gpaw = cfg.calculator.calculator == CalculatorKind::Gpaw;

    std::ostringstream out;
    out << "# Raman and infrared spectra — generated by Calango\n"
           "#\n"
           "# Both spectra describe the SAME Gamma-point phonons and differ\n"
           "# only in which electronic response couples to them:\n"
           "#\n"
           "#   IR    I(nu) ~ sum_a |sum_{k,b} Z*_{k,ab} e_{k,b}(nu)/sqrt(M_k)|^2\n"
           "#         the change in macroscopic POLARIZATION. Z* comes from a\n"
           "#         completed Born Effective Charges run — in a periodic\n"
           "#         crystal there is no molecular dipole to differentiate,\n"
           "#         so that run is the only route to an IR intensity.\n"
           "#\n"
           "#   Raman S(nu) = 45 a'^2 + 7 g'^2 built from dchi/dQ, the change in\n"
           "#         POLARIZABILITY. That is the electronic response the\n"
           "#         Optics process evaluates, taken at omega -> 0 and\n"
           "#         differentiated by finite displacement — which costs one\n"
           "#         dielectric-tensor evaluation per displaced geometry.\n"
           "#\n"
           "# The force constants come from finite differences of the forces\n"
           "# (ase.vibrations), so the run costs 6N force evaluations even\n"
           "# before the response work.\n"
           "import json\n"
           "import os\n"
           "\n"
           "os.environ.setdefault('GPAW_NEW', '1')\n"
           "import numpy as np\n"
           "from ase import units\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();

    if (!gpaw) {
        // Refusing up front beats running the whole vibrational job and then
        // failing at the response step.
        out << "raise RuntimeError(\n"
               "    'Raman and IR spectra need the Berry-phase Born charges "
               "and the\\n'\n"
               "    'dielectric response, which only the GPAW backend provides "
               "here.\\n'\n"
               "    'The selected engine was \""
            << toString(cfg.calculator.calculator)
            << "\". Re-open the wizard and\\n'\n"
               "    'choose GPAW.')\n";
        return out.str();
    }

    out << "# --- Inherited inputs ------------------------------------------\n"
           "BASELINE = "
        << pathLiteral(cfg.baselinePath) << "\n"
        << "BORN_CHARGES = " << pathLiteral(cfg.bornChargesPath) << "\n"
        << "OPTICS_REFERENCE = " << pathLiteral(cfg.opticsPath) << "\n"
        << "DELTA = " << cfg.displacement << "          # Angstrom\n"
        << "COMPUTE_RAMAN = " << (cfg.computeRaman ? "True" : "False") << "\n"
        << "LASER_NM = " << cfg.laserWavelengthNm << "\n"
        << "TEMPERATURE_K = " << cfg.temperatureK << "\n"
        << "BROADENING_CM = " << cfg.broadeningCm << "\n"
        << "FREQ_MIN_CM = " << cfg.frequencyMinCm << "\n"
        << "FREQ_MAX_CM = " << cfg.frequencyMaxCm << "\n"
        << "NPOINTS = " << cfg.npoints << "\n"
           "\n";

    out << R"PY(
from gpaw import GPAW

if BASELINE is None:
    raise RuntimeError(
        'CALANGO_ERROR this workflow restarts from a converged ground state; '
        'no baseline .gpw was configured.')

_baseline = GPAW(BASELINE, txt=None)
atoms = _baseline.get_atoms()
masses = atoms.get_masses()
symbols = atoms.get_chemical_symbols()
natoms = len(atoms)
volume = float(atoms.get_volume()) if atoms.pbc.any() else 0.0

_calango_log.event('start', f'{natoms} atoms, {6 * natoms} displacements')

# 1 e*A expressed in debye, for the (D/A)^2/amu unit the IR literature quotes.
DEBYE_PER_EA = 4.803204
# ASE's own conversion from a mass-weighted force constant (eV/A^2/amu) to an
# energy in eV.
EV_PER_SQRT_EV_A2_AMU = units._hbar * 1e10 / np.sqrt(units._e * units._amu)


# --- The physics, as pure array functions ---------------------------------
#
# Kept as named, side-effect-free functions rather than inline code so each can
# be exercised against a case with a known analytic answer (see
# tests/raman_ir_math_test.py, which extracts them from a generated script by
# AST and checks a diatomic where every number is available in closed form). A
# dropped 1/sqrt(M) or a transposed einsum produces a plausible spectrum, not an
# error, so "it ran" is no evidence at all here.

def impose_acoustic_sum_rule(hessian, natoms):
    """Force the translational sum rule Sum_j Phi_{i,a; j,b} = 0 on a Hessian.

    Translating the whole crystal rigidly costs no energy, so the three
    acoustic modes must sit at exactly zero frequency. A finite-difference
    Hessian does not know that: it is assembled from independently converged
    force calculations, and the residual error leaves the acoustic branch
    floating tens of cm^-1 above zero. Measured on MgO at a 4x4x4 grid, the
    uncorrected branch came out at 37, 43 and 51 cm^-1.

    That is not a cosmetic blemish. Everything downstream classifies a mode as
    acoustic by its frequency, and the Stokes intensity divides by omega -- so a
    spurious 51 cm^-1 "optical" mode acquires a large 1/omega weight and plants
    a peak in the Raman spectrum where the physics has none.

    The standard correction attributes the whole residual to the self-force
    term, which is the one element of each row that finite differences never
    measure directly (it is inferred from the others).
    """
    corrected = np.array(hessian, dtype=float, copy=True)
    for i in range(natoms):
        for a in range(3):
            row = 3 * i + a
            for b in range(3):
                others = sum(corrected[row, 3 * j + b]
                             for j in range(natoms) if j != i)
                corrected[row, 3 * i + b] = -others
    # The correction is applied row-wise and can break the exact symmetry the
    # eigensolver relies on; averaging restores it without undoing the rule.
    return 0.5 * (corrected + corrected.T)


def mass_weighted_modes(hessian, masses):
    """(frequencies in cm^-1, per-mode Cartesian displacements) of a Hessian.

    The eigenvectors of the MASS-WEIGHTED Hessian are what the IR and Raman
    contractions need, and the displacement per unit normal coordinate is that
    eigenvector divided by sqrt(M) again. Diagonalizing here rather than reading
    ASE's own get_mode() makes that convention explicit -- ASE has normalized it
    differently across releases, and the difference is a silent scale error in
    every intensity.
    """
    natoms = len(masses)
    inv_sqrt_m = 1.0 / np.sqrt(np.repeat(np.asarray(masses, dtype=float), 3))
    hessian = impose_acoustic_sum_rule(hessian, natoms)
    dynamical = np.asarray(hessian, dtype=float) \
        * inv_sqrt_m[:, None] * inv_sqrt_m[None, :]
    dynamical = 0.5 * (dynamical + dynamical.T)   # enforce exact symmetry
    omega2, eigenvectors = np.linalg.eigh(dynamical)

    energies_eV = EV_PER_SQRT_EV_A2_AMU * np.sqrt(omega2.astype(complex))
    # An imaginary frequency is a real physical statement (the geometry is not
    # a minimum), so it is reported as a NEGATIVE wavenumber rather than hidden.
    frequencies_cm = np.where(energies_eV.imag > 0,
                              -energies_eV.imag,
                              energies_eV.real) / units.invcm
    displacements = (eigenvectors.T.reshape(-1, natoms, 3)
                     * inv_sqrt_m.reshape(natoms, 3)[None, :, :])
    return np.asarray(frequencies_cm, dtype=float), displacements


def ir_intensities(born, displacements):
    """I_IR(nu) = sum_a |sum_{k,b} Z*_{k,ab} u_{k,b}(nu)|^2, in e^2/amu.

    A rigid translation of the crystal must come out at exactly zero, because
    translating it cannot polarize it -- that is the acoustic sum rule on Z*,
    and it is the sharpest available check on this contraction.
    """
    dipole_derivative = np.einsum('kab,mkb->ma', born, displacements)
    return np.sum(dipole_derivative ** 2, axis=1)


def raman_activities(dalpha, displacements):
    """Placzek activity 45 a'^2 + 7 g'^2 per mode, in A^4/amu.

    `dalpha` is d(alpha_ij)/du_{k,b}, indexed [atom, axis, i, j]; contracting it
    with the mode displacements gives each mode's Raman tensor, and the two
    rotational invariants of that tensor are what survive a powder average.
    """
    dalpha_dq = np.einsum('kbij,mkb->mij', dalpha, displacements)
    mean = np.trace(dalpha_dq, axis1=1, axis2=2) / 3.0
    anisotropy = np.zeros(len(dalpha_dq))
    for m, tensor in enumerate(dalpha_dq):
        diag = np.diag(tensor)
        anisotropy[m] = 0.5 * (
            (diag[0] - diag[1]) ** 2
            + (diag[1] - diag[2]) ** 2
            + (diag[2] - diag[0]) ** 2
        ) + 3.0 * (tensor[0, 1] ** 2 + tensor[1, 2] ** 2 + tensor[0, 2] ** 2)
    return 45.0 * mean ** 2 + 7.0 * anisotropy


def stokes_intensity(frequencies_cm, activity, laser_cm, kT_cm):
    """Measured Stokes intensity from the mode activity.

    The activity is a property of the mode; the intensity additionally carries
    the experiment -- the (omega_L - omega)^4 scattering prefactor, the
    1/omega zero-point factor and the Bose occupation at the sample
    temperature. Both are reported by this script, because comparing bare
    activities against a measured spectrum is a common way to conclude a peak
    is missing when it is only weak.
    """
    optical = frequencies_cm > 1.0     # skip acoustic / imaginary branches
    intensity = np.zeros_like(frequencies_cm)
    with np.errstate(over='ignore'):
        bose = 1.0 / (1.0 - np.exp(-frequencies_cm[optical] / max(kT_cm, 1e-9)))
    intensity[optical] = (
        (laser_cm - frequencies_cm[optical]) ** 4
        * activity[optical] * bose / (30.0 * frequencies_cm[optical])
    )
    return intensity


def lorentzian_spectrum(grid, centres, weights, width):
    """Sum of Lorentzians of half-width `width` at each mode."""
    spectrum = np.zeros_like(np.asarray(grid, dtype=float))
    for centre, weight in zip(centres, weights):
        if weight <= 0.0 or centre <= 0.0:
            continue
        spectrum += weight * width ** 2 / ((grid - centre) ** 2 + width ** 2)
    return spectrum


# --- 1. Gamma-point force constants ---------------------------------------
#
# ase.vibrations displaces every atom by +/- DELTA along each Cartesian axis
# and differences the forces. The calculator is rebuilt from the baseline with
# calc.new(), so every displaced run uses exactly the settings the ground state
# was validated with rather than a second, hand-copied set.
from ase.vibrations import Vibrations

vib_atoms = atoms.copy()
vib_atoms.calc = _baseline.new(symmetry='off', txt='gpaw_vib.txt')
vib = Vibrations(vib_atoms, delta=DELTA, name='vib')
vib.run()

# The Hessian is taken as a matrix rather than reading ASE's own frequencies,
# because the mode vectors have to be MASS-WEIGHTED and unit-normalized for the
# IR and Raman contractions below, and different ASE releases normalize
# get_mode() differently. Diagonalizing here makes the convention explicit.
try:
    hessian = np.asarray(vib.get_vibrations().get_hessian_2d(), dtype=float)
except AttributeError:
    # Pre-3.21 ASE keeps the (already mass-unweighted) matrix on the object.
    hessian = np.asarray(vib.H, dtype=float)

frequencies_cm, displacements = mass_weighted_modes(hessian, masses)
_calango_log.event('info', 'force constants done')


# --- 2. IR intensities from the Born effective charges --------------------
#
# I_IR(nu) = sum_a |sum_{k,b} Z*_{k,ab} u_{k,b}(nu)|^2 with u = e/sqrt(M) the
# Cartesian displacement per unit normal coordinate. The result is in
# e^2/amu; the (D/A)^2/amu duplicate is the unit the spectroscopy literature
# quotes, and 1 e*A = 4.803204 D gives the conversion.
# Optional. Without Z* there is no route to an IR intensity in a periodic
# crystal, but there is still a complete phonon spectrum and — with the Raman
# step below — a complete Raman spectrum, which is reason enough to run this
# module. A missing Born charges run therefore drops the IR column instead of
# failing the job: `ir.computed` records which happened, and every IR number is
# written as zero rather than as a plausible-looking wrong value.
ir_meta = {'computed': False, 'reason': 'no Born effective charges supplied'}
ir_e2_amu = np.zeros(len(frequencies_cm))
ir_debye = np.zeros(len(frequencies_cm))

if BORN_CHARGES is not None:
    with open(BORN_CHARGES) as handle:
        born_data = json.load(handle)

    born = np.zeros((natoms, 3, 3))
    seen = set()
    for entry in born_data.get('atoms', []):
        index = int(entry['index'])
        if index >= natoms:
            continue
        born[index] = np.asarray(entry['tensor'], dtype=float)
        seen.add(index)
    missing = [i for i in range(natoms) if i not in seen]
    if missing:
        # A partial Z* set silently zeroes those atoms' contribution to every
        # mode, which shows up as a plausible-looking spectrum with the wrong
        # intensities — far worse than refusing. Still fatal, because here the
        # user DID supply Z* and would otherwise get a quiet half-answer.
        raise RuntimeError(
            'CALANGO_ERROR the Born charges run covered only '
            f'{len(seen)} of {natoms} atoms (missing {missing[:8]}...). '
            'Re-run Born Effective Charges over ALL atoms: every atom '
            'contributes to every IR intensity.')

    ir_e2_amu = ir_intensities(born, displacements)
    ir_debye = ir_e2_amu * DEBYE_PER_EA ** 2
    ir_meta = {'computed': True, 'reason': ''}
else:
    print('CALANGO_WARN no Born effective charges supplied — the phonon '
          'frequencies and the Raman spectrum are computed as usual, but '
          'every IR intensity is reported as zero. Run Electronics -> "Born '
          'Effective Charges..." and re-run this to fill them in.', flush=True)


# --- 3. Raman activities from the static dielectric response --------------
raman_activity = np.zeros(len(frequencies_cm))
raman_meta = {'computed': False}

def dielectric_tensor(gpw_path, eta, tag):
    """Static (omega -> 0) dielectric tensor, all nine components.

    GPAW's DielectricFunction evaluates epsilon along ONE direction at a time,
    which gives the three diagonal components directly. The off-diagonals come
    from three more evaluations along the (i + j)/sqrt(2) bisectors, since
    n.eps.n for that n is (eps_ii + eps_jj + 2 eps_ij)/2. Six evaluations for
    the full symmetric tensor: the alternative -- keeping only the diagonal --
    drops the 3(a_xy^2 + a_yz^2 + a_xz^2) term of the depolarization invariant
    and silently understates every mode whose Raman tensor is off-diagonal,
    which in a cubic crystal is most of them.
    """
    from gpaw.response.df import DielectricFunction

    # hilbert=False is REQUIRED alongside an explicit frequency list. GPAW's
    # default response path Hilbert-transforms on its own non-linear frequency
    # grid and asserts that descriptor's type, so asking for the single point
    # omega = 0 on the default path aborts with a bare AssertionError deep in
    # chi0_base. Turning the transform off evaluates the requested frequencies
    # directly, which is what a static-limit calculation wants anyway; checked
    # against the full grid on MgO, the two agree to 0.1 %.
    df = DielectricFunction(gpw_path, frequencies=[0.0], hilbert=False, eta=eta,
                            intraband=False, txt=f'gpaw_df_{tag}.txt')
    axes = {}
    for key, direction in (('x', 'x'), ('y', 'y'), ('z', 'z')):
        _, eps_lfc = df.get_dielectric_function(direction=direction)
        axes[key] = float(np.asarray(eps_lfc)[0].real)
    tensor = np.diag([axes['x'], axes['y'], axes['z']])
    inv_sqrt2 = 1.0 / np.sqrt(2.0)
    for (a, b, ka, kb) in ((0, 1, 'x', 'y'),
                           (1, 2, 'y', 'z'),
                           (0, 2, 'x', 'z')):
        direction = [0.0, 0.0, 0.0]
        direction[a] = inv_sqrt2
        direction[b] = inv_sqrt2
        _, eps_lfc = df.get_dielectric_function(direction=direction)
        mixed = float(np.asarray(eps_lfc)[0].real)
        off = mixed - 0.5 * (axes[ka] + axes[kb])
        tensor[a, b] = off
        tensor[b, a] = off
    return tensor


if COMPUTE_RAMAN:
    # Broadening inherited from the Optics run when one was chosen, so the
    # static limit is evaluated with the same eta the user already validated
    # the spectrum with.
    eta = 0.05
    if OPTICS_REFERENCE is not None:
        try:
            with open(OPTICS_REFERENCE) as handle:
                optics_meta = json.load(handle)
            eta = float(optics_meta.get('eta_eV', eta))
        except Exception as exc:
            _calango_log.event('warning',
                               f'could not read the optics reference: {exc!r}')

    # Empty-band count for the response step. Four times the occupied count is
    # the same rule the Optics workflow uses, with a floor for very small cells
    # where 4x occupied is still only a handful of bands.
    _occupied = max(1, int(round(_baseline.get_number_of_electrons() / 2.0)))
    RESPONSE_BANDS = max(4 * _occupied, 24)
    _calango_log.event('info',
                       f'response NSCF with {RESPONSE_BANDS} bands '
                       f'({_occupied} occupied)')

    # dchi/du for every atom and axis, by central differences of the static
    # dielectric tensor. chi = (eps - 1)/(4 pi).
    depsilon = np.zeros((natoms, 3, 3, 3))   # [atom, axis, alpha, beta]
    reference = atoms.get_positions().copy()
    total = 6 * natoms
    step = 0
    for atom_index in range(natoms):
        for axis in range(3):
            tensors = []
            for sign in (+1, -1):
                positions = reference.copy()
                positions[atom_index, axis] += sign * DELTA
                moved = atoms.copy()
                moved.set_positions(positions)
                tag = f'{atom_index}_{axis}_{"p" if sign > 0 else "m"}'
                calc = _baseline.new(symmetry='off', txt=f'gpaw_{tag}.txt')
                moved.calc = calc
                moved.get_potential_energy()
                gpw = f'raman_{tag}.gpw'
                calc.write(gpw, mode='all')
                nscf_gpw = f'raman_{tag}_nscf.gpw'
                try:
                    # A fixed-density NSCF step with EXTRA EMPTY BANDS, exactly
                    # as the Optics workflow does. The dielectric function is a
                    # sum over interband transitions into unoccupied states, and
                    # an SCF run carries only the handful of empty bands it
                    # needed to converge the density: on MgO, evaluating the
                    # response straight off the SCF restart gives eps_inf = 3.04
                    # against 3.16 converged, a 4 % error. That error is in a
                    # quantity being DIFFERENCED here, so it does not cancel —
                    # it lands directly in the Raman tensor.
                    nscf = GPAW(gpw).fixed_density(
                        nbands=RESPONSE_BANDS,
                        convergence={'bands': max(RESPONSE_BANDS // 2, 8)},
                        symmetry='off', txt=f'gpaw_nscf_{tag}.txt')
                    nscf.write(nscf_gpw, mode='all')
                    tensors.append(dielectric_tensor(nscf_gpw, eta, tag))
                finally:
                    # Two .gpw per displacement fills a disk quickly.
                    for path in (gpw, nscf_gpw):
                        if os.path.exists(path):
                            os.remove(path)
                step += 1
                _calango_log.progress(step, total)
            depsilon[atom_index, axis] = (tensors[0] - tensors[1]) / (2.0 * DELTA)

    # chi = (eps - 1) / 4pi, so dchi/du = deps/du / 4pi. The conventional
    # Raman tensor is the derivative of the cell polarizability alpha = V chi.
    dalpha = depsilon * (volume if volume > 0.0 else 1.0) / (4.0 * np.pi)
    raman_activity = raman_activities(dalpha, displacements)
    raman_meta = {'computed': True, 'eta_eV': eta, 'off_diagonal': True}
else:
    _calango_log.event('info',
                       'Raman disabled: only the IR spectrum is computed')


# --- 4. Stokes intensities and the broadened spectra ----------------------
laser_cm = 1.0e7 / LASER_NM
kT_cm = units.kB * TEMPERATURE_K / units.invcm
raman_intensity = stokes_intensity(frequencies_cm, raman_activity,
                                   laser_cm, kT_cm)

grid = np.linspace(FREQ_MIN_CM, FREQ_MAX_CM, max(2, NPOINTS))
ir_spectrum = lorentzian_spectrum(grid, frequencies_cm, ir_debye,
                                  BROADENING_CM)
raman_spectrum = lorentzian_spectrum(grid, frequencies_cm, raman_intensity,
                                     BROADENING_CM)

modes = []
for index in range(len(frequencies_cm)):
    modes.append({
        'index': index,
        'frequency_cm': float(frequencies_cm[index]),
        'frequency_meV': float(frequencies_cm[index] * units.invcm * 1000.0),
        'ir_intensity_D2_A2_amu': float(ir_debye[index]),
        'ir_intensity_e2_amu': float(ir_e2_amu[index]),
        'raman_activity_A4_amu': float(raman_activity[index]),
        'raman_intensity': float(raman_intensity[index]),
        'acoustic': bool(abs(frequencies_cm[index]) <= 1.0),
    })

summary = {
    'formula': atoms.get_chemical_formula(),
    'atoms': natoms,
    'symbols': symbols,
    'displacement_A': DELTA,
    'laser_nm': LASER_NM,
    'temperature_K': TEMPERATURE_K,
    'broadening_cm': BROADENING_CM,
    'volume_A3': volume,
    'born_charges_source': BORN_CHARGES,
    'optics_source': OPTICS_REFERENCE,
    'raman': raman_meta,
    'ir': ir_meta,
    'modes': modes,
    'spectrum': {
        'frequency_cm': [float(v) for v in grid],
        'ir': [float(v) for v in ir_spectrum],
        'raman': [float(v) for v in raman_spectrum],
    },
}
with open('raman_ir.json', 'w') as handle:
    json.dump(summary, handle, indent=2)

# max() over an all-zero IR column picks an arbitrary mode and reports it as
# "the strongest", which reads as a result. With no Born charges there is no
# strongest IR mode to name.
# max() over an all-zero IR column picks an arbitrary mode and reports it as
# "the strongest", which reads as a result. With no Born charges there is no
# strongest IR mode to name, so the field says so.
_strongest = (max(modes, key=lambda m: m['ir_intensity_D2_A2_amu'])
              if modes and ir_meta['computed'] else None)
_strongest_cm = f'{_strongest["frequency_cm"]:.1f}' if _strongest else 'n/a'
print(f'CALANGO_RESULT raman_ir=raman_ir.json '
      f'modes={len(modes)} '
      f'raman={"yes" if raman_meta["computed"] else "no"} '
      f'ir={"yes" if ir_meta["computed"] else "no"} '
      f'strongest_ir_cm={_strongest_cm}',
      flush=True)
)PY";
    return out.str();
}

} // namespace calango::core
