#include "core/RandomNoiseScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

std::string RandomNoiseScriptGenerator::generate(const RandomNoiseRunConfig& c)
{
    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — single-point sweep over a randomly-perturbed ensemble with "
        << toString(c.calculator.calculator)
        << ".\n"
           "# Every member is evaluated at its own displaced geometry; the\n"
           "# output is the resulting energy (and force) DISTRIBUTION, which is\n"
           "# what measures the local curvature of the potential-energy surface\n"
           "# around the reference structure.\n"
           "# This is a plain ASE script: edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "import math\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read, write\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "input_path = r\"" << c.inputTrajectory
        << "\"\n"
           "output_path = r\""
        << c.outputTrajectory
        << "\"\n"
           "results_path = r\""
        << c.resultsJson
        << "\"\n"
           "\n"
           "members = read(input_path, index=\":\")\n"
           "if not members:\n"
           "    raise RuntimeError(f\"No structures found in {input_path}\")\n"
           "print(f\"CALANGO_INFO members={len(members)}\", flush=True)\n"
           "\n"
           "\n"
           "def attach_calculator(atoms):\n"
           "    \"\"\"Bind a fresh calculator to one ensemble member.\"\"\"\n";
    {
        // The same calculator block every other generated script uses, indented
        // into the function body. It binds to `atoms`, hence the rebind per
        // member — a shared calculator would carry the previous geometry's
        // converged density into the next member and quietly bias the spread.
        const std::string snippet =
            AseScriptGenerator::calculatorSnippet(c.calculator);
        std::istringstream lines(snippet);
        std::string line;
        while (std::getline(lines, line)) {
            if (line.empty())
                out << "\n";
            else
                out << "    " << line << "\n";
        }
    }
    out << "    return atoms\n"
           "\n"
           "\n"
           "records = []\n"
           "evaluated = []\n"
           "\n"
           "for index, atoms in enumerate(members):\n"
           "    _calango_log.progress(index, len(members))\n"
           "    record = {\n"
           "        \"frame\": index,\n"
           "        \"formula\": atoms.get_chemical_formula(),\n"
           "        \"natoms\": len(atoms),\n"
           "    }\n"
           "    try:\n"
           "        attach_calculator(atoms)\n"
           "        energy = float(atoms.get_potential_energy())\n"
           "        record[\"energy\"] = energy\n"
           "        record[\"energy_per_atom\"] = energy / max(1, len(atoms))\n";
    if (c.computeForces) {
        out << "        forces = np.asarray(atoms.get_forces())\n"
               "        # The per-atom force NORM, not the largest Cartesian\n"
               "        # component: a displaced atom is pulled back along an\n"
               "        # arbitrary direction, and componentwise maxima\n"
               "        # under-report that by up to sqrt(3).\n"
               "        magnitudes = np.linalg.norm(forces, axis=1)\n"
               "        record[\"fmax\"] = float(magnitudes.max())\n"
               "        record[\"frms\"] = float(np.sqrt((magnitudes ** 2).mean()))\n";
    }
    if (c.computeStress) {
        out << "        try:\n"
               "            record[\"stress\"] = [\n"
               "                float(v) for v in atoms.get_stress(voigt=True)]\n"
               "        except Exception as stress_error:\n"
               "            # Plenty of calculators implement forces but not\n"
               "            # stress; that is not a reason to lose the energy.\n"
               "            record[\"stress\"] = None\n"
               "            print(f\"CALANGO_WARN frame={index} no stress: \"\n"
               "                  f\"{stress_error}\", flush=True)\n";
    }
    out << "        evaluated.append(atoms)\n"
           "        print(f\"CALANGO_MEMBER frame={index} \"\n"
           "              f\"E={energy:.6f}\", flush=True)\n"
           "    except Exception as error:\n";
    if (c.continueOnFailure) {
        out << "        # One member that will not converge must not lose the\n"
               "        # rest of the ensemble.\n"
               "        record[\"error\"] = str(error)\n"
               "        record[\"energy\"] = math.nan\n"
               "        record[\"energy_per_atom\"] = math.nan\n"
               "        _calango_log.event(\"error\",\n"
               "                           f\"member {index} failed: {error}\")\n"
               "        print(f\"CALANGO_WARN frame={index} failed: {error}\",\n"
               "              flush=True)\n";
    } else {
        out << "        raise\n";
    }
    out << "    records.append(record)\n"
           "\n"
           "_calango_log.progress(len(members), len(members))\n"
           "\n"
           "if evaluated:\n"
           "    write(output_path, evaluated)\n"
           "    print(f\"CALANGO_INFO wrote {output_path} \"\n"
           "          f\"({len(evaluated)} structures)\", flush=True)\n"
           "\n"
           "# -- Ensemble statistics ------------------------------------------\n"
           "#\n"
           "# The reference (unperturbed) structure is frame 0 by construction,\n"
           "# so the shift of the mean away from it is the anharmonic bias the\n"
           "# displacement introduces — the number that says whether the noise\n"
           "# amplitude is still in the harmonic regime.\n"
           "energies = [r[\"energy\"] for r in records\n"
           "            if r.get(\"energy\") is not None\n"
           "            and not math.isnan(r[\"energy\"])]\n"
           "summary = {\n"
           "    \"members\": len(records),\n"
           "    \"evaluated\": len(energies),\n"
           "    \"failed\": len(records) - len(energies),\n"
           "}\n"
           "if energies:\n"
           "    values = np.asarray(energies, dtype=float)\n"
           "    reference = records[0].get(\"energy\")\n"
           "    summary.update({\n"
           "        \"energy_mean\": float(values.mean()),\n"
           "        \"energy_std\": float(values.std(ddof=1))\n"
           "        if values.size > 1 else 0.0,\n"
           "        \"energy_min\": float(values.min()),\n"
           "        \"energy_max\": float(values.max()),\n"
           "        \"energy_range\": float(values.max() - values.min()),\n"
           "    })\n"
           "    if reference is not None and not math.isnan(reference):\n"
           "        summary[\"reference_energy\"] = float(reference)\n"
           "        summary[\"mean_shift\"] = float(values.mean() - reference)\n"
           "\n"
           "with open(results_path, \"w\") as handle:\n"
           "    json.dump({\"summary\": summary, \"members\": records}, handle,\n"
           "              indent=2)\n"
           "print(f\"CALANGO_INFO wrote {results_path}\", flush=True)\n"
           "if energies:\n"
           "    print(f\"CALANGO_SUMMARY mean={summary['energy_mean']:.6f} \"\n"
           "          f\"std={summary['energy_std']:.6f} \"\n"
           "          f\"range={summary['energy_range']:.6f}\", flush=True)\n"
           "_calango_log.event(\"done\", f\"{len(energies)} of {len(records)} \"\n"
           "                            f\"members evaluated\")\n";
    return out.str();
}

} // namespace calango::core
