#pragma once

#include "core/CalphadModel.hpp"

#include <cstdint>
#include <string>
#include <vector>

namespace calango::core {

/// One ELEMENT record to emit.
///
/// `massGPerMol`, `enthalpy298` and `entropy298` are the SER reference data.
/// They are not used by anything in Calango — nothing here integrates a heat
/// capacity from 298.15 K — but a database without them is rejected outright
/// by Thermo-Calc and by pycalphad, so writing zeros silently would produce a
/// file that only Calango can read. The defaults are zeros and the writer says
/// so in the file header rather than pretending otherwise.
struct TdbElementSpec {
    std::string name;                       ///< "AG"
    std::string referencePhase = "BLANK";   ///< SER phase
    double massGPerMol = 0.0;
    double enthalpy298 = 0.0;               ///< H(298.15) − H(0), J/mol
    double entropy298 = 0.0;                ///< S(298.15), J/mol/K
};

/// A binary interaction to emit as `PARAMETER L(PHASE,A,B;ν)`.
struct TdbInteractionSpec {
    /// The pair. The Redlich-Kister polynomial variable is (x_first − x_second)
    /// as given here; the writer re-orders the names into the alphabetical
    /// order TDB requires and negates the odd coefficients when it has to, so
    /// a caller never has to think about it.
    std::string first;
    std::string second;
    std::vector<RedlichKisterTerm> terms; ///< index = order ν
};

/// A single-sublattice substitutional phase to emit.
struct TdbPhaseSpec {
    std::string name = "SOLUTION";
    std::string typeCode = "%";
    double siteRatio = 1.0;
    std::vector<std::string> constituents;
    /// The `G(PHASE,X;0)` expression for each constituent, aligned to
    /// `constituents`. An empty entry is written as `0`.
    ///
    /// A first-principles assessment normally leaves these empty: its energies
    /// are referenced to its OWN endpoints, so the pure-element Gibbs energy in
    /// this phase is zero by construction. That makes the file self-consistent
    /// and NOT mergeable with an SGTE database, whose G is referenced to SER —
    /// mixing the two references silently shifts every phase boundary, so the
    /// writer states the reference in the file header.
    std::vector<std::string> endmemberExpressions;
    std::vector<TdbInteractionSpec> interactions;
};

struct TdbWriteOptions {
    /// Free text for the `$` header. Newlines are re-commented, so a
    /// multi-line provenance note can be passed straight through.
    std::string title = "Generated by Calango";
    std::vector<TdbElementSpec> elements;
    std::vector<TdbPhaseSpec> phases;
    double lowTemperatureK = 298.15;
    double highTemperatureK = 6000.0;
};

/// Emit a `.tdb`.
///
/// The output is designed to be read back by core::TdbDatabase, and the round
/// trip — write, parse, recover every coefficient — is the strongest test a
/// writer of this kind can have: it checks the syntax, the ordering
/// conventions, the number formatting and the sign convention in one assertion
/// instead of four unverifiable ones.
///
/// Numbers are written with enough significant digits to survive that round
/// trip exactly (17 for a double), because a writer that rounds to four
/// figures produces a file that reads back "close enough" and hides a genuine
/// sign or factor error inside the tolerance.
std::string writeTdb(const TdbWriteOptions& options);

/// Convenience: package one assessed binary system into TdbWriteOptions.
///
/// `assessment` must be ok(). The elements are written with zero SER data
/// (see TdbElementSpec) unless the caller fills them in afterwards.
TdbWriteOptions tdbOptionsForAssessment(const CalphadAssessmentInput& input,
                                        const CalphadAssessment& assessment);

} // namespace calango::core
