#include "core/ThermodynamicIntegrationScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"
#include "core/LocaleSafeNumber.hpp"
#include "core/MdIntegratorBlocks.hpp"

#include <algorithm>
#include <cstdint>
#include <sstream>

namespace calango::core {

namespace {

/// Numbers that must SURVIVE THE ROUND TRIP, written with std::to_chars.
///
/// `ostringstream << double` writes six significant digits, and for the λ nodes
/// that is not a cosmetic loss: Gauss-Legendre weights are only valid on the
/// Gauss-Legendre nodes, and the reader checks that the λ values it got back
/// ARE those nodes before using them. A six-digit node misses the exact one by
/// ~1e-9, the check fails, and the run is silently re-integrated with a
/// trapezoid on a grid that was chosen for Gauss — a real accuracy loss with
/// nothing in the output pointing at the cause. to_chars writes the shortest
/// text that reads back as the identical double, which makes the round trip
/// exact by construction.
///
/// It is also the locale-safe spelling, which on this project's own
/// development machine (pt_BR, decimal comma) is not academic.
std::string number(double value)
{
    return localeSafeFormat(value);
}

std::string pythonList(const std::vector<double>& values)
{
    std::ostringstream out;
    out << "[";
    for (std::size_t i = 0; i < values.size(); ++i)
        out << (i ? ", " : "") << number(values[i]);
    out << "]";
    return out.str();
}

std::string pythonList(const std::vector<int>& values)
{
    std::ostringstream out;
    out << "[";
    for (std::size_t i = 0; i < values.size(); ++i)
        out << (i ? ", " : "") << values[i];
    out << "]";
    return out.str();
}

} // namespace

std::vector<std::vector<int>>
ThermodynamicIntegrationScriptGenerator::splitWindows(int windows, int jobs)
{
    std::vector<std::vector<int>> slices;
    if (windows <= 0)
        return slices;
    jobs = std::clamp(jobs, 1, windows);
    // Remainder spread over the leading slices, so no job carries two more
    // windows than another. With 12 windows over 5 jobs that is 3/3/2/2/2, not
    // 2/2/2/2/4 — the wall time of the whole run is the SLOWEST job, so an
    // uneven split is a slower run for no reason.
    const int base = windows / jobs;
    const int extra = windows % jobs;
    int next = 0;
    for (int job = 0; job < jobs; ++job) {
        const int count = base + (job < extra ? 1 : 0);
        std::vector<int> slice;
        slice.reserve(static_cast<std::size_t>(count));
        for (int i = 0; i < count; ++i)
            slice.push_back(next++);
        slices.push_back(std::move(slice));
    }
    return slices;
}

std::string ThermodynamicIntegrationScriptGenerator::generate(
    const TiRunConfig& config)
{
    const int windows = std::max(1, config.windows);
    const std::vector<double> lambdas =
        lambdaSchedule(config.schedule, windows, config.scheduleExponent);

    std::vector<int> owned = config.windowIndices;
    if (owned.empty())
        for (int i = 0; i < windows; ++i)
            owned.push_back(i);
    std::sort(owned.begin(), owned.end());
    owned.erase(std::unique(owned.begin(), owned.end()), owned.end());
    owned.erase(std::remove_if(owned.begin(), owned.end(),
                               [windows](int index) {
                                   return index < 0 || index >= windows;
                               }),
                owned.end());

    // A backward sweep is a SEQUENTIAL diagnostic: window k inherits window
    // k−1's configuration, and reversing that chain is what can disagree with
    // the forward one. A job that owns a subset has no chain to reverse, so the
    // option is dropped rather than producing a "hysteresis" that is really two
    // independent estimates of the same average.
    const bool ownsEverything = static_cast<int>(owned.size()) == windows;
    const bool hysteresis = config.hysteresis && ownsEverything;

    CalculatorConfig calculator = config.calculator;
    calculator.task = TaskKind::MolecularDynamics;
    calculator.temperatureK = config.calculator.temperatureK;

    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — thermodynamic integration.\n"
           "#\n"
           "# ABSOLUTE free energy of a liquid (or, with the Einstein\n"
           "# reference, a solid) by coupling it reversibly to a reference\n"
           "# system whose free energy is known in closed form:\n"
           "#\n"
           "#     U(lambda) = (1 - lambda) U_ref + lambda U_target\n"
           "#     dF/dlambda = <U_target - U_ref>_lambda\n"
           "#     F_target   = F_ref + integral_0^1 <U_target - U_ref> dlambda\n"
           "#\n"
           "# A simulation measures energy differences; a free energy is the\n"
           "# logarithm of a partition function and is not the average of\n"
           "# anything. This construction is how one is obtained anyway.\n"
           "#\n"
           "# WHAT THIS SCRIPT DOES AND DOES NOT DO. It SAMPLES: one MD run per\n"
           "# lambda window, equilibration discarded, <U_target - U_ref>\n"
           "# accumulated during production, one JSON file per window. It does\n"
           "# NOT own the physics of the assembly — the quadrature, the error\n"
           "# propagation, the reference free energy and the endpoint\n"
           "# diagnostics all live in Calango and are applied when the results\n"
           "# are read, so there is exactly one implementation of each. The\n"
           "# trapezoid value written at the end is a convenience for running\n"
           "# this file standalone, and is labelled as such.\n"
           "#\n"
           "# EQUILIBRATION IS SEPARATE FROM PRODUCTION, and that is not\n"
           "# tidiness. Averaging over the equilibration transient biases every\n"
           "# window in the SAME direction, so the bias survives the lambda\n"
           "# integral instead of cancelling — and it looks nothing like noise.\n"
           "#\n"
           "# ENDPOINT SINGULARITY. With linear coupling and a target that has\n"
           "# a hard repulsive core, <dU/dlambda> diverges as lambda -> 0\n"
           "# against an ideal-gas reference: nothing stops two atoms sitting\n"
           "# on top of each other there, and the target charges an unbounded\n"
           "# energy for it. This run reports the per-window VARIANCE of\n"
           "# dU/dlambda precisely so that divergence is visible; Calango\n"
           "# raises it as a warning rather than quietly integrating it.\n"
           "#\n"
           "# This is a plain ASE script: edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "import math\n"
           "import os\n"
           "\n"
           "import numpy as np\n"
           "from ase import units\n"
           "from ase.io import read\n"
           "from ase.calculators.calculator import Calculator, all_changes\n"
           "from ase.md.velocitydistribution import (MaxwellBoltzmannDistribution,\n"
           "                                         Stationary, ZeroRotation)\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "\n"
           "# ---- The lambda path -------------------------------------------\n"
           "# LAMBDAS is the WHOLE path; WINDOW_INDICES is the part this job\n"
           "# runs. They differ when the run was split across jobs, and the\n"
           "# summary is only written once every window in LAMBDAS has\n"
           "# reported.\n"
           "LAMBDAS = "
        << pythonList(lambdas)
        << "\n"
           "WINDOW_INDICES = "
        << pythonList(owned)
        << "\n"
           "SCHEDULE = \""
        << (config.schedule == TiLambdaSchedule::GaussLegendre ? "gauss_legendre"
            : config.schedule == TiLambdaSchedule::PowerLaw    ? "power_law"
            : config.schedule == TiLambdaSchedule::ClusteredEnds
                                                               ? "clustered_ends"
                                                               : "uniform")
        << "\"\n"
           "# The rule Calango integrates with when it reads these results.\n"
           "# Carried in the output rather than reconstructed from the\n"
           "# schedule, because Gauss-Legendre weights are only valid on\n"
           "# Gauss-Legendre nodes and guessing that pairing at read time is\n"
           "# exactly the mistake the core refuses to make.\n"
           "QUADRATURE = \""
        << (config.quadrature == TiQuadrature::GaussLegendre ? "gauss_legendre"
            : config.quadrature == TiQuadrature::Simpson     ? "simpson"
                                                             : "trapezoid")
        << "\"\n"
           "REFERENCE = \""
        << toString(config.reference)
        << "\"\n"
           "SWEEPS = "
        << (hysteresis ? "[\"forward\", \"backward\"]" : "[\"forward\"]")
        << "\n"
           "\n"
           "EQUILIBRATION_STEPS = "
        << std::max(0, config.equilibrationSteps)
        << "\n"
           "PRODUCTION_STEPS = "
        << std::max(1, config.productionSteps)
        << "\n"
           "SAMPLE_INTERVAL = "
        << std::max(1, config.sampleInterval)
        << "\n"
           "TEMPERATURE_K = "
        << number(calculator.temperatureK)
        << "\n"
           "PRESSURE_GPA = "
        << number(calculator.pressureGPa)
        << "\n"
           "EINSTEIN_SPRING_EV_PER_A2 = "
        << number(config.referenceParameters.einsteinSpringEvPerA2)
        << "\n"
           "EINSTEIN_FIX_CENTRE_OF_MASS = "
        << (config.referenceParameters.einsteinFixedCenterOfMass ? "True"
                                                                 : "False")
        << "\n"
           "LJ_EPSILON_EV = "
        << number(config.referenceParameters.ljEpsilonEv)
        << "\n"
           "LJ_SIGMA_A = "
        << number(config.referenceParameters.ljSigmaA)
        << "\n"
           "LJ_CUTOFF_A = "
        << number(config.ljCutoffA)
        << "\n"
           "\n"
           "RESULTS_DIR = r\""
        << (config.resultsDir.empty() ? std::string(".") : config.resultsDir)
        << "\"\n"
           "RESULTS_JSON = os.path.join(RESULTS_DIR, r\""
        << config.resultsJson
        << "\")\n"
           "os.makedirs(RESULTS_DIR, exist_ok=True)\n"
           "\n"
           "atoms = read(r\""
        << config.structureFile
        << "\")\n"
           "REFERENCE_POSITIONS = atoms.get_positions().copy()\n"
           "NATOMS = len(atoms)\n"
           "VOLUME_A3 = float(abs(atoms.get_volume())) if atoms.cell.rank == 3 "
           "else 0.0\n"
           "MASSES_AMU = [float(m) for m in atoms.get_masses()]\n"
           "print(f\"CALANGO_INFO natoms={NATOMS} windows={len(LAMBDAS)} \"\n"
           "      f\"owned={len(WINDOW_INDICES)} reference={REFERENCE}\",\n"
           "      flush=True)\n"
           "\n"
           "\n"
           "def attach_calculator(system):\n"
           "    \"\"\"Bind the TARGET calculator to `system`.\n"
           "\n"
           "    One definition, so every target energy in this run comes from\n"
           "    an identically configured engine — and the same engine block\n"
           "    every other Calango module emits.\n"
           "    \"\"\"\n"
           "    atoms = system\n";
    AseScriptGenerator::emitIndented(out, AseScriptGenerator::calculatorSnippet(calculator), "    ");
    out << "    return atoms.calc\n"
           "\n"
           "\n";

    out << R"PY(class _TiIdealGas(Calculator):
    """U_ref = 0: the ideal gas has no interactions at all.

    The exact reference for a LIQUID, and the one that makes the endpoint
    worst — at lambda -> 0 the atoms are free to overlap.
    """

    implemented_properties = ["energy", "free_energy", "forces"]

    def calculate(self, atoms=None, properties=("energy",),
                  system_changes=all_changes):
        Calculator.calculate(self, atoms, properties, system_changes)
        self.results = {
            "energy": 0.0,
            "free_energy": 0.0,
            "forces": np.zeros((len(self.atoms), 3)),
        }


class _TiEinsteinCrystal(Calculator):
    """U_ref = (alpha/2) sum_i |r_i - r_i^0|^2 — one harmonic tether per atom.

    The standard SOLID reference (Frenkel & Ladd 1984). Its free energy is
    3 N kT ln(beta hbar omega) in closed form, and because the atoms are
    tethered they never overlap, so this reference has no endpoint
    singularity at all.

    The sites are the positions of the structure this run was started from,
    which is what makes the reference reproducible: they are written into
    the per-window files.
    """

    implemented_properties = ["energy", "free_energy", "forces"]

    def __init__(self, sites, spring):
        Calculator.__init__(self)
        self.sites = np.asarray(sites, dtype=float)
        self.spring = float(spring)

    def calculate(self, atoms=None, properties=("energy",),
                  system_changes=all_changes):
        Calculator.calculate(self, atoms, properties, system_changes)
        # Minimum-image displacement: without it an atom that crosses the
        # periodic boundary is suddenly a whole cell length from its site and
        # the tether energy jumps by a number with no physical meaning.
        delta = self.atoms.get_positions() - self.sites
        cell = self.atoms.cell
        if self.atoms.pbc.any() and cell.rank == 3:
            fractional = np.linalg.solve(np.array(cell).T, delta.T).T
            fractional -= np.round(fractional)
            delta = fractional @ np.array(cell)
        energy = 0.5 * self.spring * float((delta * delta).sum())
        self.results = {
            "energy": energy,
            "free_energy": energy,
            "forces": -self.spring * delta,
        }


def _ti_reference_calculator():
    """Build the reference Hamiltonian named by REFERENCE."""
    if REFERENCE == "einstein_crystal":
        return _TiEinsteinCrystal(REFERENCE_POSITIONS,
                                  EINSTEIN_SPRING_EV_PER_A2)
    if REFERENCE == "lennard_jones_fluid":
        from ase.calculators.lj import LennardJones

        return LennardJones(epsilon=LJ_EPSILON_EV, sigma=LJ_SIGMA_A,
                            rc=LJ_CUTOFF_A, smooth=False)
    return _TiIdealGas()


class _TiMixedCalculator(Calculator):
    """U(lambda) = (1 - lambda) U_ref + lambda U_target.

    Both halves are evaluated once per force call and CACHED on the object,
    so the dU/dlambda sample the window accumulates costs nothing beyond the
    dynamics. Re-asking the sub-calculators at sampling time would double the
    cost of the expensive half, which for a DFT or MLIP target is the whole
    run.

    The dynamics are propagated on the MIXED forces, which is the point: the
    ensemble the average is taken in must be the one U(lambda) defines, not
    the target's.
    """

    implemented_properties = ["energy", "free_energy", "forces"]

    def __init__(self, reference, target, lam):
        Calculator.__init__(self)
        self.reference = reference
        self.target = target
        self.lam = float(lam)
        self.reference_energy = 0.0
        self.target_energy = 0.0

    def calculate(self, atoms=None, properties=("energy",),
                  system_changes=all_changes):
        Calculator.calculate(self, atoms, properties, system_changes)
        state = self.atoms
        self.reference_energy = float(
            self.reference.get_potential_energy(state))
        self.target_energy = float(self.target.get_potential_energy(state))
        reference_forces = self.reference.get_forces(state)
        target_forces = self.target.get_forces(state)
        weight = self.lam
        energy = ((1.0 - weight) * self.reference_energy
                  + weight * self.target_energy)
        self.results = {
            "energy": energy,
            "free_energy": energy,
            "forces": ((1.0 - weight) * reference_forces
                       + weight * target_forces),
        }

    def dudl(self):
        """dU/dlambda = U_target - U_ref, from the cached halves."""
        return self.target_energy - self.reference_energy


class _TiAccumulator:
    """Running mean and variance of dU/dlambda, plus the raw series.

    Welford rather than sum-of-squares: the two energies differ by orders of
    magnitude from their difference for a strongly coupled target, and the
    naive <x^2> - <x>^2 loses every significant digit of the variance exactly
    when the variance is the thing being asked for (it is what the endpoint
    diagnostic reads).

    The series is kept as well as the moments. The moments are what the run
    prints as it goes; the series is what lets the autocorrelation time — and
    therefore the real error bar — be computed afterwards, and that cannot be
    recovered from moments.
    """

    def __init__(self):
        self.count = 0
        self.mean = 0.0
        self.m2 = 0.0
        self.series = []

    def add(self, value):
        value = float(value)
        self.series.append(value)
        self.count += 1
        delta = value - self.mean
        self.mean += delta / self.count
        self.m2 += delta * (value - self.mean)

    def variance(self):
        return self.m2 / (self.count - 1) if self.count > 1 else 0.0
)PY";

    out << "\n"
           "\n"
           "def _ti_window_path(index, sweep):\n"
           "    return os.path.join(RESULTS_DIR,\n"
           "                        f\"ti_window_{index:03d}_{sweep}.json\")\n"
           "\n"
           "\n"
           "def _ti_run_window(index, sweep):\n"
           "    \"\"\"One lambda window: equilibrate, then produce.\n"
           "\n"
           "    Returns the record that is written to disk. A window that\n"
           "    raises writes a record with status \"failed\" instead of\n"
           "    writing nothing, so a missing file means \"never ran\" and a\n"
           "    failed record means \"ran and died\" — two different things\n"
           "    when a run is being resumed.\n"
           "    \"\"\"\n"
           "    lam = LAMBDAS[index]\n"
           "    record = {\n"
           "        \"index\": int(index),\n"
           "        \"lambda\": float(lam),\n"
           "        \"sweep\": sweep,\n"
           "        \"reference\": REFERENCE,\n"
           "        \"schedule\": SCHEDULE,\n"
           "        \"temperature_K\": float(TEMPERATURE_K),\n"
           "        \"pressure_GPa\": float(PRESSURE_GPA),\n"
           "        \"natoms\": int(NATOMS),\n"
           "        \"volume_A3\": float(VOLUME_A3),\n"
           "        \"masses_amu\": MASSES_AMU,\n"
           "        \"equilibration_steps\": int(EQUILIBRATION_STEPS),\n"
           "        \"production_steps\": int(PRODUCTION_STEPS),\n"
           "        \"sample_interval\": int(SAMPLE_INTERVAL),\n"
           "        \"einstein_spring_eV_per_A2\": "
           "float(EINSTEIN_SPRING_EV_PER_A2),\n"
           "        \"einstein_fixed_com\": bool(EINSTEIN_FIX_CENTRE_OF_MASS),\n"
           "        \"status\": \"failed\",\n"
           "    }\n"
           "\n"
           "    mixed = _TiMixedCalculator(_ti_reference_calculator(),\n"
           "                               attach_calculator(atoms), lam)\n"
           "    atoms.calc = mixed\n";

    // Fixed centre of mass for the Einstein reference. An untethered
    // translation of the whole crystal is free in the target and quadratically
    // penalized by the springs, so the two Hamiltonians differ by a soft mode
    // that the tether kills; removing it is what makes the closed-form
    // reference the one the run actually samples.
    out << "\n"
           "    if REFERENCE == \"einstein_crystal\" and "
           "EINSTEIN_FIX_CENTRE_OF_MASS:\n"
           "        # The tether penalizes a rigid translation that costs the\n"
           "        # target nothing, so the two Hamiltonians differ by a soft\n"
           "        # mode. Holding the centre of mass removes it; the matching\n"
           "        # finite-size term is applied by Calango's closed form for\n"
           "        # the fixed-CM Einstein crystal, so the two must agree\n"
           "        # about whether it is on.\n"
           "        from ase.constraints import FixCom\n"
           "\n"
           "        if not any(isinstance(c, FixCom) for c in atoms.constraints):\n"
           "            atoms.set_constraint(list(atoms.constraints) + [FixCom()])\n"
           "\n"
           "    temperature_K = TEMPERATURE_K\n"
           "    MaxwellBoltzmannDistribution(atoms, temperature_K=temperature_K)\n"
           "    Stationary(atoms)\n"
           "    if not atoms.pbc.any():\n"
           "        ZeroRotation(atoms)\n"
           "\n";
    AseScriptGenerator::emitIndented(out, [&] {
        std::ostringstream integrator;
        md_blocks::emitIntegrator(integrator, calculator);
        return integrator.str();
    }(), "    ");

    out << "\n"
           "    # EQUILIBRATION. Run first, with nothing attached: the window\n"
           "    # has to forget the previous window's lambda before a single\n"
           "    # sample is taken. Sampling through the transient biases this\n"
           "    # window in one direction, and every window in the SAME\n"
           "    # direction, so the bias does not cancel in the integral.\n"
           "    if EQUILIBRATION_STEPS > 0:\n"
           "        dyn.run(EQUILIBRATION_STEPS)\n"
           "\n"
           "    accumulator = _TiAccumulator()\n"
           "    # The volume is accumulated too, and not for decoration: the\n"
           "    # reference free energy is a function of V, so an NPT window\n"
           "    # whose cell breathes has no single volume to evaluate it at.\n"
           "    # Calango compares the per-window means and refuses to pretend\n"
           "    # otherwise. Under NVT this is a constant and costs nothing.\n"
           "    volumes = _TiAccumulator()\n"
           "\n"
           "    def _ti_record():\n"
           "        # get_potential_energy() is served from the calculator's\n"
           "        # cache whenever the step already evaluated it, so this is\n"
           "        # free in the usual case and correct in the case where an\n"
           "        # integrator left the state unevaluated.\n"
           "        atoms.get_potential_energy()\n"
           "        accumulator.add(atoms.calc.dudl())\n"
           "        if atoms.cell.rank == 3:\n"
           "            volumes.add(abs(atoms.get_volume()))\n"
           "\n"
           "    dyn.attach(_ti_record, interval=SAMPLE_INTERVAL)\n"
           "    dyn.run(PRODUCTION_STEPS)\n"
           "\n"
           "    if accumulator.count < 2:\n"
           "        record[\"error\"] = (\"the production run produced fewer \"\n"
           "                            \"than two samples\")\n"
           "        return record\n"
           "\n"
           "    record[\"status\"] = \"ok\"\n"
           "    record[\"samples\"] = int(accumulator.count)\n"
           "    record[\"mean_dudl_eV\"] = float(accumulator.mean)\n"
           "    record[\"variance_dudl_eV2\"] = float(accumulator.variance())\n"
           "    # The raw series, which is what an autocorrelation-corrected\n"
           "    # error bar needs and what moments cannot be turned back into.\n"
           "    record[\"series_eV\"] = [float(v) for v in accumulator.series]\n"
           "    record[\"final_temperature_K\"] = float(\n"
           "        atoms.get_temperature())\n"
           "    record[\"volume_A3\"] = (float(abs(atoms.get_volume()))\n"
           "                            if atoms.cell.rank == 3 else 0.0)\n"
           "    record[\"mean_volume_A3\"] = (float(volumes.mean)\n"
           "                                 if volumes.count > 0 else 0.0)\n"
           "    record[\"variance_volume_A6\"] = float(volumes.variance())\n"
           "    return record\n"
           "\n"
           "\n"
           "def _ti_trapezoid(points):\n"
           "    \"\"\"Convenience only — see the header.\n"
           "\n"
           "    Calango re-integrates with the configured rule, propagates the\n"
           "    statistical error and adds the reference free energy. This is\n"
           "    the plain trapezoid so that running the file standalone still\n"
           "    yields a number, and it is named accordingly.\n"
           "    \"\"\"\n"
           "    points = sorted(points)\n"
           "    if len(points) < 2:\n"
           "        return None\n"
           "    total = 0.0\n"
           "    # Held constant outside the outermost node: a Gauss-Legendre\n"
           "    # path has no sample at lambda = 0 or 1 at all, and ignoring\n"
           "    # those two panels would silently drop part of the integral.\n"
           "    total += points[0][1] * (points[0][0] - 0.0)\n"
           "    total += points[-1][1] * (1.0 - points[-1][0])\n"
           "    for (x0, y0), (x1, y1) in zip(points, points[1:]):\n"
           "        total += 0.5 * (y0 + y1) * (x1 - x0)\n"
           "    return total\n"
           "\n"
           "\n"
           "def _ti_aggregate():\n"
           "    \"\"\"Write the summary — and refuse to claim a result early.\n"
           "\n"
           "    Every job calls this when it finishes. Whichever one runs last\n"
           "    finds a complete set of per-window files and marks the run\n"
           "    complete; the others leave a summary that names exactly which\n"
           "    windows are still missing.\n"
           "\n"
           "    A DEAD WINDOW MUST NOT PRODUCE AN INTEGRAL. Quadrature weights\n"
           "    are a property of the node set: dropping a node and\n"
           "    reintegrating the rest is a different integral over a different\n"
           "    grid, reported under the same name. So `complete` gates the\n"
           "    convenience value, and Calango's own assembly refuses on the\n"
           "    same condition.\n"
           "    \"\"\"\n"
           "    summary = {\n"
           "        \"schema\": \"calango.thermodynamic_integration/1\",\n"
           "        \"reference\": REFERENCE,\n"
           "        \"schedule\": SCHEDULE,\n"
           "        \"quadrature\": QUADRATURE,\n"
           "        \"lambdas\": [float(v) for v in LAMBDAS],\n"
           "        \"windows_expected\": int(len(LAMBDAS)),\n"
           "        \"temperature_K\": float(TEMPERATURE_K),\n"
           "        \"pressure_GPa\": float(PRESSURE_GPA),\n"
           "        \"natoms\": int(NATOMS),\n"
           "        \"volume_A3\": float(VOLUME_A3),\n"
           "        \"masses_amu\": MASSES_AMU,\n"
           "        \"einstein_spring_eV_per_A2\": "
           "float(EINSTEIN_SPRING_EV_PER_A2),\n"
           "        \"einstein_fixed_com\": bool(EINSTEIN_FIX_CENTRE_OF_MASS),\n"
           "        \"lj_epsilon_eV\": float(LJ_EPSILON_EV),\n"
           "        \"lj_sigma_A\": float(LJ_SIGMA_A),\n"
           "        \"sweeps\": list(SWEEPS),\n"
           "    }\n"
           "    sweep_blocks = {}\n"
           "    for sweep in SWEEPS:\n"
           "        records = []\n"
           "        missing = []\n"
           "        failed = []\n"
           "        for index in range(len(LAMBDAS)):\n"
           "            path = _ti_window_path(index, sweep)\n"
           "            if not os.path.exists(path):\n"
           "                missing.append(index)\n"
           "                continue\n"
           "            with open(path) as handle:\n"
           "                entry = json.load(handle)\n"
           "            records.append(entry)\n"
           "            if entry.get(\"status\") != \"ok\":\n"
           "                failed.append(index)\n"
           "        complete = not missing and not failed\n"
           "        block = {\n"
           "            \"windows\": records,\n"
           "            \"missing\": missing,\n"
           "            \"failed\": failed,\n"
           "            \"complete\": bool(complete),\n"
           "        }\n"
           "        if complete:\n"
           "            block[\"delta_F_trapezoid_eV\"] = _ti_trapezoid(\n"
           "                [(r[\"lambda\"], r[\"mean_dudl_eV\"]) for r in records])\n"
           "        else:\n"
           "            # Deliberately absent rather than zero: a key that is\n"
           "            # not there cannot be read as a free energy of zero.\n"
           "            block[\"delta_F_trapezoid_eV\"] = None\n"
           "        sweep_blocks[sweep] = block\n"
           "    summary[\"paths\"] = sweep_blocks\n"
           "    summary[\"complete\"] = bool(\n"
           "        sweep_blocks[\"forward\"][\"complete\"])\n"
           "    with open(RESULTS_JSON, \"w\") as handle:\n"
           "        json.dump(summary, handle, indent=2)\n"
           "    # And a copy in THIS job's own directory. When the run was\n"
           "    # split, RESULTS_DIR is shared and lives elsewhere; the host\n"
           "    # only knows the directory of the job that just finished, and\n"
           "    # this is what lets it report the run's state — including\n"
           "    # \"still incomplete\" — after every one of them.\n"
           "    local = os.path.abspath(\"ti.json\")\n"
           "    if os.path.abspath(RESULTS_JSON) != local:\n"
           "        with open(local, \"w\") as handle:\n"
           "            json.dump(summary, handle, indent=2)\n"
           "    return summary\n"
           "\n"
           "\n"
           "reference_calculator_probe = _ti_reference_calculator()\n"
           "print(\"CALANGO_INFO reference calculator: \"\n"
           "      f\"{type(reference_calculator_probe).__name__}\", flush=True)\n"
           "\n"
           "total_windows = len(WINDOW_INDICES) * len(SWEEPS)\n"
           "done = 0\n"
           "for sweep in SWEEPS:\n"
           "    # The backward sweep walks the same windows in reverse, keeping\n"
           "    # the configuration the forward sweep ended on. That is what\n"
           "    # makes the two directions able to DISAGREE: restarting from\n"
           "    # the input geometry each time would give two independent\n"
           "    # estimates of the same average and call their difference\n"
           "    # hysteresis.\n"
           "    order = (WINDOW_INDICES if sweep == \"forward\"\n"
           "             else list(reversed(WINDOW_INDICES)))\n"
           "    for index in order:\n"
           "        _calango_progress(done, total_windows)\n"
           "        try:\n"
           "            record = _ti_run_window(index, sweep)\n"
           "        except Exception as error:  # noqa: BLE001 - reported, not hidden\n"
           "            record = {\n"
           "                \"index\": int(index),\n"
           "                \"lambda\": float(LAMBDAS[index]),\n"
           "                \"sweep\": sweep,\n"
           "                \"status\": \"failed\",\n"
           "                \"error\": str(error),\n"
           "            }\n"
           "            _calango_event(\"error\",\n"
           "                           f\"lambda window {index} ({sweep}) \"\n"
           "                           f\"failed: {error}\")\n"
           "            print(f\"CALANGO_WARN lambda window {index} failed: \"\n"
           "                  f\"{error}\", flush=True)\n"
           "        with open(_ti_window_path(index, sweep), \"w\") as handle:\n"
           "            json.dump(record, handle)\n"
           "        if record.get(\"status\") == \"ok\":\n"
           "            _calango_metric(index,\n"
           "                            energy=record[\"mean_dudl_eV\"],\n"
           "                            temperature=record.get(\n"
           "                                \"final_temperature_K\"))\n"
           "            print(f\"CALANGO_INFO lambda={record['lambda']:.6f} \"\n"
           "                  f\"<dU/dl>={record['mean_dudl_eV']:.6f} eV \"\n"
           "                  f\"var={record['variance_dudl_eV2']:.6g}\",\n"
           "                  flush=True)\n"
           "        done += 1\n"
           "\n"
           "_calango_progress(total_windows, total_windows)\n"
           "\n"
           "summary = _ti_aggregate()\n"
           "print(f\"CALANGO_INFO wrote {RESULTS_JSON}\", flush=True)\n"
           "print(\"CALANGO_RESULT thermodynamic_integration=\" + RESULTS_JSON,\n"
           "      flush=True)\n"
           "if summary[\"complete\"]:\n"
           "    _calango_event(\n"
           "        \"done\",\n"
           "        f\"{len(LAMBDAS)} lambda windows complete; trapezoid \"\n"
           "        f\"dF = \"\n"
           "        f\"{summary['paths']['forward']['delta_F_trapezoid_eV']:.6f}\"\n"
           "        f\" eV (Calango re-integrates with the configured rule)\")\n"
           "else:\n"
           "    _calango_event(\n"
           "        \"warning\",\n"
           "        \"the lambda path is INCOMPLETE: window(s) \"\n"
           "        f\"{summary['paths']['forward']['missing']} never ran and \"\n"
           "        f\"{summary['paths']['forward']['failed']} failed. No free \"\n"
           "        \"energy is reported — an integral over the surviving \"\n"
           "        \"windows is a different integral, not a noisier one.\")\n"
           "print(\"CALANGO_DONE\", flush=True)\n";
    return out.str();
}

} // namespace calango::core
