#include "core/TwoDBandsScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <algorithm>
#include <sstream>

namespace calango::core {

std::string generateTwoDBandsScript(const TwoDBandsConfig& cfg)
{
    // Clamped here rather than trusted from the dialog: this generator is also
    // reachable headlessly, and N <= 1 produces a degenerate grid that numpy
    // reshapes without complaint into something the viewer cannot triangulate.
    const int n = std::clamp(cfg.gridSamples, 3, 512);
    const int below = std::max(0, cfg.bandsBelow);
    const int above = std::max(0, cfg.bandsAbove);

    std::ostringstream out;
    out << "# 2D band surfaces E_n(kx, ky) — generated by Calango\n"
           "#\n"
           "# Restarts a converged density and evaluates the eigenvalues on a\n"
           "# grid covering the two-dimensional Brillouin zone at kz = 0, then\n"
           "# writes them as surfaces over the Cartesian kx-ky plane.\n"
           "import json\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << AseScriptGenerator::gpawImports(cfg.gpaw) << "\n"
        << "calc = GPAW(r\"" << cfg.baselineDensityPath
        << "\", txt=\"gpaw_2d_bands.txt\")\n"
           "atoms = calc.get_atoms()\n"
           "efermi = float(calc.get_fermi_level())\n"
           "_calango_progress(1, 4)\n"
           "\n"
           "# --- Geometry sanity ----------------------------------------------\n"
           "# The kz = 0 plane is the whole Brillouin zone only for a sheet:\n"
           "# periodic in x and y, vacuum along z. Run this on a bulk crystal\n"
           "# and the surface is a single cut through a 3D dispersion, which\n"
           "# looks entirely plausible and means something else.\n"
           "_pbc = list(atoms.get_pbc())\n"
           "if not (_pbc[0] and _pbc[1]):\n"
           "    raise RuntimeError(\n"
           "        'A 2D band surface needs a structure periodic in x and y; "
           "this '\n"
           "        'one has pbc = ' + str(_pbc) + '. Set the periodicity in "
           "Edit '\n"
           "        'Structure, or use the 1D Electronic Structure module.')\n"
           "if _pbc[2]:\n"
           "    print('CALANGO_WARN this structure is periodic along z as well, "
           "so '\n"
           "          'the kz = 0 plane is one cut through a 3D dispersion "
           "rather '\n"
           "          'than the full Brillouin zone. Add vacuum along z for a "
           "true '\n"
           "          '2D band surface.', flush=True)\n"
           "\n"
           "# --- 2D k-grid ----------------------------------------------------\n"
        << "_n = " << n << "\n"
        << "# Gamma-centred and INCLUSIVE of both zone edges: -1/2 and +1/2 are\n"
           "# the same k by periodicity, and sampling both is what closes the\n"
           "# surface instead of leaving a seam along two sides of the plot.\n"
           "_frac = np.linspace(-0.5, 0.5, _n)\n"
           "_fx, _fy = np.meshgrid(_frac, _frac, indexing='ij')\n"
           "_kpts = np.zeros((_n * _n, 3))\n"
           "_kpts[:, 0] = _fx.ravel()\n"
           "_kpts[:, 1] = _fy.ravel()\n"
           "print(f'CALANGO_INFO 2D Brillouin-zone grid {_n}x{_n} "
           "({_n * _n} k-points)', flush=True)\n"
           "\n"
           "# symmetry='off' keeps every grid point. The point symmetry would\n"
           "# fold the mesh onto an irreducible wedge, and unfolding it back\n"
           "# into a plottable surface is exactly the work this avoids.\n";

    out << "band_calc = calc.fixed_density(kpts=_kpts, symmetry='off',\n";
    if (cfg.totalBands > 0)
        out << "                               nbands=" << cfg.totalBands << ",\n";
    out << "                               txt='gpaw_2d_bands.txt')\n"
           "_calango_progress(2, 4)\n"
           "\n";

    if (cfg.spinOrbit) {
        out << "# --- Spin-orbit coupling -------------------------------------\n"
               "# Re-diagonalizes the converged states in the spinor basis. On a\n"
               "# 2D surface plot this is usually the point: Rashba splitting and\n"
               "# the gap opened at a band touching are invisible without it.\n"
               "from gpaw.spinorbit import soc_eigenstates\n"
               "_soc = soc_eigenstates(band_calc)\n"
               "# (nk, nband) -> one spin channel of doubled, spin-mixed bands.\n"
               "_energies = np.asarray(_soc.eigenvalues())[np.newaxis]\n"
               "efermi = float(_soc.fermi_level)\n"
               "print(f'CALANGO_INFO spin-orbit coupling applied, "
               "E_F = {efermi:.4f} eV', flush=True)\n";
    } else {
        out << "_nspin = band_calc.get_number_of_spins()\n"
               "_nk = len(_kpts)\n"
               "_energies = np.asarray(\n"
               "    [[band_calc.get_eigenvalues(kpt=_k, spin=_s)\n"
               "      for _k in range(_nk)] for _s in range(_nspin)],\n"
               "    dtype=float)  # (nspin, nk, nband)\n";
    }

    out << "_calango_progress(3, 4)\n"
           "\n"
           "# --- Band selection -----------------------------------------------\n"
           "# Every band that crosses E_F is kept whatever the counts say: those\n"
           "# ARE the Fermi surface, and silently dropping one because a count\n"
           "# ran out would remove the feature the plot exists to show.\n"
        << "_below, _above = " << below << ", " << above << "\n"
        << "_keep = []\n"
           "for _s in range(_energies.shape[0]):\n"
           "    _lo = _energies[_s].min(axis=0)  # per band, over all k\n"
           "    _hi = _energies[_s].max(axis=0)\n"
           "    _crossing = [int(_b) for _b in range(_energies.shape[2])\n"
           "                 if _lo[_b] <= efermi <= _hi[_b]]\n"
           "    _under = [int(_b) for _b in range(_energies.shape[2])\n"
           "              if _hi[_b] < efermi]\n"
           "    _over = [int(_b) for _b in range(_energies.shape[2])\n"
           "             if _lo[_b] > efermi]\n"
           "    _sel = set(_crossing)\n"
           "    if _below:\n"
           "        _sel.update(_under[-_below:])   # the highest below E_F\n"
           "    if _above:\n"
           "        _sel.update(_over[:_above])     # the lowest above E_F\n"
           "    for _b in sorted(_sel):\n"
           "        _keep.append((_s, int(_b)))\n"
           "if not _keep:\n"
           "    raise RuntimeError('No bands fell in the requested window "
           "around the '\n"
           "                       'Fermi level — raise the band counts.')\n"
           "\n"
           "# --- Cartesian k --------------------------------------------------\n"
           "# ASE's reciprocal() omits the 2pi; it is restored so the axes are\n"
           "# in the 1/Angstrom every band-structure figure is drawn in. The\n"
           "# Cartesian grid (not the fractional one) is what gets plotted: the\n"
           "# Brillouin zone of anything but a square lattice is not a square,\n"
           "# and plotting a hexagonal cell over fractional k shears its Dirac\n"
           "# cones into the corners of a rhombus.\n"
           "_recip = 2.0 * np.pi * np.asarray(atoms.cell.reciprocal())\n"
           "_kcart = _kpts @ _recip\n"
           "_kx = _kcart[:, 0].reshape(_n, _n)\n"
           "_ky = _kcart[:, 1].reshape(_n, _n)\n"
           "\n"
           "# --- High-symmetry points -----------------------------------------\n"
           "# Taken from ASE, which recognizes the Bravais lattice and knows the\n"
           "# conventional labels for it. Deriving Gamma/M/K here would mean\n"
           "# reimplementing that recognition and getting a different answer for\n"
           "# the awkward cases (a slightly strained hexagonal cell, a\n"
           "# centred rectangular one).\n"
           "_special = {}\n"
           "try:\n"
           "    _bp = atoms.cell.bandpath(npoints=0)\n"
           "    for _label, _frac in _bp.special_points.items():\n"
           "        _f = np.asarray(_frac, dtype=float)\n"
           "        # Only points that lie in the sampled kz = 0 plane are\n"
           "        # meaningful on this surface; a 3D lattice's A or L sits\n"
           "        # above it and labelling its projection would be a lie.\n"
           "        if abs(float(_f[2])) > 1e-6:\n"
           "            continue\n"
           "        _c = _f @ _recip\n"
           "        _special[str(_label)] = {\n"
           "            'fractional': [float(_v) for _v in _f],\n"
           "            'k_per_A': [float(_c[0]), float(_c[1])],\n"
           "        }\n"
           "except Exception as _exc:\n"
           "    print(f'CALANGO_INFO high-symmetry labels unavailable: "
           "{_exc!r}', flush=True)\n"
           "\n"
           "_bands = []\n"
           "for _s, _b in _keep:\n"
           "    _surface = _energies[_s, :, _b].reshape(_n, _n)\n"
           "    _bands.append({\n"
           "        'band': int(_b),\n"
           "        'spin': int(_s),\n"
           "        'min_eV': float(_surface.min()),\n"
           "        'max_eV': float(_surface.max()),\n"
           "        'energies_eV': [[float(_v) for _v in _row]\n"
           "                        for _row in _surface],\n"
           "    })\n"
           "\n"
           "result = {\n"
           "    'fermi_eV': efermi,\n"
           "    'samples': int(_n),\n"
           "    'spins': int(_energies.shape[0]),\n"
           "    'spin_orbit': "
        << (cfg.spinOrbit ? "True" : "False")
        << ",\n"
           "    'kx_per_A': [[float(_v) for _v in _row] for _row in _kx],\n"
           "    'ky_per_A': [[float(_v) for _v in _row] for _row in _ky],\n"
           "    'reciprocal_2pi_per_A': [[float(_v) for _v in _row]\n"
           "                             for _row in _recip],\n"
           "    'special_points': _special,\n"
           "    'bands': _bands,\n"
           "}\n";

    if (cfg.bzMap) {
        // Clamped to the wizard's own 6..96 rather than the surface grid's
        // 3..512: this generator is reachable headlessly too, and the map
        // exists to be folded — below 6 samples the folded picture is nearly
        // all interpolation, while past 96 the N² extra fixed-density
        // diagonalizations dwarf the run the map was meant to accompany.
        const int bzn = std::clamp(cfg.bzMapSamples, 6, 96);
        out << "\n"
               "# --- Brillouin-zone map -------------------------------------------\n"
               "# A second, independent sampling for the results window's flat\n"
               "# E_n(kx, ky) map view: an N x N Monkhorst-Pack mesh spanning the\n"
               "# primitive 2D reciprocal cell. Deliberately NOT the inclusive grid\n"
               "# above: Monkhorst-Pack tiles the cell with no duplicated seam,\n"
               "# which is what a periodic fold wants. The viewer reduces the tiled\n"
               "# cell to the first Brillouin zone (the Wigner-Seitz cell of the\n"
               "# reciprocal lattice) at render time, so no zone geometry is baked\n"
               "# into the run -- and kz stays 0 for the same reason as above: the\n"
               "# vacuum axis is z.\n"
            << "_bzn = " << bzn << "\n"
            << "_bz_line = (2.0 * np.arange(1, _bzn + 1) - _bzn - 1) / (2.0 * _bzn)\n"
               "_bz_fx, _bz_fy = np.meshgrid(_bz_line, _bz_line, indexing='ij')\n"
               "_bz_kpts = np.zeros((_bzn * _bzn, 3))\n"
               "_bz_kpts[:, 0] = _bz_fx.ravel()\n"
               "_bz_kpts[:, 1] = _bz_fy.ravel()\n"
               "print(f'CALANGO_INFO Brillouin-zone map {_bzn}x{_bzn} '\n"
               "      f'({_bzn * _bzn} k-points) at fixed density', flush=True)\n";
        out << "_bz_calc = calc.fixed_density(kpts=_bz_kpts, symmetry='off',\n";
        if (cfg.totalBands > 0)
            out << "                              nbands=" << cfg.totalBands
                << ",\n";
        out << "                              txt='gpaw_2d_bands.txt')\n";
        if (cfg.spinOrbit) {
            out << "# Same spinor treatment as the surfaces: a map without the\n"
                   "# splitting the surfaces show would contradict them.\n"
                   "_bz_soc = soc_eigenstates(_bz_calc)\n"
                   "_bz_energies = np.asarray(_bz_soc.eigenvalues())  # (nk, nband)\n";
        } else {
            out << "# Spin channels merged and sorted per k-point: the map view\n"
                   "# picks a band by INDEX, so 'band n' must mean exactly one\n"
                   "# thing -- the n-th eigenvalue at that k -- rather than the\n"
                   "# n-th band of whichever spin channel a reader had in mind.\n"
                   "_bz_energies = np.asarray(\n"
                   "    [np.sort(np.concatenate(\n"
                   "        [_bz_calc.get_eigenvalues(kpt=_k, spin=_s)\n"
                   "         for _s in range(_bz_calc.get_number_of_spins())]))\n"
                   "     for _k in range(_bzn * _bzn)])  # (nk, nband)\n";
        }
        out << "# Self-contained for the viewer: the fractional mesh, every band\n"
               "# at every mesh point, and the in-plane reciprocal rows b1, b2\n"
               "# (2pi included, 1/Angstrom) the Wigner-Seitz construction and\n"
               "# the Cartesian placement are built from.\n"
               "result['bz_map'] = {\n"
               "    'n': int(_bzn),\n"
               "    'kpts_frac': [[float(_k[0]), float(_k[1])] for _k in _bz_kpts],\n"
               "    'energies_eV': [[float(_e) for _e in _row]\n"
               "                    for _row in _bz_energies],\n"
               "    'efermi_eV': float(efermi),\n"
               "    'reciprocal_A_inv': [[float(_recip[0][0]), float(_recip[0][1])],\n"
               "                         [float(_recip[1][0]), float(_recip[1][1])]],\n"
               "}\n";
    }

    out << "with open('bands_2d.json', 'w') as _fh:\n"
           "    json.dump(result, _fh)\n"
           "_calango_progress(4, 4)\n"
           "print('CALANGO_RESULT bands_2d=bands_2d.json', flush=True)\n"
           "print('CALANGO_DONE', flush=True)\n";
    return out.str();
}

} // namespace calango::core
