#include "core/TwoDBandsScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <algorithm>
#include <sstream>

namespace calango::core {

std::string generateTwoDBandsScript(const TwoDBandsConfig& cfg)
{
    // Clamped here rather than trusted from the dialog: this generator is also
    // reachable headlessly, and N <= 1 produces a degenerate grid that numpy
    // reshapes without complaint into something the viewer cannot triangulate.
    const int n = std::clamp(cfg.gridSamples, 3, 512);
    const int below = std::max(0, cfg.bandsBelow);
    const int above = std::max(0, cfg.bandsAbove);
    const bool gpaw = cfg.backend == TwoDBandsBackend::Gpaw;

    std::ostringstream out;
    out << "# 2D band surfaces E_n(kx, ky) — generated by Calango\n"
           "#\n"
           "# Restarts a converged density and evaluates the eigenvalues on a\n"
           "# grid covering the two-dimensional Brillouin zone at kz = 0, then\n"
           "# writes them as surfaces over the Cartesian kx-ky plane.\n"
           "import json\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();

    // =====================================================================
    // 1. Bind `atoms` (and, for GPAW, `efermi` too — it comes with the
    //    restart). Every other engine reads the plain staged structure and
    //    determines efermi later, once it has actually run something.
    // =====================================================================
    switch (cfg.backend) {
    case TwoDBandsBackend::Gpaw:
        out << AseScriptGenerator::gpawImports(cfg.gpaw) << "\n"
            << "calc = GPAW(r\"" << cfg.baselineDensityPath
            << "\", txt=\"gpaw_2d_bands.txt\")\n"
               "atoms = calc.get_atoms()\n"
               "efermi = float(calc.get_fermi_level())\n"
               "_calango_progress(1, 4)\n"
               "\n";
        break;

    case TwoDBandsBackend::Vasp:
        out << "# VASP workflow (requires VASP_PP_PATH + ASE_VASP_COMMAND).\n"
               "from ase.calculators.vasp import Vasp\n"
               "import os\n"
               "import shutil\n"
               "\n"
               "atoms = read(\"structure.extxyz\")\n"
               "_calango_progress(1, 4)\n"
               "\n";
        break;

    case TwoDBandsBackend::Espresso:
        // pseudo_dir mirrors AseScriptGenerator.cpp's own emitEspresso()
        // exactly: the configured Preferences path when there is one, the
        // same "EDIT ME" placeholder as before when there is not.
        out << "# Quantum ESPRESSO workflow (pw.x must be installed).\n"
               "# EDIT ME: point pseudopotentials at your SSSP/pslibrary set.\n"
               "from ase.calculators.espresso import Espresso, EspressoProfile\n"
               "\n"
               "profile = EspressoProfile(\n"
               "    command=\"mpirun -np 4 pw.x\",          # EDIT ME\n"
               "    pseudo_dir=\""
            << (cfg.espressoPseudoDir.empty() ? "/path/to/pseudopotentials"
                                              : cfg.espressoPseudoDir)
            << (cfg.espressoPseudoDir.empty() ? "\",  # EDIT ME\n" : "\",\n")
            << ")\n"
               "pseudopotentials = {\n"
               "    # \"Si\": \"Si.pbe-n-rrkjus_psl.1.0.0.UPF\",  # EDIT ME: one entry per element\n"
               "}\n"
               "\n"
               "atoms = read(\"structure.extxyz\")\n"
               "_calango_progress(1, 4)\n"
               "\n";
        break;

    case TwoDBandsBackend::Siesta:
        // SIESTA_PP_PATH mirrors AseScriptGenerator.cpp's own emitSiesta()
        // exactly: set it from the configured Preferences path when there
        // is one; otherwise a real runtime check, not a fabricated path —
        // an invented SIESTA_PP_PATH would fail confusingly deep inside
        // libSiesta rather than with a message naming the actual fix.
        out << "# SIESTA workflow (requires the siesta binary + SIESTA_PP_PATH).\n"
               "from ase.calculators.siesta import Siesta\n"
               "from ase.dft.kpoints import BandPath\n"
               "from ase.units import Ry\n"
               "import os\n"
               "\n";
        if (cfg.siestaPseudoDir.empty()) {
            out << "if not os.environ.get(\"SIESTA_PP_PATH\"):\n"
                   "    raise RuntimeError(\n"
                   "        \"SIESTA_PP_PATH is not set: no pseudopotential \"\n"
                   "        \"directory is configured. Set it in Preferences -> \"\n"
                   "        \"External Files, or export SIESTA_PP_PATH before \"\n"
                   "        \"running this script.\")\n";
        } else {
            out << "os.environ.setdefault(\"SIESTA_PP_PATH\", r\""
                << cfg.siestaPseudoDir << "\")\n";
        }
        out << "\n"
               "atoms = read(\"structure.extxyz\")\n"
               "_calango_progress(1, 4)\n"
               "\n";
        break;
    }

    // =====================================================================
    // 2. Geometry sanity — identical text for every engine, since it only
    //    reads `atoms`, which every branch above has already bound.
    // =====================================================================
    out << R"PY(# --- Geometry sanity ----------------------------------------------
# The kz = 0 plane is the whole Brillouin zone only for a sheet:
# periodic in x and y, vacuum along z. Run this on a bulk crystal
# and the surface is a single cut through a 3D dispersion, which
# looks entirely plausible and means something else.
_pbc = list(atoms.get_pbc())
if not (_pbc[0] and _pbc[1]):
    raise RuntimeError(
        'A 2D band surface needs a structure periodic in x and y; this '
        'one has pbc = ' + str(_pbc) + '. Set the periodicity in Edit '
        'Structure, or use the 1D Electronic Structure module.')
if _pbc[2]:
    print('CALANGO_WARN this structure is periodic along z as well, so '
          'the kz = 0 plane is one cut through a 3D dispersion rather '
          'than the full Brillouin zone. Add vacuum along z for a true '
          '2D band surface.', flush=True)

)PY";

    // =====================================================================
    // 3. The 2D k-grid — engine-agnostic fractional coordinates. Every
    //    branch below hands the SAME `_kpts` array to its own calculator;
    //    only the shape/format each engine's ASE binding wants differs
    //    (handled per engine, not here).
    // =====================================================================
    out << "# --- 2D k-grid ----------------------------------------------------\n"
        << "_n = " << n << "\n"
        << R"PY(# Gamma-centred and INCLUSIVE of both zone edges: -1/2 and +1/2 are
# the same k by periodicity, and sampling both is what closes the
# surface instead of leaving a seam along two sides of the plot.
_frac = np.linspace(-0.5, 0.5, _n)
_fx, _fy = np.meshgrid(_frac, _frac, indexing='ij')
_kpts = np.zeros((_n * _n, 3))
_kpts[:, 0] = _fx.ravel()
_kpts[:, 1] = _fy.ravel()
print(f'CALANGO_INFO 2D Brillouin-zone grid {_n}x{_n} '
      f'({_n * _n} k-points)', flush=True)

)PY";

    // =====================================================================
    // 4. Evaluate the grid. Every branch below ends with `band_calc` bound
    //    to whichever calculator object actually holds the requested
    //    eigenvalues, and `efermi` set — the generic eigenvalue loop right
    //    after this switch reads both, uniformly, regardless of engine.
    // =====================================================================
    switch (cfg.backend) {
    case TwoDBandsBackend::Gpaw:
        // symmetry='off' keeps every grid point. The point symmetry would
        // fold the mesh onto an irreducible wedge, and unfolding it back
        // into a plottable surface is exactly the work this avoids.
        out << "band_calc = calc.fixed_density(kpts=_kpts, symmetry='off',\n";
        if (cfg.totalBands > 0)
            out << "                               nbands=" << cfg.totalBands
                << ",\n";
        out << "                               txt='gpaw_2d_bands.txt')\n"
               "_calango_progress(2, 4)\n"
               "\n";
        break;

    case TwoDBandsBackend::Vasp:
        // Same ICHARG = 11 restart as the 1D Electronic Structure module's
        // VASP baseline branch (see ElectronicScriptGenerator.cpp): the
        // CHGCAR has to be COPIED in, since VASP takes no path option for
        // it and opens 'CHGCAR' in the working directory, full stop.
        //
        // isym=0: unlike a 1D k-PATH (visited once each regardless of
        // symmetry), a uniform 2D grid is exactly the case VASP's own point
        // -group reduction is designed to shrink — left at its default,
        // symmetry-equivalent grid points would silently come back
        // duplicated from a smaller irreducible set rather than each being
        // its own independent diagonalization, folding the surface onto a
        // wedge the same way an un-set symmetry='off' would in GPAW.
        out << R"PY(# Non-self-consistent bands on a converged density.
#
# ICHARG = 11 reads CHGCAR and never updates it, so no SCF runs
# here. VASP opens 'CHGCAR' in the working directory and takes no
# path for it, hence the copy.
)PY"
            << "_baseline = r\"" << cfg.baselineDensityPath << "\"\n"
            << R"PY(if not os.path.exists(_baseline):
    raise RuntimeError(
        f'The baseline charge density is gone: {_baseline}\n'
        'ICHARG = 11 cannot converge one of its own — re-run the '
        'Single-point Calculation that produced it.')
if os.path.abspath(_baseline) != os.path.abspath('CHGCAR'):
    shutil.copyfile(_baseline, 'CHGCAR')
print(f'CALANGO_INFO reusing the charge density from {_baseline}',
      flush=True)
_calango_progress(2, 4)

)PY"
            << "band_calc = Vasp(xc=\"PBE\", encut=" << cfg.ecutEv
            << ", icharg=11,\n"
               "                 isym=0, ismear=0, sigma=0.05,\n"
               "                 kpts=_kpts, reciprocal=True,\n";
        if (cfg.totalBands > 0)
            out << "                 nbands=" << cfg.totalBands << ",\n";
        out << "                 directory=\".\")\n"
               "atoms.calc = band_calc\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_progress(3, 4)\n"
               "\n";
        break;

    case TwoDBandsBackend::Espresso: {
        // Self-contained: SCF first (no portable single-file restart point
        // this application establishes for QE — see the header doc), then a
        // non-self-consistent "bands" pass evaluates the eigenvalues on the
        // 2D grid at fixed density.
        //
        // K_POINTS crystal wants an EXPLICIT Nx4 array (kx, ky, kz, weight)
        // — verified against ase.io.espresso.write_espresso_in, whose
        // K_POINTS writer only takes the 'crystal' branch for an (N, 4)
        // ndarray; an (N, 3) array falls through to the Monkhorst-Pack
        // 'automatic' branch instead and is silently misinterpreted as a
        // 3-integer grid shape. The weight column is never consulted for a
        // fixed-density eigenvalue read, so it is filled with 1.0 throughout.
        //
        // nosym / noinv: an explicit 'crystal' k-list is not folded by
        // point-group symmetry the way 'automatic' (Monkhorst-Pack) is — pw.x
        // reduces only the automatic-grid case — so this has no effect on
        // this particular K_POINTS mode. Set anyway, and stated as a
        // deliberate choice rather than left to that undocumented behaviour:
        // the same explicit-not-reduced property is what every other engine
        // here needs an explicit flag (symmetry='off', isym=0) to get.
        out << "_kgrid = " << cfg.scfKpts << "\n"
            << "_system = {\"ecutwfc\": " << cfg.ecutEv / 13.605693122994
            << "}\n";
        if (cfg.totalBands > 0)
            out << "_system[\"nbnd\"] = " << cfg.totalBands << "\n";
        // kz = 1: the geometry check above already guarantees z is the
        // vacuum axis, so a uniform (kgrid, kgrid, kgrid) SCF mesh (the 1D
        // Electronic Structure module's own choice, where periodicity is
        // not assumed) would sample kgrid k-points along a direction the
        // bands cannot disperse in, kgrid-fold more expensively for zero
        // physical benefit.
        out << "scf = Espresso(profile=profile,\n"
               "               pseudopotentials=pseudopotentials,\n"
               "               input_data={\"control\": {\"calculation\": \"scf\"},\n"
               "                           \"system\": _system},\n"
               "               kpts=(_kgrid, _kgrid, 1))\n"
               "atoms.calc = scf\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_progress(2, 4)\n"
               "\n"
               "_kpts4 = np.zeros((len(_kpts), 4))\n"
               "_kpts4[:, :3] = _kpts\n"
               "_kpts4[:, 3] = 1.0\n"
               "band_calc = Espresso(\n"
               "    profile=profile,\n"
               "    pseudopotentials=pseudopotentials,\n"
               "    input_data={\"control\": {\"calculation\": \"bands\",\n"
               "                             \"restart_mode\": \"restart\"},\n"
               "                \"system\": dict(_system, nosym=True, noinv=True)},\n"
               "    kpts=_kpts4)\n"
               "atoms.calc = band_calc\n"
               // A "bands" calculation runs pw.x and populates every
               // eigenvalue, but never reports a total energy — QE has
               // nothing self-consistent left to converge, so there is none
               // to report. get_potential_energy() is still what TRIGGERS
               // the run; it is called for that reason alone, and the one
               // exception it is known to raise afterward (found by
               // actually running this against real pw.x — every earlier
               // static read of this pattern missed it) is caught by name,
               // not masked with a bare except that would also swallow a
               // genuine pw.x failure.
               "from ase.calculators.calculator import "
               "PropertyNotImplementedError as _PNI\n"
               "try:\n"
               "    atoms.get_potential_energy()\n"
               "except _PNI:\n"
               "    pass\n"
               "_calango_progress(3, 4)\n"
               "\n";
        break;
    }

    case TwoDBandsBackend::Siesta:
        // Self-contained, mirroring the 1D Electronic Structure module's
        // SIESTA branch exactly (same mesh_cutoff/energy_shift, same
        // two-calculator SCF-then-restart shape) — including its fix: the
        // 2D grid is handed through `bandpath=`, never `kpts=`. SIESTA's own
        // `kpts=` is the SCF Monkhorst-Pack grid DIMENSIONS ONLY (it indexes
        // into whatever is passed as a 3-tuple); an explicit k-point set —
        // a 1D BandPath or, here, a flattened 2D grid — is the separate
        // `bandpath=` keyword, which writes %block BandPoints from
        // `path.kpts` verbatim, unreduced. A bare BandPath built directly
        // from the grid array (no path string, no special points — just the
        // points themselves) is exactly what that block wants; verified
        // against a real Siesta(bandpath=...).write_input() call.
        out << "_kgrid = " << cfg.scfKpts << "\n"
            << R"PY(# kz = 1: the geometry check above already guarantees z is the
# vacuum axis, so a uniform SCF mesh would sample kgrid k-points along a
# direction the bands cannot disperse in, kgrid-fold more expensively for
# zero physical benefit.
scf = Siesta(xc="PBE", mesh_cutoff=200 * Ry, energy_shift=0.01 * Ry,
             kpts=[_kgrid, _kgrid, 1])
atoms.calc = scf
atoms.get_potential_energy()
efermi = float(atoms.calc.get_fermi_level())
_calango_progress(2, 4)

# %block BandPoints, unreduced, from a BandPath built directly from the
# grid — DM.UseSaveDM is set automatically once `bandpath=` is given,
# so this restarts from the SCF density matrix rather than solving fresh.
_grid_path = BandPath(atoms.cell, kpts=_kpts)
band_calc = Siesta(xc="PBE", mesh_cutoff=200 * Ry, energy_shift=0.01 * Ry,
                   bandpath=_grid_path)
atoms.calc = band_calc
atoms.get_potential_energy()
_calango_progress(3, 4)

)PY";
        break;
    }

    // =====================================================================
    // 5. Spin-orbit coupling (GPAW only), SIESTA's own band_structure()
    //    read, or the generic eigenvalue read everyone else shares.
    // =====================================================================
    if (gpaw && cfg.spinOrbit) {
        out << "# --- Spin-orbit coupling -------------------------------------\n"
               "# Re-diagonalizes the converged states in the spinor basis. On a\n"
               "# 2D surface plot this is usually the point: Rashba splitting and\n"
               "# the gap opened at a band touching are invisible without it.\n"
               "from gpaw.spinorbit import soc_eigenstates\n"
               "_soc = soc_eigenstates(band_calc)\n"
               "# (nk, nband) -> one spin channel of doubled, spin-mixed bands.\n"
               "_energies = np.asarray(_soc.eigenvalues())[np.newaxis]\n"
               "efermi = float(_soc.fermi_level)\n"
               "print(f'CALANGO_INFO spin-orbit coupling applied, "
               "E_F = {efermi:.4f} eV', flush=True)\n";
    } else if (cfg.backend == TwoDBandsBackend::Siesta) {
        // Real bug, found by actually running this against a real siesta
        // binary and real graphene pseudopotentials: ASE's Siesta
        // .get_eigenvalues()/.results['eigenvalues'] is populated from the
        // ORDINARY (SCF) eigenvalue output, not from the %block BandPoints
        // pass — even though band_calc IS the calculator that ran with
        // bandpath= set. Reading it the same generic way every other engine
        // here supports raised "IndexError: index 1 is out of bounds for
        // axis 1 with size 1": only the SCF's own (tiny) k-point count was
        // actually there. Siesta.band_structure() overrides the generic
        // Calculator method and returns self.results['bandstructure'] —
        // built from the %block BandPoints pass specifically — which is
        // the one that actually holds all _n * _n points; confirmed by
        // printing its .energies.shape against a real run.
        out << "_bs = band_calc.band_structure()\n"
               "_energies = np.asarray(_bs.energies)  # (nspin, nk, nband)\n";
    } else {
        // Generic ASE calculator API (get_number_of_spins / get_eigenvalues),
        // implemented by GPAW (without SOC), VASP and Quantum ESPRESSO alike
        // — verified for real against all three — which is what lets this
        // one block serve them without a second copy.
        out << "_nspin = band_calc.get_number_of_spins()\n"
               "_nk = len(_kpts)\n"
               "_energies = np.asarray(\n"
               "    [[band_calc.get_eigenvalues(kpt=_k, spin=_s)\n"
               "      for _k in range(_nk)] for _s in range(_nspin)],\n"
               "    dtype=float)  # (nspin, nk, nband)\n";
    }

    out << "_calango_progress(4, 4)\n"
           "\n"
           "# --- Band selection -----------------------------------------------\n"
           "# Every band that crosses E_F is kept whatever the counts say: those\n"
           "# ARE the Fermi surface, and silently dropping one because a count\n"
           "# ran out would remove the feature the plot exists to show.\n"
        << "_below, _above = " << below << ", " << above << "\n"
        << R"PY(_keep = []
for _s in range(_energies.shape[0]):
    _lo = _energies[_s].min(axis=0)  # per band, over all k
    _hi = _energies[_s].max(axis=0)
    _crossing = [int(_b) for _b in range(_energies.shape[2])
                 if _lo[_b] <= efermi <= _hi[_b]]
    _under = [int(_b) for _b in range(_energies.shape[2])
              if _hi[_b] < efermi]
    _over = [int(_b) for _b in range(_energies.shape[2])
             if _lo[_b] > efermi]
    _sel = set(_crossing)
    if _below:
        _sel.update(_under[-_below:])   # the highest below E_F
    if _above:
        _sel.update(_over[:_above])     # the lowest above E_F
    for _b in sorted(_sel):
        _keep.append((_s, int(_b)))
if not _keep:
    raise RuntimeError('No bands fell in the requested window around the '
                       'Fermi level — raise the band counts.')

# --- Cartesian k --------------------------------------------------
# ASE's reciprocal() omits the 2pi; it is restored so the axes are
# in the 1/Angstrom every band-structure figure is drawn in. The
# Cartesian grid (not the fractional one) is what gets plotted: the
# Brillouin zone of anything but a square lattice is not a square,
# and plotting a hexagonal cell over fractional k shears its Dirac
# cones into the corners of a rhombus.
_recip = 2.0 * np.pi * np.asarray(atoms.cell.reciprocal())
_kcart = _kpts @ _recip
_kx = _kcart[:, 0].reshape(_n, _n)
_ky = _kcart[:, 1].reshape(_n, _n)

# --- High-symmetry points -----------------------------------------
# Taken from ASE, which recognizes the Bravais lattice and knows the
# conventional labels for it. Deriving Gamma/M/K here would mean
# reimplementing that recognition and getting a different answer for
# the awkward cases (a slightly strained hexagonal cell, a
# centred rectangular one).
_special = {}
try:
    _bp = atoms.cell.bandpath(npoints=0)
    for _label, _frac in _bp.special_points.items():
        _f = np.asarray(_frac, dtype=float)
        # Only points that lie in the sampled kz = 0 plane are
        # meaningful on this surface; a 3D lattice's A or L sits
        # above it and labelling its projection would be a lie.
        if abs(float(_f[2])) > 1e-6:
            continue
        _c = _f @ _recip
        _special[str(_label)] = {
            'fractional': [float(_v) for _v in _f],
            'k_per_A': [float(_c[0]), float(_c[1])],
        }
except Exception as _exc:
    print(f'CALANGO_INFO high-symmetry labels unavailable: {_exc!r}', flush=True)

_bands = []
for _s, _b in _keep:
    _surface = _energies[_s, :, _b].reshape(_n, _n)
    _bands.append({
        'band': int(_b),
        'spin': int(_s),
        'min_eV': float(_surface.min()),
        'max_eV': float(_surface.max()),
        'energies_eV': [[float(_v) for _v in _row]
                        for _row in _surface],
    })

)PY"
        << "result = {\n"
           "    'fermi_eV': efermi,\n"
           "    'samples': int(_n),\n"
           "    'spins': int(_energies.shape[0]),\n"
           "    'spin_orbit': "
        << ((gpaw && cfg.spinOrbit) ? "True" : "False")
        << ",\n"
           "    'kx_per_A': [[float(_v) for _v in _row] for _row in _kx],\n"
           "    'ky_per_A': [[float(_v) for _v in _row] for _row in _ky],\n"
           "    'reciprocal_2pi_per_A': [[float(_v) for _v in _row]\n"
           "                             for _row in _recip],\n"
           "    'special_points': _special,\n"
           "    'bands': _bands,\n"
           "}\n";

    if (gpaw && cfg.bzMap) {
        // Clamped to the wizard's own 6..96 rather than the surface grid's
        // 3..512: this generator is reachable headlessly too, and the map
        // exists to be folded — below 6 samples the folded picture is nearly
        // all interpolation, while past 96 the N² extra fixed-density
        // diagonalizations dwarf the run the map was meant to accompany.
        const int bzn = std::clamp(cfg.bzMapSamples, 6, 96);
        out << "\n"
               "# --- Brillouin-zone map -------------------------------------------\n"
               "# A second, independent sampling for the results window's flat\n"
               "# E_n(kx, ky) map view: an N x N Monkhorst-Pack mesh spanning the\n"
               "# primitive 2D reciprocal cell. Deliberately NOT the inclusive grid\n"
               "# above: Monkhorst-Pack tiles the cell with no duplicated seam,\n"
               "# which is what a periodic fold wants. The viewer reduces the tiled\n"
               "# cell to the first Brillouin zone (the Wigner-Seitz cell of the\n"
               "# reciprocal lattice) at render time, so no zone geometry is baked\n"
               "# into the run -- and kz stays 0 for the same reason as above: the\n"
               "# vacuum axis is z.\n"
            << "_bzn = " << bzn << "\n"
            << "_bz_line = (2.0 * np.arange(1, _bzn + 1) - _bzn - 1) / (2.0 * _bzn)\n"
               "_bz_fx, _bz_fy = np.meshgrid(_bz_line, _bz_line, indexing='ij')\n"
               "_bz_kpts = np.zeros((_bzn * _bzn, 3))\n"
               "_bz_kpts[:, 0] = _bz_fx.ravel()\n"
               "_bz_kpts[:, 1] = _bz_fy.ravel()\n"
               "print(f'CALANGO_INFO Brillouin-zone map {_bzn}x{_bzn} '\n"
               "      f'({_bzn * _bzn} k-points) at fixed density', flush=True)\n";
        out << "_bz_calc = calc.fixed_density(kpts=_bz_kpts, symmetry='off',\n";
        if (cfg.totalBands > 0)
            out << "                              nbands=" << cfg.totalBands
                << ",\n";
        out << "                              txt='gpaw_2d_bands.txt')\n";
        if (cfg.spinOrbit) {
            out << "# Same spinor treatment as the surfaces: a map without the\n"
                   "# splitting the surfaces show would contradict them.\n"
                   "_bz_soc = soc_eigenstates(_bz_calc)\n"
                   "_bz_energies = np.asarray(_bz_soc.eigenvalues())  # (nk, nband)\n";
        } else {
            out << "# Spin channels merged and sorted per k-point: the map view\n"
                   "# picks a band by INDEX, so 'band n' must mean exactly one\n"
                   "# thing -- the n-th eigenvalue at that k -- rather than the\n"
                   "# n-th band of whichever spin channel a reader had in mind.\n"
                   "_bz_energies = np.asarray(\n"
                   "    [np.sort(np.concatenate(\n"
                   "        [_bz_calc.get_eigenvalues(kpt=_k, spin=_s)\n"
                   "         for _s in range(_bz_calc.get_number_of_spins())]))\n"
                   "     for _k in range(_bzn * _bzn)])  # (nk, nband)\n";
        }
        out << "# Self-contained for the viewer: the fractional mesh, every band\n"
               "# at every mesh point, and the in-plane reciprocal rows b1, b2\n"
               "# (2pi included, 1/Angstrom) the Wigner-Seitz construction and\n"
               "# the Cartesian placement are built from.\n"
               "result['bz_map'] = {\n"
               "    'n': int(_bzn),\n"
               "    'kpts_frac': [[float(_k[0]), float(_k[1])] for _k in _bz_kpts],\n"
               "    'energies_eV': [[float(_e) for _e in _row]\n"
               "                    for _row in _bz_energies],\n"
               "    'efermi_eV': float(efermi),\n"
               "    'reciprocal_A_inv': [[float(_recip[0][0]), float(_recip[0][1])],\n"
               "                         [float(_recip[1][0]), float(_recip[1][1])]],\n"
               "}\n";
    }

    out << "with open('bands_2d.json', 'w') as _fh:\n"
           "    json.dump(result, _fh)\n"
           "print('CALANGO_RESULT bands_2d=bands_2d.json', flush=True)\n"
           "print('CALANGO_DONE', flush=True)\n";
    return out.str();
}

} // namespace calango::core
