#include "core/UnfoldingScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

namespace {

/// The projection itself. Written once here rather than per backend: only the
/// calculator construction differs, and the Popescu-Zunger algebra is the
/// same whatever produced the wavefunctions.
constexpr const char* kProjection = R"PY(
def unfold_weights(calc, primitive_cell, matrix, k_primitive, k_supercell_index):
    """Popescu-Zunger spectral weights P_Km(k) for one primitive wavevector.

    For each supercell band m at the folded wavevector K, sum the squared
    plane-wave coefficients whose supercell G-vector reduces to a PRIMITIVE
    reciprocal lattice vector when expressed in the primitive basis:

        P_Km(k) = sum_{G : G in G_prim} |C_{Km}(G)|^2

    Only those components carry primitive Bloch character at k; the rest of
    the expansion belongs to the other k that fold onto the same K. The sum
    is exactly 1 for a pristine supercell (every component is primitive) and
    drops toward 0 for states created by the defect.
    """
    import numpy as np

    weights = []
    # Supercell reciprocal lattice vectors of the plane-wave basis at this K,
    # in units of the supercell reciprocal vectors (integers).
    wfs = calc.wfs
    kpt_rank, kpt_local = wfs.kd.get_rank_and_index(k_supercell_index)
    gd_indices = wfs.pd.get_reciprocal_vectors(q=kpt_local, add_q=False)
    # Express each G in the PRIMITIVE reciprocal basis: G_prim = G_super . M^T
    # (the same transpose relationship the C++ fold uses). A component is a
    # primitive reciprocal vector exactly when all three coordinates are
    # integers to within tolerance.
    icell_super = calc.atoms.cell.reciprocal()      # rows: b_super / 2pi
    icell_prim = primitive_cell.reciprocal()
    # Cartesian G -> primitive fractional.
    g_cartesian = gd_indices / (2.0 * np.pi)
    g_primitive = g_cartesian @ np.linalg.inv(icell_prim)
    # The primitive k we are projecting onto shifts the acceptance test.
    residual = g_primitive - np.round(g_primitive - k_primitive) - k_primitive
    primitive_mask = np.all(np.abs(residual) < 1e-4, axis=1)

    for band in range(wfs.bd.nbands):
        coefficients = wfs.kpt_u[kpt_local].psit_nG[band]
        total = np.vdot(coefficients, coefficients).real
        if total <= 0.0:
            weights.append(0.0)
            continue
        selected = coefficients[primitive_mask]
        weights.append(float(np.vdot(selected, selected).real / total))
    return weights
)PY";

} // namespace

std::string generateUnfoldingScript(const UnfoldingConfig& c)
{
    std::ostringstream out;
    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — effective band structure (Popescu-Zunger band unfolding).\n"
           "#\n"
           "# Converges the supercell, then projects each supercell eigenstate\n"
           "# back onto the primitive Bloch basis along the primitive cell's\n"
           "# high-symmetry path, writing effective_bands.json for the\n"
           "# Results heatmap. Reference: Popescu & Zunger, Phys. Rev. B 85,\n"
           "# 085201 (2012).\n"
           "# This is a plain ASE script: edit it freely or run it standalone.\n"
           "\n"
           "import json\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "atoms = read(r\"" << c.supercellFile << "\")\n"
        << "primitive = read(r\"" << c.primitiveFile << "\")\n"
           "\n"
           "# supercell = M . primitive, as deduced by the wizard.\n"
           "M = np.array([\n";
    for (int i = 0; i < 3; ++i) {
        out << "    [" << c.matrix.m[i][0] << ", " << c.matrix.m[i][1] << ", "
            << c.matrix.m[i][2] << "],\n";
    }
    out << "], dtype=int)\n"
           "\n"
           "# Commensurability guard: unfolding is only defined when the\n"
           "# supercell really is an integer multiple of the primitive cell.\n"
           "#\n"
           "# Measured RELATIVE to the supercell's own size. The absolute\n"
           "# residual this used to compare is a tight bound on a 4 Ang cell\n"
           "# and a meaningless one on a 40 Ang slab.\n"
           "residual = np.abs(atoms.cell[:] - M @ primitive.cell[:]).max()\n"
           "_scale = float(np.abs(atoms.cell[:]).max()) or 1.0\n"
        << "if residual / _scale > " << c.commensurateTolerance
        << ":\n"
           "    raise RuntimeError(\n"
           "        f\"Supercell and primitive cell are not commensurate \"\n"
           "        f\"(residual {residual:.4f} Ang, {100 * residual / _scale:.2f}% \"\n"
           "        f\"of the cell). Check the mapping matrix, raise the \"\n"
           "        f\"tolerance, or tick 'Force commensurability' — a relaxed \"\n"
           "        f\"supercell needs the last of those.\")\n"
           "if residual > 1e-9:\n"
           "    print(f\"CALANGO_WARN the cells are commensurate only to \"\n"
           "          f\"{100 * residual / _scale:.2f}%; the projection assumes \"\n"
           "          f\"an exact integer relation\", flush=True)\n"
           "print(f\"CALANGO_INFO primitive_cells={int(round(abs(np.linalg.det(M))))}\",\n"
           "      flush=True)\n"
           "\n"
        << "energy_min = " << c.spectral.energyMin << "\n"
        << "energy_max = " << c.spectral.energyMax << "\n"
        << "energy_bins = " << c.spectral.energyBins << "\n"
        << "sigma = " << c.spectral.sigma << "\n"
        << "weight_threshold = " << c.spectral.weightThreshold << "\n"
        << "points_per_segment = " << c.pointsPerSegment << "\n"
        << "kpath_string = "
        << (c.kpath.empty() ? std::string("None")
                            : "\"" + c.kpath + "\"")
        << "\n"
           "\n"
           "# The path lives on the PRIMITIVE lattice — that is the zone the\n"
           "# effective band structure is drawn in.\n"
           "band_path = primitive.cell.bandpath(\n"
           "    kpath_string, npoints=None,\n"
           "    density=None) if kpath_string else primitive.cell.bandpath()\n"
           "kpts_primitive = band_path.kpts\n"
           "print(f\"CALANGO_INFO kpoints={len(kpts_primitive)}\", flush=True)\n"
           "\n"
           "# Each primitive k folds onto a supercell K: K_frac = M^T . k_frac,\n"
           "# reduced into the first zone. The supercell SCF only needs those.\n"
           "folded = (kpts_primitive @ M.T)\n"
           "folded -= np.round(folded)\n"
           "\n";

    switch (c.backend) {
    case UnfoldingBackend::Gpaw:
        out << "# GPAW in plane-wave mode: its wavefunction object exposes the\n"
               "# expansion coefficients the projection needs. FD and LCAO do\n"
               "# not, so PW is required here regardless of the Stage-3 choice.\n"
            << AseScriptGenerator::gpawImports(c.calculator)
            << "\n"
               "atoms.calc = GPAW(\n"
            << AseScriptGenerator::gpawKeywordArguments(c.calculator, "    ")
            << "    txt=\"unfold_scf.txt\",\n"
               ")\n"
               "atoms.get_potential_energy()\n"
               "efermi = float(atoms.calc.get_fermi_level())\n"
               "_calango_progress(1, 3)\n"
               "\n"
               "# Non-self-consistent pass at the folded wavevectors.\n"
               "band_calc = atoms.calc.fixed_density(\n"
               "    kpts=folded, symmetry=\"off\", txt=\"unfold_bands.txt\")\n"
               "_calango_progress(2, 3)\n"
            << kProjection
            << "\n"
               "columns = []\n"
               "for index, k in enumerate(kpts_primitive):\n"
               "    energies = band_calc.get_eigenvalues(kpt=index, spin=0)\n"
               "    weights = unfold_weights(band_calc, primitive.cell, M, k, index)\n"
               "    columns.append({\n"
               "        \"path_coordinate\": float(band_path.get_linear_kpoint_axis()[0][index]),\n"
               "        \"energies\": [float(e) for e in energies],\n"
               "        \"weights\": [float(w) for w in weights],\n"
               "    })\n"
               "    _calango_progress(2 + index / max(1, len(kpts_primitive)), 3)\n";
        break;
    case UnfoldingBackend::Espresso:
    case UnfoldingBackend::Siesta:
        out << "# EDIT ME: "
            << (c.backend == UnfoldingBackend::Espresso ? "Quantum ESPRESSO"
                                                        : "SIESTA")
            << " does not expose plane-wave\n"
               "# coefficients through its ASE calculator, so the projection\n"
               "# has to read the code's own wavefunction files. Converge the\n"
               "# supercell here, then fill in unfold_weights() against that\n"
               "# output (pw.x writes .save/wfc*.dat; SIESTA writes .WFSX).\n"
               "raise NotImplementedError(\n"
               "    \"Unfolding for this backend needs its wavefunction reader; \"\n"
               "    \"use GPAW, or complete this hook.\")\n"
               "\n"
               "columns = []\n"
               "efermi = 0.0\n";
        break;
    }

    out << "\n"
           "labels_x, labels = band_path.get_linear_kpoint_axis()[1:3]\n"
           "summary = {\n"
           "    \"efermi\": efermi,\n"
           "    \"special_x\": [float(x) for x in labels_x],\n"
           "    \"special_labels\": [str(l) for l in labels],\n"
           "    \"energy_min\": energy_min,\n"
           "    \"energy_max\": energy_max,\n"
           "    \"energy_bins\": energy_bins,\n"
           "    \"sigma\": sigma,\n"
           "    \"weight_threshold\": weight_threshold,\n"
           "    \"columns\": columns,\n"
           "}\n"
           "with open(\"effective_bands.json\", \"w\") as handle:\n"
           "    json.dump(summary, handle)\n"
           "print(\"CALANGO_INFO wrote effective_bands.json\", flush=True)\n"
           "_calango_progress(3, 3)\n"
           "\n"
           "print(f\"CALANGO_RESULT kpoints={len(columns)} efermi_eV={efermi:.6f}\",\n"
           "      flush=True)\n"
           "print(\"CALANGO_DONE\", flush=True)\n";
    return out.str();
}

} // namespace calango::core
