#include "core/WannierScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>
#include <string>

namespace calango::core {

namespace {

/// Ground-state acquisition. Both branches leave `calc` (a calculator holding
/// the Bloch wavefunctions) and `atoms` defined, and log progress 1..2.
///
/// The localization runs through ASE's Wannier, which needs the full
/// (unsymmetrized) Brillouin zone, so the fresh GPAW SCF forces `symmetry='off'`
/// and writes `wannier.gpw`. The GPAW knobs come from the wizard's Calculator
/// Settings via the shared helpers. A non-GPAW engine still runs its own ground
/// state (its Conda env is bound per engine from Preferences); the localization
/// below is guarded and raises a clear error if that calculator can not feed
/// ase.dft.wannier.
std::string groundState(const WannierConfig& cfg)
{
    std::ostringstream out;

    if (!cfg.baselineDir.empty()) {
        out << "_base = r\"" << cfg.baselineDir << "\"\n"
               "_gpw = sorted(glob.glob(os.path.join(_base, '*.gpw')))\n"
               "if not _gpw:\n"
               "    raise RuntimeError('No GPAW wavefunction (.gpw) found in '\n"
               "                       + _base + '. The MLWF localization needs '\n"
               "                       'the Bloch wavefunctions — re-run the '\n"
               "                       'single-point with '\n"
               "                       \"calc.write('single_point.gpw', \"\n"
               "                       \"mode='all').\")\n"
               "from gpaw import GPAW\n"
               "calc = GPAW(_gpw[0], txt='gpaw_wannier.txt')\n"
               "atoms = calc.get_atoms()\n"
               "_log.progress(1, 3)\n";
        return out.str();
    }

    out << "atoms = read('structure.extxyz')\n"
           "_log.progress(1, 3)\n";

    if (cfg.calculator.calculator == CalculatorKind::Gpaw) {
        out << AseScriptGenerator::gpawImports(cfg.calculator)
            << "# symmetry='off' — ASE's Wannier requires the full "
               "(unsymmetrized)\n"
               "# Brillouin zone; it raises otherwise.\n"
               "calc = GPAW(\n"
            << AseScriptGenerator::gpawKeywordArguments(cfg.calculator, "    ")
            << "    symmetry='off',\n"
               "    txt='gpaw.txt',\n"
               ")\n"
               "atoms.calc = calc\n"
               "atoms.get_potential_energy()\n"
               "calc.write('wannier.gpw', mode='all')\n"
               "_log.progress(2, 3)\n";
    } else {
        out << "# Ground state via the selected engine ("
            << toString(cfg.calculator.calculator) << ").\n"
            << AseScriptGenerator::calculatorSnippet(cfg.calculator)
            << "atoms.get_potential_energy()\n"
               "_log.progress(2, 3)\n";
    }
    return out.str();
}

} // namespace

std::string generateWannierScript(const WannierConfig& cfg)
{
    const std::string preamble =
        "# Maximally Localized Wannier Functions (MLWF) — generated by Calango\n"
        "import json\n"
        "import os\n"
        "import glob\n"
        "import numpy as np\n"
        "from ase.io import read\n"
        "from calango_log import CalangoLog\n"
        "_log = CalangoLog()\n";

    const int nWannier = cfg.nWannier > 0 ? cfg.nWannier : 4;

    // Map the (untranslated) projection key onto ASE's `initialwannier` arg.
    // The atomic sets fall back to 'orbitals', from which ASE derives the
    // projections; 'bloch' / 'random' pass straight through.
    const std::string init = (cfg.initialWannier == "bloch"
                              || cfg.initialWannier == "random")
                                 ? cfg.initialWannier
                                 : std::string("orbitals");

    // Marzari-Vanderbilt localization via ASE. Guard the import so a missing
    // ase.dft.wannier surfaces a clear error rather than a bare ImportError.
    std::ostringstream computeStream;
    computeStream
        << "try:\n"
           "    from ase.dft.wannier import Wannier\n"
           "except Exception as _e:\n"
           "    raise RuntimeError('Maximally Localized Wannier Functions '\n"
           "                       'require ase.dft.wannier, which is not '\n"
           "                       'available in this ASE install: ' + repr(_e))\n"
        << "nwannier = " << nWannier << "\n"
        << "# initialwannier seeds the trial projections (atomic orbitals give\n"
           "# good initial overlaps + centre estimates).\n"
           "wan = Wannier(nwannier=nwannier, calc=calc,\n"
        << "              initialwannier='" << init << "')\n"
        << "# Iterative Marzari-Vanderbilt minimization (Omega = Omega_I +\n"
           "# Omega_tilde_D). Repeat localize() until the spread functional\n"
           "# stops decreasing, so convergence of Omega is guaranteed rather\n"
           "# than relying on a single fixed-iteration call.\n"
           "_prev = None\n"
           "for _it in range(50):\n"
           "    wan.localize(step=0.25, tolerance=1e-6)\n"
           "    _val = float(wan.get_functional_value())\n"
           "    if _prev is not None and abs(_val - _prev) < 1e-6:\n"
           "        break\n"
           "    _prev = _val\n"
           "_log.progress(3, 3)\n";

    // Evaluation. Centres are in Å; per-orbital spreads use get_spreads() (Å²)
    // with get_radii()² as a fallback; every optional API is guarded so version
    // drift degrades gracefully.
    const std::string evaluate =
        "centers = np.asarray(wan.get_centers(), dtype=float)\n"
        "try:\n"
        "    spreads = [float(s) for s in np.asarray(wan.get_spreads(),\n"
        "                                            dtype=float)]\n"
        "except Exception:\n"
        "    try:\n"
        "        _radii = np.asarray(wan.get_radii(), dtype=float)\n"
        "        spreads = [float(r * r) for r in _radii]\n"
        "    except Exception:\n"
        "        spreads = [float('nan')] * nwannier\n"
        "total_spread = float(np.nansum(spreads))\n"
        "cubes = []\n"
        "for _i in range(nwannier):\n"
        "    _fn = 'wannier_%d.cube' % _i\n"
        "    wan.write_cube(_i, _fn)\n"
        "    cubes.append(_fn)\n";

    // Write wannier.json and emit the result marker the controller watches for.
    const std::string tail =
        "result = {\n"
        "    'total_spread': total_spread,\n"
        "    'centers': [[float(v) for v in row] for row in centers],\n"
        "    'spreads': [float(s) for s in spreads],\n"
        "    'cubes': cubes,\n"
        "}\n"
        "json.dump(result, open('wannier.json', 'w'), indent=2)\n"
        "print('CALANGO_RESULT wannier=wannier.json', flush=True)\n";

    return preamble + groundState(cfg) + computeStream.str() + evaluate + tail;
}

} // namespace calango::core
