#include "core/WannierScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>
#include <string>

namespace calango::core {

namespace {

/// Ground-state acquisition. Both branches leave `calc` (a calculator holding
/// the Bloch wavefunctions) and `atoms` defined, and log progress 1..2.
///
/// The localization runs through ASE's Wannier, which needs the full
/// (unsymmetrized) Brillouin zone, so the fresh GPAW SCF forces `symmetry='off'`
/// and writes `wannier.gpw`. The GPAW knobs come from the wizard's Calculator
/// Settings via the shared helpers. A non-GPAW engine still runs its own ground
/// state (its Conda env is bound per engine from Preferences); the localization
/// below is guarded and raises a clear error if that calculator can not feed
/// ase.dft.wannier.
std::string groundState(const WannierConfig& cfg)
{
    std::ostringstream out;

    if (!cfg.baselineDir.empty()) {
        out << "_base = r\"" << cfg.baselineDir << "\"\n"
               "_gpw = sorted(glob.glob(os.path.join(_base, '*.gpw')))\n"
               "if not _gpw:\n"
               "    raise RuntimeError('No GPAW wavefunction (.gpw) found in '\n"
               "                       + _base + '. The MLWF localization needs '\n"
               "                       'the Bloch wavefunctions — re-run the '\n"
               "                       'single-point with '\n"
               "                       \"calc.write('single_point.gpw', \"\n"
               "                       \"mode='all').\")\n"
               "from gpaw import GPAW\n"
               "# Absolute, and recorded in wannier.json below. This run reads\n"
               "# the wavefunctions from ANOTHER job's directory and writes no\n"
               "# .gpw of its own, so a later Wannier interpolation that looked\n"
               "# for one beside wannier.json found nothing and died.\n"
               "_gpw_path = os.path.abspath(_gpw[0])\n"
               "calc = GPAW(_gpw_path, txt='gpaw_wannier.txt')\n"
               "atoms = calc.get_atoms()\n"
               "_log.progress(1, 3)\n";
        return out.str();
    }

    out << "atoms = read('structure.extxyz')\n"
           "_gpw_path = None\n"
           "_log.progress(1, 3)\n";

    if (cfg.calculator.calculator == CalculatorKind::Gpaw) {
        // ASE's Wannier requires the full (unsymmetrized) Brillouin zone, so
        // force symmetry="off" through the shared GPAW keyword emitter (a
        // single source of truth — no hand-written duplicate keyword).
        CalculatorConfig scf = cfg.calculator;
        scf.gpawSymmetryOff = true;
        out << AseScriptGenerator::gpawImports(scf)
            << "# symmetry=\"off\" — ASE's Wannier needs the full "
               "(unsymmetrized)\n"
               "# Brillouin zone; it raises otherwise.\n"
               "calc = GPAW(\n"
            << AseScriptGenerator::gpawKeywordArguments(scf, "    ")
            << "    txt='gpaw.txt',\n"
               ")\n"
               "atoms.calc = calc\n"
               "atoms.get_potential_energy()\n"
               "calc.write('wannier.gpw', mode='all')\n"
               "_gpw_path = os.path.abspath('wannier.gpw')\n"
               "_log.progress(2, 3)\n";
    } else {
        out << "# Ground state via the selected engine ("
            << toString(cfg.calculator.calculator) << ").\n"
            << AseScriptGenerator::calculatorSnippet(cfg.calculator)
            << "atoms.get_potential_energy()\n"
               "_log.progress(2, 3)\n";
    }
    return out.str();
}

} // namespace

std::string generateWannierScript(const WannierConfig& cfg)
{
    const std::string preamble =
        "# Maximally Localized Wannier Functions (MLWF) — generated by Calango\n"
        "import json\n"
        "import os\n"
        "import glob\n"
        "import numpy as np\n"
        "from ase.io import read\n"
        "from calango_log import CalangoLog\n"
        "_log = CalangoLog()\n";

    const int nWannier = cfg.nWannier > 0 ? cfg.nWannier : 4;

    // Map the (untranslated) projection key onto ASE's `initialwannier` arg.
    // The atomic sets fall back to 'orbitals', from which ASE derives the
    // projections; 'bloch' / 'random' pass straight through.
    const std::string init = (cfg.initialWannier == "bloch"
                              || cfg.initialWannier == "random")
                                 ? cfg.initialWannier
                                 : std::string("orbitals");

    const int maxIter = cfg.maxIterations > 0 ? cfg.maxIterations : 50;

    // Optional disentanglement window → ASE's Wannier(fixedenergy=…). Keeps the
    // occupied states up to `energyWindowEv` (eV, relative to E_F) frozen while
    // the remaining manifold mixes.
    std::string fixedEnergyKw;
    if (cfg.useEnergyWindow) {
        std::ostringstream fe;
        fe << "              fixedenergy=" << cfg.energyWindowEv
           << ",  # eV above E_F; disentanglement outer window\n";
        fixedEnergyKw = fe.str();
    }

    // Marzari-Vanderbilt localization via ASE. Guard the import so a missing
    // ase.dft.wannier surfaces a clear error rather than a bare ImportError.
    std::ostringstream computeStream;
    computeStream
        << "try:\n"
           "    from ase.dft.wannier import Wannier\n"
           "except Exception as _e:\n"
           "    raise RuntimeError('Maximally Localized Wannier Functions '\n"
           "                       'require ase.dft.wannier, which is not '\n"
           "                       'available in this ASE install: ' + repr(_e))\n"
        << "nwannier = " << nWannier << "\n"
        << "# initialwannier seeds the trial projections (atomic orbitals give\n"
           "# good initial overlaps + center estimates).\n"
           "wan = Wannier(nwannier=nwannier, calc=calc,\n"
        << fixedEnergyKw
        << "              initialwannier='" << init << "')\n"
        << "# Iterative Marzari-Vanderbilt minimization (Omega = Omega_I +\n"
           "# Omega_tilde_D). Repeat localize() until the spread functional\n"
           "# stops decreasing (early exit), capped at the requested maximum.\n"
           "_prev = None\n"
        << "for _it in range(" << maxIter << "):\n"
        << "    wan.localize(step=0.25, tolerance=1e-6)\n"
           "    _val = float(wan.get_functional_value())\n"
           "    if _prev is not None and abs(_val - _prev) < 1e-6:\n"
           "        break\n"
           "    _prev = _val\n"
           "_log.progress(3, 3)\n";

    // Evaluation. Centres are in Å; per-orbital spreads use get_spreads() (Å²)
    // with get_radii()² as a fallback; every optional API is guarded so version
    // drift degrades gracefully.
    const std::string evaluate =
        "centers = np.asarray(wan.get_centers(), dtype=float)\n"
        "try:\n"
        "    spreads = [float(s) for s in np.asarray(wan.get_spreads(),\n"
        "                                            dtype=float)]\n"
        "except Exception:\n"
        "    try:\n"
        "        _radii = np.asarray(wan.get_radii(), dtype=float)\n"
        "        spreads = [float(r * r) for r in _radii]\n"
        "    except Exception:\n"
        "        spreads = [float('nan')] * nwannier\n"
        "total_spread = float(np.nansum(spreads))\n"
        "# Localization functional Ω = Ω_I + Ω_D̃ (the minimized value); it is\n"
        "# the trial-projection overlap metric surfaced in the MLWF viewer.\n"
        "try:\n"
        "    functional_value = float(wan.get_functional_value())\n"
        "except Exception:\n"
        "    functional_value = float('nan')\n"
        "cubes = []\n"
        "for _i in range(nwannier):\n"
        "    _fn = 'wannier_%d.cube' % _i\n"
        "    wan.write_cube(_i, _fn)\n"
        "    cubes.append(_fn)\n";

    // Write wannier.json and emit the result marker the controller watches for.
    // `projection` records the trial-orbital seed so the Wannier band
    // interpolation can rebuild the same localization from the saved .gpw.
    std::ostringstream tail;
    tail << "result = {\n"
            "    'total_spread': total_spread,\n"
            "    'functional_value': functional_value,\n"
            // The interpolation re-runs the SAME localization from the SAME
            // wavefunctions, so both have to be recorded rather than guessed.
            // `gpw` may point outside this directory (a run started from a
            // single-point baseline never writes one of its own), and
            // `nwannier` used to be recovered as len(centers) — which is only
            // incidentally right.
            "    'gpw': _gpw_path,\n"
            "    'nwannier': int(nwannier),\n"
         << "    'projection': '" << init << "',\n"
         << "    'centers': [[float(v) for v in row] for row in centers],\n"
            "    'spreads': [float(s) for s in spreads],\n"
            "    'cubes': cubes,\n"
            "}\n"
            "json.dump(result, open('wannier.json', 'w'), indent=2)\n"
            "print('CALANGO_RESULT wannier=wannier.json', flush=True)\n";

    return preamble + groundState(cfg) + computeStream.str() + evaluate
        + tail.str();
}

std::string generateWannierInterpolationScript(
    const std::string& mlwfDir, const WannierInterpolationConfig& cfg)
{
    const int bandPoints = cfg.bandPoints > 1 ? cfg.bandPoints : 200;
    const int kx = cfg.kmesh[0] > 0 ? cfg.kmesh[0] : 8;
    const int ky = cfg.kmesh[1] > 0 ? cfg.kmesh[1] : 8;
    const int kz = cfg.kmesh[2] > 0 ? cfg.kmesh[2] : 8;
    const double width = cfg.pdosWidth > 0.0 ? cfg.pdosWidth : 0.1;

    std::ostringstream out;
    out << "# Wannier-interpolated bands + PDOS — generated by Calango\n"
           "import json\n"
           "import os\n"
           "import glob\n"
           "import numpy as np\n"
           "from calango_log import CalangoLog\n"
           "_log = CalangoLog()\n"
        << "_base = r\"" << mlwfDir << "\"\n"
           "\n"
           "# --- Locate the MLWF run's inputs ---------------------------------\n"
           "# wannier.json is read FIRST, because it is what says where the\n"
           "# wavefunctions are. An MLWF started from a single-point baseline\n"
           "# reads that baseline's .gpw and writes none of its own, so globbing\n"
           "# this directory for one finds nothing — which is exactly how this\n"
           "# step used to fail, with an error that named the wrong directory.\n"
           "_mj = os.path.join(_base, 'wannier.json')\n"
           "if not os.path.exists(_mj):\n"
           "    raise RuntimeError(\n"
           "        'No wannier.json in ' + _base + '. The interpolation rebuilds "
           "the '\n"
           "        'same localization the MLWF run produced, so it needs that "
           "run\\'s '\n"
           "        'summary — point this at a COMPLETED MLWF job.')\n"
           "_meta = json.load(open(_mj))\n"
           "\n"
           "# Resolution order: the path the MLWF run recorded, then any .gpw\n"
           "# sitting in its directory (which is where a fresh-SCF MLWF puts\n"
           "# wannier.gpw).\n"
           "_gpw_path = _meta.get('gpw')\n"
           "if not (_gpw_path and os.path.exists(_gpw_path)):\n"
           "    _found = sorted(glob.glob(os.path.join(_base, '*.gpw')))\n"
           "    _gpw_path = _found[0] if _found else None\n"
           "if not _gpw_path:\n"
           "    raise RuntimeError(\n"
           "        'The MLWF run in ' + _base + ' left no GPAW wavefunction "
           "(.gpw) '\n"
           "        'this interpolation can restart from, and recorded no path "
           "to one. '\n"
           "        + ('The .gpw it used (' + str(_meta.get('gpw')) + ') no "
           "longer exists. '\n"
           "           if _meta.get('gpw') else\n"
           "           'That run predates Calango recording the path. ')\n"
           "        + 'Re-run the MLWF calculation: it now records where its '\n"
           "          'wavefunctions live, whether it computed them itself or "
           "read '\n"
           "          'them from a single-point baseline.')\n"
           "\n"
           "from gpaw import GPAW\n"
           "calc = GPAW(_gpw_path, txt='gpaw_wannier_interp.txt')\n"
           "atoms = calc.get_atoms()\n"
           "\n"
           "# ase.dft.wannier needs the FULL Brillouin zone. A .gpw written by a\n"
           "# symmetry-reduced run carries only the irreducible wedge, and the\n"
           "# failure surfaces deep inside Wannier as an index error that names\n"
           "# nothing the user can act on. Comparing the two k-point counts is\n"
           "# version-robust and says what to do about it.\n"
           "if len(calc.get_ibz_k_points()) < len(calc.get_bz_k_points()):\n"
           "    raise RuntimeError(\n"
           "        'The wavefunctions in ' + _gpw_path + ' were written by a '\n"
           "        'symmetry-reduced run (' + str(len(calc.get_ibz_k_points()))\n"
           "        + ' of ' + str(len(calc.get_bz_k_points())) + ' k-points "
           "kept). '\n"
           "        'Wannier localization needs the full Brillouin zone — re-run "
           "the '\n"
           "        'baseline single-point with \"Symmetry: off\", or let the "
           "MLWF '\n"
           "        'wizard run its own SCF (which forces it).')\n"
           "\n"
           "try:\n"
           "    efermi = float(calc.get_fermi_level())\n"
           "except Exception:\n"
           "    efermi = 0.0\n"
           "_log.progress(1, 4)\n"
           "# Prefer the recorded count; len(centers) is only incidentally the\n"
           "# same number, and silently interpolating a different manifold than\n"
           "# the one that was localized is worse than failing.\n"
           "nwannier = int(_meta.get('nwannier') or len(_meta.get('centers', "
           "[])) or 0)\n"
           "if nwannier <= 0:\n"
           "    raise RuntimeError('wannier.json in ' + _base + ' records "
           "neither a '\n"
           "                       'Wannier-function count nor any centers — the "
           "MLWF '\n"
           "                       'run did not complete.')\n"
           "projection = _meta.get('projection', 'orbitals')\n"
           "from ase.dft.wannier import Wannier\n";
    // Frozen energy window → fixedenergy (relative to E_F).
    if (cfg.useFrozenWindow) {
        out << "wan = Wannier(nwannier=nwannier, calc=calc, "
               "initialwannier=projection,\n"
            << "              fixedenergy=" << cfg.frozenEnergyEv << ")\n";
    } else {
        out << "wan = Wannier(nwannier=nwannier, calc=calc, "
               "initialwannier=projection)\n";
    }
    if (cfg.useDisentangle) {
        out << "# Disentanglement windows (eV, relative to E_F): inner="
            << cfg.innerWindowEv << ", outer=" << cfg.outerWindowEv << "\n"
            << "# (recorded; ASE's Wannier disentanglement is limited.)\n";
    }
    out << "_prev = None\n"
           "for _it in range(50):\n"
           "    wan.localize(step=0.25, tolerance=1e-6)\n"
           "    _val = float(wan.get_functional_value())\n"
           "    if _prev is not None and abs(_val - _prev) < 1e-6:\n"
           "        break\n"
           "    _prev = _val\n"
           "_log.progress(2, 4)\n";

    // --- Band structure along the requested path --------------------------
    if (!cfg.kpath.empty()) {
        out << "path = atoms.cell.bandpath(path='" << cfg.kpath
            << "', npoints=" << bandPoints << ")\n";
    } else {
        out << "path = atoms.cell.bandpath(npoints=" << bandPoints << ")\n";
    }
    out << "band_energies = []\n"
           "for _kpt in path.kpts:\n"
           "    _H = wan.get_hamiltonian_kpoint(np.asarray(_kpt, dtype=float))\n"
           "    _eigs = np.linalg.eigvalsh(np.asarray(_H))\n"
           "    band_energies.append(np.sort(_eigs.real))\n"
           "band_energies = np.asarray(band_energies)[None, :, :]\n"
           "from ase.spectrum.band_structure import BandStructure\n"
           "bs = BandStructure(path=path, energies=band_energies, "
           "reference=efermi)\n"
           "x, special_x, special_labels = bs.path.get_linear_kpoint_axis()\n"
           "bands = {\n"
           "    \"x\": list(map(float, x)),\n"
           "    \"special_x\": list(map(float, special_x)),\n"
           "    \"special_labels\": list(special_labels),\n"
           "    \"efermi\": float(efermi),\n"
           "    \"energies\": [[list(map(float, kpt)) for kpt in spin]\n"
           "                 for spin in bs.energies],\n"
           "}\n"
           "with open('bands.json', 'w') as _fh:\n"
           "    json.dump(bands, _fh)\n"
           "_log.progress(3, 4)\n";

    // --- Wannier-projected PDOS on a dense mesh ---------------------------
    out << "# PDOS from the Wannier H(k) on a Monkhorst-Pack mesh; the squared\n"
           "# eigenvector amplitudes project the DOS onto each Wannier "
           "function.\n"
           "from ase.dft.kpoints import monkhorst_pack\n"
        << "_mp = monkhorst_pack((" << kx << ", " << ky << ", " << kz << "))\n"
        << "_all_eigs = []\n"
           "_all_w = []\n"
           "for _kpt in _mp:\n"
           "    _Hk = np.asarray(wan.get_hamiltonian_kpoint("
           "np.asarray(_kpt, dtype=float)))\n"
           "    _w, _v = np.linalg.eigh(_Hk)\n"
           "    _all_eigs.append(_w.real)\n"
           "    _all_w.append(np.abs(_v) ** 2)  # weights[wannier, band]\n"
           "_all_eigs = np.asarray(_all_eigs)\n"
           "_nk, _nb = _all_eigs.shape\n"
        << "_width = " << width << "\n"
           "_emin = float(_all_eigs.min()) - 5.0 * _width\n"
           "_emax = float(_all_eigs.max()) + 5.0 * _width\n"
           "_egrid = np.linspace(_emin, _emax, 600)\n"
           "_proj = np.zeros((_nb, _egrid.size))\n"
           "_norm = 1.0 / (_width * np.sqrt(2.0 * np.pi)) / _nk\n"
           "for _ik in range(_nk):\n"
           "    _wk = _all_w[_ik]\n"
           "    for _ib in range(_nb):\n"
           "        _g = np.exp(-0.5 * ((_egrid - _all_eigs[_ik, _ib]) "
           "/ _width) ** 2) * _norm\n"
           "        _proj += np.outer(_wk[:, _ib], _g)\n"
           "pdos = {\n"
           "    \"energies\": [float(e) for e in _egrid],\n"
           "    \"efermi\": float(efermi),\n"
           "    \"projections\": {\n"
           "        (\"Wannier %d\" % _iw): [float(x) for x in _proj[_iw]]\n"
           "        for _iw in range(_nb)\n"
           "    },\n"
           "}\n"
           "with open('pdos.json', 'w') as _fh:\n"
           "    json.dump(pdos, _fh)\n"
           "_log.progress(4, 4)\n"
           "print('CALANGO_RESULT bands=bands.json pdos=pdos.json', "
           "flush=True)\n";
    return out.str();
}

} // namespace calango::core
