#include "core/WavefunctionScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

namespace {

const char* quantitySuffix(WavefunctionQuantity q)
{
    switch (q) {
    case WavefunctionQuantity::Real:
        return "real";
    case WavefunctionQuantity::Imaginary:
        return "imag";
    case WavefunctionQuantity::Density:
    default:
        return "density";
    }
}

/// The Python expression turning `_psi` (real or complex ndarray) into the
/// real-valued field write_cube needs, for one quantity.
const char* quantityExpression(WavefunctionQuantity q)
{
    switch (q) {
    case WavefunctionQuantity::Real:
        return "np.real(_psi)";
    case WavefunctionQuantity::Imaginary:
        // Identically zero for a real (Gamma-point/molecular) orbital —
        // written anyway, matching a genuinely complex k != Gamma state's
        // own nonzero imaginary part. np.imag() on a real dtype array
        // already returns an all-zero array of the same shape, so no
        // special-casing is needed here.
        return "np.imag(_psi)";
    case WavefunctionQuantity::Density:
    default:
        return "np.abs(_psi) ** 2";
    }
}

std::string spinLabel(int spin)
{
    return spin == 0 ? "up" : "down";
}

std::string cubeFileName(const WavefunctionState& s, WavefunctionQuantity q)
{
    std::ostringstream out;
    out << "psi_n" << s.band << "_k" << s.kpt << "_spin-" << spinLabel(s.spin)
        << "_" << quantitySuffix(q) << ".cube";
    return out.str();
}

} // namespace

std::string generateWavefunctionsScript(const WavefunctionsConfig& cfg)
{
    std::ostringstream out;
    out << "# Wavefunctions (real-space Kohn-Sham orbitals) — generated by "
           "Calango\n"
           "import json\n"
           "import os\n"
           "import glob\n"
           "import numpy as np\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble();

    if (cfg.states.empty()) {
        // Fails BEFORE the (comparatively slow) baseline restart, the same
        // "cheap checks first" shape Wannier's engine-mismatch refusal
        // uses. This is not a defensive edge case: the wizard's state table
        // starts with every row unchecked and nothing stops Run with none
        // ticked — without this, that produces a job that exits 0, writes
        // a `wavefunctions.json` with an empty `states: []`, and
        // MainWindow::openWavefunctionsResults() then registers nothing
        // into the Volumetric Data dock — a "successful" run with no
        // visible result and no explanation anywhere.
        out << "raise RuntimeError(\n"
               "    'Wavefunctions: no states were selected. Tick at least "
               "one row '\n"
               "    'in the state table before running — otherwise there "
               "is nothing '\n"
               "    'to write.')\n";
        return out.str();
    }

    out << AseScriptGenerator::gpawRestartFromBaselineScript(
               cfg.baselineDir, "Wavefunctions",
               "Wavefunctions reads the SAVED Kohn-Sham states — re-run the "
               "single-point with wavefunctions saved (mode=all).")
        << "_calango_progress(1, "
        << (cfg.states.empty() ? 1 : static_cast<int>(cfg.states.size()) + 1)
        << ")\n"
           "\n"
        << AseScriptGenerator::gpawWaveFunctionHelperScript()
        << "\n"
           "from ase.io.cube import write_cube\n"
           "\n"
           "_periodic = bool(any(atoms.pbc))\n"
           "_entries = []\n";

    int step = 1;
    for (const WavefunctionState& s : cfg.states) {
        ++step;
        const std::string fileName = cubeFileName(s, cfg.quantity);
        out << "\n"
               "# n=" << s.band << " k=" << s.kpt << " spin=" << s.spin
            << "\n"
               "_psi = _calango_wave_function(calc, " << s.band << ", "
            << s.kpt << ", " << s.spin << ",\n"
            << "                              all_electron="
            << (cfg.allElectron ? "True" : "False") << ",\n"
            << "                              grid_spacing="
            << cfg.allElectronGridSpacing << ")\n"
               "if _psi is None:\n"
               "    raise RuntimeError(\n"
            << "        'No wavefunction for n=" << s.band << " k="
            << s.kpt << " spin=" << s.spin
            << " — out of range for this baseline, or not on this rank.')\n"
            << "_field = np.ascontiguousarray(" << quantityExpression(cfg.quantity)
            << ", dtype=float)\n"
            << "with open(r\"" << fileName << "\", 'w') as _fh:\n"
               "    write_cube(_fh, atoms, data=_field)\n"
            << "_eigs = calc.get_eigenvalues(kpt=" << s.kpt << ", spin="
            << s.spin << ")\n"
               "_occs = calc.get_occupation_numbers(kpt=" << s.kpt
            << ", spin=" << s.spin << ")\n"
            << "_entries.append({\n"
            << "    'spin': " << s.spin << ", 'kpt': " << s.kpt
            << ", 'band': " << s.band << ",\n"
               "    'energy_eV': float(_eigs[" << s.band << "]),\n"
               "    'occupation': float(_occs[" << s.band
            << "]) if _occs is not None else None,\n"
            << "    'quantity': '" << quantitySuffix(cfg.quantity) << "',\n"
            << "    'all_electron': " << (cfg.allElectron ? "True" : "False")
            << ",\n"
               "    'periodic': _periodic,\n"
               "    'complex_valued': bool(np.iscomplexobj(_psi)),\n"
            << "    'cube': r\"" << fileName << "\",\n"
               "})\n"
            << "_calango_progress(" << step << ", "
            << (static_cast<int>(cfg.states.size()) + 1) << ")\n";
    }

    out << "\n"
           "_summary = {\n"
           "    'baseline_dir': _base,\n"
           "    'gpw': _gpw_path,\n"
        << "    'quantity': '" << quantitySuffix(cfg.quantity) << "',\n"
        << "    'all_electron': " << (cfg.allElectron ? "True" : "False")
        << ",\n"
           "    'periodic': _periodic,\n"
           "    'states': _entries,\n"
           "}\n"
        << "with open(r\"" << cfg.resultsJson << "\", 'w') as _fh:\n"
           "    json.dump(_summary, _fh, indent=2)\n"
        << "print('CALANGO_RESULT wavefunctions=" << cfg.resultsJson
        << "', flush=True)\n"
        << "print(f'CALANGO_SUMMARY states={len(_entries)}', flush=True)\n"
           "_calango_event('done', "
           "f'{len(_entries)} wavefunction(s) written')\n";

    return out.str();
}

} // namespace calango::core
