#include "core/XasScriptGenerator.hpp"

#include "core/AseScriptGenerator.hpp"

#include <sstream>

namespace calango::core {

namespace {

/// GPAW's Generator takes the core hole as (n, l, occupation-removed).
const char* coreLevelQuantumNumbers(XasCoreLevel level)
{
    switch (level) {
    case XasCoreLevel::L1:
        return "2, 0";
    case XasCoreLevel::L23:
        return "2, 1";
    case XasCoreLevel::K:
        break;
    }
    return "1, 0";
}

/// The setup NAME encodes what is in it, following the tutorial's convention:
/// hch = half core hole, fch = full, xes = none, then the level.
std::string setupName(const XasRunConfig& c)
{
    const char* level = c.coreLevel == XasCoreLevel::L1    ? "2s"
        : c.coreLevel == XasCoreLevel::L23                 ? "2p"
                                                           : "1s";
    const char* kind = c.coreHole == XasCoreHole::Full ? "fch"
        : c.coreHole == XasCoreHole::None              ? "xes"
                                                       : "hch";
    return std::string(kind) + level;
}

double holeOccupation(XasCoreHole hole)
{
    switch (hole) {
    case XasCoreHole::Full:
        return 1.0;
    case XasCoreHole::None:
        return 0.0;
    case XasCoreHole::Half:
        break;
    }
    return 0.5;
}

} // namespace

std::string XasScriptGenerator::generate(const XasRunConfig& c,
                                         const std::string& structureFile)
{
    const std::string name = setupName(c);
    std::ostringstream out;

    out << "#!/usr/bin/env python3\n"
           "# Generated by Calango " << CALANGO_VERSION
        << " — X-ray absorption spectroscopy (XAS) with GPAW.\n"
           "#\n"
           "# Follows the GPAW XAS tutorial:\n"
           "#   https://gpaw.readthedocs.io/tutorialsexercises/opticalresponse/"
           "xas/xas.html\n"
           "#\n"
           "# Three stages, because a core-level spectrum needs a PAW dataset\n"
           "# with a HOLE in the core level and no such dataset ships with\n"
           "# GPAW:\n"
           "#   1. generate the core-hole setup for the absorbing element;\n"
           "#   2. converge a ground state that uses it on the absorbing ATOM;\n"
           "#   3. evaluate the spectrum from those wavefunctions.\n"
           "#\n"
           "# This is a plain ASE/GPAW script: edit it freely or run it "
           "standalone.\n"
           "\n"
           "import json\n"
           "import os\n"
           "\n"
           "import numpy as np\n"
           "from ase.io import read\n"
           "\n"
           "# gpaw.xas runs on the LEGACY engine only — the new one raises\n"
           "# 'New-GPAW not supported'. Every other script Calango generates\n"
           "# sets GPAW_NEW=1, so it is explicitly cleared here and the\n"
           "# calculator is asked for the legacy path by name.\n"
           "os.environ['GPAW_NEW'] = '0'\n"
           "\n"
        << AseScriptGenerator::jsonLoggerPreamble()
        << "atoms = read(r\"" << structureFile
        << "\")\n"
           "print(f'CALANGO_INFO natoms={len(atoms)}', flush=True)\n"
           "\n"
        << "absorbing_atom = " << c.absorbingAtom
        << "\n"
        << "element = \"" << c.element
        << "\"\n"
           "setup_name = \""
        << name
        << "\"\n"
           "results_path = r\""
        << c.resultsJson
        << "\"\n"
           "\n"
           "if not 0 <= absorbing_atom < len(atoms):\n"
           "    raise RuntimeError(\n"
           "        f'Absorbing atom {absorbing_atom} is outside the structure '\n"
           "        f'({len(atoms)} atoms).')\n"
           "_actual = atoms[absorbing_atom].symbol\n"
           "if _actual != element:\n"
           "    raise RuntimeError(\n"
           "        f'Atom {absorbing_atom} is {_actual}, not {element}. The '\n"
           "        'core-hole setup is generated for one element and applied '\n"
           "        'to one atom; they have to agree.')\n"
           "\n";

    // -- Stage 1: the core-hole setup ---------------------------------------
    out << "# 1. Core-hole setup ----------------------------------------------\n"
           "#\n"
           "# Written into the job directory and found through setup_paths, so\n"
           "# the run is self-contained: nothing is installed into the GPAW\n"
           "# distribution and re-running elsewhere regenerates it.\n"
           "from gpaw.atom.generator import Generator\n"
           "from gpaw.atom.configurations import parameters\n"
           "from gpaw import setup_paths\n"
           "\n"
        << "_xc = \"" << c.calculator.gpawXc
        << "\"\n"
           "_generator = Generator(element, xcname=_xc, scalarrel=True,\n"
        << "                       corehole=(" << coreLevelQuantumNumbers(c.coreLevel)
        << ", " << holeOccupation(c.coreHole)
        << "),\n"
           "                       nofiles=True)\n"
           "_generator.run(name=setup_name, **parameters[element])\n"
           "setup_paths.insert(0, '.')\n"
           "print(f'CALANGO_INFO generated core-hole setup "
           "{element}.{setup_name}.{_xc}', flush=True)\n"
           "\n";

    // -- Stage 2: the ground state ------------------------------------------
    out << "# 2. Ground state -------------------------------------------------\n"
           "#\n"
           "# The core-hole setup goes on the ABSORBING ATOM only, keyed by\n"
           "# index. Keying it by element would give every atom of that species\n"
           "# a core hole, modelling a solid in which all of them are excited\n"
           "# at once.\n"
           "from gpaw import GPAW, PW\n"
           "\n"
           "calc = GPAW(\n"
           "    legacy_gpaw=True,\n";
    // XAS is run in FD in the tutorial and in practice: a core-hole setup has
    // a hard augmentation that a plane-wave basis only resolves at an
    // impractical cutoff, and LCAO has no unoccupied states worth summing
    // over. PW is still emitted faithfully when asked for, with the caveat in
    // the script rather than silently overridden.
    switch (c.calculator.gpawMode) {
    case GpawMode::PlaneWave:
        out << "    # Plane waves. The tutorial uses FD, and so does most XAS:\n"
               "    # a core-hole setup's hard augmentation needs an impractical\n"
               "    # cutoff to resolve in a plane-wave basis. Raise it until the\n"
               "    # edge stops moving, or switch to FD.\n";
        out << "    mode=PW(" << c.calculator.planeWaveCutoffEv << "),\n";
        break;
    case GpawMode::Lcao:
        out << "    # LCAO. The spectrum is a sum over UNOCCUPIED states, and an\n"
               "    # atomic-orbital basis carries very few — expect a spectrum\n"
               "    # that is truncated rather than merely coarse.\n"
               "    mode='lcao',\n"
            << "    basis='" << c.calculator.gpawBasis << "',\n";
        break;
    case GpawMode::FiniteDifference:
        out << "    mode='fd',\n"
            << "    h=" << c.calculator.gpawGridSpacing << ",\n";
        break;
    }
    out << "    xc=_xc,\n"
        << "    nbands=" << -std::abs(c.extraBands)
        << ",  # negative = this many bands ABOVE the occupied ones\n"
           "    setups={absorbing_atom: setup_name},\n"
        << "    kpts=(" << c.calculator.kpts[0] << ", " << c.calculator.kpts[1]
        << ", " << c.calculator.kpts[2]
        << "),\n"
           "    txt='xas_gs.txt',\n"
           ")\n"
           "atoms.calc = calc\n"
           "_calango_progress(1, 3)\n"
           "energy = atoms.get_potential_energy()\n"
           "print(f'CALANGO_RESULT energy_eV={energy:.6f}', flush=True)\n"
           "calc.write('xas.gpw', mode='all')\n"
           "_calango_progress(2, 3)\n"
           "\n";

    // -- Optional delta-Kohn-Sham calibration -------------------------------
    if (c.computeDks) {
        out << "# Absolute energy scale from a delta-Kohn-Sham total-energy\n"
               "# difference: the spectrum GPAW produces is relative to the\n"
               "# first unoccupied state, which is not where a measurement puts\n"
               "# it. Two extra total energies, hence roughly double the cost.\n"
               "from gpaw.occupations import FermiDirac\n"
               "\n"
               "_gs_atoms = atoms.copy()\n"
               "_gs = GPAW(legacy_gpaw=True, mode='fd', h="
            << c.calculator.gpawGridSpacing
            << ", xc=_xc,\n"
               "           txt='xas_dks_ground.txt')\n"
               "_gs_atoms.calc = _gs\n"
               "_e_ground = (_gs_atoms.get_potential_energy()\n"
               "             + _gs.get_reference_energy())\n"
               "\n"
               "# The excited state: a FULL core hole, one electron added back\n"
               "# to keep the cell neutral, and the magnetic moment fixed so the\n"
               "# SCF cannot relax back into the ground state.\n"
               "_fch = Generator(element, xcname=_xc, scalarrel=True,\n"
            << "                 corehole=("
            << coreLevelQuantumNumbers(c.coreLevel)
            << ", 1.0), nofiles=True)\n"
               "_fch.run(name='fch_dks', **parameters[element])\n"
               "_ex_atoms = atoms.copy()\n"
               "_ex_atoms.set_initial_magnetic_moments(\n"
               "    [1.0 if _i == absorbing_atom else 0.0\n"
               "     for _i in range(len(_ex_atoms))])\n"
               "_ex = GPAW(legacy_gpaw=True, mode='fd', h="
            << c.calculator.gpawGridSpacing
            << ", xc=_xc,\n"
               "           charge=-1, spinpol=True,\n"
               "           occupations=FermiDirac(0.0, fixmagmom=True),\n"
               "           setups={absorbing_atom: 'fch_dks'},\n"
               "           txt='xas_dks_excited.txt')\n"
               "_ex_atoms.calc = _ex\n"
               "_e_excited = (_ex_atoms.get_potential_energy()\n"
               "              + _ex.get_reference_energy())\n"
               "dks_energy = _e_excited - _e_ground\n"
               "print(f'CALANGO_INFO delta-Kohn-Sham edge = {dks_energy:.3f} eV',\n"
               "      flush=True)\n"
               "\n";
    } else {
        out << "dks_energy = " << c.dksEnergy
            << "  # 0 leaves the relative scale GPAW produces\n\n";
    }

    // -- Stage 3: the spectrum ----------------------------------------------
    out << "# 3. Spectrum -----------------------------------------------------\n"
           "from gpaw.xas import XAS\n"
           "\n"
           "xas = XAS(calc, mode='xas')\n";
    if (c.linearBroadening) {
        out << "# Linear broadening ramp: the width grows with energy above the\n"
               "# edge, which is the physical behaviour (core-hole lifetime plus\n"
               "# final-state broadening) and what makes this comparable with a\n"
               "# measured spectrum.\n"
            << "_linbroad = [" << c.linearBroadeningStart << ", "
            << c.linearBroadeningEnergyStart << ", "
            << c.linearBroadeningEnergyStop << "]\n";
    } else {
        out << "_linbroad = None  # uniform broadening at fwhm\n";
    }
    out << "energies, intensities = xas.get_spectra(fwhm=" << c.fwhm
        << ", linbroad=_linbroad,\n"
           "                                        dks=dks_energy)\n"
           "stick_energies, stick_intensities = xas.get_spectra(\n"
           "    stick=True, dks=dks_energy)\n"
           "_calango_progress(3, 3)\n"
           "\n"
           "# get_spectra returns (3, N): the x, y and z polarizations. The\n"
           "# isotropic spectrum — what a powder or solution measurement sees —\n"
           "# is their average, and the three are kept alongside it because for\n"
           "# an oriented sample the anisotropy IS the result.\n"
           "energies = np.asarray(energies, dtype=float)\n"
           "intensities = np.asarray(intensities, dtype=float)\n"
           "isotropic = intensities.mean(axis=0)\n"
           "stick_energies = np.asarray(stick_energies, dtype=float)\n"
           "stick_intensities = np.asarray(stick_intensities, dtype=float)\n"
           "\n"
           "_summary = {\n"
           "    'element': element,\n"
           "    'absorbing_atom': absorbing_atom,\n"
           "    'setup': setup_name,\n"
           "    'core_hole': "
        << holeOccupation(c.coreHole)
        << ",\n"
           "    'dks_energy_eV': float(dks_energy),\n"
        << "    'fwhm_eV': " << c.fwhm
        << ",\n"
           "    'energy_eV': energies.tolist(),\n"
           "    'isotropic': isotropic.tolist(),\n"
           "    'polarization_x': intensities[0].tolist(),\n"
           "    'polarization_y': intensities[1].tolist(),\n"
           "    'polarization_z': intensities[2].tolist(),\n"
           "    'stick_energy_eV': stick_energies.tolist(),\n"
           "    'stick_isotropic': stick_intensities.mean(axis=0).tolist(),\n"
           "    'ground_state_energy_eV': float(energy),\n"
           "}\n"
           "with open(results_path, 'w') as _fh:\n"
           "    json.dump(_summary, _fh, indent=2)\n"
           "print(f'CALANGO_RESULT xas={results_path}', flush=True)\n"
           "print(f'CALANGO_SUMMARY points={len(energies)} "
           "transitions={len(stick_energies)} '\n"
           "      f'range=[{energies.min():.2f}, {energies.max():.2f}] eV',\n"
           "      flush=True)\n"
           "_calango_event('done', f'XAS spectrum written to "
           "{results_path}')\n";
    return out.str();
}

} // namespace calango::core
